// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `byn`.
 *
 * BYN itself is the bare language, `byn`; the entries are the locales below it.
 */
public enum class BYN(override val tag: String) : LocaleRef {
    ER("byn-ER"),
    ;

    /** The bare language, `byn`. */
    public companion object : LocaleRef {
        override val tag: String = "byn"
    }
}
