// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `cch`.
 *
 * CCH itself is the bare language, `cch`; the entries are the locales below it.
 */
public enum class CCH(override val tag: String) : LocaleRef {
    NG("cch-NG"),
    ;

    /** The bare language, `cch`. */
    public companion object : LocaleRef {
        override val tag: String = "cch"
    }
}
