// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `da`.
 *
 * DA itself is the bare language, `da`; the entries are the locales below it.
 */
public enum class DA(override val tag: String) : LocaleRef {
    DK("da-DK"),
    GL("da-GL"),
    ;

    /** The bare language, `da`. */
    public companion object : LocaleRef {
        override val tag: String = "da"
    }
}
