// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `de`.
 *
 * DE itself is the bare language, `de`; the entries are the locales below it.
 */
public enum class DE(override val tag: String) : LocaleRef {
    AT("de-AT"),
    BE("de-BE"),
    CH("de-CH"),
    DE("de-DE"),
    IT("de-IT"),
    LI("de-LI"),
    LU("de-LU"),
    ;

    /** The bare language, `de`. */
    public companion object : LocaleRef {
        override val tag: String = "de"
    }
}
