// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `dua`.
 *
 * DUA itself is the bare language, `dua`; the entries are the locales below it.
 */
public enum class DUA(override val tag: String) : LocaleRef {
    CM("dua-CM"),
    ;

    /** The bare language, `dua`. */
    public companion object : LocaleRef {
        override val tag: String = "dua"
    }
}
