// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `ee`.
 *
 * EE itself is the bare language, `ee`; the entries are the locales below it.
 */
public enum class EE(override val tag: String) : LocaleRef {
    GH("ee-GH"),
    TG("ee-TG"),
    ;

    /** The bare language, `ee`. */
    public companion object : LocaleRef {
        override val tag: String = "ee"
    }
}
