// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `fil`.
 *
 * FIL itself is the bare language, `fil`; the entries are the locales below it.
 */
public enum class FIL(override val tag: String) : LocaleRef {
    PH("fil-PH"),
    ;

    /** The bare language, `fil`. */
    public companion object : LocaleRef {
        override val tag: String = "fil"
    }
}
