// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `kab`.
 *
 * KAB itself is the bare language, `kab`; the entries are the locales below it.
 */
public enum class KAB(override val tag: String) : LocaleRef {
    DZ("kab-DZ"),
    ;

    /** The bare language, `kab`. */
    public companion object : LocaleRef {
        override val tag: String = "kab"
    }
}
