// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `kkj`.
 *
 * KKJ itself is the bare language, `kkj`; the entries are the locales below it.
 */
public enum class KKJ(override val tag: String) : LocaleRef {
    CM("kkj-CM"),
    ;

    /** The bare language, `kkj`. */
    public companion object : LocaleRef {
        override val tag: String = "kkj"
    }
}
