// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `km`.
 *
 * KM itself is the bare language, `km`; the entries are the locales below it.
 */
public enum class KM(override val tag: String) : LocaleRef {
    KH("km-KH"),
    ;

    /** The bare language, `km`. */
    public companion object : LocaleRef {
        override val tag: String = "km"
    }
}
