// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `kok`.
 *
 * KOK itself is the bare language, `kok`; the entries are the locales below it.
 */
public enum class KOK(override val tag: String) : LocaleRef {
    DEVA("kok-Deva"),
    DEVA_IN("kok-Deva-IN"),
    LATN("kok-Latn"),
    LATN_IN("kok-Latn-IN"),
    ;

    /** The bare language, `kok`. */
    public companion object : LocaleRef {
        override val tag: String = "kok"
    }
}
