// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `lzz`.
 *
 * LZZ itself is the bare language, `lzz`; the entries are the locales below it.
 */
public enum class LZZ(override val tag: String) : LocaleRef {
    TR("lzz-TR"),
    ;

    /** The bare language, `lzz`. */
    public companion object : LocaleRef {
        override val tag: String = "lzz"
    }
}
