// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `mua`.
 *
 * MUA itself is the bare language, `mua`; the entries are the locales below it.
 */
public enum class MUA(override val tag: String) : LocaleRef {
    CM("mua-CM"),
    ;

    /** The bare language, `mua`. */
    public companion object : LocaleRef {
        override val tag: String = "mua"
    }
}
