// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `pcm`.
 *
 * PCM itself is the bare language, `pcm`; the entries are the locales below it.
 */
public enum class PCM(override val tag: String) : LocaleRef {
    NG("pcm-NG"),
    ;

    /** The bare language, `pcm`. */
    public companion object : LocaleRef {
        override val tag: String = "pcm"
    }
}
