// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `quc`.
 *
 * QUC itself is the bare language, `quc`; the entries are the locales below it.
 */
public enum class QUC(override val tag: String) : LocaleRef {
    GT("quc-GT"),
    ;

    /** The bare language, `quc`. */
    public companion object : LocaleRef {
        override val tag: String = "quc"
    }
}
