// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `sd`.
 *
 * SD itself is the bare language, `sd`; the entries are the locales below it.
 */
public enum class SD(override val tag: String) : LocaleRef {
    ARAB("sd-Arab"),
    ARAB_PK("sd-Arab-PK"),
    DEVA("sd-Deva"),
    DEVA_IN("sd-Deva-IN"),
    ;

    /** The bare language, `sd`. */
    public companion object : LocaleRef {
        override val tag: String = "sd"
    }
}
