// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `sdh`.
 *
 * SDH itself is the bare language, `sdh`; the entries are the locales below it.
 */
public enum class SDH(override val tag: String) : LocaleRef {
    IQ("sdh-IQ"),
    IR("sdh-IR"),
    ;

    /** The bare language, `sdh`. */
    public companion object : LocaleRef {
        override val tag: String = "sdh"
    }
}
