/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `sr`.
 *
 * SR itself is the bare language, `sr`; the entries are the locales below it.
 */
public enum class SR(override val tag: String) : LocaleRef {
    CYRL("sr-Cyrl"),
    CYRL_BA("sr-Cyrl-BA"),
    CYRL_ME("sr-Cyrl-ME"),
    CYRL_RS("sr-Cyrl-RS"),
    CYRL_XK("sr-Cyrl-XK"),
    LATN("sr-Latn"),
    LATN_BA("sr-Latn-BA"),
    LATN_ME("sr-Latn-ME"),
    LATN_RS("sr-Latn-RS"),
    LATN_XK("sr-Latn-XK"),
    ;

    /** The bare language, `sr`. */
    public companion object : LocaleRef {
        override val tag: String = "sr"
    }
}
