// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `to`.
 *
 * TO itself is the bare language, `to`; the entries are the locales below it.
 */
public enum class TO(override val tag: String) : LocaleRef {
    TO("to-TO"),
    ;

    /** The bare language, `to`. */
    public companion object : LocaleRef {
        override val tag: String = "to"
    }
}
