// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `vai`.
 *
 * VAI itself is the bare language, `vai`; the entries are the locales below it.
 */
public enum class VAI(override val tag: String) : LocaleRef {
    LATN("vai-Latn"),
    LATN_LR("vai-Latn-LR"),
    VAII("vai-Vaii"),
    VAII_LR("vai-Vaii-LR"),
    ;

    /** The bare language, `vai`. */
    public companion object : LocaleRef {
        override val tag: String = "vai"
    }
}
