// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `vi`.
 *
 * VI itself is the bare language, `vi`; the entries are the locales below it.
 */
public enum class VI(override val tag: String) : LocaleRef {
    VN("vi-VN"),
    ;

    /** The bare language, `vi`. */
    public companion object : LocaleRef {
        override val tag: String = "vi"
    }
}
