/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.cities.internal.data

internal val TIME_ZONE_CITIES_WAE: String =
    "005Q\u000FTi\u0015w\u000Da\u0011\u007F39\"<b\u0006#\u0010\u000BA\"\u0014)\u0008\u0012]\u0014-MZ2nm5\u001C;6@Q\$\u0012=\u0001u~wLz\u000C7Dx:Uh,M6\u000A\u0015`\u0018AJ\u000E\u000CU\u00032coC\u000F\u0017#/n_\u000AG.W\u0016\u000A*p!k:\u000D8SeQ\u000D)V,k#zsPA}:T\u0012\u0002dM\u0001v%T\u0004%\u000Co9\u0011\u0012{\u0004\u0012\u001Fb\u0008~\u0019Wi\u001B\u0009\\\u001EAi\u0014__d/M~F4^>\u0005GHD/\"@/\"h\$\u0002\u007FNjocUpR\u001A09~\u000Ck\u001B-\u007F\u001F\u0006D\u0005\u00175j.cCY\u001D&5\u001CO\u001B\u000E\u0003`-Kh\u000Ek\u0016Rt\u000Cl/e\u0019\u0018k\u001A<\u001Cw\u0006tF)G+CJ)j)\u000Epi0Zs]@R+\u001D`a\u0009vg<i%9\u001Ej\u0012\u0001]\u000E\u0001>\u0006IP[\u0004#/I\u0002w|1Wj_Iaj@@\u0019\u0007e.U>\u0018\u0016u\u0013`h@A"

internal val TIME_ZONE_CITIES_WAE_CH: String =
    "0006\u0016TjJ*]a\u0005\u0001\u0001"

internal val TIME_ZONE_CITIES_WAL_ET: String =
    "0006\u0016TzJ\u000A]a\u0005\u0001\u0001"

internal val TIME_ZONE_CITIES_WA_BE: String =
    "0005\u0016TsD:A\u0009\u0001"

internal val TIME_ZONE_CITIES_WBP_AU: String =
    "0006\u0016Tf*\u0002]a\u0005\u0001\u0001"

internal val TIME_ZONE_CITIES_WO: String =
    "000N\u0016sZs}Eoq<\u000F8DRn7\"U~\u001F\u00055\u0017\u0016Eo5DA\u0001"

internal val TIME_ZONE_CITIES_WO_SN: String =
    "0005\u0016tst:A\u0009\u0001"
