/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.collation.cldr.internal.data

internal val COLLATION_TAILORING_EE: String =
    "00CC7e\\9u\u000DA\u0015#`z\u000E\u0004B!A~\u000E*\"\u0009p\u00105|9Q[y\u007F\u000AMb|\u001D\u000F\u001Fix\u000Cbq\$w:<9\u0010dU\u000CuD5`SKhbT0.qE\u0019\u001C[p\u0006]H?\u000E\u001F; K`\u0009\"C\u001FL\u007Fx0\u0009*osy6\u0012fS!oi\u001AguDcX-nwD0\u000A*\u0017\\\u0019I\u001Ad\u0001N\u0010\u001D.,?+\"+ G|L\u0015W\u0012t\u0013\u0015yNn1.YeFo\u0017W\u007F\u000B\"\u001Fn\"5d\u0009\u0014rmp[*Y'/w^atg}\u0015J\u001E\u0009\u0005x'\u0019KNG,.\u0007&XJ~a=\u0008B%NY\u000CG`g\u000DF\\\u0001F?S \u0018\"t\u0019GR%%FS6\u0011cJ\u001C\u0011*NgJ}X[3)*\u00147&RE\u00137gJ\u001CE\$64/Hh\u0011\u0017J\u001C\u00179dj\u0019On~@Hq\u0005"

internal val COLLATION_TAILORING_EL: String =
    "000lZnWd2L\u001C7\u0015\u000E;\u0004\u001EJ\u0019L(t;t\u001AL\u00175\u0019\u000D;\u0001\u0010K\u0016+J>2B\u0013P\u001AtAaM\u0003/\\.W\u0001\u0001"

internal val COLLATION_TAILORING_EN_US_POSIX: String =
    "00B5/uJ1u\u000A\u0001\u0011C9\"2L\u0003\u00168P\u0002C\u0009\u0009BG\u00151a\u001B3[uWkj;9\\@2\u007F]=R(\"8M*#|T#s\u0018]?\u0015\u000CVd3}haE\u0010\"8\u007F#6q7|\$?\u0005\u0014y\u0017|rN#\u0016w'\u0008q\$>Y,`F.\u001E\u000DE@\u001303\u0019x\u0005!|AO IZ\u001D\u000F8\u0009a,D\u0015\u007F\u0006\u001AicuJ\u001DJW}\u0019\u00122kaiSJ\u0002kRJ*BgFH/A2H*\u0002o|\u0017R\u0003lO\u0013\u0004Tg\"%\u0008\u000FW>+\u0002^\u001E6h\u0011\u0008n>fC\u000Dr\u000DO\u0009k8x`\u007F+=r\u001Fw\u001Ex\u0002A"

internal val COLLATION_TAILORING_EO: String =
    "004z7tJ\u0011U\u0001a\u0011#5\"5OS%\u0019DuyDH\u000D\u0001\u000BD\u001F\u0010)nw\u0018^nru{_\u0019D\u0017X!HL+\u000B\u001ARN\u00091l\u0011\u001F\u0015)_G\u000F\u0018\u0017uH\u0011s\u0017T3t\"]GU-%Hp\u001B\u0005\u0007\u0005I{DEJ\u001B7aNQ\u000A\u000E@\u0014U\u0014R//`B D\u0005\u000E5VF\u001A0M\u007F7{d\u0018\u000B8[pAa"

internal val COLLATION_TAILORING_ES: String =
    "000vZNGn\u0017.\u00144\u001A\u000DGsJ%XU\u001CsF\u0005{</8\u001A\u000Cft\u0016L!2\u001A1e&\u001C'6\u001C8D!!\u0001"

internal val COLLATION_TAILORING_ET: String =
    "005g7u\u001C\u0011U\u0001A\u0011Cy#qV\u000Fd5s\\&&_#e\u000ER.nrP*E\u001D\u0018@\u0004N!i:S\u001FV\u001C1Cv\$6\u0011{\u000D9*S\u0001\u001Fp(j\u001FE+S\u0006{k\u0001a&\u0015GP\u000AS\u000F5N6R\u0009RW\u000A\u000F\u0009n8]\u001F\u0015D]k\$8AW<\u0001\u000D\u0015y'n\u0007@\u0018;ANfx_\u0011%p\\\u0017AN'S ?\u007F=t\u0001A"
