/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.collation.cldr.internal.data

internal val COLLATION_TAILORING_PA: String =
    "007t#e.:\u0015\u000DA\u0011C\u000CmC*jW\u0005Jub\u0002E#Q\u0009c\u0017\u00100X7dwy[n,x&M\u001F\u00093@6+>^#9\u000A7\u0013-J\u000Bv\u001B\u000Al+(z\u00108\u000AZ7@j\u0009VtEPY:}+Vw(1'\\\u000E\u007F&\\[@=\u0019\u007F\u001F\u0007o0,]Y/kPnbb1h\u000B~\u0008\u0002\u0017\u0008@%\u0015u#\u00029\u001EV|\u00123!\u000E\u0017i\u001A')>\u0007y\\\u00085\u000DT+\u000FE\u0008]i'kgWD\u000Cs\u0002am&\$+\$\u000C2i_\u001B7G'CeC6c\u0001[\u001A\u000FY'w\u000A7Cj\u001EyyUAE;\u000B6\u0006@-\u0014%[\u0014E\u0014E0m\u0005Zh=\u000AZriR4UL\u001D\u000F'5\u0010\u0013mlNG\u007F\"xAmN.A{\u0013\$b1[Y\u0009\u0003]4{p\u0001TeY\u0010uYyv\u001AUE\u0004\u0006\u0010_:['bP\u0007]\u0008C\u0017%IP\u0007m6^\u0012v\u0018Cq3\u0016qIf\u000E|>\u0011c4c M\u000C%e\u00159uhG\u0001ie\u00100\\RWyRz\u0018HHa_@pmD\u00109*w\u0018\u000Exo\u001C9r;QFJ\u000A\u0008\u007F!i"

internal val COLLATION_TAILORING_PL: String =
    "007I7u,\u0011u\u000DA\u0011A9\"2M^d\u0002m5m\u0003,[#/&\u0006(\u001CmVT\u001B\u001D\u0004RxhfO\u0013I\u0013b^0!>\u0011a\u001A(h9'\u0011z\u0001\u0007*\u0015>?0S\u001F\u0014\u007F\u0009S6/D=fd|i=fLe6ID\u0007\u0012||KU\"\u001C\u0012\u00137\u0019azG}ln\u001F\u001CdS\u000E\u0008\u0011\$'E1j\u007F|u\u0007\u0015\u00127\u001DCG)\u0012[\u0005\u0012w\u0015\u000DGQXs\u00045\u0007\u0009\u00156\u000E2?S\u007Fvahs8\\I\u0018\$BY\u000F\u000AmtR)"
