/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
@file:OptIn(InternalKotlinxLocaleApi::class)

package dev.carcara.kotlinx.locale.phone.metadata

import dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi
import dev.carcara.kotlinx.locale.country.Country
import dev.carcara.kotlinx.locale.phone.PhoneNumber
import dev.carcara.kotlinx.locale.phone.PhoneNumberFormat
import dev.carcara.kotlinx.locale.phone.PhoneNumberSource
import dev.carcara.kotlinx.locale.phone.PhoneNumberType
import dev.carcara.kotlinx.locale.phone.PhoneParseResult
import dev.carcara.kotlinx.locale.phone.candidateRegions
import dev.carcara.kotlinx.locale.phone.detectRegion
import dev.carcara.kotlinx.locale.phone.metadata.internal.data.phoneFormatRegistry
import dev.carcara.kotlinx.locale.phone.metadata.internal.data.phoneTerritoryRegistry
import dev.carcara.kotlinx.locale.phone.metadata.runtime.AsYouTypeFormatter
import dev.carcara.kotlinx.locale.phone.metadata.runtime.PayloadPhoneNumbers

/**
 * Phone number parsing, validation and formatting over the bundled metadata.
 *
 * Not keyed by locale: a number is valid or it is not, and it formats the way
 * its own territory formats it, whoever is reading. That is why this object
 * takes a [Country] where the rest of the library takes a
 * [dev.carcara.kotlinx.locale.Locale].
 */
internal val PhoneNumbersSource: PayloadPhoneNumbers = PayloadPhoneNumbers(
    phoneTerritoryRegistry,
    phoneFormatRegistry,
)

public object PhoneNumbers : PhoneNumberSource by PhoneNumbersSource

/**
 * [text] read as a phone number, or `null`.
 *
 * [region] supplies the calling code when [text] carries none of its own.
 * The result knows its own territory, so the country comes back with the
 * number rather than needing a second call:
 *
 * ```
 * val number = phoneNumberOrNull("+55 11 96123-4567") ?: return
 * number.region   // Country.BR
 * ```
 */
public fun phoneNumberOrNull(text: String, region: Country? = null): PhoneNumber? =
    (PhoneNumbers.parse(text, region) as? PhoneParseResult.Parsed)?.number

/** [text] read as a phone number, with the reason when it cannot be. */
public fun parsePhoneNumber(text: String, region: Country? = null): PhoneParseResult =
    PhoneNumbers.parse(text, region)

/** True when [text] is a number that could exist in [region]. */
public fun isValidPhoneNumber(text: String, region: Country? = null): Boolean =
    phoneNumberOrNull(text, region)?.let(PhoneNumbers::isValid) == true

/** The territory [text] names itself, or `null` when it carries no calling code. */
public fun phoneRegionOrNull(text: String): Country? = PhoneNumbers.detectRegion(text)

/** Every territory [text] would be valid in, for a number that names none. */
public fun phoneRegionCandidates(text: String): List<Country> = PhoneNumbers.candidateRegions(text)

/** This number written in [format]. */
public fun PhoneNumber.format(format: PhoneNumberFormat = PhoneNumberFormat.INTERNATIONAL): String =
    PhoneNumbers.format(this, format)

/** True when this number could exist in its territory. */
public fun PhoneNumber.isValid(): Boolean = PhoneNumbers.isValid(this)

/** What kind of number this is, or [PhoneNumberType.UNKNOWN]. */
public fun PhoneNumber.typeOf(): PhoneNumberType = PhoneNumbers.typeOf(this)


/** An as-you-type formatter for this country, for a text field. */
public fun Country.asYouType(): AsYouTypeFormatter = PhoneNumbersSource.asYouTypeFor(name)
