/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_ID: String =
    "00OGcUb\u0011u\u0009a\u0011\u007F\u0003<Q=\u0002\$@q\u0013d&LGl\u0008\u0015R{K4}0U\u0016\u0011\"j-!C*'^od\u0012P<[G\u000DQ\u0011t2\u0005\u0006\u0016@lz5mi8F3n1IU6\u001FIVFa&mm\u0019RsR\u0009_Q\u000B8=\u0012\u000E+\u001D8J#l\u0006L\u000DqyjA@1\u001E#)P\u0007fc\u0002<\u0010\u000B\u0010UoR7B(::0KJ`\u0012>u t\u0013C+`r\u0019\u0015bC*e}\u00110]ui,?!\u0010{|[\u0014 |\u0004\u0014^{B\u001C\u007F~-\u0017\u001AR=\u0005\u0011|PjFi[\u0018x}B\u0009\u0011?)8X`Zv1Js2N7kj\u0010MBdAd<Q9\u0009\u001BH~`.W\u001Ca\u007FYf\\{\u0010\u001EsKAiWg\u001ED0\u0011i\u0018\u0007)\$O.JG\u001B3qf\u00102U\u0010h8:NV\u0002\u001E]\u0013q"

internal val PERSON_NAMES_IG: String =
    "00Q5kUb1u\u0009a\u000D_C<1\u000F\u0013QXy\u000A\u0002>'gr\u0010\u000DY\u001BG,]/U\u000D!K1D*EId5Xlvw~.\u001C2lI\u0006\u000F.d\u0001V V}W8-\u0019#J \u0006mV\u0019\u000D\u0013\u0009\u001F/\"\u000Ag\u0012?r|+^Y-[u\\D\u0001eg\"l\u001C\u0014|Jp\u0010\u0014c(6\u001AeZX{(K\u0007nS#M[\u001BHKm>jAi\u007Fag`1W\u0005,\u0017D.N6\u0002qq\u000A[Y\u0006\u007F`W>G7J]\u000D\u0006D:6\u001A-ni~|z(VCO*\u0010@R~lM\u001B2qm` 2<z]C\u001BXP Og\u000C\" Ed\u00037n\u0002e0\u001B5\u001F\u001Ew\u0001\u000E\u0010\u0017l'2U\\f\u001DWPmr\u001Ba\u000FMyE\u000Ff\u0016#)#\u0014OjQ{\"\u001F\u0006i=seC#d\u0011s\u0002E\u001C(tZCgkq^V\u0017w\u0001"

internal val PERSON_NAMES_IS: String =
    "00P3_V\u0002\u0011u\u0009a\u0011\u007F\u0003<Q=\"\$@q\u0013d&LFG\u0010*1\u0016\u0005p}]\u001F\u0015\u0001VQ\u0017G!\u0001utBl\u001DN3m&\u0002kAx4\\:V\u0018_.\u0012!^Rgq\u000Eab\u001BQ\u000Br\u0009O~\u0009u\$\u0014n\u001BE<L!A\$.U\u0005\u001C\u0002\u001CS\$v^\u001Bq;IX\u001E\u000E\u000CM3w\u00135h]_\u007FP1Q=]oST8c\u0014_T:R).=\u00058[VEF\$&qB.\u0014/#\$\u0004\u0010\u0005m\u0018R\u0006^bo\u0013`wE|F\u0018u\u001CJ#>&z^uS\u000B}xr\u0007[\u001E/N\u001D\u0012`/\u0004r~g~2QRPa\u0006z\\s52\u000CL|j\u0006Y\u001CuV|1vu W\u0004Zv-\u001D\u000Dx\u000B,\u0010GaRT/\u0009\u001D\u0009\u001C\u0002WH K)\u00057@O'sSQ\u0008\u0016Z01q\u001F\u0003QF\u001D<T\u000D%\u0016\u0016Ix\u0019!~,\u0011-p@p1\u0006ni\u0015"

internal val PERSON_NAMES_IT: String =
    "00OjceB1u\u0009a\u0011#\u001Ci09\u0002FU\u0016_\u0013%3\\:YHK9[C8_/\u00150kGSA'\u000D\u0005N\u001C_PT\\1h%C_G\u0008Ku\$60d?WE)Gy_&\u000B\u000B\u000C\u0007.uZ#\u007F\u0004[\u000D4+\u0006H\u000BHre\u0015Tj\u001FnW#]\u0007\$E[tX]x\u0002\u001D83\u000EX&:qM]U\u00144t*y\u00049EF\u0008cK<w]\u0007Zgzb.afi7+\u0014k(\u001Ar/\u001F`]{#SdWj\u000F\u001E[EZi!r=3\u001Ac^r\u0011?\u001F\u000Dm ypte}'\u000Epr#\u0019\\\u0008qTF\u0009\u0012f}}\u000B9{(K((\u0014aP,Q8N?\\l1!g\u001Fa\u00070\u00114G>\u000C5J\u0007xX5y(tVO&&!\u0016L\\)q\u0014/\u0013aF]\u0008\u0014M\u0015&\u001EKP\u0006!>8\u001A#-09[pa1"
