/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_UK: String =
    "00d1sV21u\u0009A\u0015\u007FEx\u0012}C\\}CpQC)U\u0014Y+8\u00120\u0010@4-?!\u001DK[ZWoF!p=vxO\u001F!\u001A'G\u001B\u0013\u0008[jh\u0012\u000D:]Q\u0007UT\u0001O6\u00115\u0006>\u0001.*]C\"\u0009G\u0019SgV>:m*m22\u001D;3>e\u0015d{\u0002\"0r-2 1\$M?4\\15v'\u007FS-\u000A~|\u000Fqf\u0017Q\u001Eg%\u001C\u0003uU\u00151>\u000BkVwa:{`A~\u001F`\u0018oC\u001C>\u0006%NOO_hF\u0002/u\u0008N\u0005=LP4gL\u0002Exz\u000E7bxN{/m?X&\u001C*a52\u001D\u000A[5E\u001AeqD,pj\u0016j\$\u001E] !f'Kw'GwD\u000EyTdB^7?k\u000A6(\$=\u001Ac&d\$_{?:\u0002V^|r.~OG}Hj'\u0006eh\u000B:R\u0001l-*\u0001QDI\u0005\u0008'\u0015\"HI\u0015h%Y\u000F-\u0001q\u000AUz\u0016\u0006e\u0017Ayk\u0013Fwz>!l?B!"

internal val PERSON_NAMES_UR: String =
    "00Mq_U^Qo\u0009A\u0015o\u0012\u001Ca\u0012XU\u000B(\u0011FF1SR\"Sc#\"\u0011\u001Ea\u0018l}7z\u001FbV@\u0006m7gK\u000D\u0005\u0005H9~loM\u0003NE\u000D\u0015\u0004-N^#\u0013B-c'v\\%yC2\u000BP\u0019#Z\u007F\u0001\$b,n\"s'\u001BY\u0001-<TM%9eI.9\u001Dy\u0015\u0011I\u000F\u0014:DG\u001C?\u0014JK`\\\u0012|\u0018u]gw\u0018wlqdn>{(\u001F.\u00074Qf\u0012d\u000BIC\u000BETZWmQMz=n+q\u000Al5i+n\u0001{a-4!Y4{X|HRE\u001Er/{{3hy\u0010ue(&T<Q~\u0012h_~sEV\"\u000C\u0005\u0003z}\u007F\\jdvUhaYN&C\u0004J;\u0012\u000F\u000DT\u0005C1IR\u000Ea=\u0011\u0014PKRaUq\u0005uu\u0006<\u001F1NQ6}aa"

internal val PERSON_NAMES_UZ: String =
    "00M/_ebqu\u0009A\u0019c\\e\"b\u00027vCTY0'N2}9K\u0016g'q{+\u001BUl\u001B7Oc\u000ABHz@\u0004\u0008%[\u0002\u000D\u001C\u000Chk(\u001Cs\u0017R\u0015\u0013\u0007\u001C#CM\"\u0001\u0015K-\\q\$1F&\u0012%r\"\u000F]\u0007\u0001*51=\u0007^\u001D\u000F7\u000A\u0018\"*B0\u0005Cbw\u0014\u0017.g[\u007F\u001E-k\u0017Y2.|r\u000D_|<C;\u0009?zl#h[\u0007\u0015\u0010iW\u001FHX[wmq~<Xq:aQ*8e~Q\u000Fw\u0007L\u001F L_\u0012}lgc<<Mz\u001Bcho\u0004({(tRgT\u0011j\u000BRAx\u0012V;A\u0005g\u0006\u0005p\u000FLh?b_f/\u001C@\u00091[QO=)+>%E-2l\u00068%Sr%}la\u00161`\u0009!TgU!3\u001035:m@?9\u001F8#?\u0001\u0001"
