/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_VI: String =
    "00MK_UB\u0011u\u0009a\u0011\u007F\u0003<Q=\"\$@q\u0013d+KA[\\*dIJ`z;\u0011f\u0015%K\u0001\u0012\u0005\u0003S\u000Ft]g3\u001DO=KT\u0001\u0009xf\u001DQ4iU}IT%9zyB\u0006'5sEZQxR\u000C2A\u0019:+K#\u0019Xa`2f>&E+\u001E6hGmh7\u0014\u0004\\\u0002w\u0015%eU\u001B>V\u0012\u0004 uI'\u000C=-^\u0004M\u001B(\u0018\u001F\$9ng\u0006ELpWmR\u0005\u0003hL)!Uzk1\u0018\u000DQ\u001Bz?n\u001CnLlFZjV\u0012\u0010\u000F~!X!0w\u000Cb-<-lSbS6a,\u001C<\u001EWZ0-skN5;GG.(\"mh\u000Ec?7\u0013m.{R\u0017\u000E\"5JCAR\u0004\u000Eb(9%s\u00084rM\u000A-EC2\u0013\u0006!e\u0008FR\u0004mfv~\u0003 g\u0007A"
