/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_KA: String =
    "00YTwV>QW\u0009A\u0015?e\u007FA\u000E[R>\"\u0014e/nZI\u007FC5i\u0019P@>G`\u00185=1)5\u000D!Lyx];>d\u0008l5jU\u0008\u00077QO2\u000757\u0015#\u001ASC\u0001sv,\u00034B'\u0011C5\u0014Lo,^!n'qIcC>8\u000CZm)\u001E[NQ\u0002;\u000BM\u000B96dv]\u0010U.\u0008=)\\t\"\\~\u000B*\u000C&tlA,AA\"'F)\u000B\u000C\u007F\u001Bj7\u0014eDx}h\u000EzOdS\u0001\u0018\\h/L4Qc#X\u0017i\u0011Cbw\u0012\u000EjPP&ty\u001B\u0018D\u000FZep0Y\u001A8[\u001A\u000D\\X@t\u0017^D\u000Aa\$(Ec\u001A\u000EF\u001D\u000A&\u000A*cNy8A\u0008k}\"\u0007N\u0007R{M5\u0006a2wq>]Y(8#>\u0001A"

internal val PERSON_NAMES_KGP: String =
    "00hHwe,QW\u0009a\u0011C\u001Cm01\u0002.U\u0016_\u0013-.9c5 J.QQjfx\\\u0015F\u0017\u0018iBk\"Y\"\u0013#-m43>R;l)k&E\u0015OW%Or\u0015']\u0003ik6,y}^KJ\u00147+k\u0014<-\"VU 8C};eM=NAWT|\u0004<&eI[*Ex?<`>\u000D!\u007F7\u00019gX|\u001Br=\u000F}g.-/gLi?M{Llme\u0005s1D`\u0015oj]\u0007bymL\u0001#n\u0005&6U(\u001FAT9\u0003a&!eUU\u00199]<k\u0001Yb-]\u0014x8\u000D\u000EqI\u001FA"

internal val PERSON_NAMES_KK: String =
    "00I5ceBQu\u0009a\u000DC\\}(1\u0002NU\u0016_\u0013!))nmDD\u0009~\$\u0016ox!\u0005\u0005+\u0011\u001B\u0005genWO|V@;^\u0004\u00066\u0005{vS\u000E2%Y#m\u000D\u000B\u0007\u0010u62{E/\u001C%\u0011\u0004R\u000D0&po\u0009mkCL[%\u000CI+\u0006O{I[A6\u001A/9\u001A\u0018G\u0003o\u001F#\u0018S<fO\u001F6d\u000E&2\u0006<O+f\u0004\u0002{sA<ayE\u000D\u001E5_GIR3\u000C\u0019~5\u001Az6~FPu8=3\u001E\u0014-c1M'n\u0003>i89T@\u001FD\u001F\u0017\u0016D\u0015HAg!EjH\$6-n(%|ps2\u001E-&\u001BtJ\u001B|#\u000Av6!\u001Ces\u0012\u0006\u0003,%Ke\u0014\"3ptn_U7x@_"

internal val PERSON_NAMES_KK_ARAB: String =
    "00IGceA\u0011u\u0009A\u0015D\u001Cc/y\u000Bjk\u0006(1OON\u0011\u0002DwF-15uadS/\u0012S/\\'ZrAofx\u007F?\u001FhB M'K\u0006JF|,\u0011\u0006,.d\u0003\$*/r\u0013| A2\u001C!\u0019R\u000C(\u0015\\Ku3(TX\u0009eQ/-WAvGz\u0004)\u0005C%F.32\"\u0018T\u001Fso.[lv\u001AlGU9T\u0016rh:V\"&vZr\u007FE\u0019\u0017]&WS\u0018MCw\u00182\u000F@.R\$n\u0006p^\$`S6M#\u000B\u0007&)d?L\\N^]_bb?5iG\u007F<\u0015\u0018()D\u001900*\u0017.q\u0015p\u0007j\u0013C\u000A\u0011\u0013:\u001A\u0013\u0003Jbb9KC;q\u0011A2s*%)e&\u00027h2v_A<\u001EU\u001F"

internal val PERSON_NAMES_KM: String =
    "00OI_V\u0002\u0011u\u0009a\u0011\u007F#<Q=\"\$@q\u0013d&DGl\u0008\u0015R{K4}/UC!\u0016R\u0002\u000DC\u0002j(\"l\u001EN'm(/)\u0001:[K\u0013+}|F2>3b\u000B&rr\u0012)i=\u0014l<B\u00142Y1!f#2=f7=qE6\u001Cj[&\u000Ch.QWmd8\u0016\u0010/\u000C\u001A\u0003lTU9\u0007/\u0013\u000C\\z\u001D]fr\u0001}\u0015/X\u000B\u001Bq=\u001CL\u007F\u000C\u0001A\\~v]\u0007\u0016\u0005v*]x\u0014\u00098/a4fS\u0011HYna,\u007F)py[l4^x3\u000B}x\u0014\u00153|/\u0006shA4\"g#\u0001\u0016Jh\u001F\u00078@\u007FO\u007F\u000F\u00193\u007FhgD4E\u001ADX\\\u001FxFczi8^jj58)\$Bf\u000771y@1\u0010X\u0009RP\u0011jiUUb\$DEqJ\u001D\u001B&an)\u000CAw2EC\u0003Z\u001Ar!\u000EV3vnf/\u0001oo\u0008!"

internal val PERSON_NAMES_KN: String =
    "00OAcf\u0002Wu\u000Da\u000DC\\i(e\u0001en^qJb\u0011X'z'h\u00060d\"8\u0015^Fh!\u0015!m\u001C\u0007&\"!KDzs{?=\u001F\u0003)U\u0016>\u001D\u0001{UH\u0008t[_&\u0013W.%`&3\u000E\u0007+'\u000E~\u00088\u001Cg\u0015\u001A:\u0013+\"*xx\u0011Sr8,\u0013gVQ[ra_,\u000AM\$\u0008\u0003\u001C\u001C\u0002f8*)+{JJy0=Ao\u000B\u000FV\u007F_,*}\u0010_?1m'k~wf\u0009!U{\u000EF\u0001\u0004Oj\u0002\u001EZF|jt_\u00113\u001E^xo\"tw\u001B*l\u0007_-,\u0010r8lp\u0003\u000B\u0014\u0010p\u0001\u0009%]_(Gd\u000C&Nq5h`\u000DcNX^M=[=-t>\u0008\u0017\u0017v\u0003\u001Dsn\\@*f8b\u001E9cM|E/\u00164]\u000DP\u000A\u0008CiQ\u000A`\u000BQC~`CrRCR7\u0005O!\u001Dx\u0017@*_a0@\u0004\u0019"

internal val PERSON_NAMES_KO: String =
    "00HMge,1u\u0009a\u0011#^m'9\u000D1v\u0006lUI\u0009\u0006\u000E{\u0011 #\u000C0(=FCc\u000D+#\u007F\u000E <5X\u001E\u001D|=\u001C\u0016;K\u0005)# ~i\u0006{b_\u0015Lw+\\W\u0005\u0008\u0017\u0011\u000C\u000ENju\u000B\u001BVU\$\u001DG\u0012\u000C9M\$H(\u0019\u000CLaz\u0011.;:(\u0005fc\"H0\u0017Y]5,t\u007F(}\u00080%Z5<[hi'N/\u0014a\u0002Z\u0011}\u0009j9{M6]-eD7\u000B(\u0006N@\u001AXc2pgVGItv6chd\u0006=\u0015W>O\u000F\u0017B\u0011i\u001BS\u0001J?\u0002ar\u0005H9\u001D\"\u000E9l\u0014-%\u0013warG\u000D-7\u0019_lw\u00041HNa"

internal val PERSON_NAMES_KOK: String =
    "00Ps_V\u000EWw\u0009a\u000D_S31\u001FBSqC<Rj\u001B\u0018\u001B\u000A3\u0001uSP\u0009\u0017s|GI\u0017C\\E\u0012[\u0007\u0006,7\\E@ PhU&pC%D\u001CL<\u000B\u001F;\u007FFi>\u0008V.\u0004b\u000D2)Z6V5q\"\u001B\u0017\u000F\u001C|S2!|!MB<)(&7^\u0002.G\u0016e\u001Cb\u000A+>\u001CGKS/&SB\u000E\u001Cl!V%\u000F)pY;y:C>NdGR\u001Eg%/O~\u0010Cp6\u0004@\u0003\u0018)f\u0004cZz\u001D;J}~X\u0007\u001B\u0019EM(\u0011\u0017<b\u0011 7vSK%\u0016\u0014\u001F\u001C~sOgM:nuW|\u000F+J\"gW\u0015e?\u0010\u000B)8:zbYH\u001E~\u001CeO^\u0017c\u0019ki~m\\jOr\u0013DP\u0019?5rN\u0016\u0004pHiC_\u001C\u000B)cbhM%ul;qg\u007F5n?\u0010|}\u0004'p\u0001\u0011zp=\u000Azxf0\u001BU|\u0009C{cUa\u007F\u001F\u0010G`a\u0013 x\u001A}\u0019E"

internal val PERSON_NAMES_KS: String =
    "00hPwe,1W\u0009a\u0011#^m'1\u0006.U\u0017o\u0013-\u000D9k5\u0008s5;\u0002\u0006x8KSC\u001E\u0019>#@\u0006\u0011e\u0002JKt\u0018o\u000F&\u001DF\u0001QD6\u001A\u0009\u007F4h^|b\u0012mv\u0007N)\u000ELRit-eAR}p\u000A%_Q~_,7D.Zd)\u0016\u0016\u001E9\u0009_?GHQM(,l^~lcH\u0014\u0001\u001CO2=F\u0018tqpk5jawX\u001FLubV`_\u0007\u0011@\u001C\u0001\u001Df';ny3\u000AFzYC\u0015i7[\u0018WB&s\u000A\u0001\u000A\u0003(1GR\u0017t\u001DC*L522 W5\u0016\u0001@UWoy\u001A\u001C\u0013\u00188a\u001D"

internal val PERSON_NAMES_KY: String =
    "00atwV\u000EQu\u0009a\u000D_c>1\u000F\u0003QXy\u000A\u00125f4ZD\u0007\u0012A-`9])E\u000D_y\u001B\u0012!33;kf=_~7Nl7\u0007\u00073\u0004NYZ\u0017\$]\u001B\u0012Nl&\u0017\u0005\u000E,_P\u000E\u000A2B3!so,>Jh\u000E_Y-+\u0006\u0016\u00176\u000BM\u001DXk=`9v\u000F\u001CdBmP`z\u00176{)>\u0015\u001FL\u0010BVc\u000CV VVa\u0003\u0014\u0003\u001AsU.\u0015\u0008i*\u000D)\u001Aj\u000DI\u001F\u001B_q=#T>nE+3SO`N(W\"zLy*\u0010f%9bu\$~\u0008~tU\u000Ab8I\u0007B\u0018}/\u001D=|q\u0002Ef\u0001WIMqUc\u0007\u0013Q\u000DB_YI#.!\u0009z\u0012c\u0017AZ<9{oa\u001EnkX"
