/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_NB: String =
    "10:other=00 mrd'.'\u001E11:other=000 mrd'.'\u001E12:other=0 bill'.'\u001E13:other=00 bill'.'\u001E14:other=000 bill'.'\u001E3:other=0k\u001E4:other=00k\u001E5:other=000k\u001E6:other=0 mill'.'\u001E7:other=00 mill'.'\u001E8:other=000 mill'.'\u001E9:other=0 mrd'.'"

internal val COMPACT_SHORT_NE: String =
    "10:other=00 अरब\u001E11:other=0 खरब\u001E12:other=00 खरब\u001E13:other=0 शंख\u001E14:other=00 शंख\u001E3:other=0 हजार\u001E4:other=00 हजार\u001E5:other=0 लाख\u001E6:other=00 लाख\u001E7:other=0 करोड\u001E8:other=00 करोड\u001E9:other=0 अरब"
