/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_MK: String =
    "10:other=00 милј'.'\u001E11:one=000 мј'.'\u001E11:other=000 ми'.'\u001E12:other=0 бил'.'\u001E13:other=00 бил'.'\u001E14:other=000 бил'.'\u001E3:other=0 илј'.'\u001E4:other=00 илј'.'\u001E5:other=000 илј'.'\u001E6:other=0 мил'.'\u001E7:other=00 мил'.'\u001E8:other=000 М\u001E9:other=0 милј'.'"

internal val COMPACT_SHORT_MN: String =
    "10:other=00 тэрбум\u001E11:other=000Т\u001E12:other=0ИН\u001E13:other=00ИН\u001E14:other=000ИН\u001E3:one=0 мян'.'\u001E3:other=0 мян\u001E4:one=00 мян'.'\u001E4:other=00 мян\u001E5:one=000 мян'.'\u001E5:other=000 мян\u001E6:other=0 сая\u001E7:other=00 сая\u001E8:other=000 сая\u001E9:other=0 тэрбум"

internal val COMPACT_SHORT_MR: String =
    "10:other=00 अब्ज\u001E11:other=0 खर्व\u001E12:other=00 खर्व\u001E13:other=0 पद्म\u001E14:other=00 पद्म\u001E3:other=0 ह\u001E4:other=00 ह\u001E5:other=0 लाख\u001E6:other=00 लाख\u001E7:other=0 कोटी\u001E8:other=00 कोटी\u001E9:other=0 अब्ज"

internal val COMPACT_SHORT_MS: String =
    "10:other=00B\u001E11:other=000B\u001E12:other=0T\u001E13:other=00T\u001E14:other=000T\u001E3:other=0K\u001E4:other=00K\u001E5:other=000K\u001E6:other=0J\u001E7:other=00J\u001E8:other=000J\u001E9:other=0B"

internal val COMPACT_SHORT_MY: String =
    "10:other=ဋေ 0 ထ\u001E11:other=ဋေ 0 သ\u001E12:other=ဋေ 0 သိန်း\u001E13:other=ဋေ 0 သန်း\u001E14:other=0 ကောဋိ\u001E3:other=0 ထောင်\u001E4:other=0 သောင်း\u001E5:other=0 သိန်း\u001E6:other=0 သန်း\u001E7:other=0 ကုဋေ\u001E8:other=00 ကုဋေ\u001E9:other=000 ဋေ"
