/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_BA: String =
    "10:other=00 млрд\u001E11:other=000 млрд\u001E12:other=0 трлн\u001E13:other=00 трлн\u001E14:other=000 трлн\u001E3:other=0 мең\u001E4:other=00 мең\u001E5:other=000 мең\u001E6:other=0 млн\u001E7:other=00 млн\u001E8:other=000 млн\u001E9:other=0 млрд"

internal val COMPACT_SHORT_BAL_LATN: String =
    "10:one=00Kr\u001E10:other=00Kr\u001E11:one=000Kr\u001E11:other=000Kr\u001E12:other=0T\u001E13:other=00T\u001E14:other=000T\u001E3:one=0H\u001E3:other=0H\u001E4:one=00H\u001E4:other=00H\u001E5:one=000H\u001E5:other=000H\u001E6:other=0M\u001E7:other=00M\u001E8:other=000M\u001E9:one=0Kr\u001E9:other=0Kr"

internal val COMPACT_SHORT_BE: String =
    "10:other=00 млрд\u001E11:other=000 млрд\u001E12:other=0 трлн\u001E13:other=00 трлн\u001E14:other=000 трлн\u001E3:other=0 тыс'.'\u001E4:other=00 тыс'.'\u001E5:other=000 тыс'.'\u001E6:other=0 млн\u001E7:other=00 млн\u001E8:other=000 млн\u001E9:other=0 млрд"

internal val COMPACT_SHORT_BG: String =
    "10:other=00 млрд'.'\u001E11:other=000 млрд'.'\u001E12:other=0 трлн'.'\u001E13:other=00 трлн'.'\u001E14:other=000 трлн'.'\u001E3:other=0 хил'.'\u001E4:other=00 хил'.'\u001E5:other=000 хил'.'\u001E6:other=0 млн'.'\u001E7:other=00 млн'.'\u001E8:other=000 млн'.'\u001E9:other=0 млрд'.'"

internal val COMPACT_SHORT_BLO: String =
    "10:one=ŋkl 00\u001E10:other=akl 00\u001E10:zero=ŋkl 00\u001E11:one=ŋkl 000\u001E11:other=akl 000\u001E11:zero=ŋkl 000\u001E12:one=ŋkr 0\u001E12:other=akr 0\u001E12:zero=ŋkr 0\u001E13:one=ŋkr 00\u001E13:other=akr 00\u001E13:zero=ŋkr 00\u001E14:one=ŋkr 000\u001E14:other=akr 000\u001E14:zero=ŋkr 000\u001E3:one=kt 0\u001E3:other=ɩkt 0\u001E3:zero=kt 0\u001E4:one=kt 00\u001E4:other=ɩkt 00\u001E4:zero=kt 00\u001E5:one=kt 000\u001E5:other=ɩkt 000\u001E5:zero=kt 000\u001E6:one=gkl 0\u001E6:other=bkl 0\u001E6:zero=gkl 0\u001E7:one=gkl 00\u001E7:other=bkl 00\u001E7:zero=gkl 00\u001E8:one=gkl 000\u001E8:other=bkl 000\u001E8:zero=gkl 000\u001E9:one=ŋkl 0\u001E9:other=akl 0\u001E9:zero=ŋkl 0"

internal val COMPACT_SHORT_BN: String =
    "10:one=0 শত কো\u001E10:other=0শত কো\u001E11:one=0কো\u001E11:other=0কো\u001E12:other=0 লা'.'কো'.'\u001E13:other=00 লা'.'কো'.'\u001E14:other=000 লা'.'কো'.'\u001E3:other=0 হা\u001E4:other=00 হা\u001E5:other=0 লা\u001E6:other=00 লা\u001E7:other=0 কো\u001E8:other=00 কো\u001E9:other=000 কো"

internal val COMPACT_SHORT_BR: String =
    "10:other=00G\u001E11:other=000G\u001E12:other=0T\u001E13:other=00T\u001E14:other=000T\u001E3:other=0k\u001E4:other=00k\u001E5:other=000k\u001E6:other=0M\u001E7:other=00M\u001E8:other=000M\u001E9:other=0G"

internal val COMPACT_SHORT_BRX: String =
    "10:other=00बि\u001E11:other=000बि\u001E12:other=0ति\u001E13:other=00ति\u001E14:other=000ति\u001E3:other=0के\u001E4:other=00के\u001E5:other=000के\u001E6:other=0एम\u001E7:other=00एम\u001E8:other=000एम\u001E9:other=0बि"

internal val COMPACT_SHORT_BS: String =
    "10:other=00 mlrd'.'\u001E11:other=000 mlrd'.'\u001E12:other=0 bil'.'\u001E13:other=00 bil'.'\u001E14:other=000 bil'.'\u001E3:other=0 hilj'.'\u001E4:other=00 hilj'.'\u001E5:other=000 hilj'.'\u001E6:other=0 mil'.'\u001E7:other=00 mil'.'\u001E8:other=000 mil'.'\u001E9:other=0 mlrd'.'"

internal val COMPACT_SHORT_BS_CYRL: String =
    "10:other=00 млрд\u001E11:other=000 млрд\u001E12:other=0 бил\u001E13:other=00 бил\u001E14:other=000 бил\u001E3:other=0\u001E4:other=00 хиљ\u001E5:other=000 хиљ\u001E6:other=0 мил\u001E7:other=00 мил\u001E8:other=000 мил\u001E9:other=0 млрд"
