/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.intervals.internal.data

internal val INTERVAL_FORMATS_VEC: String =
    "00UK今᝛恦ࣈ㉹ᅘ囡⊵姀砖圑ࠁ緧⠁ဠ⡫箏ㄝ腉ắ瓉႗㺺ઓ矙夦憏㿃绽䞿矖濽䚮⿇葦⫆㻊刬䋂喍㬾尒⯰䷽箛瀴淣䍤∔簛᱌ᬦⴹ㻼蔎Ⱉㄔ弡㤒綩昖⣂氽⤽䅍槶䎝䯅茑䆆┖溪∾╪聯臄㌸焱䍅ᵭ欜䓴ത湢㔏妛蝻婭盀絢挕䕟䞼奢ㄎ㋢臻╨⸅犸ᒛⲭ岈灤⃆栣᷈㲆ᡫⱀ慐༓綴㖐ᄾᛀ槑笌⎜䂷ࣳ砾㬕㟵ↈ㌁皃搏眀ఖ緖祼⻵慑撷戨尻㩢夰㖨河悘⋊葪䜌掜稳碿䬙㚂攀涸஭蛯㹾⁀䲦纖䀟櫸⺵杓倛螐徑甡㨳粽ൽᦁ䍔嶯耋㳹縤䊑艃⍌簁傦憏㊼ಇ咞燶࣒紒ⴅ䒡㑎剣Ꮕᳯ勭╥指吱⤱ⱥ䈦笃掀㣧栌ᠡ寴฀"

internal val INTERVAL_FORMATS_VI: String =
    "00UD亪ᑛ悄इ案瓨眬㝩ㆭᚦ㓗㿎ढ㞜スᝎᯎ洊庽㥇刈艀淲僮᪘丰硘᷆⏛✚帋ู➯⎵蛻㽙泷⚟Ẇ䌴ẍ昝㞟枿絃殭ᤅ䤤ᕬⰨ㲜燪㞧契㢌溙卦女ᚵ㚙伔缎回ᔪ嬑ਉ氽犍⪤ℇ⎉⢚梬㜻筳盖曷䒢舀囓₇腕㜈穵㚕।㱄᜖⏫涑膬箃㟼疛䋔䅭怀⡫呢嗭㼔糴㏓䆡爡薣史᧕摽屈䨗潙ಊ⫁椤乨㼄嬠⬲™ↂᔛ枵㬪⭀ᡍ䶅ఀᢦ恫懭ᗡ岐互䊡䔌⟏燘肱ᨘ໑狈㪡⮮摊㙨ᔃ䪍堆匜ᷳ㮂窄䈏怶㍰Ⴡ帚䩳炼蔝䘞∢斁棛㲖玘琧㊭ࠒṑ奉⥞䬛⽑䡧俇乒ᒡ腈ᠺ㇤ൊ㢁㘩᠏䳔ᇁᖪ枅䉔蟧緢ㅗ碎甦ધ᭗寮啖⼱↽攐武ᖮ煅᭶臚ଡ佉聵咎⠓ᦼ苉㟼➀"

internal val INTERVAL_FORMATS_VMW: String =
    "00TF今ᑛ恦ࣄ㉻ᅜᛑᑶ續ဤᣞऀ㧠⢠შᶂࠬ囹気崴窔乑墓ᤕῄ虾㲚ਟ典蕟勽湯◕竹蚽床䜛ୗ櫣荽癷䁌澑簛Ⱈ㳄ᘝ᤯箹⪐態⒢ᗣ㊻⵩⟴塊淼萣ᱜ蜐簍䧈࢐㆐焇⊇⒟䵮㦦㬭※ṥ盎䪠䲹᚛㲸㙆ᄻ㿺⛎ᤝ苊௣⸱丽廼䚪蝴紽䳇孺奓毖儐⽛癗ં潭罎畱苆奤⡋ᄺ玕梴墁媀෠ᔠ旑丣㽇㣎䠱ࠨ信爎瞀笙࣌䀦㹣⡰፸㯴仉㋉ᮐ殀䤛查孼沺搱潏↺瞗桳珠䆧摬莛子㫲઺䴝䵖扭ঔ㟫ᖠ抋婟ࠂ薮嘳早㾯䍂ᱪ᷈愜④綞據ፒ媵汙ᵑỐ噬⿳垳毈䙭ᒟ⩿曘蜵倏江⥪㪷ಔⱻ⣢ဲ䵯劲肝倏蚒秓ᕉ䑘ᢣ綢筳嘦芩೔菞蝻絩籛ᷧ仯纱㏌旭㭿᷼଀"
