/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.intervals.internal.data

internal val INTERVAL_FORMATS_RM: String =
    "00XE亪ᛣ恤ः灍啳ব皻㫒㨅ᘑಂ绣䠀り劻䊇㒝腉Ⅾ耆ᜟ㹉⛷᜘☧揿朿᏷苲䙟荻螽✗᧞搠篲ཀ蔆ഏ䍬ᚅ⍉⏫ㅲ廻熹椹ᯧ⸉挌畨烍莅緷瑀槆㍐簵䱊唪娗⳧剳⛣⬦╷目湗时娉Ⴀ㴱䥍戵≉捆㯦ᩕ摔能㊯姗厺燯ᵖ乍㓪徤痋ㇼ嵎፾㎧㩻ⵊ浔窹➸殭䓃㾯㎀⍫䖴夢抭孀ḛ⠞㎉➞瞥ᕂ䏨⬷䤒亲䑳⤍姱简帡⩨⨬ᰂ䫺᤾෿菈ᆤ୷奋㲤动຦㭁㉈ⰳಌ㵩ᤰ ⼃䎞᎗䴱㭊窻紥炂䆢⩢౪構㾐䘴∃攸椴❠❸㌍竮寳䓧㺸ഘ䣐粓擄絒夘࣐ᐧ〛မ䯒ᴎ❰䤦䑊㢽蝂㤲塖憭ᬺ᎞艒稅毈䢼羰ᜰ吇螖ᘮ䴛⮏᫑⦡⩒腞流敔ᡌ蘭㉬ 灺坚泭渆罦⠆㑉怒ぞ⤺㷈⢞䨐㤑ᶗ儉蜋塸潉䷼"

internal val INTERVAL_FORMATS_RO: String =
    "00Uc努ᛛ恦ࣃ瑊桶䠡⊵姀堖圑ࠁ綧⠁ఠ⡫㮏焝腉᪭ᖗ艅㈟㻹眉塤⊗㿳狶䙿㛦篯藲葬㔖ᬌ璸⫩蛡⡦畢曘ᾜ喹䫢ᲅ欴䀯⽌㉌ᔰ幉㹛死苷堲㖠舡ᤘ⡟籋ᨉᤇⱹ毭౞玸撪系祵ፂ剐壊猉應瘃薖畤揜蕁圛呱ᠾ篜ᆼ筷⟭懘჏ᇎ᠈⩵側䛔礳学⒃媗蒃㞘㲥㢶帢⤫綴䤥抰奁ᵕ๩㑦㊪嫝吇ⴹ癋ℹ႔ェ刱ⵀ咅▖胻磱偕ᆷ樢䩹ឍཡᙔ㮿櫑稷盱䑏耝ཤ೗晜஻桁喤㸇ㄹ勈䳀狖竳Ώ暒廼䨨杽感ᆗㅺ搘ࣔ༼⠩䠰䗖炷瀸ᓻ玂ᓧ梆䕰ᦜ耊瘶』ルᢘ⃈ผ㢃ସ⒐Ὺᵮ厜ክᵞ丈旬㍠㺿ࠓ㇀え耞࿬➃ᏼ਀"

internal val INTERVAL_FORMATS_ROOT: String =
    "00TG今ᑛ恦ࣄ㉻፜ᛑᑶ纴ဤᣞऀᇣ歄ଐ⡀獧ធ◲儵⤡ᵩⳉ䵋㤿ដ㚉៭暿翧磺䙖螼蛯埩咳䮮㓂寑❻ᾗ㽸呡ᧂᇾ䊔ㄏ⑛␣萩弨⬳䳖䀲姏蔳䲔䂒䠡༠ᩁⱽ氝劜㬸Ꮬ篘箞⩷埰笸㭂婠⹎嫱〘Ⱉ枈⨝䨻࿈㟍₤ᣵ揶絑聳ᶜ䳷孲娟御ⲡ嗔搫ᶅ䦻悧⵭蓈徦⡱匧剥⢈梂媀ᶀᒑ盋⩑䌣䡔䠪䤀㛾縀ↁា懫⊵曺漒ᇞ፼兰䮢㲄⣴ㅲ淾䉝ℨ綯僳㸮叅緿㓣虶㷽藄ᴵ౞梎䭫㵖墛⿥竘䕩瘢⢃脶咷儣柪糜罅し珉㨄ミ漼獬㕎竗㧤ൄ茒䆑⟞䚫ᝡ胔㫿凶荃瓎⠌ᶸ䫜汫ᇠႚ槔ᡭዛ᭷砄᥷纲ᇓ䕡⡄⊊䭓焺沓ᗜ艜䗽㶱粻薿勋櫷㌨旮㪸叞槰"

internal val INTERVAL_FORMATS_RU: String =
    "00VT努ᑛ恦ࣇ汊榽䐕⥝▃ਫ ⱁࡺ菐ࡂ႐廴⼃蚀禟尝窃茄杒僙ℒ⫋㹴噧ᙆ䲑牎ῳ憮厓䔾柋ⳟᴺₛ皺䙜᨟㽝蜆ॆ↝纆⣥⻌ⴱ㳏ᱯᤏ洅ℂ緖䌡ᮥ獿㿝㙕⊏伧⌉ጄ巆㦆ᝨዖ㓭ᛱ埂⋰䮳ง㱯㰜笑毱葮ଠ沃᜶⨇৔筟殙䔱妮碴蜘篮蓝匆ቬ笵䂼埝㼹㑤婏熈絔ᮺ汮䅓❊㤣㨧㈟♥懙渢຀狳⇀牌ⵗ㜗漃∬㊙䄪橂㖒嵇拼摘碝☊䵻㭤ᵯ漣㻪ㄩ੩⮔問疟緥暂ↂ蘵焟碉䠝፞ᆜ໼㿶臅Ე䀠௴昲斸唈䗛寉䯁墙帋玝牢☤溃䭽ㄘᔯ⚀煥縱⢘ඣ♐㸷⧒倻礀㊂瘘媨㣀商爁⸀๨㈰ᰏ⵸⣔弬Ⴖ済悖ౘ㬅䝴઩ᱢ㗴೤掬ᷯ埡ဨ⠪䱬䵛ግ〕㿱㗩嵛劦ᦗ搋芘਑⛊ྭ撪㈀Ⴡ―ᐂ耀"

internal val INTERVAL_FORMATS_RU_UA: String =
    "00UT努ᑛ恦ࣇ汍䍺耨䪻䌆ఖၾ傂ࣵ箠઄ᠠ㗨噇蔁笯⠻紇缋䒤ᄒ繬喔璩᱆⒍ኧ氝㞧㭻㞍⃪蔽✴䡮橨⍛蓡硻勳昜ฌ㤸┌禔揱撅䬬冼䬾⹏吔㐳慉薝忆珽腫㫨籽㬽梽㢉㡄䋅甂捋ᔱ碤㘉掐ᦖ㲾櫚㝺䀜ཧ孷煰⿙磌䧣䌹忱⸮湴䋞ፏ蘶綻㜨ᔪ恤㵱Ⓙ孮⥐泤埗ᇫ屧䊈噲ᬾ扪⺢᮪៞㪳旌⨯⃏蓦荆㤩䛺苡㹀ප溥咐左᪘絔㖼⎗琿眅⺻㭠ᵯ渣绕᫒Ⲳ伩ખ虿揞茋㪄શ焟秣ᠪ᭯冮๡⍛⑑ᴵโ෡ᾌ幎᭩潛䙲泠㺓᫃䔰矍⮄懃禾公ầ坐㺙䔝墘ു缞縷䛢值糀᳁㢌宨㣄䵣⪀ㆄ඘ଜኇㅞᰊ䫭⹀憪㈐㰳䪺㽰⾷ᰍ浵ᙐ㻟蓰䰫䰎ዳ光歒舵☡偬ί娂䟲䡓൐䖞⦂痰ᜀ"

internal val INTERVAL_FORMATS_RW: String =
    "00Sl亪ᛛ恦ࣃ瑊桶䡭抵㧀㠆屈㡏༂ᰜ⤄࡙⛳倯㉩洩ῒ剙⹟ỹ睑礣肛䕿瞪楾♎虯矻毴湓畊᩸漑蚀硑෭㡜ಟἚ窵伧䆄⒉ෳປ♜䉃濒㸡空᧠ೄ⦑䍛⨒厂ⱚ⹭᪉䰟㞂篼缕㼺䓷⚇搤ᰅⴝ㩵Ⱉ⮩寛䢽蚈潃ᤫ䓜䕡⧖癆嚸㔒ᅺ硪藲㬽㸌嵝ટ⇖᫨歲動ⶥ₡༥烽Ⴆ⭉ⴀ孖脕ं娹㇝蒟㱕斜尔䈻徯ᛍⶻㄶ奱✙┾ᖩ㋆峚搣耷ङ亙⦔㑨஋㨒羞㍁彀墤缸稊蝟⎊ॹਝ块笹㙈᧋薅簺㈎৐荝㋄ঠ喙护ഃ句叒⠔拐蒕帑啹妕蕞涬倂晾䢙䄘潚撬丁甄ⵐ㻠᜼䰃㊒憻ཱྀ⁗奢䱋䦴㈄∖䟚ᮮ䃬湆悰臘䤈宰挃葀ࣿ㿭櫲ூᾓၗ狈㤿㕣᲎৶傓㖆㧤ৣ腵䉞搓㶪滓嘢爴৲䥂❯圜㜟䏯砀"
