/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.intervals.internal.data

internal val INTERVAL_FORMATS_CA: String =
    "00XT亪ᛛ恦ࣃ瑊榵㨅⽝▃਻ధ䱀ࢿ䥀䊀ဂ㩶漠蚉比削湙ჺ瑧䁢㧉蝓∭翯翇矹腻杴♿眗凚䝵㢙舜⢭䣠ᩓ⪙耖ᙕⓄ宗മ⏜伤汬欪涺纾懝䭾㔙戥㲯ࣩृ檈現਱ᡇ⡳ᔜ仃掸滭⪻ᙺ♒洁⨗䷤叄縴罗戽♲஗ᷪ臓㹖⓺✸矤繞㗧䦣攁⡀㰰䀋㥗९怸菖⭢痞↖婆浇⻏值Ꮚ幉㛚䴤艋䮪⥄ᄎ⦼㏋ḛ冈峆嫐䁕殗Ⱑ嗚࠴လ㠘㟧ⷢ柃଀⎍戈ഈ緟憼⢝㕑㷆渙ੲ䗅慠䄄ᠧᔀ⊦䀪㝻ⳍ䣓⨀⦤渮䭯䕞腬灍ᘠ䑬伆㳗Ὢ㉠䄇曄ቨഘ⸅抟䢆娸ᥨ☈执भᏀ紇叏坐蜞柝௶䳕ᗠ㎇喤勉歱ᬗ庻䇝坳൞太㈱䃎॑後瑫歁อ䑡潯桁㧐热ᇙἹ➳ṧ᫶仴䜪㚭烢䪀狷峲᝟㞞Ⴛ䝠䉨唋唗䕣砀"

internal val INTERVAL_FORMATS_CCP: String =
    "00RG今᝛恦ࣈ㉹ᅔᛡ⑶續ဤૃ琨࠹䓨ࠢೈ甜䧺㮮ㄨ墧屮箓᪘瞽沊㨼癟⍐苞署葝➧㻟ቓ㮓獱萆Ꮏ碬৮㴅摃ྋᯣ畾繰汭㧆笡䜱涙浭倛濵硌ထ眔栚ἠൂ粅倚舭ᷜ㇧⋯ᥞ疅䉌穯ᚈ樳积䭑⤽绠使欃ⓙ⠽戢傰舭聞ẝ㎫≴㼑㆞㝠㖖䘽聩呟䒹ᯇ❿㧉愬ᖑ↱徸⾔⸘ᐍ⣃䦊姬獛奖ᬍ䌰㨉፜ᕑ翄䜇⊜䄗吹纞⧜⭼⟼᧲ᝐ⎸ྺ㌼㜦㚱ែ嘺♵幩桜泺⚀劕⊔虃ੈ⤅┪朕粴巋〒ࡖ廀繉᭎ম浒፽ᛝ筃ᇲ旊䱐娹焢䨴膴炥ṷቘ㴓䱈菤ᦣ厏ுℂ⯆ᖜ咰৊卲槠ᱫ彖⚊搕熘悉薠䨕䀾吔ᇞῩᴇ☚〚尒ᙏ偈允孎ᶥ㋪ㆠ糁凳崄⪡㴉㈕┢䎚厢㽈悞ᱻ蔃䠀"

internal val INTERVAL_FORMATS_CEB: String =
    "00Tw亪ᡣ墄इ桍峹䧅瑞莴ᒤㅧ萬Ⱈ摹ࡍ᭸盹垙⟦䫵區嶤ᇢ櫨嵑⍺᳓燺螿篎䓿旷蓺蚺᳖洵⚘ὂ揃䡉⺗ᾀ摤旼㸡〺㬷⃳礎哂䋛䍥䖷⼍蕯纠㊛⡲ऽ᧤懋መ脧䥭᜿欻㴃獸㽳ᔑ暁壴㵃窊归ᒝ㦦᪜仕䳹匼䅲䙠擢篟喰祚େ肿䯷ᢖ൰ᵽ⮥岴⎧⛩蚔咨㒒粼塑皘䩉兑碪偧ᴬⲬ⨹Ꮫ橂兠䰍ᮽ捐㊕敩娺梭墆壿ᑀ㚢᩼梳૧㩧⬞䋲䖄⇭砜晬碩⼉狠堯慥ᝰ狙䞈ᾆ绉ॺ㢎┽⵩憭羞螂榃礪檻磂嶝刴泈牘ḸⰅ伤ᬃ༣簬礦䯌墨ᒇ披塲㉚ཡ⛡偍䃤ໜ⊃උ䪱㔪厂禱Ⳛ仦蛂䇋堥㑚ୄ䚠蓽ᰟ䝟栀"

internal val INTERVAL_FORMATS_CHR: String =
    "00R4今᝛悄ई㉾ሬ❠稶㺥᫊艹䨒淋䬌஠爥揔擤⎙ᩰ偤殗➰ㄶ減毀⡭臯䊽暶螻篫芘匿ⱂ棩䍴ࠤᘦᛛ蔱氾㚪ඝᖺ儹嘏ᚪᴎ伣㥗ᗊ俚価擉䗹㿀简ଡῙ嶏綌䑅嘒㮥玺螆❻⏆砲䃺䈄悳ഊ⿊用㍗焱࿹ᵄ盿䍟斎䑋咓㓾垑ಯ∸ச荜ᅨ䨴係ᔥ㚔熤癀箻斫抄燆ᘠ疦嘦㱹๕㱛ᯡ㎂㎆㕤㏠⫙櫫沊䦪葼僊㞅剆ㅡኃ团缌世崀蓯弍䂝歷娜⥹䮇策䧳㋐♲ⴍ磟የᥭ罪䟧蚐㐇玀൫ࢼ㍯⋉⩉ṭ蚍羫䁘犃Ⳡ₪ᕎ༧≮笼ᆠ斸排䈆臋⡕巨ᒯ捃汼犅⫮㭎廆᳝葑⭕圣摖璋५殺澊㮱丸蔓ⵁㆻᆪ箨ᕶ濠"

internal val INTERVAL_FORMATS_CS: String =
    "00Tb今ᛛ恦ࣈ㩹ᅘ嚡⎵姀砇慈㡏༂ᰜ⤄࡙◳倯㉩津Თ廁䗭梈➟前ാ㟯㏁藿䞞᾽翋秱纕Ზ殐り挃䱍㸲ᛐ湾㋗㉒潏籭獣␵䚨↨瓜ṁ澲噫ፆᑙ⽠㢜੺矈ⶁ⡙ौ∾ㆻ㽵溡㊽沪᪔並ᰌ噢硧瘏ឦ⾘䄓⒉ួΩ師最⫔ᅰុ肝亾扉商ᡂ幚቟Ⴇ漍杮摇⎉㙻桓籙剠඄᥇烀ᦇၩए䎼㾀暝ṋ䌞劊ே⓰洂ẵ䱂伂䶳ㅺ綟渜ጸᆶ⩤ᠺ᫃䎸Ⱋ䬇䇻ு櫀砑᠔㍍ᕰ挐洩᛺佲⌶䊱婽䛱㨸嵬⡍⊳∱喛洽ᡓ䩵嵷ㄊ⁆ᑪㆄ芘椬⯊᡽ႁ∮宠་ី䣁૚◫漚䢔㜙㢆丵ᘎ屸②癹⑩䎅䵈膕䃐ဵ忤঻䚇⣩棻蜈䟦ᾷ㬤䍞煹螀䠀"

internal val INTERVAL_FORMATS_CV: String =
    "00V1今᝛恦ࣈ㉻ᅝ㺴⠐畚惠ဋ⾈䠀苳堀䩐᠎嚝⛈ᮯヶ㱕洤劤⨭柭嫸侮肚൧煷䙾☷㿣荼俪荸蔾嚣⚺册ṝ⇷头䂑⛼椉䐛懒㼄徲⏘冬喧Ვ崩㢼矞蛔⩗ថ㒁င㐩探௜姣斷Ṵᑲ౏ཁ♏忄䲍ပ⡩兄ท䎫甾儡ṣ硚ⴺ⒄⢠᪳㲥擮⼷梩ⱳტᷧ㨈᳆㊅孙㓌⟶勚ጭඳ匎喑ၴ屭勨᪄ᵍᒭℤ牙᨞Ⲳ⨂封㐑ভᔻॴ቎綣扫㗆磿蛽睟䮯⻕ᔨ䐷蕸洳汇毆祁ྐྵ尓呷哃Ⳬ㘒⑅䙅⃃ᶹ搉械㾘搆從㼘螡〜蒛捨฾⬳蘃኏ⅉ㽷団脋瀒蓮䛹ॵ㒳肻᠃俢᭱琱薳ⓢ居᱁莠姎㣈浚㣆㵙ផᶰ傒ᆤ㛌罠䑡浪ऩᴼ背䉦≉棌瑣繛佥毃嶸㬋䘥䲞筇䓥愩綬㸌⭇⨙ᚘᖵ牐㰺➩奈䍙䆶竿ࢀ"

internal val INTERVAL_FORMATS_CY: String =
    "00Ti今ᑛ恦ࣄ㉹ᅔᚑ╶續ဤᣝ⤀ᇣ歄ଐ⡀獧ᙒ◲儵ⴡ⨥ⳉ弙ᅸ蟙磆溕移䌿羟篾䱯緳荻㺙剳テ噅亳佱ゥ䬔稂ྐ帊偐Ɐᢇ聪墩猳ોᰶ㇗欙⪤䂀桳脇䝹᱕࿤蓯ኃ綧♧哞淮䟏ସ⌢⳦㹌⳨婯癴㫂៦蓏歛嗣⸿䏯屽㌋ẫ檚䙯爦ⓛ茵ু瞚傰悿↓欮⿌㴶⨧₱㹓缅㫤௨࣐ࠒ஑媏⫮⼁䌀ഉⰿ珱涀໣ᩓ澊繎■ⲏ⼸壑ᓓඡ䣹塤簪䕼耹呻岡ⵐ寷㌞⺬⽋羗纃䀘怖䉏榓⡒㿼㩳必ᛧ䯪ㄔᄩ畞䌄ⷡ⩦屋䌓␸⼈㏫㾔䇯䛺㝐攔嚽ᝨ】浇奧⫋㤙ᳳ㟵∷㒭⃭ൟ匞緓歘煋曅゙䁙䀠㻍敔࡭৚㛸沬࠱〨ᖩ簄㏤茠〪廰缙㉬潒亅䍋愭溛岆秊伒ᗈ♆樄䑶礸膙脶㭷⬇ᯰ਀"
