/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.collation.cldr.internal.data

internal val COLLATION_TAILORING_RO: String =
    ";2p.li:25k8ue/2hwcg/27wr28,1t.li:25k8ue/2hwcg/27y5mo,2p.le:25k8us/2hwcg/27wr28,1t.le:25k8us/2hwcg/27y5mo,2x.le:26iyue/2hwcg/27wr28,21.le:26iyue/2hwcg/27y5mo,37.mf:280zae/2hwcg/27wr28,37.me:280zae/2hwcg/27wr28,2b.mf:280zae/2hwcg/27y5mo,2b.me:280zae/2hwcg/27y5mo,38.mf:2881x2/2hwcg/27wr28,38.me:2881x2/2hwcg/27wr28,2c.mf:2881x2/2hwcg/27y5mo,2c.me:2881x2/2hwcg/27y5mo;;;;;"

internal val COLLATION_TAILORING_ROOT: String =
    ""
