/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_RM: String =
    "0064+u\u001A\u0011M\u0001a\u0011\u0003u\u000Ao8*\u001B\u0013Lo\u0011\u0006oc\u0002\u00031\u0004F)HZG.,:S.LL\u001Ad4G\u000E6T7;;r\\N@\u000B\u000F%'q\u0018h\u00174'\u001FMr+Eab(\u0019Cx\u0010YpyI\u0009\u0015i4B]Va\$-Q2Xl\u0012&\u000AE5q\u00079\u0004}\u0005(\u0011r\u0016\u0016Ir[:C+:f3\u0013SUoc\u000BFPyUvks\u000FF\u0010zW%6q\u0007(ve\u0001A"

internal val COMPACT_SHORT_RO: String =
    "003S\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0002ci!\u001CJiVk><Oi\u0005\u0006i2\u0012Q\u0005\u000AP\u0017K\u0006\u0011Q4\u0004L\u000Dif\u00113/5!VBZ\u001AV\u000Di<&W=\u000BJN.tCFNwp\u001D\u000DQMSs\u0013_:Z\u0005e\u0015\u0011YQ/C#\u000C\u0013\u0014%\u000A<\u000DA\u0001"

internal val COMPACT_SHORT_ROOT: String =
    "002K\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0004C/4\u001B\"\u000F5\u0002qG\u0019\u0018R\u001An\u0001a]\u0004s'\u0005\u000A%\u0018\u0012B3p\u001DR\u0008\u000C=sT\u0003\u0007^tJM1H,tDKt9Xh\u0001U\u001D3`\u001D\u0013d\u001D!q\u0001"
