/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_CA: String =
    "002n\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0002ci!nVzn\u0001D\u001E\u0008\u0006\u0007\u0019\u0011!9[qJ\u000DgE3I\u001EeN\u0009\u001685IgGU43d\u001B\u0005mZh\u0006\u0019Vbeh\u0005&\u0018h\u0018\u001A\u0013,?:\u0006Z\u0003TxK-\u0009X\u0003\u0002y\u0001"

internal val COMPACT_SHORT_CE: String =
    "003w\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0002cjab(B<Z=m]m\u0009MwA!/F\u0009NQ!I~5qYC&\u000C(p\u0005_\u001DQm3!M\"#\u00143\u0005m\u0005\u0017\u001C\u0012\u0007;\u0018\\\u0008x\u0006\u0007FD/#7\$ubB*F\u000ET\u0007Eg\u0005<%\u00059\u0005\u001B5\$]hf\u0007!\u0006^wQ\u0007\u0015[S\u001B!pA\u0001\u0001"

internal val COMPACT_SHORT_CEB: String =
    "002q\u001AN\u0017\u000DW>\u00186\u001BM\u000F\u000A\u0012M\u00093&MK)Z\u00019DU\u000F\u0013AmU\u0002rG\u0019\u0018B\u0002f\u0007d]\u0004\u0013\u0007\u001D\u000A!\u0017\u0012\u0002s\u000DZ\u0008\u0009>st\u0013\u0017RrLMq(\u000CtLMq9Xh\u0011]\u00115`\u001DSr\u0004]r\u0001\u000DE+\u00031\u0001"

internal val COMPACT_SHORT_CHR: String =
    "002K\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0004C%4\u001B\"\u000F5\u0002qG\u0019\u0018R\u001An\u0001a]\u0004s'\u0005\u000A%\u0018\u0012B3p\u001DR\u0008\u000C=sT\u0003\u0007^tJM1H,tDKt9Xh\u0001U\u001D3`\u001D\u0013d\u001D!!\u0001"

internal val COMPACT_SHORT_CS: String =
    "003e\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0002ci!\u001CJiVk><Oi\u0005\u0006i2\u0012Q\u0005\u000AP\u0017C\u0002%g\u0008\u0017\u001A\u0012K!]MgB,\u0003sT#\u001AQ.%L\u0011aIcBj\u0003#T\u0013\u0018-\u0009\u000BMi7G3\u000B\u00193d^Fe#!\u0006F\u001Be\u0017\u0015Z\u0011\u001Ba|Aq\u0001"

internal val COMPACT_SHORT_CV: String =
    "003q\u001AN\u0017\u000DR@\u0013I\u0017mGT\u0002cjab(B<Z=m]m\u0009MwA!/F\u0009NQ!I~5qYC&\u000C(p\u0005_\u001DQm3!M\"#\u00143\u0005m\u0005\u0017\u001B\u0012\u0004\u0018\u001C\u0008|\u0005\u000FQc\u0002\u001C\u0018u#!*F:#\u0004\u000AMJ\u000E>q\u0009jN\u000Ds\u001D\u0015\u001A\u0011\u001Ft+B\u0019\u0013kIj\u0002}\u0001"
