/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.country.cldr.internal.data

internal val COUNTRY_NAMES_QU: String =
    "00gr㪫㛝䭦礏炛᤮绠囲಑᭒㫉ᆑᅏὣ䏙癸⒓ඨḠ໛ᩔ㉓笁ᰮ㋔㨜ⵖ枲䟌即ੜᬧ㳻ࡃⓏ♰簗柆㿟䘿䇚䯠䆕兔຋攗蛧⢒旱㮒䖧㼿㵱ಝ䏘䜻䇳ろᤱⰳᔊ䪚㵡娤悼㻄剏ၹ㾞瓕䔮◎䪔ኆ⭘演䌲Ặ埅㓥᠊聿涎嬜俁≮獉ᫌ巧ಷ✸愪普湅ຒ穐⎓㞠榯༜圎⨷䝖廵䱪䁂㼸洬目ℳ簏揀䱌焬ᢪ༔糮☽抐ᗢⱿ倓囲䊼㉦毖☝蘹亗暺荿栚攊ạ⠘㇈槞ⵯ⯞胢⦆护⸖甛㴪匹㎕❼㘥⓵ᚑ丮㳔೭帟╎吺妲咱㓻澱爔珸⟺刿䈩坮㞧濦卻蝔礪᪢㩆菁燝呚ጙ㋉⃯佷蘡䆨蟾艭狯㋱糮忦愰盅崎慮城䞹恱ዑ⿫⪊㉮⊢峓䜲䲥蛣嚡橈ഺ儏肦ᗀ⨊ຊ༄␭⸛蝈㔔嫛㷏䦺劘姌ⷔ掊〻粭葚圕䖈祛䄁༭䊖㪪ፖଲ習峏廈ἑᐉ๪᜛嵕ᤛ䣉唬Ⰶଠ㗈蟞菂⟆翽᧌撜ᥢ┚簜㻀斐㈫╙Ⰺ眸燉澃弿୦䀎稕猗㈻ῧគ买䘠瘮䦋䤖薨㈲᱀䊗㮠⯜粁চ䒰㎍䭉⡙Ⰷ㺐े⛏漮㰓嘘愤䋎ⴴ瓚胜ᰚ⎚ᠸサⓢ繥怫㵛㥊墰ゼጎે葑左扐皈幍猽㮲寡䱄旿⓰寧⺲耄䎍㸿㽦愱㈾尝脢亯⹵ᇨ᯹扚⪵紆岠揍Ⲋ㙋㡿⋋積。㟀恡䦘棐禪ᲈ纀⭦娭剴ᢂ槍लᢖᾓ䘐௩ᙛ✝䚯蔃ᣣ蜫䨕堊戂烵┻᭎柅百巇ທᵰಗ᎟ᴎ䉃繅▖嵽㳃ຸ匀耆㔁盒培ລᢒ䳧獙庉拉ㆢ掿粤傺୼ᯞ恚ฤ㫛掟᤟啛蜷擩芈๎⺢㲪妭㭌⟞佺䆡⻳蜈洩焀寈揎匳⌋㍍㩫奸ℵ倡⮛六䉞愉㯧⽁缜礥⑳⩸蓢掦䠧⾼砏肎᷍ࡀⱖ⌬မၗ業纻蘼䇜榀嗈午蚄᪶㥨઺ᕴሡ☚ᠺ໬䫇㥝䕗犭禢┨老ᨐ㷵ⲩ஭慪⯾❠፥ⵚᲯ臐䔿➙䒠䪝䆘䊖㣿ⴵ⿫佲徉獯ẽ捑堞爲ഴ┾ᰃ藭腤烍慰葎㰶牲ष䱻瀇㹰㛮䔳膱笒命䓳䌵掩Å⏘ᄜೂ㞙᫺殇ペ灝脓幁ᶺ榞䍴璆眒㨊娵埊瑻৸䋗䏄䰼㐲璩⌴ⷱ冑蟓芥瀻椸眽喍㜿᎔㛓湉㖈漎େ敦嵥氻䓶啣ↅ㾈㲩䂑㘰␑୊夫䢽刌⎝ 浰࿳嵆捴䣭ᢳফ䱺紗䋥ჴ㠿ဉ㮋㳤禔ຖଌ徘儼㽩䷇缸଼殞ᣈ䶩⭪審᱘㣐䊻窠瓘椚槒㶀ዅ┽ቒ礌罩䬀职慩蒍䟓羾薩☱膙ⳗᒃ䧽偦癔ᖄ刕ൢ潯㱂㴴㛚ἂᳰ徿湦⯡色଑柽琛㍐㛖◀恘ः砵琙禝㚻柧傀䮈抠コ෨刓ธ歗倜妮ᇓ᱁梭ห滑救蚊姝₯ᙀଦ⓬业犎䎮ⲣᲖ扨ᳫ㋯璵ध呚栗叴↽࡝仇㉵圩䢐窑䤤⾛枩ಢཞᠢ缠⻫㺥粟⤿Ჾ嬳᛹ᓜ⃫菫䥘䎱告挎ࣴᡔ㏠㱽蔎䛜⸖Ꮿ㯙掻斷敝╘晷⬍琬婇泮㑹㩼㰰檼㸋╍ᯕቦ蔏㩰亞瓷␯䇄七䇀Ⲛ嚣‡囧暧㠠ि蒹羏蕌峱形ᯊ⠷䐩蜑⃻碔⥯䳰綪⾙ᜡᩨ⻧᳓᳻䈇嘘⡊ს砑ⓦ怲໣朷㣅ᖾ剛ㅌ蘋䠀"

internal val COUNTRY_NAMES_QUC: String =
    "000Qᷥ㯋稦筏䉪㤹⎓埋⸪ᨒ䆪✌慹ㄤሀ"

internal val COUNTRY_NAMES_QUC_GT: String =
    "0006ᶖ᭥仦ࠀࠀ"

internal val COUNTRY_NAMES_QU_BO: String =
    "0005ᶖⵍ渀ࠀ"
