// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_JA: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0}時間\u001F{0}標準時\u001F{0}夏時間\u001F{1}（{0}）"

internal val TIME_ZONE_FORMATS_JV: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FWektu {0}\u001FWektu Standar {0}\u001FWektu Ketigo {0}\u001F{1} ({0})"
