// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_UG: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} ۋاقتى\u001F{0} ئۆلچەملىك ۋاقتى\u001F{0} يازلىق ۋاقتى\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_UK: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001Fчас: {0}\u001Fчас: {0}, стандартний\u001Fчас: {0}, літній\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_UR: String =
    "+HH:mm\u001F-HH:mm\u001FGMT {0}\u001FGMT\u001FGMT+?\u001F{0} وقت\u001F{0} معیاری وقت\u001F{0} ڈے لائٹ ٹائم\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_UR_IN: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} وقت\u001F{0} معیاری وقت\u001F{0} دن کا وقت\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_UZ_CYRL: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} вақти\u001F{0} стандарт вақти\u001F{0} кундузги вақти\u001F{1} ({0})"
