// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_KA: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001Fდრო: {0}\u001F{0} სტანდარტული დრო\u001F{0} ზაფხულის დრო\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KAB: String =
    "+HH:mm\u001F-HH:mm\u001FKLG {0}\u001FKLG\u001FGMT+?\u001FAkud: {0}\u001F{0} Akud amezday\u001F{0} Akud n unebdu\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KEA: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FOra di {0}\u001FOra Padron di {0}\u001FOra di Veron di {0}\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KGP: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FÓra kar {0}\u001FÓra pẽ {0}\u001FPrỹg kã óra kar {0}\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KK: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} уақыты\u001F{0} стандартты уақыты\u001F{0} жазғы уақыты\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KK_ARAB: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} ۋاقىتى\u001F{0} ستاندارتتى ۋاقىتى\u001F{0} جازعى ۋاقىتى\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KL: String =
    "+HH:mm\u001F−HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0}\u001F{0} (+0)\u001F{0} (+1)\u001F{0} ({1})"

internal val TIME_ZONE_FORMATS_KM: String =
    "+HH:mm\u001F-HH:mm\u001Fម៉ោង​សកល {0}\u001Fម៉ោង​សកល\u001FGMT+?\u001Fម៉ោង​នៅ​ {0}\u001Fម៉ោង​ស្តង់ដារ​នៅ ​{0}\u001Fម៉ោង​ពេល​ថ្ងៃ​នៅ​ {0}\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KN: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} ಸಮಯ\u001F{0} ಪ್ರಮಾಣಿತ ಸಮಯ\u001F{0} ದಿನದ ಸಮಯ\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KO: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} 시간\u001F{0} 표준시\u001F{0} 하계 표준시\u001F{1}({0})"

internal val TIME_ZONE_FORMATS_KOK: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} वेळ\u001F{0} प्रमाण वेळ\u001F{0} डेलायट वेळ\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KOK_LATN: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} Vell\u001F{0} Promann Vell\u001F{0} Dis-uzvadd Vachovp Vell\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KS: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001Fجی ایم ٹی\u001FGMT+?\u001F{0} وَکھ\u001F{0} معیٲری وَکھ\u001F{0} ڈے لائٹ وَکھ\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KSH: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FZick vun {0}\u001FSchtandattzick vun {0}\u001FSummerzick vun {0}\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KS_DEVA: String =
    "+HH:mm\u001F-HH:mm\u001Fजी एम टी {0}\u001Fजी एम टी\u001FGMT+?\u001F{0} वख\u001F{0} मयॉरी वख\u001F{0} डे लाइट वख\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KU: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FSaeta {0}(y)ê\u001FSaeta {0}(y)ê ya Standard\u001FSaeta Havînê ya {0}(y)ê\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KXV: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} belā\u001F{0} mānānka belā\u001F{0} ḍayliṭ belā\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KXV_DEVA: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} बेला\u001F{0} डेलाइट बेला\u001F{0} मानांकॉ बेला\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KXV_ORYA: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} ବେଲା\u001F{0} ମାନାଙ୍କ ବେଲା\u001F{0} ଡେଲାଇଟ ବେଲା\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KXV_TELU: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} సమయం\u001F{0} ప్రామాణిక సమయం\u001F{0} పగటి వెలుతురు సమయం\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_KY: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} убактысы\u001F{0} Стандарттык убакыт\u001F{0} Күндүзгү убакыт\u001F{1} ({0})"
