/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_IA: String =
    "001Qj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsM\u007F)YI+S*\u0006)\u000B\u0014\u0002m_@\u0015.g\u0011;\u0015Q6\u001D*\u00173eUMU7W\u00063\u0005\u0008Ii\u0002\u0001\u0001"

internal val TIME_ZONE_FORMATS_ID: String =
    "001Qj~_\u000E\u00070\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsqc<\u001B.\u0015\u0016!\u0019C\u00064B\u0013c0\u0013M\"\u000DK\u0011p5]-ks\u000A\u0001c0\u0019G\u0016FT61,\u0011!=GA\u0009\u0001"

internal val TIME_ZONE_FORMATS_IE: String =
    "001cj~_\u000C\u0007,\u001C\u0016lb+\u0003\u000E|^V\u0004.%\u0001U\u0013lnsSbk\u007F1\\I\u0018UJ\u0005KU\u0001Ja/\u0019S-&s*ER&\u001FH\u000BTF\u0013g-YJebb61l!)5AD\u000AA\u0001"

internal val TIME_ZONE_FORMATS_IG: String =
    "001Bj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns;6\u0019V\u0001#\u00117W;RQ{\u000AEga\u0017\u000B]8W\u0016\u001B\u0001\u0002Mi\u0001"

internal val TIME_ZONE_FORMATS_II: String =
    "001pj~_\u000C\u0007,\u001C\u0016lb+\u000B~k0@6\u001CP^*`kVmKsp.=v;\u0016D>\$\u0009\$\u0016<~b^\u000E[/\u0008&\u0011`\u0013\u0001[e=E\u0004{,\u0011\u0010\u000D8W 8{9\u000DR{@\u0014eq\u0001"

internal val TIME_ZONE_FORMATS_IS: String =
    "001Gj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsQ(C\u0003\\!)\u0018\u0013(Lb\u0005d(s=\u001C.c2\u001C))\u001B.g\u0011F\u001AA\u0009\u000B\u0001\u0002'U\u0009\u0001"

internal val TIME_ZONE_FORMATS_IT: String =
    "001Ij~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns22\u0011V\u0001#\u0011/X\u0003\"E_&YK\u0019QR;&\u0014N(T\u000A\u0019,CX\u000EvF'A\u00014\u001B\u0001\u0001"
