/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_NB: String =
    "001Tj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsSg&\u001D+\u0018tzUC^\u0018K\u0017\u0015!\u0015P K\u0017t\u000A\u001DQ\u000D\u0019+\u001D\u001C\u0014aIY`Ngt*#s\u0005.-\u001Bk\u000B\u000E\u0011\u0011c1\u0001"

internal val TIME_ZONE_FORMATS_NDS: String =
    "001Hj~_\u000E\u00070\u001C\u0016lb+\u000B\u000A\u0008\u001EV\u0004.%\u0005W|;8#7lbw\$'\u000EeT\u0006Q\u000AO\u0005L\u000A=k\"\u0015.%Kq\u0001U\\NgSF\u0009,M\u001Bm\u0009\u000DQ'\u0005a\u0001"

internal val TIME_ZONE_FORMATS_NE: String =
    "001Cj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsa(I)\u001E\u0017w\u001F\u0017\u0017/w\u0007&v1(Qp5\u000FLL\u001B9:O+\u0003M\"I\u0003=GY\u0009\u0001"

internal val TIME_ZONE_FORMATS_NL: String =
    "001Qj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsSg,\u001BI)3zF\u0009\u000B\u0017\u0015L\u000A=K2\u0019K\u0015TIB\u0016@\u001CN&\u000CI\u000261l))5AD\u000AA\u0001"

internal val TIME_ZONE_FORMATS_NN: String =
    "001Tj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsSg&\u001D+\u0018tzUC^\u0018K\u0017\u0015!\u0015P K\u0017t\u000A\u001DQ\u000D\u0019+\u001D\u001C\u0014aIY`Ngt\u000A#s\u0005.-\u001Bk\u000B\u000E\u0011\u0011c1\u0001"

internal val TIME_ZONE_FORMATS_NQO: String =
    "0025j~_\u000C\u0007,\u001C\u0016lb+\u0010@ 9`>`~0l(+\u0007[]\u0017lfn`\u0009\\0(F\u0003!\u0004Iwox\u007F8|\u0006|/[\u001CP\\.jp\u0018oh|y`\u0019Z{@g\"\u0001t@\u0004pf0L,\u0007[CD%\u0002\u00175\u0001"
