/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_LB: String =
    "001Ij~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsa(I.\$\u0007L\u001A\u0013y\u0003fz#o2\u0014CRa9\u001B\u000Eg|)\$\u00158W\u0016;\u0001\u0001*U\u0003\u0001\u0001"

internal val TIME_ZONE_FORMATS_LIJ: String =
    "001Jj~_\u000C\u0007,\u001C\u0016@v\u0007\u0011O\u0009\u0011\u000E9lGkA\u0016\$sx0E\u001EX\\fzEVB#\u0005HyECyS-&s*ER\u0006\u0018\u0005\u0003)UQw=\u0007!F61,\u0011!=GA\u0009\u0001"

internal val TIME_ZONE_FORMATS_LLD: String =
    "001Pj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns22\u00165)A\"\u0011\u0011e\u0014F\u0013c0\u0013M&\u0009*\u0005%\u0003c\u0004d/4\u0019-\u0018\u000F8B\u0012\u000A5n-+u\u0001\u000C\u0012Q\u0003\u0001\u0001"

internal val TIME_ZONE_FORMATS_LN: String =
    "0018j~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns;0 P%\u0014\u000BKC2+\u0004EAW)\u0015\u0017n\u0001\u0013f\u000D\u0001D\u00193\u0001\u000E\u0011TC!\u0001"

internal val TIME_ZONE_FORMATS_LO: String =
    "0028j~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsH~Gtcal}alUYZ[S\u0001\u0013%\u0011Zr16I4\u000AhJBXk\u0002x42t16\u0007t\u0014YK\u0016C\$M\u001C\u0011qL;\u000A*V\u000EVF/A\u00013\u001B\u0001!"

internal val TIME_ZONE_FORMATS_LT: String =
    "001Uj~_\u000C\u0007,\u001C\u0016@v\u0007\u0011O\u000Abx\u0007k'kA\u0016#!W\u001C&\u007F}O2\u001AOW\u000EK)\u0001%>^\u000Eg4*_\u007FY\u0011Bj\u0013b3c9YC\u000A[gkaW!Az\u000E\u0001\u0011\u0001"

internal val TIME_ZONE_FORMATS_LV: String =
    "001Xj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns`#\$\u001EM'\u0016Z=R8\u0019K[\u0015!\u0015I\u0007f\u0016!]J'\u0013z\u0013b*\u0013U%\u0001:\"?\u000D\u0009L\u000A#c9YK\u0017\u0012b\u0003D&)\u001Bl\u001BA!"
