/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_RM: String =
    "001Uj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsa(A-7&Uo\u0001QZhtJE\u000F\u0014%I\u000Etz#/\u0016\u0013\u001A#\u0013\u000CcJ2\u0003K\u0005ACQ\u0005\u000B\u0016aI\u0001"

internal val TIME_ZONE_FORMATS_RO: String =
    "001Uj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lns22\u0011V%3zF\u0009\u000B\u0012\u0002mr%YLeT\u000A#\u000BF\u0019\u000A+S\u000A3cie-lD\u0003kbWaAj\u0006\u0005\u0013\u0001"

internal val TIME_ZONE_FORMATS_ROOT: String =
    "000+j~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsQ(C\u0003\\\"Q\u001C5\u0011D\u00113\u0003\u000D\"I\u0001=GM\u0009\u0001"

internal val TIME_ZONE_FORMATS_RU: String =
    "001mj~_\u000C\u0007,\u001C\u0016lb+\u000FvyDV\u0004.%\u0001U\u0013lnsQ(C\u0007Z\$9m\u001F\u0017\u001FO\u000B\u000D\u000C>LnLNDCc\u0002e\u0018`?\u000B}\u000C.F&gfl1q1{qTi`w\"f\u000C^LvA+-]F*^\u0016B-B\u0002k\u0009\"\u0019\u0001"
