/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.collation.cldr.internal.data

internal val COLLATION_TAILORING_NE: String =
    "003Nᛇ拃塦ࣈⅼᡃ徰リ㳍ㄣ爴ႌᴷ忐濶淙蜎ቱ䬞岏形烗緀窫坸膮䣍狽楑㔍ᓐ䅍癠ᭈ灅㇜␁㡴ᥓ堗ధ苣姖蟩ポ欩उぇ᮰蟸᳚ጠᒈ磌絏薈擲ᣀ瘶燩䙣圇䀢膐ᣢࡸ暷怠洈宲㕈㓈ᰙ胹婜䣖⡯ⓗ蝾檌蒀䠀"

internal val COLLATION_TAILORING_NO: String =
    "00Bw䛈幃塤ॄㆻᫀ薇⡝⺡汆䣩䭚㗗瀩ㅔ僪ஏ藷❤溕怓胷䑹෇ㅙ䴪ៀⲶ䢞ハ撨䪔厵舽䓘渲䫙昔ⰱ厴⤠㊟῕卓Ⲿ⫹䘟艖ᡲ⯕㊞⩣ゔ巡嬲ᡑ⥠湄攪璌犄⛊㺰䍹♝㩉㪕掺䷢箏᭶጑浣❳⥺勧䌒䜻㏢葰侈㻰㒏⳿㨹婤⽢℘㹚据玳终墄晥⡎䗙菤羄䑌璷疩佢ᚍ჏艟苻⛴ᤞ᾿Ⲱ㮑禷吾宙ⅸᜂ☸癲ᮛ㐤喡㒍ᬋ蓟䀈"

internal val COLLATION_TAILORING_NSO: String =
    "002X憛ኴ䅩⍓ᦕ㺪履娷洔ᯓ拦笢腹勋⡣㓀ᤩ扦孵縶桤情➘㴯⩪惙ᧈ塪ᠹ⩍曊污お渢峄碘恢⨼爐ࠀ"
