/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.collation.cldr.internal.data

internal val COLLATION_TAILORING_LKT: String =
    "0049㻥廂堄ऄຈ㴧㪈ㆵ啔茀ヌ儝佑ឝ朱荻搞椰䯣孁䃑⦆⏆媂䲀猪䯈ᴫ⃸ㄡ㶉妱箊椧儆㕸凭ࠗ᪞疲㑾傟棈⚇ᄥ晽◬璂蘧蟽栠"

internal val COLLATION_TAILORING_LN: String =
    "001X⶗璌乕抪妖僟᱐坎玛咋淦㌭੉億㝜㳍滫婳细⬤虡崼ᐔ彥㕠ᴉ竔⢸⊢瘌਀"

internal val COLLATION_TAILORING_LO: String =
    "007Jᛈ拤墄ࣈ⥻ᥤ╵傔寰兣夗佅槯緛璮㉟敉䰩唬⯵糢缯䕧㮱㪞㟗ᖒᅔ䖺㩨樅勍䯗ᡭ忀ᵞ煠㦩㈯⢪絃ᤫ睨᳝蘝⁭償ໄᰚ瀙剗┝╄䢀櫣ᆨ璲綬᭯ࢄ䵣礸᷏纅皕ᕐ蔻䬢Ṧ㜂䣩㙖葁⇄慄廁㧬ᓝ䚐繷儾篿ࡼ揧ඒ✘泀ᐏ璑的暚栒㸋䘈蕾ࠓ瞌㡿ᤰ႕臞೪怐愧Ⳙ㚀䉶㦆囫種⇒慼ཉ✧禋㌜娌沽ሗẵ煹⵽㿯ടᇩ㵽᚟羬糑䅺眚ᯖ脿⸊ᜒ糏疂欻䜧椷渖㫬ᒲ⤸䴗ᱎ྘ᴖ仍廴栏旺融燚䝀㠀"

internal val COLLATION_TAILORING_LT: String =
    "0095㻉䉅偦ऄ㫾⫆ℇ墧エ廕ᥤ⾟嬲ཇᮟ矦漦ට泂൯漙煃૦縠唽倅媚膀䍫斎玛㫄肄௢㽽嵒ᒫൣႦ笌យ༥冝䨛潥愠䣑ဪ㙅⪛₃㤚᫒獃㽙᭤Ⱁ氙⇑㗙傃ቲ猴ᢼ旺Ṅṇ⋍繏䲺処垌㧕㍅皽䠱稕宍ᛴ狢䴚៧棽梃ት㪮⭙滗✊ၦ聯癏ⶰ墇ᖓ唄᧑菲疂尯Ⲻ䮬Ḁ"

internal val COLLATION_TAILORING_LV: String =
    "00BM㻉ᩄ塤ऄㅻᣤ灕䲜ୢ爢䃆ᣩ槲㋯峕Ẽ䕏翠ฃ≌瞉㐎奯⨊⠷ೊ৭㎧焢翾ᆂ瞫้⯨偖䬎⮑穣腬䟉帒䰙璡஧䓕幘籶䯐㓾莝㻚玪໩㤏⦃㱫煌弐₂ཎ綥༱ោႆ␣椒ⓟ岾㰌梇夀⬲㜫⚓慂཈⭙㷔坒⬙䥧⽍䭏⻺࣌ሹ灟⽂巔泌梓恶攄㏝਻䬐䈥ᬖ獈䙶僇ᏻ奫蘀"
