/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.phone.metadata.internal.data

internal val PHONE_TERRITORY_QA: String =
    "QA\u001F974\u001Fp\u001F\u001F00\u001F\u001F\u001F\u001F\u001F\u001F800\\d{4}|(?:2|800)\\d{6}|(?:0080|[3-7])\\d{7}\u001F7,8,9,11\u001FFIXED_LINE\u001D4(?:(?:[014]\\d\\d|999)\\d|2022)\\d{3}\u001D8\u001D\u001D44123456\u001FMOBILE\u001D[35-7]\\d{7}\u001D8\u001D\u001D33123456\u001FTOLL_FREE\u001D800\\d{4}|(?:0080[01]|800)\\d{6}\u001D7,9,11\u001D\u001D8001234\u001FPAGER\u001D2[136]\\d{5}\u001D7\u001D\u001D2123456"
