/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.phone.metadata.internal.data

internal val PHONE_FORMAT_ZA: String =
    "ZA\u001F(\\d{2})(\\d{3,4})\u001D\$1 \$2\u001D8[1-4]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{2,3})\u001D\$1 \$2 \$3\u001D8[1-4]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D860\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{4})\u001D\$1 \$2 \$3\u001D[1-9]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{4})\u001D\$1 \$2 \$3\u001D8\u001D0\$1\u001D\u001D\u001D"

internal val PHONE_FORMAT_ZM: String =
    "ZM\u001F(\\d{3})(\\d{3})\u001D\$1 \$2\u001D[1-9]\u001D\u001D\u001DNA\u001D\u001F(\\d{3})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D[28]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{7})\u001D\$1 \$2\u001D[579]\u001D0\$1\u001D\u001D\u001D"

internal val PHONE_FORMAT_ZW: String =
    "ZW\u001F(\\d{3})(\\d{3,5})\u001D\$1 \$2\u001D2(?:0[45]|2[278]|[49]8)|3(?:[09]8|17)|6(?:[29]8|37|75)|[23][78]|(?:33|5[15]|6[68])[78]\u001D0\$1\u001D\u001D\u001D\u001F(\\d)(\\d{3})(\\d{2,4})\u001D\$1 \$2 \$3\u001D[49]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{4})\u001D\$1 \$2\u001D80\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{7})\u001D\$1 \$2\u001D24|8[13-59]|(?:2[05-79]|39|5[45]|6[15-8])2 2(?:02[014]|4|[56]20|[79]2)|392|5(?:42|525)|6(?:[16-8]21|52[013])|8[13-59]\u001D(0\$1)\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{4})\u001D\$1 \$2 \$3\u001D7\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D2(?:1[39]|2[0157]|[378]|[56][14])|3(?:12|29) 2(?:1[39]|2[0157]|[378]|[56][14])|3(?:123|29)\u001D0\$1\u001D\u001D\u001D\u001F(\\d{4})(\\d{6})\u001D\$1 \$2\u001D8\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3,5})\u001D\$1 \$2\u001D1|2(?:0[0-36-9]|12|29|[56])|3(?:1[0-689]|[24-6])|5(?:[0236-9]|1[2-4])|6(?:[013-59]|7[0-46-9])|(?:33|55|6[68])[0-69]|(?:29|3[09]|62)[0-79]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D29[013-9]|39|54\u001D0\$1\u001D\u001D\u001D\u001F(\\d{4})(\\d{3,5})\u001D\$1 \$2\u001D(?:25|54)8 258|5483\u001D0\$1\u001D\u001D\u001D"
