// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.phone.metadata.internal.data

internal val PHONE_FORMAT_XK: String =
    "XK\u001F(\\d{3})(\\d{5})\u001D\$1 \$2\u001D[89]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D[2-4]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D2|39\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{7,10})\u001D\$1 \$2\u001D3\u001D0\$1\u001D\u001D\u001D"
