/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.phone.metadata.internal.data

internal val PHONE_TERRITORY_XK: String =
    "XK\u001F383\u001F\u001F\u001F00\u001F\u001F0\u001F0\u001F\u001F\u001F2\\d{7,8}|3\\d{7,11}|(?:4\\d\\d|[89]00)\\d{5}\u001F8,9,10,11,12\u001FFIXED_LINE\u001D38\\d{6,10}|(?:2[89]|39)(?:0\\d{5,6}|[1-9]\\d{5})\u001D8,9,10,11,12\u001D\u001D28012345\u001FMOBILE\u001D4[3-9]\\d{6}\u001D8\u001D\u001D43201234\u001FTOLL_FREE\u001D800\\d{5}\u001D8\u001D\u001D80001234\u001FPREMIUM_RATE\u001D900\\d{5}\u001D8\u001D\u001D90001234"
