/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from libphonenumber v9.0.19. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.phone.metadata.internal.data

internal val PHONE_FORMAT_HK: String =
    "HK\u001F(\\d{3})(\\d{2,5})\u001D\$1 \$2\u001D900 9003\u001D\u001D\u001D\u001D\u001F(\\d{4})(\\d{4})\u001D\$1 \$2\u001D[2-7]|8[1-4]|9(?:0[1-9]|[1-8])\u001D\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D8\u001D\u001D\u001D\u001D\u001F(\\d{3})(\\d{2})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3 \$4\u001D9\u001D\u001D\u001D\u001D"

internal val PHONE_FORMAT_HN: String =
    "HN\u001F(\\d{4})(\\d{4})\u001D\$1-\$2\u001D[237-9]\u001D\u001D\u001D\u001D\u001F(\\d{3})(\\d{4})(\\d{4})\u001D\$1 \$2 \$3\u001D8\u001D\u001D\u001DNA\u001D"

internal val PHONE_FORMAT_HR: String =
    "HR\u001F(\\d{2})(\\d{2})(\\d{3})\u001D\$1 \$2 \$3\u001D6[01]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{2})(\\d{2,3})\u001D\$1 \$2 \$3\u001D8\u001D0\$1\u001D\u001D\u001D\u001F(\\d)(\\d{4})(\\d{3})\u001D\$1 \$2 \$3\u001D1\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D6|7[245]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D9\u001D0\$1\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D[2-57]\u001D0\$1\u001D\u001D\u001D\u001F(\\d{3})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D8\u001D0\$1\u001D\u001D\u001D"

internal val PHONE_FORMAT_HT: String =
    "HT\u001F(\\d{2})(\\d{2})(\\d{4})\u001D\$1 \$2 \$3\u001D[2-589]\u001D\u001D\u001D\u001D"

internal val PHONE_FORMAT_HU: String =
    "HU\u001F(\\d)(\\d{3})(\\d{4})\u001D\$1 \$2 \$3\u001D1\u001D(06 \$1)\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3})\u001D\$1 \$2 \$3\u001D[27][2-9]|3[2-7]|4[24-9]|5[2-79]|6|8[2-57-9]|9[2-69]\u001D(06 \$1)\u001D\u001D\u001D\u001F(\\d{2})(\\d{3})(\\d{3,4})\u001D\$1 \$2 \$3\u001D[2-9]\u001D06 \$1\u001D\u001D\u001D"
