/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_BA: String =
    "001t燻䐬⅙慝䐪䮺葃崆抐ડẽ晘ᇤᰮ㹜璸扸₽肴炽猄ฮ∯⌮㹜㐽聒梱慱慱憄山㣳腦⫮淭䯣ಮ㴸榭䤃ᰠⳀࠀ"

internal val TIME_ZONE_FORMATS_BE: String =
    "001i燻䐬⅙慝䐪䮺葃崆抐ડẽ晒腥蛃䫅⮕त䔰恑㳑䆲筡绂ፐ帀稷坶ᶾ጑癊඲ᾶ䥂燨⤊禽㥓⠀㬴ࠀ"

internal val TIME_ZONE_FORMATS_BG: String =
    "002W燻䐬⅙慝䐪䡜咾璸恱碷她奷㫣㪼畐䴓⣱抶腰䕀ඎ኎ᖒሗᖗ喗䌎พ萩㱜璸琀慻徶ᳮฑ⊆❘Ỷ㙬䫕盬❬⯵⾳ჭ⣓殅䚋喨⴦担㚀ફ㘈ࠀ"

internal val TIME_ZONE_FORMATS_BGC: String =
    "001n燻䐬⅙慝䐪䮺葃崆抐ડẽ晘ᇤᰝỬ䑘慷㡤暬ᇨ㶴ಙ㣐燯䦒蓇涝律ଡ乢菡䦒ຈড䧈㳟卒ᒀྑ嬄ࠀ"

internal val TIME_ZONE_FORMATS_BHO: String =
    "001r燻䐬⅙慝䐪䮺葃崆抐ડẽ晘ᇤᰝῌ䝘慷硤曀粽㨈὚ਊ帼㐙൲⌠♪萺サ腠Შ䀉嬱瞌䡘㶨どࢫ∀"

internal val TIME_ZONE_FORMATS_BLO: String =
    "001y燻䐬⅙慝䐪䭔ᕪዮ瓹္୴⻐蜳⒜响➜䅚໓ᮓ伪㠍皣ඒ熩咐⬐潇嬞犢敉䳭⩼抰獠䣊ᄒ㠀"

internal val TIME_ZONE_FORMATS_BN: String =
    "001/燻䐬⅙慝䐪䮺葂ዕ୚倆墖曞㐉稔ព縼㑛䎰㹞壹㽬నࣳ茞ḭ葘〉介Ṙ肳㿾棙ᕘ⺓⧲潶⅑嚱㎠ࢪ犂ࠀ"

internal val TIME_ZONE_FORMATS_BR: String =
    "001G燻䐬⅙慝䐪䪄䮝崆抐ડẽ晕≜㑑ࡄ⠺蓪⾣➘吱晟࢈㫠暵㣖梁娔ᢐࠀ"

internal val TIME_ZONE_FORMATS_BRX: String =
    "002Y燻䐬⅙慝䐪䠾㖘膰㩟羠沿壹㵠ᕉἀ䒅㵁庫ਫ਼㛫礎珛沀熅஥斀₴Ⓤぼ掱罠泚䧒罃竖䯕䶐ඐᔕਝ㠂勰ऄ⡕᷐ಳ㰈彪㑕瀀㊕碐ࠀ"

internal val TIME_ZONE_FORMATS_BS: String =
    "001Q燻䐬⅙慕䚄ὃ敼⤊犃㕈୐卞眪೰䦬夨ἤ笒焥䲬噚撠徕告溦楢⓬剙㤄㑧㑔瀀᪚ࡀ"

internal val TIME_ZONE_FORMATS_BS_CYRL: String =
    "001A燻䐬⅙慝䐪䮺葃崆抐ડẽ晒艥獡棃玅⚋疖䴰่ૂഏ㺀ᯊ ᒃᠡ䨄肘ࠀ"
