// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
@file:OptIn(InternalKotlinxLocaleApi::class)

package dev.carcara.kotlinx.locale.number.cldr

import dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi
import dev.carcara.kotlinx.locale.Locale
import dev.carcara.kotlinx.locale.number.Decimal
import dev.carcara.kotlinx.locale.number.NumberFormatSource
import dev.carcara.kotlinx.locale.number.NumberGrouping
import dev.carcara.kotlinx.locale.number.NumberNotation
import dev.carcara.kotlinx.locale.number.NumberSymbols
import dev.carcara.kotlinx.locale.number.OrdinalFormatSource
import dev.carcara.kotlinx.locale.number.PluralCategory
import dev.carcara.kotlinx.locale.number.PluralRuleSource
import dev.carcara.kotlinx.locale.number.PluralType
import dev.carcara.kotlinx.locale.number.SignDisplay
import dev.carcara.kotlinx.locale.number.cldr.internal.data.compactLongRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.compactShortRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.numberPatternsRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.numberSymbolsRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.ordinalRuleIndexRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.ordinalRuleSetsRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.pluralRuleIndexRegistry
import dev.carcara.kotlinx.locale.number.cldr.internal.data.pluralRuleSetsRegistry
import dev.carcara.kotlinx.locale.number.cldr.runtime.PayloadNumberFormats
import dev.carcara.kotlinx.locale.number.cldr.runtime.PayloadOrdinalFormats
import dev.carcara.kotlinx.locale.number.cldr.runtime.PayloadPluralRules
import dev.carcara.kotlinx.locale.number.format
import dev.carcara.kotlinx.locale.number.formatPercent
import dev.carcara.kotlinx.locale.number.formatPercentValue
import dev.carcara.kotlinx.locale.number.ordinal
import dev.carcara.kotlinx.locale.number.pluralCategory
import dev.carcara.kotlinx.locale.number.symbols

/**
 * The plural rules this build carries.
 *
 * Its own object rather than a member of [CldrNumber], because the rules
 * are useful without a formatter: a caller picking between translated
 * strings needs the category and nothing else.
 */
public object CldrNumberPlurals : PluralRuleSource by PayloadPluralRules(
    pluralRuleSetsRegistry,
    pluralRuleIndexRegistry,
)

/**
 * The number formats this build carries.
 *
 * The formatting lives in `kotlinx-locale-number-cldr-runtime`; all this
 * object contributes is the tables.
 */
public object CldrNumber : NumberFormatSource by PayloadNumberFormats(
    numberSymbolsRegistry,
    numberPatternsRegistry,
    compactShortRegistry,
    compactLongRegistry,
    CldrNumberPlurals,
) {

    /**
     * The symbol table itself, for a domain layered over this one.
     *
     * `kotlinx-locale-currency-cldr-full` reads it rather than carrying a
     * second copy of every locale's separators.
     */
    @InternalKotlinxLocaleApi
    public val symbolRecords: Map<String, String> get() = numberSymbolsRegistry
}

/** The ordinal forms this build carries: `1st`, `1.`, `1º`. */
public object CldrNumberOrdinals : OrdinalFormatSource by PayloadOrdinalFormats(
    ordinalRuleSetsRegistry,
    ordinalRuleIndexRegistry,
    CldrNumber,
    CldrNumberPlurals,
)

/**
 * [value] written for [locale], with its grouping separators.
 *
 * Compact notation is this call with [notation] set, so `1200` reads
 * `1.2K` under [NumberNotation.COMPACT_SHORT].
 */
public fun numberFormat(
    value: Long,
    locale: Locale = Locale.current,
    notation: NumberNotation = NumberNotation.STANDARD,
    signDisplay: SignDisplay = SignDisplay.AUTO,
    grouping: NumberGrouping = NumberGrouping.AUTO,
): String = CldrNumber.format(value, locale, notation, signDisplay, grouping)

/**
 * [value] written for [locale] at exactly [fractionDigits] digits.
 *
 * The digit count is required rather than read off the float, because the
 * targets do not agree on how many digits a `Double` has.
 */
public fun numberFormat(
    value: Double,
    fractionDigits: Int,
    locale: Locale = Locale.current,
    notation: NumberNotation = NumberNotation.STANDARD,
    signDisplay: SignDisplay = SignDisplay.AUTO,
    grouping: NumberGrouping = NumberGrouping.AUTO,
): String = CldrNumber.format(value, fractionDigits, locale, notation, signDisplay, grouping)

/** [value] written for [locale], keeping the digits it carries. */
public fun numberFormat(
    value: Decimal,
    locale: Locale = Locale.current,
    notation: NumberNotation = NumberNotation.STANDARD,
    signDisplay: SignDisplay = SignDisplay.AUTO,
    grouping: NumberGrouping = NumberGrouping.AUTO,
    minimumFractionDigits: Int? = null,
    maximumFractionDigits: Int? = null,
): String = CldrNumber.format(
    value,
    locale,
    notation,
    signDisplay,
    grouping,
    minimumFractionDigits,
    maximumFractionDigits,
)

/**
 * [fraction] written as a percentage: `0.075` in `en` is `7.5%`.
 *
 * Multiplies by 100, which is what a `%` in a CLDR pattern means and what
 * `Intl.NumberFormat` does. For a value that is already scaled, use
 * [numberFormatPercentValue].
 */
public fun numberFormatPercent(
    fraction: Decimal,
    locale: Locale = Locale.current,
    fractionDigits: Int? = null,
    signDisplay: SignDisplay = SignDisplay.AUTO,
): String = CldrNumber.formatPercent(fraction, locale, fractionDigits, signDisplay)

/**
 * [percent] written for [locale] without scaling it: `7.5` is `7.5%`.
 *
 * The counterpart to [numberFormatPercent], which takes a fraction and
 * multiplies. Reading one as the other is a hundredfold error, so the two
 * are named for what they take rather than told apart by the argument.
 */
public fun numberFormatPercentValue(
    percent: Decimal,
    locale: Locale = Locale.current,
    fractionDigits: Int? = null,
    signDisplay: SignDisplay = SignDisplay.AUTO,
): String = CldrNumber.formatPercentValue(percent, locale, fractionDigits, signDisplay)

/** [value] as an ordinal in [locale]: `1st`, `1.`, `1\u00BA`. */
public fun numberOrdinal(value: Long, locale: Locale = Locale.current): String =
    CldrNumberOrdinals.ordinal(value, locale)

/**
 * [locale]'s number symbols: its digits, separators and signs.
 *
 * For building something this library does not format. An amount field that
 * formats while someone types cannot round trip through a formatter, because
 * that would normalise away the half-finished states the caret depends on.
 */
public fun numberSymbols(locale: Locale = Locale.current): NumberSymbols = CldrNumber.symbols(locale)

/** A formatted number read back, or `null` when [text] does not parse in [locale]. */
public fun numberParseOrNull(text: String, locale: Locale = Locale.current): Decimal? =
    CldrNumber.parseDecimalOrNull(text, locale)

/**
 * The plural category of [count] in [locale].
 *
 * An integer is the one case where a raw number is enough: it has no visible
 * fraction digits, so nothing a formatting choice could change is left.
 */
public fun pluralCategory(
    count: Long,
    locale: Locale = Locale.current,
    type: PluralType = PluralType.CARDINAL,
): PluralCategory = CldrNumberPlurals.pluralCategory(count, locale, type)

/**
 * The plural category of [value] shown with [fractionDigits] digits.
 *
 * The digit count is required: in Czech `1` is `one` and `1.0` is `many`.
 */
public fun pluralCategory(
    value: Decimal,
    fractionDigits: Int,
    locale: Locale = Locale.current,
    type: PluralType = PluralType.CARDINAL,
): PluralCategory = CldrNumberPlurals.pluralCategory(value, fractionDigits, locale, type)
