/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_VAI: String =
    "00AU庨᭒聨ॏ椻䟜ᘉ≍燧滥ㅅ砚ᐓ⚖ᚼ苪峋⢈ख恖Ị㴩ፃⴇႊ媅よ⟼蟠㍼啣㴇櫁史䇉圭繣⁇䑄㰒笇䆒せ簉蘑笉䀡吘㭃䐦䭫Ꮒ⏡ḓ溱඗‥榉Ⳑ㦀桹䀣⨫㱭坡䬆⯂ᇩᆬ簱䡩吇௞萎炄䇭婔䄛愾ⲋ稉篩㝿ి孾䶤ゎ၅ᜲ穩殜抔਩㉅沒ㅒ圠㔐亘䉌蘚埬蛍劬៙摳⚀㙩栞挊䐨澼⣯士洍槔᧿蚭㚀ུ汧侵㴥潠ᶈ蘣᳜巰㛲撙ၠ淋ᤝ戧ኌ⸈ℎ籋ừ㙗㫘茤⽝睲榱禴ኧ斗㏙蚊役㒟涋檉〫穕渻尨䔿ⱝᛲ蛛喈芓曊᳒᭞殪ベ傚度啶籁憩∧稉"

internal val LOCALE_VAI_LATN: String =
    "007f囈᫓恦ॄ㎻剼㘡ㆶ秾ᚨ紅ऴ扂ᶋ恕ଘ⊦Ⲓ㴥㌐䐲簓徐㹘ಛ副槃ᐋ♻罝藽兞ᖼ⍒ㅃ咔䩰ㅊⰕ晨椺禢柼㾠⑘堸㫤ᰨダ奵匃㑭⏃牰ႇ悅ᣀ㚩䃅睥⏔⥵࠿侗␢䌐䭳㞋艨臞硎㿘㠑巗嗗拊纾ዹ呉㉑坐薜唴痂淢螲劺绝慷翧台㾦᫢䏰䆚蘶ஹ崁瞿䭖挚噟劊愉✡攨婸㜨脲㸱滴䘐ល怄唸⍤㑫悕狻㛌濡䗺ⅳ瓓怀"

internal val LOCALE_VEC: String =
    "007e䛇᭓恨ࣈ㍻ጼୄ㸩䪡◡㡕㊠≂⢳㢛傐⌵㦚ᩈ沪廵♰丯䭎萔介ᦿ寇忷㬰緆ᇞ㹶ㅹ惂硎㻫䛚㔷ᐠ痒殘Ὤ㺕ᥒ㈋ഭ廅省ⵉ₪╟䑋㳪ଲ終ቍ㐁ಃ刐䨠⣈愦㪄ⷜࣃ⹯沵䮋縈᝱༹㼻授稒⼷枥䜑ḵል㉶汳绊ᆉ䤅໳苠㸵祷方拑䋻⑊⒲磅䒆Ꮌ↿஌禡膪戎㸂⺒㼜崨亐芯ᕼ䩨Ⅺ⛖⊗ප澓票㍑椺簿愋瘣槐▸䐷脔㤙埇箋泲䵰囬ঈ⸋ᡑై䆈歱䰵榐佘萻耜惀薍㞿窝⋸ಟ教皗⁎"

internal val LOCALE_VI: String =
    "00Af䋈寒䡦᥌㭿傔ᘰ炒蓭莭ख㺑䎱䃀夰㛚⻓櫬⪂䳽घ塞䲠糝ἕ羘澑Ỿ㤭ᰨᖅ翋䖏翲熅⾽湷䚑ᖊ格䨏ႃ縰葄❑࿏⧯⣕䲧㹶夙㜢棶᥍砉潳␓擋ᓷⰉ䚲ᶤ㤉တᦠ檃ឲၝ庡ㆱ滱ᵹ⒂糙䔴ត宁对脴䆜ᙛ嫛疞瓳㐶ᢽ泙⏽弹ṱ䬨㉹᚞榧䱩䵰ḅ⒤稧啊㩲晱䄐椮䵋∗舡㙊烦䰩偛虐௞屫緈懠茵圅䱃睩囎宲ఊ溢犻珶晔痂ᰧ㲫෼瓖ኾ㌿⏣ᕾ梚䶻䑠୷㻐硺㚁崜〈栾聀䪥ࡄᝒ壬⬊⹢ⴝີ嬨㕤唂㼉⚀拚䩒滰䙗搑䘬䂭䃒菡曶㞢翡㙲䑶矠଀"

internal val LOCALE_VMW: String =
    "009M拈㭛塦ई⻻᮰ᙀᨦᨒ㙍㊥⫤䲪劧嚊䃅੍䪻ງ蒫暺੯喤挻愻瞗㶨煢憒勔⑶膐纠⺶懐✥㺬艕࿋咩忚珽⋎啪ᒚ掫䁞㿎敯᭜欀聓桾ફ蘔Ẉ•欆䓉ጌ࢑ሐ⠠ᤳ崪⛱熺䕅᷻葀⃒⩓嶀庺晧䧎㊈䆁Ṥᚲ᧥㉼ᐕ攬彦罼ዊ胁巟寶ᑙ㧣ᾴ竇珇໹䇱⹅淠㏯ᗕ岏災冲Ⲩ琍Ꭽ⏞姓菚緖瘸ढ़樊翰啵臨孄焽喓櫉䁖涁吢౏篿牪ᡱᙙ㲡簣刳ᜱᔖ竌朳⽡嫜⋿眄ೡ耄"
