/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_OS: String =
    "006e䫈ᡚ恨ࣄ㍹凌ྡྷ⯚೦ႂㄢ歩Ⲑ堩⍯紤ਮ㗣巾ၒ蚥䛄㫯忝䘤蓿穾႑窹奫妝椝䎮㕐ᡭ脺䊢螤ᕛ䬑ঝ藷′萻❶乮璎爜㲻㳭㫗⼧伛欿蘏䳉螊罗眸渱Ⴌ⓯㱍熑搒გ㳒ᦔ㟵ᙀ⁀箲稤⹼肏䏎䰶६斮爹猭㐑欦僃㍳䊳ⰛḂ✺⫀㡱振ছ唰ఢ៴卦ᭂↅ㷉ᯝॡ⚻ጬ扚⸤࡭ີ暌㢃⨙櫴⒐⚿蚁㠀"
