/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_UG: String =
    "00B5溨ᛛ恈ऋ癍㠽䡅㜱瞙ౄ冭气ሚᴔ⢊汘义梱勠၂ᤊ᪨ㄸ殆暦㾋䠧㮔ᔴ槷濍嗛炤㮖渾烛䏡᧦狗䠣尜穰嘷䩽紁菏⭜蝘泠穒噗㥅☕浝䷽匮蓲ও欆⏋䀯䖐ዿ晘ᦴ楄౳Ḉ⋟蘂௨帪蓣盚㥕᳠冭⤤拔宇䈢Ấ秂慁叾瀋瑶掸垅䘥ₘ枎㉚ጹ蘩葡↬嘔਼怆剏榾腲㿴ᬿ㰃眧ᩁഄ㲙㳑ࡖᏹ砎竤嵘艹粔Ᾰ炎劇䞕墳⡈⛑嘋䜆♂盕穅㝆䠚塨⊫䟟ᙆ相嘞ဪ劣无თ㍦栚滕Ꮯ។㲌䞭ᭅ慪䎊㽐炌ो㬖罛劢⹈婃ᑩ䐚凥濐 "

internal val LOCALE_UK: String =
    "00CJ䚨盛捨ए沙緙崐ഩ燛䌷堃㟘す暹䁓ก䴃㌋䣋劀搒墤亦娜␐繩荟恗橋⏟备ጠை㗳笻ᯕ睊⍟ⷒ⯉⿾爣䚖ㄹ缢氹㶖䥞㥷ᵖ䪆盦䰞㥛㷑㒽怎偹ᣡ䬛羓槒⣬㰄盾䮥囈匱竩濄঩䕬ⲻẺ澩噈◒ၻ口れ冒ᮞ休☕၉⑤胕桄潄湄氰㣖ᎀࡺ砀㳗䤖亏㺡䔍剜❷惪஌ᝒ冱⳽Ⱆ㰌俟䧧䂬ᬅဆ㟟蔤䃘莰❼ㅐ⟑瓬䈢㫤㶿㱥烆㴵㠰㩸᷅⛆⣿ᣏᨧ儗兗愍妉砚Ⱉ尽嗫ⅴ噤桰药怙⌼杤౎揾峟孭ᯎជ䜅緿ᬖയ厰垏翷毫藎⳻䥹箒ᓆ搖菜斖玏擾乑⽇狸空䖁垫థ嶸奼䓹嶻䒪曾䥨嵽毘狟ᅒ⯌䆑㏚ഗ科㾲乕❖炝䑖ጹ䢩忌幝㊪墉䕕䩕爉⵵ᆾ澼昀"

internal val LOCALE_UR: String =
    "00BK檨瑓恦ए璝哼䢥═畩㍄嚕ॄॐ僌Ⰶ厧⽒芄⊈䦟ᢨ㫑ㅛ⪨⁘䄎臞⓿ॳⰕೄ櫀僷睎菿◓嗥帥⍲砙瓄⫈禯⑔㒨䪽恒ᦻ剬ૣ圍㴹憥䤑㐺捕⓷晐瑒፾㨓ኽ榥我亱伦⦪柈蛑ᑩⲐ௬ჟࡣ䔱⫮勦潉劤᳛婥っ⒗䪤㆗‼摁䈹␗ႅ簽磘䰡พ藾虁Ⱋ攢澨䳶↨⭕獑琓忶岨畑薷䁖ᱥᒒ斦὘ᘴ蛧㑀᳍⹾烃㖰⋍牡蟌唩艷幵薉苮䝸満䓟氬虯ᅜ烼磒❶攞瓱ㇶ㉄枧༁䳯吽䧳☿ቘ朧俜斤俾䭏仸缉ᵸጹ礍扞瀛徍为夞擣尵熈莿簌芵䐿 ᜡ撤ዩ䉴籏㤟ࡀ"

internal val LOCALE_UR_IN: String =
    "00BU檨瑓恨࣏炞藵ै暢崖罊倰粠ᔡჄ乣㡴紪㊃倩慂ዾഁᾪ㊄戠⷟ᣥ蟡坥ᡔᤓᄁ⯳藻ṹ罨歘睤㡦勀ୌཚ㤁䓌塃䦄ΰ悹葏䘂拦獥ၫ嘺峹ጲ檎᷈ᥜ䅩䱏䙦⍰㪤歨篤⺪枈薨❀ᘾ艼୾䕘ं缀紾ずゐ婨妙䅲䮓全㒠㧆☲Ὕᚆઠ࡝澼㈦祲◷蛻টἰ⺳篯䆢壵䚻苊❰㲳京號濒⇅涅⯄剔ᓅ冞募㫌椳ゞ抳䭯渓⊋彳⽔䌟粍枳䘛矞₣ቮ穢䜷悯Ⱇ浴ⵜ捚ロ罄糹奟硑歒备烀族ჾ棂啹ຂब壓堧眢畹澓年摹伸䬍வ纙涳⚀厴䅩ᒴ⫝厚㬝ൎৄ苇䢭ら㊱搦ࡸ俐᠀"

internal val LOCALE_UZ: String =
    "008V䛈㡛恆ࣈ㻾ᮥ欦㩈ᳵ不梓㭪㡱᫡桩㱛斛ፒ歴倇侾涴➦ᙳዿ必⟵椸䜨ⰵ聈⾃઴ᔃ䐚ᩈ桱冝ẜ෠糩綃䊉▞໲੖皤庎ᪧ⒄搶ᙃ绤᧯瀻䁁綳哆茸奫ᐛ☡䢍玕朌挘ࢽ茁ඍ㵌懮傆ᜇ≙㝇刮李㖨巓恡睈帤ଦ湈⧌涁≦㒭䬆潰䧎䌚໾㦄⊗媝瑗㤽冽ࠐ簦䈨嶝⑸奈ᾟ૪᲌葉蝑౹ᒢ墹肙㵞捊緬瓏Ꮫ㜭䃟艐᎟势⥷㏨䙐蜔乷磡脤㯚㙍孟⧖㽴ះ厷㒒ᆀ㡞砏六ᓭ⒑娃收筕⺱ፘ㬑ᥔㄠ倇烑⥸欨䢨㬌ቂ潩᷄梲㵪⣺䨇䙓ᾉ刳⥭᭣䮏瀀"

internal val LOCALE_UZ_ARAB: String =
    "009P䊧㭓恈इ粜泻থ璶㑈⻆䦒穢㳇栈䅰磢婂ᤄ涃侈脓⸈㏹槂䇦㒍篘喗㫙羢具筽㞳矛洚䂕窃䉚䤾灅䒢澊㲿冀യ熀㉺殍䞨ㆅ潅▸檕㚓ᘚ畩໚䅴⺷繁敝胁㨩䱦㈝㯥䨕⒇㷉䍇叻᧥䄮⪼盹瓡エᡁధ嘠䤋㔸⮒䡊㈀ᴠ㾼涧ᆭ䉮䚳ᇱ粹峼哴盓㶠俆ᒇ蜱卽曞䢥咒禎恛篥忛㾏沗伙城箐俘缐害纾䨜蒽䱸ᇱ腕⫿⎿䌑䆼䥸㙗⺥怞汱榸‏懪䎣〳᜽䯗Ύࣔ搀哗牌竺㾛珉仭繦掷⍵脰埳㫻ਕ㐤቉ࢄㅘ䧛দ఑剨儈⹆蔋ᥭ൶灂䪞〲嗘缌䡞ુ䀏瓵຀"

internal val LOCALE_UZ_CYRL: String =
    "00Bt䚩᫓案ᣏ礼糵履ख़栂癦眜᷷༆ሤ⸤᨞ᬼᱏ਌㿆ড⇫乂ク䫟萣㿹ᓥᬫᚊ⾺熿⽽畧㴽娬⣂ᝬ䣷ሩ歛⡈㫐兛⛈惇㵠甪⍦ੌ睰ἂ撷䇲⁯掶⺻㖓㛁仜掱䶉ᕙ㧘䢈䋛皸⻠摳᪁悩।叞ⲽ㿱儤掐⫬桖ᐈ濂ᛰ咶䷴䃿㘾ၽ榞瀩渜∬糁㬔ᦅု༝笵礃⌗മᰳ杭痪夼嵥祿ဉ᨝⨑ⴐⱝ䤒屨⫒垄ᯁ൰⪾ᄃ䨓蔷㛔㌄嬄涆࠱Ờ蓂䅗⮞ᔵ綏⡕竑㚫䞴Ⱄ冂碬博屴䟏勥䙒胻ᮞ▸蜐筠嵗濖曍牿洱凴嬰䈉懟᤟倳Ⅱ窸蓭玷竕䇍♝㖅ᓬ操燍獭淘嗆蟙灮ఏ朳ᬅ芟⏎㗆⌐䨬☇᭏勥ớⴍ嬺唙茩姩桴〬ઇෟ愷⒠㘒甧瓠翲擤璭桴峛⌣掾䡀"
