/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_IA: String =
    "008K䚧硛塦࣏炙瓜敩઎庭援溑ᢽᯱแ焀⡁ಐ╕㲿攟筊蓈罡㇛㣇䐞绝坴楞㲑䋇榨ⷛ琗归ᰀ絷⺠䦴嘦穇㻴蕼䱰拰䚏撗⿁㍑慍ᛋ榤媼඀帛玲ᥥ瑆ᕶ᤮斀↿湌㝡ඣ舐䉚蔩✆จଋ敤戵㢘⠶抲㺸䦯ᬤ棖⬝墋腪㔦癗戵婕冋棎ᖞᫀ羘䠼䯸戱啤姸㑰᫠㙟㵋慬䀬肦ဨ燈簨剀䡐㇇ൿ嶊㴩䴦橼瞚᝸䝺ṯካ絃厁⇽ᩑ㼿ᯈ䚓嫝⺻⛭翯簏䡲㮈冽眒Ⱌ秚㫄嶍䔠⢆⸃㐶倡歚藾䟔␴㞁㟇䈊噤䷀"

internal val LOCALE_ID: String =
    "008o䊨捚恈ऋ癌瑰䧐乓➿ফᄌ卙䢛㧁ᬬ⺫㩉梅㰦蚩珔厸六尟囘䓷军毆㻊孥⑪๫嚛坤㵚᫙ᮛᒩᣛᡶ匩慤ઓ庳携㩽㺻澺棿㕏⸽泦舛ᚕ䊞さ化繣㾯燍䱃罢ཎ膒䮔㥆䩑᯺埸冓㣇༕㫭຺芲张堼巟㥕戸義狅嬹㖰纖檋墱剂㍘樉⶜ᗹ⯎ᐎ疼䊃娢㲢粉優⬸薅桸໒⮸け聏ৄ懍腱奦⇕苤㙸⎸臾岸䈒斢㖸䵭矊᱙ᭇ糖㱝ổ㴭㈌紪晝䗨撖螂怔ସ妶䁸䊍กຉᡒ䮀㲜⾂࿱ΐ梘჏◃害ੳᑄ楐ຌঌ㖍ୈ朎穘ዡ瞶∗期㞍⿪ῃ⧱揵ᙤ痠"

internal val LOCALE_IE: String =
    "0086䋇᫓恨ࣈ㭻ጼ੄獒ू莲兪᱖ઌ⿶瀲傣晊ℊ墵Ȿᢢ砱群Ἃᙢ蟏毟䜾ⴳ劚ሟ䍪⪥糽䫉唶硗怏兝拔噅濛渝男㇫嫛嫛䅪Ừ䋯䫕暮狂⮷㰷呍⫏ᩐ䲀┩ሻ⑱稰ᆈ䨡ᢈ᎘ଲ⦇◿ா⒖考㏼ᤐ抶湔嘳烅掵膗䇁礍滖㏭೏英寕䫮㨺␥ᯄ㆒୉⎤凒⫼㢾璜㮾苝ኆⵡᥤ籀簒坜ⴊ剑歒ࣿᔨ᪚ଆ⃶䌩殬翫䵰䂝縴␅藚峮蟺屵╝⫫嗴荇䁆ᴀ䇔椸焉᪃⁅ᔙ䦐㻄⸞⨜㥤茼牊䑋砱䘽叝✰昀"

internal val LOCALE_IG: String =
    "008v䛈᱓恈ई㭹勌ᛐ䪋ᱥ⻂ভ⌫沤ᮜ折㐑ഴ櫁䤑⛾堉稂埐燪Ⳏ㹋㡅糣旞蜳旿睦᧥䊺數晇㞨₄右䇒武Რ䐤橵少∉夶礮仚䋺架⋣翁䔪ᣒ寒ᴘ粟ⵚ磎➭喴‭෌ᐨ冁礕它㮲盄纳ᆋↈ㕊ะ⤃⡡沏蓰ᕢ◇⁠᭄料欅卣族琶嫆ጓ⎖嫈䗊祘塬ⴷẜ偎⣺₿㤣㒒涿畄ຉ渜壏侈漟䝝⛽ⶲⲭ滱උ‿瀽硿䤡䭓䇒噵য়耬楮罫拠㳪庫㝨刏䃨材摷䡂䁺絰࿿桧纅莭䆾絮缈宠㿼羭疸䈂₿壨葌璈Კ槽棁䨈ㆤ೒➛લ茥䐔⯋Å᷸ࠀ"

internal val LOCALE_II: String =
    "009X拈᝛恈ई㍹勌ᙡ媮₌ለ炮㘴℣勄∪嶂ᰱᇉ挂ᙄ䤆䈀愢㩝缙燲⟈䄳᪟槶濧滭浪䎪࿀㽕㶰⒏彇᥍㿒ᚆ䌪蝫ষ冹垛ᾕක懟舖悩࿱㵥࠘䭈㠂⃒ᐠⴱࣤ᠀⩇嵻㴥╍⼝⠦灼荙᚟⏞ㆺ岋薮放牤㈭槶盙㻝㕬ᡸ狚盕┷㵃佺荸孫殺㒸㛒䚓崛抆洏寓㤩竅䘬㈣䍖ክ૖棏௢䡖㻋㣺䙚Ử㓪孅舀⫬㑑㿧岟洢ᜓボ⽓ᨯ䨐菄夛嵿牯娉न芜ᨆ熢槳ᢁ昁虂੃虌獟୨፩砋"

internal val LOCALE_IS: String =
    "00AX䛈筒䡦ᤈ໻᫈❠ᒻ㻖畍瀩㴕䁹脇᳝㾻㻛ⲻ૊䡇炍ౝ枊䫁⦇徹冯䤣≏㝿ଈⳟ้毂⴬展敋๲⍨ଥ技晨甦挴楙⦥㿲武ྭ䆭຦憎洶䍐妦㢟獚⁪ᔖ䜊冡吹ၒ㍤⋙ඖ㥻紧⩷天假㨌嚄Ṡ摁䡩ฅ䵵园娓㙡䵗⁑ᴋⵤ煓唚๺玂獲玴䫂著Ⲹ㰮動䗓ᗬ蓳ệᵉ繮喵㆜ዎ䰧⤋‎礷偷僄ᰉ灙捚㐜硕汙䴹⣉䒍肮ᓼ埍ⱱ䴠梑琉㿢ᾜ娼዁偷甯猘ხ综䱟㰠缑秼ἁ臫砟⪸狷༝৯㱸῝䞢卜᎘瀙㭼䡄勐↮日㈀⁚烍㓁厏玪ය浫禁虀㚛倖吢䱭ࡰ䕬⩟炄绗㇫慸崒萔胯൱安ᡛ䕗౤獦Ⓡ毻੾આ㥋蘞ធ曫㞁㟄滥哰ಀ"

internal val LOCALE_IT: String =
    "009e㋈屛恆ࣈ㭿ᏐࠫⳐࣱ正⦣皃㭎卹⼵ⶑ甂ㅀ㤤㉁獆债欷琤應扠儕᯵枳䛭⮤₡Ở㫬嚀勗෨ễ潵᧨᱂呩䛹ⶆ侵ㄅ♑捹෎蔗廔愶෭斒≻䱀嫛䡦ᩐ煄咡ᤦ➈傉㨤⣪崲キ䡐芆ࠋ昕㹨㞰乧吙ᦫ璎忞埒肈然荄樀節⧂⢌䊂⽊ࢁ綍䪸盰㊨␦树㪩傹㈀㖶ॿ㏚ᕻṬヘⷠ夸⟘ય姧द屉䢓噬啤ධ瑛ᇠ腥絺睛䓫兯⯁䛱蔙䥏璜噼䙴峚萋⚉櫾㪘澷幊杋榟槧栺ᨮ乶蒅ⴓ獼Ꮓ㠜⧞筋寠哤䍩㥞ඌ刹ⴸ笛嫩䳩⥏⮉稤標㾈渝㩠熖箎ᒳ᳣䵮☂䬟橃瘀㷔は呯蔙葹䑄甍㏀媋游ૠ"

internal val LOCALE_IT_CH: String =
    "009f㋈屚恦ࣈ㭹᎜ࡂ䁭猻❺苕忖䶶ඃ暝欹䭢Ꭳ卭ದး现⥷兎Ⅴ侨溧អⴢ蕊慈㥂㖼ⷕ䒡மူ㖋囨㏑ゅ⃒旲挝ི帮䒡㻷ጽ䉯䖅⩼Ꮣ䜤㳷ႁ㔷䣌ಡ媙⅂⹈䔓ᤒ泈ক㉤奛Ⴉ礈ᨗ䐫瑐❡㓯ဢ㍟攛㖿➤禑娭纭封澀䮀䤚簄曔ः匛㳡巨嵐䉍䠢浓ᤲ尠卬ዶ宴⋶㗙夲Ꮙ⩻῜㭗烳䢓ᬺ᳸儑盁幎敡㫏伣㗗臗⻽瞦㘋垇胄౷淧穢㯥滗塩籾⌗⋈䊻㫎企吾៾ਙ४䆻椳爝䉡⛻⢂໷๩┎缢揋厱呤ᦺ㇧᳁╎⭎Ꮕ┏ᤦ䢛ᓦ䓣℄凳奰Ⱈ濜挀㠼ₚ␞礇㐡䣳⮿䂿篣稦桢搅὞码ῠ"

internal val LOCALE_IU: String =
    "006o勇筪恆ई㛿ᤰ䑀梒嬿莕᪍栤ᡝ䉔ᳫ⦂畂檻藕⏿䅰壳ᩮ䇃้儆ᥬৈ呁Ⓟ᪐刲儑帐茌臘⣿璴䁄胄ⱈ႐槂涞戳㳞妴ⵦ涍ᵴ瑖ⶺᓠ蕂男眵㉌ⱂㅒ䬠䦐㳈䄛ൻ⸴䵊ክ㽙⯿䆥糫攻⵩快蝿䏙嵘埔盻莛禸疅皦煸蔽䲻泣ᩦ擰ቌ䍝ᕏᖚ罓㓶笛䯣攝ဣ⼂犅ࡥᲢ䓮纏⤝蛖⽷ "
