/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_RAJ: String =
    "00EV犩᭒桦ᤏ焼埲࡚瓖犵⏊暢椂寀換䥋⾞戊㔈එᑵᲄቝ᪶痕ㅔ䔙⟹㟁⤼囖總䓫恍晻沲䏇梄䀢圈㏂૜仈ᮏᵎ፼᩽఼ဟ哯䱯䤌᪒䋤₄筎ᦹ✧䶴ථ粖ン㈚ზㅃ耄ᗣប慾㧢池爡蘤ᆊ抌ዾ㌝⵵晊䷿䜅঄茐ॗ䌀䎮樜๠㤘ওᱬ擗妅氫㰒盻禳幕⓬⾕Ფ⒈捊㗕࿰⢸䤏潗啴犨㏶叩缌㒜⣜蟉舀ㅫ嶣㍒嵇殦祷窶槃屛婍亖௰撳⍋䅺乚⛫䇐練䩟䆪≢⢮⚩峷䌚芾㮹⃜䩮ⴷṷῦ䆛凰⡞泸嫞㋾৒屷ኢ䗠䗻⌙≆慢ⴊ桅菤ఀ"

internal val LOCALE_RHG: String =
    "005s勇筂恆ई⻻ᣘ⚠⥉燯滢摌尖不啂䨼屐䖨䑷㮤Ⴁ䀬◰罷咲ၚ䮚侩Გ࣎ⴥઔ婁嚒缜珞哷瀼䑐ਲ稔ᰨ案㹯ᚫਹ疲榴籨薀蓸櫙枨欶毿■橅笴㰲ጌ抓᳎䈓曅ᰲ㚱↵ᝯ䭭ሽ㊎攧䶢睶芴脫劘蝎紩煳䆻擬蛕绹牲ᙜ㛈⵸ⰶ悤聾䄫ऱ䐔幻ហ䜯᧋ী"

internal val LOCALE_RHG_ROHG_BD: String =
    "005x勇筂恆ई⻻ᩈᝑᢤ糷孩䏂灁㧠㒷ㄆዖ᝚䘻凟揲䧇᭮䋋ẅ䱘䰸焉ை剂㡊ⴤᑢ໰澝ㅟ痋䎀⮄⩂亂ሌ丌䭩蛗䕇瀚彌仕茬།䴚籹⿯䇞ᐔ㎲⡄岓ゥ屜眴ᾈ结⥴ᛴ⢞妮笿㱎⪒撫⍯掼緺㺧洹蜞睼䆶栯䔘ⷫ莫ॿ奂䍉⇂ㅥउ儣俣庶෩曝滰擇㑗ࠀ"

internal val LOCALE_RM: String =
    "0080䚦塓恦ए湍䆾荈幒ू羨䫛グᕈ刟䖹怤匉᧢婩໕㑋䟀芽䨺ὂ䳊璧憙哪乊筹᱖提ᄞ竨㦵४琟巗殓ᐩ崠䕁㟱箬畝ⷫἋᗰ∻㎼粚䗚䍝縻瀦翍❒ẹ弎ᄪ哨䙣᛽ᘾᗡ績耪䭷㯈㰲䪼濳ᠦ⮅ა☫䭳ద჈籭䱲吁㫿ࡡ㒰峇ᵶ浼Ἧ纺䍙㊀棴ろ䪠⳻⢚綒㈏嫒瞋舺斐皝穑⽑⎊㠐ත祇ਕ㬁῁ㅗ滃凕莓碐᮱䳔缡ത溍䠋蘆㰔㦽會缛૎揗౰綧藸敡࠼᪳䨧䑞䟺ੳ⃝嫛旼蝀聙縁渮䷰㒇橷剒≣ಠ尡圖ຽ昀"

internal val LOCALE_RN: String =
    "0089䋈㽚恈ई㛿ᦰ䒁幬也藫㡄䥻ㄗ憸炗㪄幈ℂ㈰古㫽䔿ⲳ屢ᾝᩳ垖㬷惄剹狻䪛᷼㉂ᔻ㴔疶崠潔摩潢㭡䵓碭炠∤归Ⲿ剻ℌ腝綉Ṩ⴯⽵撵体挟葂纼ₛ祼兝ᵘㄑ瑴纨䰫禢☤犫娻䑙ᬙ涶᫓撶秥沤いᐐ禆੩䬜⃡㈑ⲡᥘ旐ヨཝථ☱ᱵ⃛癅⼖葎姱畔蜾惴㞲毮藹競ᶆ䀤焮椴䳟┧眗㗳兤漞ⷨ勱侏末⍬⨃笭剝䃫搹汞䷚淞昸⤖⨎၃珄㛸☦榯㌕奵ⶣ⩫䮙祔蛱ୱカ怤描糚ᑖ⏅祤╍䫏ၐ倷঄㿢⛲▨␇ᥰ㓅໭㾇倌"

internal val LOCALE_RO: String =
    "0091䚨塛恈࣏汉搽ᥛ౐塮Ⱊࢪ攱祗廸冷檊㹑ᄢ梑ഹ縍㰿塏检憵ᇭᕅ罛⳵䶏➴拒獴沃ᾓⱝ喊㩜猆㙊㕚偀⼹䃉渦狶筕໊ቚ穅扒੷㛱乯⹋ᾚ娱檭Ⴊᱱሴ伕暚᱉ሢ挽㈔儅㚱⠊姌砇₦䘳✳䐃⇦಍↫ዧნ蓠㠩军䲗ࣴ嚱ᬵ⹕胑织ୟ㕌ད勈ㄹ⋩┦㠫䜋惦疊ぴ小䘩䬽蘘⭴璪ℸ㏅᚟␕屩㶷繟◮娯㭹ᗺⶂ᳣ᑻ劍卤禗何窶㹟炇荂⍐枽苜῭螑ᡶ᥿䕸ἇⴛ毢抶脶ᾼ⛀宲◬島᧬㳺䙨砮檔発柮ᕁ勩兡䇦Ꮹ瀞埜ࡱ࿎ᕸ䠏艾ሺ⌴ⓘ⸁⸅⠔蜘䀝䌔⅚愢䐻᳘蜑舂"

internal val LOCALE_ROF: String =
    "008l䊧捛恆࣋瑌簍いㆅॿ喚⩁ྗ薰㑢ૐぉ炍⤀ఽ妫曲䃉嘺゛吖柯⛬⩺ᘟ㌶將㏺桿㤐໹佦折棣悧吾⒎縉瑍㰺ᶭ礢⣏䝊笶⻚ớ殿怾㈁涛໯炅晈婀⒨្ࠗ⠀瀈㈁⭠⃈౤摃䇊䂇澯耑䞋ᚢ槖䓝羯藭敹䓮䯹⭯ᖅ㽣㦬缕䏢唕瑢蛹筤ᒄ搠萜䱉椤茬ৠ壆ࡁᱣᥢ溿蜾䟘⃫ර荲ል澄係ᯘ嬋⪱⊒⟳䆉䏭ၺ⯎ᮉ臉斥㳮ᡉ烗䌆濳コ杞⻽ㄷ䑞ໂ䄚᦮ଢ଼㳖㬭䌃ጹ₢炬㨌崷㕑ᚐ怀"

internal val LOCALE_ROOT: String =
    "005t勇筂恆ई⻻ᣘ⚠⥉熟揊䪥碴ᡜ舔ᷫ⢂畁䶷莥ᱟᔗੁ替⁥ᠵཱུᝂㄴ࢔削⇉Ⲁ┥昹羝ᇿ䁰胄థⳈ偑䠓㝈䕎呅獭䭦獐掎涹澵㛑㊫柳捃了Ḩ灤嬹ⶦ㗱⨗曍ᰲ⺲᪺徱琽ऽ㉎唣嵪䔜ᬋ櫮䉳綷擠▥䎇糶胚绹瑲ቍ困⥸ⰶ愨膾䅴ᱢ砡㒷ྡᛑᑥೀ"

internal val LOCALE_RO_MD: String =
    "008z䚨嫛恆ऋ癉栝ᢎᅐ塶Ⱊࢱፀ攧䀵殖峘䳎ข⨕㧈⋨䝁ἠ෇紜≪盚䌓潾㲟♦቉秒ᅁⷭ⹕攵Ჴ㫈癩痂हআ㼣粷䍔㉊ᰪῊ徾⧶⽙單㦓焪叕攲梩ဵ胥磅粱蓗⪗⩗樣⯏⪖Ⲩ編ਨ㭸䠂㦟ᓯ呫డ◢ᄓ惲☯䎞哄๝䙰勱刈䌲䴴摞䋵䎢彘ㅊ垓墺形㢆ㄔ偘⸼痏晦⅘䄑嬧ુ㫧ု⏃⅞咄⩆傽藞〕⑙ᆷ聺挘娠碅斘巾ᦎᲓ୻⁎⮭⯢䱇ጏ瑓膡ᾈ㤾䫠呎枨舫亟㽷琏䬻棝侷ໆග糘唡⏥桷ᩯᱲ䕫ᠮ蓞杕⊧榨どᒦᆞ㗹ᤁ熄ろ堍௎稗蔐旚䬯粘㚏䬈䬆検㫺㼘旲㶱磅悴臁旧栀"

internal val LOCALE_RU: String =
    "00CC䚩㝓䡈ᤇ粞澭塝⌻⠠ᚂ橳ⲷ桀と屔Ⱔ䎰ㄐ⸸听᳼橡㧥✐艰൙司᩿ᛝ汔桢㛜罻筳懏䬻挶ᢧ⛲牢↑⓱⵳熹䴿砇ᴾ櫯胊‶䀷殭䶍㬴捎䝀⍓ਭ⸏愼䤌垁ࣔ艦標橳獻槍⒥搞洉笆Ⴢኈ罞䷩᮳㋒⽄螫瀧⤝䭞䯫厲濔蔺纹扱੼⭾ᨿᓮ㠿氎蘥䜓➈忊菌⟈对ὒ蘈晳୐㉡蘖ᨺ䷄恽ぺ栕茳⸸菂ీ縇ක摋⾦⿙蜍挻繰ో妆熧䑤ዦ溒奁ᣁค⦐媞瓆夼⥾ᶉⷴ圔ࣆ紖峅娐䃚水臣嘌㶺芎碽敋聞ᖥ螉ᬞἸ广ᗇ♗ヲỪ拕㽩悬挭羉䃢▬ᡥ⤿㯩䑏烾ுᐗ洓煌岮嚲舾突ᒭ䂺杏ੇ䰣ᢿᱼ㢒㼇ㄨ苍⫷ḃ㕉穿砃ᵼ䅟ᐇ窯忋ሙ᳄ᎃⴠൖ䞖ࠇⓅ㽙≪⢗ᕌ昬扦砀"

internal val LOCALE_RW: String =
    "007s䋈㽢恆ई㛻ᩈᝑ⦩苻掕玀悒淇Ꮧㄌ扊᧚୩㥝菣⎳廵檐⹧᭤秒㦍茌ᢓท獒䭇勂棫㞚嶣ໆ䤙藨ᷖⒶ㐭ৌ▶ᐉ䄎尺柜㜶⵰翍ጜ䥜᧷吓᲻縦ᝧ箅窈歸富㌆ᵓኩ䵄檾㶃嘩ᬔ䦊ᡖ㜄䭄⦄⁡ᑣఉ⼱ऎ⢵簤䌟०㓊棉脮ദ⒜発禓䭿纋柚蟗蒋⽽壼挟〉㈸㙍㡭ᮐ棣䟶㍇⓲劭䮣ᤣट⑨䜠䮽呈䂎蔙聝Ẃ⬓䭡ㆀ䎚⯄拷䣪棌ᠦ神侥蒷勮㐯ኗ綔暈ᷟ㩺蜏㮰㷔焘俣沺ᆸਤ⣌ᬀ卄团ᙴᙃ肑ง᝖伇堬"
