/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_NB: String =
    "000v凧媳ᩩ㲴璖㔴愤匬ᰁ㲦㙋≗刄碎㚱∮㏎Ẉ᫳緒᲼敼唯ᩚḇ䢉䣀桠ࠀ"

internal val LOCALE_STANDALONE_NE: String =
    "002D᫆᫂堆ࣄ⭾养੗䊐ὢㅂ౑ଈኑ葑㝝簪䆊㳉䢒ㅼ汧朑ಈ俬刨ມ聈揄ⴰ㬒憸ᦩ⥗ᯂ㷟ቃ㕛㻟婌╏ລ▆ᵮ≟⹒䰝檵䩆䘓䖖憡砀"

internal val LOCALE_STANDALONE_NN: String =
    "001M໢硃㠄ࣀ㚂㷹㟁桂⊋გ䰥憃䲁痡噢䆼☥㌢Ṅ㌸ᕞ㰾兝嬅缝弊慛∎㘱ℹჳ䒊茜⪎卆᱁⋦箇产⨥䩸ࣀ"

internal val LOCALE_STANDALONE_NQO: String =
    "0011凋淥翧蛿簧疯撟ẃⅳ⣆ើ祼曬藲蘏䲛໒㶠✞䛯䛶藑蘍ბ䊿蝿㬾㜠㠀"
