// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `aa`. */
public enum class Aa(override val tag: String) : LocaleRef {
    BASE("aa"),
    DJ("aa-DJ"),
    ER("aa-ER"),
    ET("aa-ET"),
    ;
}
