// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `ann`. */
public enum class Ann(override val tag: String) : LocaleRef {
    BASE("ann"),
    NG("ann-NG"),
    ;
}
