// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `bas`. */
public enum class Bas(override val tag: String) : LocaleRef {
    BASE("bas"),
    CM("bas-CM"),
    ;
}
