// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `bgn`. */
public enum class Bgn(override val tag: String) : LocaleRef {
    BASE("bgn"),
    AE("bgn-AE"),
    AF("bgn-AF"),
    IR("bgn-IR"),
    OM("bgn-OM"),
    PK("bgn-PK"),
    ;
}
