// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `bgn`.
 *
 * BGN itself is the bare language, `bgn`; the entries are the locales below it.
 */
public enum class BGN(override val tag: String) : LocaleRef {
    AE("bgn-AE"),
    AF("bgn-AF"),
    IR("bgn-IR"),
    OM("bgn-OM"),
    PK("bgn-PK"),
    ;

    /** The bare language, `bgn`. */
    public companion object : LocaleRef {
        override val tag: String = "bgn"
    }
}
