// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `cad`.
 *
 * CAD itself is the bare language, `cad`; the entries are the locales below it.
 */
public enum class CAD(override val tag: String) : LocaleRef {
    US("cad-US"),
    ;

    /** The bare language, `cad`. */
    public companion object : LocaleRef {
        override val tag: String = "cad"
    }
}
