// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `ckb`. */
public enum class Ckb(override val tag: String) : LocaleRef {
    BASE("ckb"),
    IQ("ckb-IQ"),
    IR("ckb-IR"),
    ;
}
