// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `fa`.
 *
 * FA itself is the bare language, `fa`; the entries are the locales below it.
 */
public enum class FA(override val tag: String) : LocaleRef {
    AF("fa-AF"),
    IR("fa-IR"),
    ;

    /** The bare language, `fa`. */
    public companion object : LocaleRef {
        override val tag: String = "fa"
    }
}
