// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `gn`.
 *
 * GN itself is the bare language, `gn`; the entries are the locales below it.
 */
public enum class GN(override val tag: String) : LocaleRef {
    PY("gn-PY"),
    ;

    /** The bare language, `gn`. */
    public companion object : LocaleRef {
        override val tag: String = "gn"
    }
}
