// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `gv`.
 *
 * GV itself is the bare language, `gv`; the entries are the locales below it.
 */
public enum class GV(override val tag: String) : LocaleRef {
    IM("gv-IM"),
    ;

    /** The bare language, `gv`. */
    public companion object : LocaleRef {
        override val tag: String = "gv"
    }
}
