// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `hi`. */
public enum class Hi(override val tag: String) : LocaleRef {
    BASE("hi"),
    IN("hi-IN"),
    LATN("hi-Latn"),
    LATN_IN("hi-Latn-IN"),
    ;
}
