// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `hnj`. */
public enum class Hnj(override val tag: String) : LocaleRef {
    BASE("hnj"),
    HMNP("hnj-Hmnp"),
    HMNP_US("hnj-Hmnp-US"),
    ;
}
