// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `id`.
 *
 * ID itself is the bare language, `id`; the entries are the locales below it.
 */
public enum class ID(override val tag: String) : LocaleRef {
    ID("id-ID"),
    ;

    /** The bare language, `id`. */
    public companion object : LocaleRef {
        override val tag: String = "id"
    }
}
