// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `ii`.
 *
 * II itself is the bare language, `ii`; the entries are the locales below it.
 */
public enum class II(override val tag: String) : LocaleRef {
    CN("ii-CN"),
    ;

    /** The bare language, `ii`. */
    public companion object : LocaleRef {
        override val tag: String = "ii"
    }
}
