// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `kgp`.
 *
 * KGP itself is the bare language, `kgp`; the entries are the locales below it.
 */
public enum class KGP(override val tag: String) : LocaleRef {
    BR("kgp-BR"),
    ;

    /** The bare language, `kgp`. */
    public companion object : LocaleRef {
        override val tag: String = "kgp"
    }
}
