// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `ksf`.
 *
 * KSF itself is the bare language, `ksf`; the entries are the locales below it.
 */
public enum class KSF(override val tag: String) : LocaleRef {
    CM("ksf-CM"),
    ;

    /** The bare language, `ksf`. */
    public companion object : LocaleRef {
        override val tag: String = "ksf"
    }
}
