// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `lkt`.
 *
 * LKT itself is the bare language, `lkt`; the entries are the locales below it.
 */
public enum class LKT(override val tag: String) : LocaleRef {
    US("lkt-US"),
    ;

    /** The bare language, `lkt`. */
    public companion object : LocaleRef {
        override val tag: String = "lkt"
    }
}
