// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `luo`.
 *
 * LUO itself is the bare language, `luo`; the entries are the locales below it.
 */
public enum class LUO(override val tag: String) : LocaleRef {
    KE("luo-KE"),
    ;

    /** The bare language, `luo`. */
    public companion object : LocaleRef {
        override val tag: String = "luo"
    }
}
