// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `mgh`.
 *
 * MGH itself is the bare language, `mgh`; the entries are the locales below it.
 */
public enum class MGH(override val tag: String) : LocaleRef {
    MZ("mgh-MZ"),
    ;

    /** The bare language, `mgh`. */
    public companion object : LocaleRef {
        override val tag: String = "mgh"
    }
}
