// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `mi`.
 *
 * MI itself is the bare language, `mi`; the entries are the locales below it.
 */
public enum class MI(override val tag: String) : LocaleRef {
    NZ("mi-NZ"),
    ;

    /** The bare language, `mi`. */
    public companion object : LocaleRef {
        override val tag: String = "mi"
    }
}
