// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `mn`. */
public enum class Mn(override val tag: String) : LocaleRef {
    BASE("mn"),
    MN("mn-MN"),
    MONG("mn-Mong"),
    MONG_CN("mn-Mong-CN"),
    MONG_MN("mn-Mong-MN"),
    ;
}
