// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `nv`.
 *
 * NV itself is the bare language, `nv`; the entries are the locales below it.
 */
public enum class NV(override val tag: String) : LocaleRef {
    US("nv-US"),
    ;

    /** The bare language, `nv`. */
    public companion object : LocaleRef {
        override val tag: String = "nv"
    }
}
