// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `or`.
 *
 * OR itself is the bare language, `or`; the entries are the locales below it.
 */
public enum class OR(override val tag: String) : LocaleRef {
    IN("or-IN"),
    ;

    /** The bare language, `or`. */
    public companion object : LocaleRef {
        override val tag: String = "or"
    }
}
