// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `os`.
 *
 * OS itself is the bare language, `os`; the entries are the locales below it.
 */
public enum class OS(override val tag: String) : LocaleRef {
    GE("os-GE"),
    RU("os-RU"),
    ;

    /** The bare language, `os`. */
    public companion object : LocaleRef {
        override val tag: String = "os"
    }
}
