// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `pt`. */
public enum class Pt(override val tag: String) : LocaleRef {
    BASE("pt"),
    AO("pt-AO"),
    BR("pt-BR"),
    CH("pt-CH"),
    CV("pt-CV"),
    GQ("pt-GQ"),
    GW("pt-GW"),
    LU("pt-LU"),
    MO("pt-MO"),
    MZ("pt-MZ"),
    PT("pt-PT"),
    ST("pt-ST"),
    TL("pt-TL"),
    ;
}
