// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `qu`.
 *
 * QU itself is the bare language, `qu`; the entries are the locales below it.
 */
public enum class QU(override val tag: String) : LocaleRef {
    BO("qu-BO"),
    EC("qu-EC"),
    PE("qu-PE"),
    ;

    /** The bare language, `qu`. */
    public companion object : LocaleRef {
        override val tag: String = "qu"
    }
}
