// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `ru`. */
public enum class Ru(override val tag: String) : LocaleRef {
    BASE("ru"),
    BY("ru-BY"),
    KG("ru-KG"),
    KZ("ru-KZ"),
    MD("ru-MD"),
    RU("ru-RU"),
    UA("ru-UA"),
    ;
}
