// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `so`. */
public enum class So(override val tag: String) : LocaleRef {
    BASE("so"),
    DJ("so-DJ"),
    ET("so-ET"),
    KE("so-KE"),
    SO("so-SO"),
    ;
}
