// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `sq`.
 *
 * SQ itself is the bare language, `sq`; the entries are the locales below it.
 */
public enum class SQ(override val tag: String) : LocaleRef {
    AL("sq-AL"),
    MK("sq-MK"),
    XK("sq-XK"),
    ;

    /** The bare language, `sq`. */
    public companion object : LocaleRef {
        override val tag: String = "sq"
    }
}
