// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `sr`.
 *
 * SR itself is the bare language, `sr`; the entries are the locales below it.
 */
public enum class SR(override val tag: String) : LocaleRef {
    CYRL("sr-Cyrl"),
    CYRL_BA("sr-Cyrl-BA"),
    CYRL_ME("sr-Cyrl-ME"),
    CYRL_RS("sr-Cyrl-RS"),
    CYRL_XK("sr-Cyrl-XK"),
    LATN("sr-Latn"),
    LATN_BA("sr-Latn-BA"),
    LATN_ME("sr-Latn-ME"),
    LATN_RS("sr-Latn-RS"),
    LATN_XK("sr-Latn-XK"),
    ;

    /** The bare language, `sr`. */
    public companion object : LocaleRef {
        override val tag: String = "sr"
    }
}
