// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `suz`. */
public enum class Suz(override val tag: String) : LocaleRef {
    BASE("suz"),
    DEVA("suz-Deva"),
    DEVA_NP("suz-Deva-NP"),
    SUNU("suz-Sunu"),
    SUNU_NP("suz-Sunu-NP"),
    ;
}
