// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `tzm`.
 *
 * TZM itself is the bare language, `tzm`; the entries are the locales below it.
 */
public enum class TZM(override val tag: String) : LocaleRef {
    MA("tzm-MA"),
    ;

    /** The bare language, `tzm`. */
    public companion object : LocaleRef {
        override val tag: String = "tzm"
    }
}
