// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `vec`.
 *
 * VEC itself is the bare language, `vec`; the entries are the locales below it.
 */
public enum class VEC(override val tag: String) : LocaleRef {
    IT("vec-IT"),
    ;

    /** The bare language, `vec`. */
    public companion object : LocaleRef {
        override val tag: String = "vec"
    }
}
