// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/** The CLDR locales whose language subtag is `yrl`. */
public enum class Yrl(override val tag: String) : LocaleRef {
    BASE("yrl"),
    BR("yrl-BR"),
    CO("yrl-CO"),
    VE("yrl-VE"),
    ;
}
