// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.catalog

import dev.carcara.kotlinx.locale.LocaleRef

/**
 * The CLDR locales whose language subtag is `zgh`.
 *
 * ZGH itself is the bare language, `zgh`; the entries are the locales below it.
 */
public enum class ZGH(override val tag: String) : LocaleRef {
    MA("zgh-MA"),
    ;

    /** The bare language, `zgh`. */
    public companion object : LocaleRef {
        override val tag: String = "zgh"
    }
}
