/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_UG: String =
    "007P_Th\u0011w\u0009a\u0011\u007F3(\"{\u000390Q\u0013Z2\u001B\u0002\u0005K\u000FQ1V\u0011\u0015n\u0008\u0015\u001B\u001F)*\u0012f\u0004\u00096\u0018G\u001A`w\u001Al*\u000F\u0016\u0004,Ic\u001F-w:rF@9q\u000DgX#]Z&\u0002\u000CTQ\u0005pG7 <\u000D;\u0005i5/\u0001i\u00105_\u0016`3*\u00024EW<\u0011h\u0018;\u0019\u00110T)Z)\u001DP*\u000FU\u000F1Q\u0016G(S\$\u000D9\u000F{\u001E,tug\u0011u+8\u001C+RJ\u0002/D;An/U\u001B*.v\u0001!3k~\u0007\u0019qva\u0013Y6u?6UFV\u0006+4^\u0005lON\u000D',-\u0016\u0012MdtEZl@D\u0014T\u0014KRjAB\u0006\u0009lE\u001EC\u000AOMy\u000A(-aDf\u0014Xq4@_zi="

internal val SKELETON_NAMES_UK: String =
    "0063WdY\u0011m\u000A!\u0011#\u000F| |>:u\u0016[AZr#\u000B\u001F\u0005\u0003.\u0010#\u0014\u0006\u000E\u001E#\u0001-\u000D>\u0001\u000CZH8\u001D8# IiwxJO4Z#t\u0002\u0005X\u000F\u0009\u000B-ayQ&\u0018\u0003\u0001\u0013\u000Fy:a.\u001F:tMMe%\u0015\u00155>4W]\"58\u0012}rp=(\u000D\u0015#\$qcI\u001BC\u0018\u001D 3-i`;\u001C*\u000B\u000C\u0004q**\u0003S\u0005Gtjgz\u001AynG>x</t>rZRG]n/3\u0016\u0009\u0001\u000D\u0016w\u000B+z\u0019~W\u0010Bj5\u0008;2!Z?C\u007F\u007F}19"

internal val SKELETON_NAMES_UR: String =
    "0062_U\u00182\u000F\u0009a\u000DoR\u001Fa7\u0001\u0015UG1BlITM\u0013rqCUZ\u0012ddfU5]IrvW\u001A3\u000BC#Bh;j|j\u001F(\u000A\u000C\u001D4YEy|!j\u0009\u001A{ \u001A\u0002\u001D#Qla\u0016qq\$\u000AByeA{mM\u001F\u0017\u001Ap\u0008RmF]=\u0012\u000BvY\u0007X3gBdhP\u0008zRQeZ1Q=+Tl'KKKaNy\u000A#\u000AJk\u0009PR8\u0004v\u0001\$l4}\u0007J\u0012\u0014}\u0008Ev\u0012y8a@{Aq\u0013n'6k2gk{S\"\u000C2gn5\u0018O\u000Ed\u001C\u000E="

internal val SKELETON_NAMES_UR_IN: String =
    "005/_U\u00182/\u0009a\u000Do:\u001EAm\u0001[\u0019\u0013O}K*A_2\u0018\u0018\u0017\u0015\"z\u001B_\u0010\u00164-f\u0007h\u0017ajE)\u000Dj\u000D(oS%to(\u0019!\u0006z\u0006\u0014om\u001Ak\u0017\u000F~\u001E,%\u000A<\u0002>\u001E!\u0006#H\u0014%HgioJ8\u001Au}\"a\u0004=f1\u0017V\u001D\u000B3;.\u0014\u0007-Z0g\u0005BN5i}zV82\u0016S,\u0012'N\u0012\u001F\u0002\u0019*2;k\u001Bw@Q\u0007\u001DM]Z_bj?\u000B5Bz\u001FM_\u0008qT|3QQq[^%]ME1;o9\u001C\u000DCrPG?1\u0011"

internal val SKELETON_NAMES_UZ: String =
    "0039&L**&0\u001AMISzmB>\u0016ML3vz%O(L%\u0014\u00065KT\u0011/gssA\u0019J\u0002\u0002\u0009 R\u0004?tc\u007F2\u0003,MT\u000ACg1IC\u0002m`4\u001A\u0015*ewz!\u0018V5b\u000D2C\u000D2')\u0002L\u0001ka=-\u0004FCx=Dh\u0011f}\u0013%]C`7W\u0016;\u001BB[Q\u0016bt3\u000B?\u0019.\u0001\u0001"

internal val SKELETON_NAMES_UZ_ARAB: String =
    "002J;cI\u0011W\u0009a\u0011#\\\u007F*\u001A\u000F2k\u0005cI\$2;\u000D/F3n\u0005>\u0019\u0011\u001A\u000DeISNgw\u0017,X8\u0010X=|\u007FcENja2*\u0014\u000BNLD)]\u0003q(#{{:@\u0005\u007F3 N`v.`7-JiKoh\u001D6Y\"PgAy\u0002H\u0001V\u0001\u0019v\u0004(\u000FRiMAx%Do\u0007T&y=\u001Bl/\"q"

internal val SKELETON_NAMES_UZ_CYRL: String =
    "004KOT(1W\u000A\u0001\u0015_3>Fs\u0001bk\u0005l\u001B(Q\u0011\u0017\";u\u0006!\"\u0011\u0016\u0017\u001C\u000EF!Az\u0001YW6R\u0004O\u000Fz\u001De.t71m8\u000Cdgf}\u001D\u001EZja\u000Dh^{bZ\u0017s_KY\u0012_}\u0001{\u0014h.K.\u0007hmsRb|la\u0013A'A<\u0007R\u0019kd\u000C(<Z5ia\u0015{\u000FHX:!6\u0015ri\u0007&\u000Ds1\u0006enL\u000B&\u00135SMaM'<\u0019Gg>\u000AIqt\u000B\u001DCK7.W\\G\u001B`PP\u001F@E\u0018"
