/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_DA: String =
    "003h\u001Ep\u0016CCH^qj\u0009X\u001FfL\u000A#J2\u0004LOt\u0007LzUK?(\u0014IKjUk2\u0017PKA-\u0014Zn\u000B]A,lED\u001A^+/\u001CMv|#\u0013]9\u001BogA~\"\u001A_)\u0014a\u001B7U\u0012B\u001B\u0012G\u0005p\u0002\u001A\u0009n\u0005HYC\u0009An\u0007**S\u0006Sz\u0008O\"pL,\u0007\\\u0003>\u001ERlUz\u00066!l\$A3=\u0010\u0006\u0011Tr0)\u0001"

internal val SKELETON_NAMES_DAV: String =
    "003tSd*QW\u0009a\u0015C\u001Cg(J`\"+\u0014E\u00025V!Q^] T+9&S\u001C\u0005\u0003)UX>]WR\u0003k{u\u001A`\u0019Pyi<U\u0002MehO\u000Dys%F\u001B\u0009\u00081\u0002j}T]\u0015W5\u0019]\$\u000F\"3hr;0\u000C*\$3lB\u0017{+_\u0016PBu1\u0003K^P{-jKr\u007Fv3z\u001AZw\u001D_37=Eq~2i\u0006_aLe\u001C@)\u001F<+ugV\u001AS:rbv(\u007Fz="

internal val SKELETON_NAMES_DE: String =
    "003b:L:\u0005\u007F:\u0012\u0016zSZCEI\u0017-'L\u0006%O3\$tgtj3eG(\u0014\u0006Bj\u001F-UJ'fb!\u000C\u0009s\u0011M\u0017tH\u000Cb\u0011P.\u0013\u0016&lF\u0011i0\u0013V:d:O_\u0015c\u0013zQ4PLe\u0007~#G\u0008\u00191\"M2B\u000B1'9*\u0010[\u0006\u0002<!I\u00185\u000C\u0003wB\u000C_\"tI,wkcX!0'V;sB[Q\u0016bzn\u000B\u0006DIJYC\u0011\u0001"

internal val SKELETON_NAMES_DJE: String =
    "003OGd\u0009\u0011W\u000A\u0001\u000D#\\\u007F\$\u001A`!k\u0018U\u0003\u0002a\u00110FCu\u000CQ3\u001D6\u000B\u0012b\u001A\u0015\u0013,_o\u0009/cNh\u0011\u007F_@\u000D_\u0009\u0019.\u001D#\u0016;\u0012\\,\u001A\u000Ce:\u000Da\u0001<{\u000Ch\u001Fv\u0007\u0019<0\u001D\u0014\u0004\u001ANq\u0009^\u0018\u000A=f\u001AU;4=K@1(\u000AV(C-#kP\u0010A\u0002l+L\u000C\u0007PG\u000A^\u0006\u007FCFX.zlpT*2\u0005DOh\u0005=o}\u0005?I\u007FPpA"

internal val SKELETON_NAMES_DOI: String =
    "0092gTi\u0011W\u0009a\u0011\u007F35a}BRV\$~\"{+C|YBP*&)\u0011_\u001C\u0009f%)\u0016\u00010~f5\u0013|C'b.%\u00100>Uh4ZeB\u0018I\u000Dg\u0001\u000C\u0002(v(!\u0015~\u0004\u0010QD\u00034_I\u0015\u00080Y;\$\u0013\u0013V\u0017A>{mH\u0011S \u000FLWt\u0019\u0003y\u0014Chzx\u000BE\u0007-}bXaW7E|z)X\u000C+o@a\u001A\u000C.3/4a\u0015_\u001E7]T^U9ek\u007FKs\u0001\u0010-v\u0009c\u0018\u0018_^JcoA^lVp1:\u0005/_sV\u0010E.2B&C;\u0017kKh/aJk1CrvTcY#F\u0016\u0004C5J.Yi\u001F\u0013\u000E\u0002`[~\u0001>*r|y\u0003"

internal val SKELETON_NAMES_DSB: String =
    "003v&L:\u0005\u007F:\u0012\u0015fO',Z\u0012?/^P\u0017\u001BB\u0011cH\u0018\u000Ef<\u000AakZ(\u0014^oF<*\$\u0017CEZ+\u0001u0\u0016E9!))0e\u0010\\:-{*\u001DU%\u00012\u001B1=};\u0016mfv\u000A9o4\u0018N\u0015N\u000A9r6\u001EN\u0016s+F\u001DO0\u0015\u001Aq\u000C\u0019I\u0012B\u001B2G\u0005j\u0002\u001Az7=Y7\u0004w\u000EA7\u0014\u0009C8I>s\u0010\u001DC]8W\u0016+\u000B{.\u001BO\u0017UKkB_T\u0015brI{ \u0016\u00121\u0009\u0001\u0001"

internal val SKELETON_NAMES_DUA: String =
    "0065cTG\u0011u\u000Da\u000D\u007F#33=Sn\u00101<#9e\u0009U\u0005\u0005C\u001A)\u0001A\u0007t\$w\u0014\u000AF.\u0019mW\u0006I3!z,(*62\u001CM\u0010`%\u001E\u007FpA*6\u000ER\u0007\u000FU\",9l\u0017Ho\u0001Oo\u001B{X\u0005A\u000E\u000C\u0016\u001BCZ6\u0008SV&!#yiSnM1\u0016.\u000A#?+\\8\u001D<\u000E:\u0005g\u0009f%8\"q\u001BiR3\u0001b.\u001E7Lp\u0015PN\u0007_)AXr\u000A4\u001A}INnTn\u0014W\u0007s\u000F\u0019<Z\u000DtL\u0008|=4P\u00070va\u0013\u007FVO\u0010\u000CDkb\u0003\u0009R\\Qe~[M\u0009\u0007\u0017@; !1"

internal val SKELETON_NAMES_DYO: String =
    "002PzSZEo2\u0018-K\u001Dz]j3#\u000C\u0017\u0014&CS%\\\u0013:KzUK5|[\u0017Je\u007F=J2*I(uf\u0005K\$+\u0009(T*Q7*J&t\u0001iRo+gszf/B.q(t\u0008\u000Cj]eXhIXl#(\u001F8\u001A,WS#Q_:\u001BO(ss\u0012\u001DO 5\u000B\u0003wB\u0011/i\u0017\u0006n\u0009\u0017\u000Cn\u0011ze\u0016t62,)\u001C+\u0013]\u001B\u0008\u0018L\u0002A\u0001"

internal val SKELETON_NAMES_DZ: String =
    "00B4ke\u0009\u0011W\u000A\u0001\u000D#\\s0\u0009\u001CUR\u001F!B;\u0010/E,ujJ\u0005\u000FqQW\u0015aR+lT@k&\u000AHU]:F\u0013\u001E\u0009\u0019*\$:<5zep z\u001D\u001AbH=\u000A\u0016EL;\u0011\u0010\u0012'F_\u0009\u0006y\u0012n\u0007\u0006K4\u0008z\u0017:\u001F%W6\u0008\"\u001Aa\u0015\u0008(.=lQ\u001AUiaW\u000FE{cWYE12\u007FIPD,P)MzuER\u0012\u00086,4S\u0011B\u0005\u000F(&t(m]\u0010\u0002.L\u001Bg^%40\u001B7^\u0006q_0G\u0006jC0wEW\u00165Oy-?\u0016^nZ\u000Al_R.I~u<xk\u0008zlngHm@\u001D;x#r|Na\u0011\$\u0019s\u000F\u00043k\u0019!z(}mgxa\u000D"
