/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_UG: String =
    "007H_Tx1o\u0009a\u0011oz\u0014A)D?\"5\u00071\u0019\u0011\u0015!U)kQEYr\$Q=\"!LK\u0005RUMyfl92PS\u001D#\u0004,Lb~pp?(`\u001D\u0015[\u0018k5I<\u0009Y\u000F]\u0004A/o@xcu\u001D\u0001G^\$I\u001B\u0001\"Lrh`LE\u0013h*-/%\u0009[>mqJ\u0009\u0019\u0017L#\u000C_0Q\u0001OuL%Tf\u0012P\u001D'^onjq1\u000Al\u001Bnc\u00051yrV!8\u001F\u000B^-C\u000FF\u0013Y\u001E\u0004w\u0019a\u000Fe\u000EM\u001Bk\u0008<(\u0012\u000E\",M{?4Ua_g \u0009\u000CH\u0016\u0018c<\u001Dr\u000C7+T\u001Bd\u000Ff\u000AE7\u0019.>\u0014\u0017.%FD\u0005+(0ig>rT9"

internal val SKELETON_NAMES_UK: String =
    "005+WdI\u0011u\u0009a\u0015#\u001C\u007F.Yu8.R\u0008Q\$YE&Qu#QBp\u001DA\u000BT\u0006U\u0016=b\u007F\$`M<)B4<NNs:P!qH\"h\u000F1k\u001Ea9RE<\u000B\u001B\u0006 9:t!V<tF\u0013E5\u0015-\u001F\u0003L\u0017m9F,\u0018jr0m,}\u000F\u0009%0\u000D\"\u0006Y8 iR\u001C\u000C@\$1Z%q?\u0005.\u0011+(\u0009Ko>\u001DP\u0004 \u000E[h_86r@Z\u001A\u0019\u0019i.U\u0017'R\u0005\u000A&9jM9aG\u001E\u0018-t%\u0018\u000C\u0018)@pp1\u0005"

internal val SKELETON_NAMES_UR: String =
    "005z_U\u0017\u0012\u000D\u000Da\u000Do\u0012\u001Fa3'mc\u0004dY\$P\u000E\"9f\u0005Q\u0002Y\u007F0\u000BD\u000F?N2L\u0012*\u0002\u00134U2@T&@h0\u0002/\u001F4ycIxI\u0012c\u0018\u001F\$]#!Lu\u000B\u00059R\u0005Au;'=7g0\u001C%q\$i\u000Fc\u000F\u000F9'~7\u0004\u001C\u0016,3rrcK}iy;)]\u001C\u00026\u000AF,.&.2'#\u001DS\u0002Jk\u000B0\u0009HZsA\u000Bu\u001A:4=EJ\u007F\u0013\u0013[\u0009m\u0014\u0010\u001A}!i5\u001D6SpOAy\u001C7_\u001EOCrm?31\u001E"

internal val SKELETON_NAMES_UR_IN: String =
    "005z_U\u00182/\u0009a\u000Do\u0012\u001Fa7\u0002.mI&y,g\u0013qqcE`\u0014\$zsU5MYznU\u00197\u000BC;D\"lSO\u001E;\"\u0019I\u0007\u0018aEa,Q\u000CW->\u0004\u001E\$),u\u000B{;IU)q;g?7(G\u0006B\u0012uz\u0004E<d\u0006KWUq*BmY%GWS\u0004ih\u0017)7>lYY\\r\u001AkVg\u0005pQr\u000BMwYun\u00109\u001E*\u0004:7?#o15\u000673yMhp\$y\"bV>g6gj&`t\u0007dN]f-)\u000Ed \u000E=\u0001\u0001"

internal val SKELETON_NAMES_UZ: String =
    "0034&L**&0\u001AMISzmB>\u0016ML3vz%O(L%\u0014\u00065KT\u0011/gssA\u0019J\u0002\u0002\u0009 R\u0004?tc\u007F2\u0003,MT\u000ACg1IC\u0002m`4\u001A\u0015*ewz!\u0018V5b\u000D2C\u000D2')\u0002L\u0001ka=-\u0004FCx=Dh\u0011XnVF/GQ7U\u00069=mCPG\u0002!\u0001"

internal val SKELETON_NAMES_UZ_CYRL: String =
    "004FOT(1W\u000A\u0001\u0015_3>Fs\u0001bk\u0011uP!!-_\u0011[\u0003Q\u0012\u0001\u0016\u0017\u001C\u000EF!Az\u0001Z*l\u0013\u000F)4et\u00128NzT2Y.\u0010\u001CXqc~(TA\u0016P(vH=pF8\u0017q\u0001~y\u0004\u000D\u0017h\$K.\u0007hms1\u0014bvq\u000C!t\u0002\u0006D*P=6RvS9\u0019Y6q\u000A\u000E\u0010\$j_T[K\u000Dm\u000C\u0015g99C\u0013/fF\u0012J\u001AJ\u0016)'\u0012\u001EMd\u0014\u001FEe<<\u0016-Z:8M\u0015>`\u007F\u000D\u007Fa!"
