/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_FORMATS_JA: String =
    "00B03e\u0007\u0019u\u000E\u0001\u000D#Tm#\\\u0017mKPEB\u0017.\u0013+\u000CH!\u0015\u000B\u0006\u0007F\u001B\u001C\u0016.l\u0003iSn8-\u001ARr#9\$>G\u0005b\u0019*i>\u007F \u0010|h\u001BEg~(`\u0016N\u001B+h=rL*cz0\u0006NgIa\u000DoNz\u00082gm_Meh\u0019i=S4j\u000F lf\u0001r\u000EZB.I|)\u001E&-h5k<*p\u0019g[/z%\u0012jfe\u000A;#.z\u007Fk#\u0006*\u001F\u0004Q3e\u0015~\u0009uFc\u0014\u0017>t=\u007F{\\ 4\u0005`l\u0010k&8k:h\u000EaKrQ\u0001\u0011OMJ:]Hb&DE\u0017VZR2\u0007Z6\u000FA\\\\\u001AN{.r&Z\$,\u000AOsF\u001C7LH&\u0003=cyrs\u0005E\u001B\\Y\$J\u0015\u000BID\u00053T\u0007/t(\"GT\u0019U1Y\u0011\u0002\u000C*\u0008<J!\u000A^d-Y9X\u0006XB]c\u0011\u001Ey<\u0008-v\u0015~N|\u001AA@E\u0005"

internal val SKELETON_FORMATS_JGO: String =
    "0087'U\u0017\u0012\u000D\u000Da\u000DO\u0012\u0008!}AaA&<OH\u000D\u0005\u0015Gq\u001D\u001D\u00195+\u0015/\u000EZ5uaK{ea\$@S~v?{Hf.\"TgY\u001Ckvwa/q<@|86\u000E\u0006k]-2J*\u0016\u0001+I\u0007\"L\u0016awli\u001Awh\u0016Q\u0006s@E^\u000C\u0019VD\u0006d0pzx2Ft\u001A\u001D{\u0018B<y>v(bLY`kQ\u000B5JI\u001Av\u0011z\u0013Q*<eqm\u0005m\u000A=/EVi7\u000COCM}]fZomGj6z-UN\u0007PP\u000B\"MQckN\u000ARc\u000F]\u0001v@D?2\u0019\u000D.C\u0016O| we( \u0010D/PP\u0005G29I\u0011;nB\u0010v[8;ayl\u0003\\(\u000CUSR58n\u0016sr\u000B_\u000F3M=hM{[nT1q\u007F2y"

internal val SKELETON_FORMATS_JV: String =
    "008L'U\u0017\u0019o\u0012\u0001\u0009W\u0002\u0009A\u000C\u001E{\u007FQJ/B]d\u0001&_0\u0019\u0013599:~dXk>@I\u001Aa\u001Ebcd\u001AA=\u0007\u000FbrRLg=<\u0007Zxk>q\u0005@\u0008Qv\u001E\u0016\\\\-:i\u0013SAV%\u0008\u0015vK\u000B:6{D\u001D.>q\u0001}/r\u0015{exk\"O\u000E\u001APt~?\u000F\u0018nr>x3Fv\u001E;%[9^\u0008\u001Eg\u0001\u001CSO(*|\"F\u0006Y^f1\u000BW\u000A\u001D\u0010\u0015H9{58\u000CLCFXmqMh*\u0016~g\u001C\u0017D\u0008z/{]\u0010osg0\u0008:\u0003JYV]-\u000C\u0001B\u0006\u000Di\u0010h\u001F,~_yvHXD\u0006p\u000CD~d!_?uZ8~Q\u000BFWXPcD32\u0019\u0013p!kC>\u001D.*\u00171#\u000B2x/v\u0013@eG\u000C\u0005N\u007F"
