/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_FORMATS_LB: String =
    "008Y3e8Wo\u0011a\u000DCJe\u001D\u0010;5<\u0008]\u000CQa\"-b\u000C\u0008E\u001C\u0001\u000BQr\u000AI1\\\\3*\u001E\u001A\u0013\$kM\u0017&Ci\u001FtkGIIgg7-btP\u0004z@(\u000BR3^pSA\u0001?pp\u001Dbh\u0006\u0019C\u0015\u000F\u000BCl9\u001D\u000E\u0009V7}c=+W\u0015\u0012GQ\u000494E\u001AJ\u0019\u0014\u0004t\u007Fphk\u000BuNfE0 %\u000Eo\u001D.tP')\u0006NuE/;8+%J\u00168\u000B,S+aL\u000BM\u0015M.,n{z\u001A\u0015pTZ}f1s\u0017\u0015T\u0018Ldw9/F\u0016nbwD\u0004j#[=\u000A;yF4R;X\u0015zhCRfka,O\u0002\u0019nH\u007Fp\u0019@9\u0006\u001C\u000F\u0010\u001D\u0001n7K3\u00032\u0002(.HZt\u0004)<t`~\\\\\u0018\u0010\u001EP\u0001m\u0004\u001Ew\u000Dk.NY\"\u0016,;\u0004@\u0001\u0001"

internal val SKELETON_FORMATS_LIJ: String =
    "008H'U\u0007\u0011u\u0011a\u000D>S5'r3\u0010Y\u000De&\$UC\u0003(\u0011\u0007\u0018+\u0001o2Yx\u0012\u007F{<p\u0013:%a&n#;\u0019\u00144s\u0013M\u001F\u0002\u0008_\u0015~?xAb]\u0010Bn\u000B\$V;:\u0008'-&\u0004\u0016)*Q#u;Mu-~j\u001EJ#B!}/B\u000CYynZ0\u0009\u000F4>P@e^\u0001\\gs\u001ET4DrS\u000D4HC\u0014?W#\u0009,JfS8:QJ\u001Ba\u0009\u0005*\u000A:=\u001A\u000BQk.+\u000CTCB\u0018\u000Ec`.Nhp=Y5Y\u007F\\_\u001CT15'|\u000D?qFE\u0014c<&{fDzKe4H\u000C6\u0017~/W{\u0008 7\u0009A?{j\u00132\u000FiE\\r\u000BV}0Wa&6f+C^\u0018WnG..l\u001Ew8!T\u000B\u000FN\u0011\u0008\u001Ct\u0007\u00098a1/>"

internal val SKELETON_FORMATS_LLD: String =
    "008L3e\u00189o\u0011a\u000D#\u000Be\u001D\u0009\u0009\u0019\u0018Y)!\u001D\u0011+ZA\u0013L\u0016E\u0005%GHf,U?`%V:\u0011~?\u0012T0\u0002a\u001F#DymZ\u0019Z\u000C\u0018_%Pfl\u001F+XVf\u007F]\u000BU\u001E\$Q8/'IcK[UTS'WW\u0018\\|DU\u00090\u0005A\$\u0019\u0014)\$P-eM\u0017 W\u0003 pN}JGdstS:{e\u0016-*\u00055\u001D3\"C6G\u00195\$O\u0015t%&6+\$\u0017Gmm)Z\u0016n0WE\"o3iIa\u001Ah\u000D\u001A1HAq]\u0008B!\u000Em@9\u007F*G8|#\u001E\u000F\u000E_\u001C\u001F>D 1U\u001FP9\u0017\u0019A]>ov1=\u0015\u007F|^}3Q<FF!g`aiyXNn'8f\u0018*t\u0007J}>\u001F=G\u001Dl\u0018=xbLKLQ y\u0003"

internal val SKELETON_FORMATS_LMO: String =
    "008E'U\u0018\u0012\u000F\u000Da\u000DNb\u0008AiA`\u0011j\u001EhKYA\u0018\u000Eq-b4.:**fR\\\u0013MO\u000A\u0010\u0017+w\u0011\u0001I\u000D\u000AX\u0002*&DE[\u0018K>oTN3\u000E`[CETE9\u0007j\u0017Q\u0009\u001A.\u0012&\u0002\u0018\u000AK4`8v)wG\u0015[\u0006d=E^\u0013\u0005zf>\u0001I4>`8d_\u0004Dgs\u000EL8\u0010-a\u0006T\$n4^CW\u0015\u000CJj7P:%c6B\u007Fa\u000C]\u0013sy3\u0015bU[M\u0018\u0007\u0005\u00155T\u000B~7x0/g3!Q\u007FrH\u0002mZ%C\u0010Mil\u00036B8`m90r.\u0015wK\u0019l?Xp6\u000BP\u0019~sG\u0013O75\u000B\u0015\u0013nIL\u001Fz\u0017LA\u007FogO%n;,_{.2l\u00168w\u000D\u000D\\h\u0017\u000B`\u0012X1r\u0001A"

internal val SKELETON_FORMATS_LO: String =
    "008Y7U'\u0019u\u000Da\u0011?36p1\u0007\$i*IL\u001CG\u0001\u000BP!/\u000F\u0005\u001B\u0018Lo;\u0014<j\u0009^:P?B\\U\\<-lr\u000A\u0002*\u0018H\u0019-^yy\u0018n\u0009I>|[5X#v0\u0004.q;wi\u000El5\u0017\u0003x4uG(u|~/@dy@|\u007Fw\u000E|\u001D+X+l:j+\u001FH6k[|\u0008Q'\u00187J)\u001A#}KuJ3~N\u0017yj8Izv4\u0009;3\u0005f7A\u0010/A/giB2\u0016qR\u0001\"\u0018&&>\"9IJ>V%\u001Cc!%12uAy\u001A\u0018[\u0019\u0012\u000CQ\u0003\$o9=is[R!{`\u0005r\u000F\u007F9UOd\u0008\u0003\u000EZw'\u000Ev3\u0015\u007FP\u0011m,5.g\u0004\u000D,uee\$]rZMn}bL\u0017\u0002N5Mj&+\u0014k%sO1e\u0004'uiFD\u000BaaI a"

internal val SKELETON_FORMATS_LT: String =
    "00Bd7U(\u0012\u0015\u000Da\u000D?#'OT#%=\u0011\u000A'1aR\$B\u000AMX\u000B\u0004HL\u000B\u0018\u0010z*K&iY#-\u0005\u0014\u0006mXDz+\\\u007F\u000A\u0015>|\u001Bqp-{hD2?\u000CiWA\u0004\u00173q5\u001C>q\u0017\u000E\u0006\u0017nk\u001A\u0008@%\u0015qgIKJ\u0013r\u0014\u001D#2\u0012\u0014wLdt~@lQY.[Rc\u0009R.&Vc\u001D19nl:^5\u0006\u001AL\u0003w3\u001E&\u0014e^=RRu':D\u000F@}4=|o{\u0005\u001E{Uk86*\u0014J\u0018US<\u007Fs`m>w1o)i+%Pr\u0001gGrLr\u0001\u00074v23kZ`SuV=,\u0017.B\$:#D_@LRd)\u0016\u0013\u0018]\u0006R\u0007\u0008\u0015/j\u0003E/aN18\u0001*r_\u0002C?W\u000C\u0011\u001B\\w2>,a?g\u001CHR{F\\3n^\u0010\u001Dw\u0010H_8\"k}k1.\u000Eb\u000B>h-K]D#dd}\u0003A"

internal val SKELETON_FORMATS_LV: String =
    "00AA7U(\u0019w\u000Da\u000D?\u0003\"\u0018,%%>\u0011*!\u0013\u000A,\u001AC(W\u0014\u000D\u0006*\$&&\u00180j\"[LL\u0006\u0005^O'^,My0\u0008D\"\u0014\u0011o!J=UD]:\u000EL\u0002^{-#\u001B18oqc/\u0006ak\u0007;BV;^<\"mo~x\u007F\u0012N\u0009)f\u0005W*ISdq\u000A.L\u000ER\u000A t{z?\u00013:}\u000F77M=\u0015\u0010,p88c\u007Fy\u0011*\u001EE6\u0012##G84\u000Br;QE;o\$ZE4\u0013|\u0010\u0002(n!hT#v:t\u0004.zF\u0005\u000D\u0015?l \u0016j8]G\u0019\u0019Vu\u00084\u0014}V\u0006\u001E4X\u000BZ]z{)@\u0003\u0015D\u0005d1!V4\u001B\u0001&\u0019wW R0k}0Kw\u001Ag/\u0003\\\u0015Dc\u0003\u000Br\u001DO4I#U\u000BdC1-^XP\u000C\u000FB`4E)._WJG pDS\u0018\u001F`\u001C<;a.^CNm`Q\u0011"
