/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.plurals.internal.data

internal val CURRENCY_PLURAL_NAMES_ZA_CN: String =
    "000B嶥ⴍ渒୳ࠑက"

internal val CURRENCY_PLURAL_NAMES_ZGH_MA: String =
    "000C嶥㯤໦ᄃ䆀ႈࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH: String =
    "002Bᷥ㯋稦蒧涳䟏ῒ㎞挛㫏䎶ᙶ嚼ᆟ䌻圧澼繏昿✨剼朱絴薋ᘨ䔚䛴乾改穾芟盽均⇜狇懻螦ṛ办缴杯糊䛭咵ᴅ劜缴柎㞃㴂ຉ䗬ආ犂疵㡖匘ᅛ琀䠀"

internal val CURRENCY_PLURAL_NAMES_ZH_HANS: String =
    "000B工Ⰽ渒୳ࠑက"

internal val CURRENCY_PLURAL_NAMES_ZH_HANS_CN: String =
    "000G工㰽ㄙ䪹㦹䩀癠ਢࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH_HANS_HK: String =
    "001R工㰽ㄙ䪹㦾㇪糃埓异篮佳糹羛篧ᅎ卦⛮瞑䗟Ⓥ煹▾⹮㢬⍔ᵪ໕兒㒔惜栄ࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH_HANS_MO: String =
    "001n工㰽ㄙ䪹㦾ㇻ⭷蕩緃ㇺ潓蓶寎烇莳㳵澳菤睷⸜蚝䀗❴䎟⿏䓟✸剴挱罶蒋盹湞叉痲㭳ൡ抡㍐㺬劒沥仦ࠠࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH_HANT: String =
    "002Y⻦ὂ塈ী⾄皱㘑圕౨䥾堊橜Ⅴაᾤ娡上㪖▆㓯羮Ⲯ瀞䔄膙䜦ଣ⑥亜◃嗀㇂㳹䮪㎌ㅜ挖㚒㸥㜑绤盠◣⸓ᛠẲ⽨嗲ढ़㚲昅䶟◓帝⢛䊙槊㣗慯䰷繮珣湎妆嵈ㅿ䕷昃ṇ⡢眞ೕ撋冚畫秒᳋堭㘷瀪㞀"

internal val CURRENCY_PLURAL_NAMES_ZH_HANT_HK: String =
    "0012ࢡ࠯䟯⺂牃ඹ瀾㩭糋⫹孷噻紧Ỏ痏䚎竂棇擵䂾响掖攷熇乲灥௜獊㜭樏卯㳩埅艡稣笃᣹䣈"

internal val CURRENCY_PLURAL_NAMES_ZH_HANT_MO: String =
    "000J工㰽ㄙ䪽ឯ䩘癡ᠷ ႀࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH_HANT_MY: String =
    "000G工㰽ㄙ䪹ᆹ䩀癠ਢࠀ"

internal val CURRENCY_PLURAL_NAMES_ZH_LATN_CN: String =
    "000G工㰽ㄥ咙↹䩀癠ਢࠀ"

internal val CURRENCY_PLURAL_NAMES_ZU: String =
    "007H㻈ᡚ䡦ᣄ㍾凢㊻⧤୉扴䷖⪪ᐯ䎒⬤ሼ焐㧽❖懁㤴済矞藱ử崋統朆⋹ᄢ㡐獾㐈ᬅ⏙ℊ廧Ẇ䦼捪獃忯倐ኾ塋漹࿊㸀㦺➡䢓Ṱ᳛⢍፸籯ᠡ壛垎㝯檨ᴮዡ⡱㥁癒勼帶臔ᇁ濊ỽ畑瑌ࡀ椀樼㷃㔁−琞ἷ烝宿㻫廖槚翝ㅺ ᱥ翂糤䦱孹溃脒攉葸᯾敿ዿ䧯斟☣⨷綨椽羟ㆥ⾞ᜀ"

internal val CURRENCY_PLURAL_NAMES_ZU_ZA: String =
    "000B嶕ⵍ渒୳ࠑက"
