/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_XH: String =
    "004X囇ᛃ塦ऄ⭽凙ᘧᳰ撡ᄉᇖ⁔㊶⋘ノ㤆䃻丧ᡅෙ寯嚘㡛嗊➨⮲娑抁ᇄᛑ罋⏄༄࠻ጶ㧈ⓔ媙慓痙姣苷ㆅཝ䦸⢣沦ছ䪋箂ᔚ䁃䤳᷒㶖ሾ夞⵽㌳㌻ⴖ藌ሏ犌᭑䵇㚌㋓㫎欄㋥䕭耱淫氟澞ၨ"

internal val SKELETON_NAMES_XNR: String =
    "009l犨ᡂ恈࣏湋䁼䣑嵇芇煨Ꮮ刄䕌⢃೘᷅ጞቒ➹⯌ㆢ畁ᅚ弯ⲳᒲ㇒檎䰲ᦪᡦ夒ᯔ堷ᤋ導⮠ᚧ壌⋇筊墚㦒ॾᴀ㤐僧ℴᨶ浊皞⁫䪷叝慫泸橓䲶蕍᱊濦礋வଡ଼⚫㸖篧茋ᘤ膸䶎耷㟷空⚑Ṣ㒧焖等⌒弤扟⹵叻櫟╺䏶㸲僆磩સ凜⯡䎲蘸萇"

internal val SKELETON_NAMES_XOG: String =
    "005w曇ᡂ恆ऄ㍿卌㻑崓ఀ旉ンญऊⰍᬌ婋羷ኋ斺瑖䜶䑭啽ᘒ㙚ஐ箙स檅䂹枭䔘栈ℛᰁ㤷㐩㧏叞吚亙䚎⮦䯲⤧⥉塅瀻䓳▛Ḋ㖟Ⅎধᾊ淪噎糹猽䎊⶷是↓Ꮵ湝琔᪫安ᦑ缰ᯌᑳ゛圫畝╶种䍢寕圁瞀"
