/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_FORMATS_NB: String =
    "008i㫈囃恤ࣈ㩻ሬ戶࿈ᐄ楀㣃刐堚剮ᩒ捯爝蕉⚠㲅హ⯿瞷窋᪡喂淟 棼✨䳴㚅灠瞻蔒棌箅⎍ㄥ⋬ᨭ瑹坡泼蚻ᨷ盉㭓⭅咴Ⲿㄤㄼỿ枟୤差䐕单坘⺝㯒Ḡ畕抨䇒ḣ೚䃑明㫀粘拁৻種甍叏壹洈棱絃缊墐ั☲腾堃熤付ᖑ⟄ᯘ።松䧕蘈楂ᚁᎠབྷ痧䔻ࣷ㎨Ꮰ㟽䂲Ẉ❘䭢朁澶㺠⿔ⴳ㘀䀀"

internal val SKELETON_FORMATS_NDS: String =
    "008h⺨ᑃ塦ࣇ汍㶰恚៨䰊౪㜜࢑つ䵫㄃ᆭ⟵⿾婓盐૎⭷篠懗㫥へ淅腆號ᇀ狸捗瀤㳍ᘽ䬬㔆䊡㒀㽇䆝卿岜䅂ू臞౓侙笥樇ᖻ⛿⏨ࡻ㼙峋ᝮ⏵ᣡ惾䯘嵆ᡚ嚮憶棉ແ蘠㥈掗䭨岚൪䶓媂㘿༷膫㴠拜当棯峬縸ự䓒槜䚢⊼ก曙਴祢㳱嶎ዋ忆྆₫㠷呾㴠宔↝⛭┲៘籡攘傯ᇵペ怙㜢扈啘⅓ᾩ丹嫚㐋劤⫍ৄ䓇䣕㧡耇"

internal val SKELETON_FORMATS_NE: String =
    "0088⺨㑤䁦ࣉ搡砶⢹芔東幡㌯ࡉ芭⧇劕敯舝慤堔噋䶈ࡈᐒ嚕㵍☪䣺杷အ硶螞᭔㱯日崲⩅⑒Ⰵ๙㘎畺繶伴㸏䣠᥶㒄ⴉ䶽板柆萌晦⽵忇䇑嘍ྉ㞶孁搔⓲⵽刨屍ሸ⦠氞䕉磃⌗㾚ኅୠ熇ᬵ㱴ᶷ䛖接䫦孽㌻咔㥮㜈毈⊠罗恏帘⟢愙徏‼胜瓨䏳୰䑍⨴㹆登ᧇ熍䊂眛ႍ岞臉㵊羣䚺繀団㻮旕ሆ枇ᛗᾀ"

internal val SKELETON_FORMATS_NL: String =
    "007z㛈ᑃ塦ࣄ㉻Ⴌ㚁琝ᦢ愒࣑瀆ๆቒ᭚㿪嚽ⲟ捩ᶨ堧漼疾繼壱᜾癊⾙派⺫粢㌰灟䏇ប☊⦒⢦倪ྭ⌶䕔䉆ᨢී愂㖆ऺ⑔㷾蜻⨈䓎኿㞍卅厭搙ⅎ㴾㦈䜻᧋理㓯㽘䣻堤࿚葺␨⭣㰍幉䯞㹤廠㪟↤㊥橛冐掫舖傴๿棊撱Ὥ菖⊞肣䀲棾憗㫫ᨣ菪舖虏肩広᨜歙朶ঌ㌚腟৔嚨ਾ"

internal val SKELETON_FORMATS_NL_BE: String =
    "007z㛈㑃㢆ࣄㄿ䵜畁⽄䴤ᡂ僈ഊⴊㄕ瘷敎⏤杶稐㰸ΰ⑯㹾䮑ᄃଙ㫺㛻晛㋪未⁥㚫礨㄁䶡喬孊὆崻坺婴洦∋嫶ࢳ䲍成廫臽㏅ඳ␛皼Ꮖ⥇ᐼ愲䎵⏄䚹棎㛦烤蓸⨛䙁ए珻繀偊硩㞬嗛杬熝࠲ᄝ⎧ೇၒ狯耵☕☁䗣ው纺㦪矊珈ᜇ喠㟞ᵶ姼㙱㿨䢥侔ᆜ㞘ㆎ䓏椛瘍ᆿࠠ"

internal val SKELETON_FORMATS_NN: String =
    "008W㫈㝃䂄ࣈㄽ伔ဲ⠥ᄅॅ଼⅁⦥⺣ⶺ亷熦撳滒౅䄆膝㿼膾〸澟⼵ᓌ䌍努䓖ആ畛⭠淢凅⠱⸖燅⣕䭖垒佈桄⺸䌡涰䧻樠滟䏳祶⽾揇㒜䯋ⳓ廼ᒹⴵ╮侂₹噮づ监瘔繴⻁焒ᴣ㦷㺖嫣窦䉘啻沲交勼ᘑᘾ䵮怍筨䫞੘⟃䍞玾䏞䬅磋⤯ࠃ㻳蒿ᛐ◆甑漅蟌獅愎厈圗␎㷕䘓咙㈆蘀"

internal val SKELETON_FORMATS_NNH: String =
    "0090䊨㑛䂆ࣉ樠ᣬ盼蓿媀聕㬐屳རᄖ䆍ᶺ่ୌ傂璀ᡉ儔喓ᦔ芗ⲑ彔㳧䄤⑰氞㳤Ỳ㻭伻䣝螰糒ᓊ愨༜夕咪䪚ౝᚦ䊬藒篊ᰔᾃ硊肦曃琸㆚瓧竾榛ᗈ泦㶚紮磧䤥蔯夅၈撞㖩摑ᆽ懜ᠪ傇᯲ⴼ灙⑝᱂ⵂ㦯㖽掯ㅣಓ狖礚⍇პ㆑㤄悅擾榅芕”恶⻞挖爬䖗☉檩᪊㢴໖ⳑ淏➺嫹䙵矗忇美㝳殹㣶帜╩呡蟱䉜伅㥗᧯窦揅㱽劕簍↯࡝✆ᵎ最"

internal val SKELETON_FORMATS_NQO: String =
    "008L⺨㙄䂄࣊樠瀨礟笋咰嬠ࡒ蘃ဌⲌ䵥珨䕝᪓䧸橆㪺犾燤ඊ致㫁䒯巐㵟ᇞ折ஜ範硅椉煄ᔠ㤴䂨疴緑甘蒐㘇墟䆋ᤠ朮㠨㓷蓯㬁歲㆚渇㼆喵蜤ᾁ䄔ற仉僫欒㳯求㴉䁋戹卖偡䅠䨌ⱅ绶幞斉唅෢⏣㨬᪂㖹䦄ᇔ༳薌ૻ忤㹤㧵択荘㗪⓺⠓嗭〈㣺璉密㊭橚瓏┒浒旫ⶻ嵞㛧帎斝耾翮䀋聑睻萀"

internal val SKELETON_FORMATS_NSO: String =
    "008M⺨㑃䁦࣋戤ွ堽瀘桄⧚℁᱓毆⾐媶䟪⿞焥ᒗ㷦᪓Ⴁ⫗⤒㌯㫑䒯᷐絟ඞ捁᧎臲㘅奈⅕ᔬࢺ╌绚舤绊㰴ᎇ㰑䌝⇲ᤢ⮙蛯俥萎纷ⶑ坋疦Ữ☑⏨层ᓤ碳㨸夒綃摠⺑✯಺㣔折㚜ᰒ禼志⻣羰捩㯻丸ᛛ䏎蝳ଔ᭤ዡ莎ዛ忆䜣ᡫ䋧㾌⌟ᬛ௺積掑嘑㻚唾㡛㨇㾼ㆭ㍭ᷖ笝巗〞䆪࿸␇㈼ົᜏဘ"

internal val SKELETON_FORMATS_NUS: String =
    "0089⺨㛫䂆ࣉ戤သ硁薕ࣂⓄ⪣☑ࢻ䅊勥缆䑝缎勷粑礩湼䱢ㄑ婒㉔冢㳷㔟獲甁䏣篟⣂嶽䒣᪬冑ᱢㅠ䱢結㽧涳挸堳明䦗嫀൅替㞿嗠഼湎羯⏟亯㉘䈿㡵〙䨤氨竈礒敟扂ᚁ䃆䑝冭㭂滂瓹㆓Ꮊ㦵༾⬫溶➼枩幕ඵ㧦䑲媰仓犾畳ா箬ॄ㫿亝䛱枺᧙粳怿彁ᔛ㦳佻༸㑪ᙅ扦઎㝝᪒῔缫伷噚ⓆỈ愈㜅䈆䒃栀"
