/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_YAV: String =
    "004C勆千塨ई㍿剘เ勡ၬᝐ䩢ᆶ㖼᡿⨠చ䶭嵢〚敔碄痂堝㔨孑↷仫緦㶡ㆥ䒏∭㼿䒴潈㍩䕖ⲭ䇒夨ࠓ⏺ᴠ䘺䍭⯝䩧洝浻ჷ໎ಛ↑痎Ⴕ䖵滜㦫Ẏ籐䴙㢴⋔扸揀㐆䎿⍇䈌ᢾ䘞␟␈咠侈䑩ొ⩆ᱝ犃罪䃑祏移栀"

internal val SKELETON_NAMES_YI: String =
    "0033㋆呃塈ऄ㍿凜⛀⧢႖∽椄䴥䭉慨㦄█愄嫨㐉䱂蔄统䢿余ශ絓⏟蜸㡾莡砻暬⡧撞Ḱ薚㎴畧榉᪭栓拀ᶗ螔ၟ峱帼腡忲羂㔯玕⢿ⷺ⾳嵺೯ㅕࢲ她゘䳬䯂猛ੀᒄ䆁䩨㳏螴ᨥᵇ䫧㇁ノ㬠㩓簀"

internal val SKELETON_NAMES_YO: String =
    "005/拇ᑃ塈ऄ㍹僬䌛ᅺඉ૒畢㫐⻨ᄢ⁂Ⳑ綎斞紵倏ᶺ稊㹱䌦ᵠ続柟垖茲兠㠵䋫བ冒ḯ䦭崵䙊ཌ綊䭤⭨簷䝑㌻毀㬍ᜎ䦦尚盒㬧㉧洤ᴊ娂䜜⟑㐆廖ଜ栲玹穌ዐ蝵䶓᎜࢑⿿⏶↎竌䇑旍⧾ᇱ䴕厶枮牟荃⴪垛ἂ୘ጸ㜊唺㓤㈝⢐"

internal val SKELETON_NAMES_YO_BJ: String =
    "005d拇ᑂ聈ࣈ㟺ⲹ㸮䧽ᎂ䧑瓴ᣥ羬⋘䢤ይ祪㱫䅻廢䄽瓸⠕蕑孂墭㹪䄯䗬撒ᔇⷷẠ⃂ᒠᑾ䖷㈫壐瀛禢儔Ỿ苮ࠢ䛻৥㆏栢爃⥹฿᜽ᔯ膐෶㠜導ၧ䎁ল಴围莡炦ấ夗搡ᕏท樆ᛥ欈⺢孰䑮⊻㚭偿徤蘰烓翉㕱叝匧仩᷑㸭✍ㅏ堀"

internal val SKELETON_NAMES_YRL: String =
    "005cⶖ媥ᅹ䳪槥礬敯㰸惰䐶屉嗜帧ግ忊⢤嘮ₔ㱈㜜⋫痌♟嘃愥⡠倄∈ⴝ䗺फ़摆᳈⳦笪綥ᥒ晲㳼籥ⵔ漧ឌ庬ᜌ弖ᘯḧᵐ⻦獳⿗⬫⇄䲬ㄨ៕挙䨺༊檗勺ᓥ䙆䅟㦜忄眡箐菋㌍㴊犃㕜伍ྒྷ巘䐀"

internal val SKELETON_NAMES_YRL_CO: String =
    "005kⶖ媥ᅹ䳪槥礬敯㰸惰䐶屉嗜帧ግ忊⢤嘮ₔ㱈㜜⋫痌♟嘃愥⡠倄℈⻵ఖ竵舅㠥Ꭸ檅ᆉ擊敩ⱔ徜唿┙ㅕ⇉毣ᶫ௃᷅䮋涉浔ᆹ苜燵烊湱ᤫቊ௵㻆㢎䧂悥窾䬹㞑噗瑧ᷱ⏈㫤⇲狃㕂抠獗ᧃ⧤絶ᜀ"

internal val SKELETON_NAMES_YUE: String =
    "002h䗝⓲穻悾㓷䍰䷮糭㥜懜潜噎⫱憱腴沥癙艒砳䩳旔菙痐䟙炆焹ᯍ皇膵唧擒俛涄哹ᯅ臲⤹⟽膚≃倳ရ⢔惚ᖠ⹀呑✡厐忛㌕㴆犁㘞ዽ峐ಲ㩲桠ࠀ"

internal val SKELETON_NAMES_YUE_HANS: String =
    "002f䗝⓲穻悾㓷䍰䷮糭㥜懜潜噎Ⳳ䅳櫩兊撳糥桇᳷㮡羷掠螲妍娲⾻攏荧烚筎╭ᾓ筥睷濉᳤篳湪猌⣍⡭ਲ䭨㺑ℂ㵁䒇噃札㐵尫㈍㱰⒴昞ࠀ"

internal val SKELETON_NAMES_YUE_HANT_CN: String =
    "002h䗝⓲穻悾㓷䍰䷮糭㥜懜潜噎⫱憱腴沥癙艒砳䩳旔菙痐䟙炆焹ᯍ皇膵唧擒俛涄哹ᯅ臲⤹⟽膚≃倳ရ⢔惚ᖠ⹀呑眡箐忛㌕㴆犁㘞ዽ峐ಲ㩲桠ࠀ"
