/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_SA: String =
    "00Bu犨筂塈इ粚汼䡑㎓⿲ᛢᨈ楄⨸⻨瑗娡曄╴㋳ᱶ厵怶亱䉶嗷揽䭤拄匼ᤜ䣘ᄛ焃碋呐䬣ᶉỰⷭష楀琠૱栄ང㗡⮱䍡๖ࣰ剄⥖፷杬挚ᕲᴻ寭懵冚慏༛ᥙᕘ倴揖㨕怺匐㇚‗掝耆〗೾溣㠭ᗭ甿羔彡倯媥更斅揻㋶ᨹ䇓抧环⍁১፰噜蓢ㅢ䰪沉剙䟋᷶⦘嫸洦㾁暶藿倈"

internal val SKELETON_NAMES_SAH: String =
    "006E拇ᡃ塈ࣄ㍾厄ಈᤎ棎䨂㸄挳䈠暺⁢ై㐔೰檯瑰懌簓䎁婍藹线獶勋匂㻡栚䮸祠二瓜⁃擲ᨒ滇⮟ᑫࡉ捼ᩚ㨴ᢲ灱癜㲒】臤昒⦞睦⑗⟿杄寈Ⴠ粄ㄉ⊸๒₼巰㪝ば脌憨膿棉◿ἰḌ宱㏲嫌夨媪憔௬垩禵矯螀␀"

internal val SKELETON_NAMES_SAQ: String =
    "002x䛆ᭂ恆ै⭹傼瞠牏᠗ጪ⌃缃皑␵ધ媸᱒旍荖拣練涇⑆➌橈硨垆᱀牋瀋㣦㳾㼱ㇹ嵝⼎姹ᚂ媯唅⊴屭ᚚ検㔆䃿㾨勥㿯ℾᑖ㸋愄撫剒厞涀罓峍䭭⏖‿ᵿ㼷"

internal val SKELETON_NAMES_SAT: String =
    "00AK皧竃䁊࣍愧䖵⦱㈻㈎梳椡㉐䪀ఄ浅ਞᑣ⻄♊࡙㒇⩕Ḥ䍎礈६Ⲧ㘢縤烠ⱋ㤤腄㈢शᨺ窶㫖坕ᮩ剦橆縺臫ⶉ⫌檍嵓Ở䍵㼰䌙偺☉ᱽ࠴⽓ᡆ猵⻕㹪捪蘰綶␅昙㻦䥠煲蕠䁢烮❾蛥听⸝弅䍘⎇᛺烽拯禱厾俿ต㣅ῴ㇏蔔朲㇗怀"

internal val SKELETON_NAMES_SBP: String =
    "003O䛆ᡃ恆ࣀ⯽匸⹑簅噔ഃ䮟⠊∴㇆䢥௩壵㿂㦸䣔紜絶纞ẙ㟱㲳༙苉ᎉ乺䓂㈱㨀簉腴㝩凁䓞繧葦㵻睝皰竤圶ᮠᒭ姂ᙪྐ栙ჽ䚉形楞䁔扲⫋緜兤籂╪㶪㖻ኟ娿翗堐"

internal val SKELETON_NAMES_SC: String =
    "003v囆呃恆ॄ⍿Ᏸ或᪤纂縮劌㒀㗶⡝僑ᢒ虔芷⭤瀬⸣᣽Ὤⴳ␒女㘲崫┄Ⰰᢢ〈ዓ䛌棏漴敾㟦痁嵚㶦ẅィ熨᠖₥芍พ欏ㆃ妎蜀⟠⣾㨳㯙瘧ⶋ䌸㑝᮶濄湲蔙臧蕀⠀"

internal val SKELETON_NAMES_SCN: String =
    "004l◞ႊ⴦㮕ᅱ䲾暩㚤ᰙ嗭⬉ᒮ㌰憟ᶓ入窋腥ⵔ䧅索䩲㬷ₗఈ䠒伟㚠䟆㉔㑊੕筊涥⅂干㲼ሲ⤦㽼携榀恄䨵⵱䲫㘉ഫ㾌႙檄⹱椓⑈䷞⧧᢯捖ᵴᇪ䵵੺俽ち嬽≔㳗Ⱛ㈍㱱㯅བྷ䢜蒥ἂࠀ"

internal val SKELETON_NAMES_SD: String =
    "005B䋇ᡂ恆ॄ⭹匤⎨揵དྷ䫨ㆩ⭡紘偐寔劢珼⳴蜄㢍Ầ尰濸㽟ἎⅡ厌帠脰⌭୺漀䮑┇࠵ᗔ暢焸䃚䙼ധ槇楹ෘ箖茡∢୲㨗峣墼冇Ⱚ೎㘆棸婋癷⍘曆Ⅺ㢭䮭忸嵅䥮棚蕇㜤杞䡣疮懶疰毦晠瀀"

internal val SKELETON_NAMES_SD_DEVA: String =
    "00AT溨塂恈࣏橎瀜᧕㟺䮩∞蘴෨⫲ᢡ౅⨢⶧荱㟌懦ᦲ嵅䅺ᆞ⌙泓೅侀䋌ࡶષ砅瘴ᵠ睾ᖗ࠾⼥࣏琞ℓ傠烹ब沂氳䕑⢏蕲耄幖㖔᭘㋌㇍佪礶㕆䫻ⴶ兆᝖⥇缃啨礕嫫䒼ୱ紬⯰磏㖽ᗲ䑼൚䘿狁䐞艘㙵硘✻ᜢ䅈優䳩⋅揇媉欷搽ቘ䳵ᛯ架螚䚅⠀"

internal val SKELETON_NAMES_SE: String =
    "002V䋤㑃㡦ऄ㼊㷸渄Ⱉ䥻ᦎᒉ㷂棞⿛⩁๱咜掌⪑ᩤ㕗枧㭎㣞獫刈ⒺⰤᖔ苌න䜿紉ḝ怣旁䱓忆㽮暫桅匒㨤嚽壕ᘚ妲㯠㰁ᝐᇺᚼ䆛⇝⇎碌᯿㴮⥠"

internal val SKELETON_NAMES_SEH: String =
    "002G䋅硂塦ऀ㟿ᢖ䚡㕿堡ᎅ䫁臡䋣㐢礤⹈᷿⛁㇧权⠞ᛒ⪣圜ᑊᙉ夽୯叀࠶蝚嘶溱৤㠈羯咅䛁ᷨ䋂粼旟愩├憙䚌ഌቐೝ⣪䯮缆㥸䋯䘝蒡₯䠀"

internal val SKELETON_NAMES_SES: String =
    "003J仆㡂恆ऄ⿻᫊䛁㴿ဈଠ䣩簦腜ⷐ檌悺䱊䞮睶౼ᙞ㦍唱ट瘸ഔ䀻ᶊ䔒⭲氃想嗏ᗦ惈ㅵὰ橡舋䲜㺲⚜㒱㕚榐䆙屰冓ⳮἄ᱕ⷘ燓禆羄皅✢⏏䛴䣰兎㭵෦滁྇蟧ៀࠀ"

internal val SKELETON_NAMES_SE_FI: String =
    "003Z䋆塃塤ॄ⭹凢൭ょ䁥䱏堺䣰ゼၯ仂䀋Ꮩ婗㪆䷛痢⶚听蘮䬉༳㯂⇚㒽㜗⧴ᅂẘ憀⍫䟚᥯会码㢾㖆磫ၨ瘉似堢忪䄚ू㜝㏲䚅惪灴㸪媡㎌഑䲤泆Ჺ⛜蘝蒡萜盲䳠"

internal val SKELETON_NAMES_SG: String =
    "004k膟㜌翼圊ᷧ姰筿糃旲䢒橱㲥ᱟ᯲岥淤穎஫臥泙⾙滰ᦑ祋㉤ࡌ枚ㄿᾞ偏司婊䶇䏔䄐㼚恵䜭Ἀ篥穮堩䳌奡苳藢㾅椭瓼撪౗䂵⊊ᴃ撀ᴩ઩蒛䳑禢㣞㈄婆ၥ๐嬹ྼ䯎ⵘ㶬㍔ᕪ窸㰼抎㢠ࠀ"

internal val SKELETON_NAMES_SHI: String =
    "008S䗚╳履妱筬翥姗汇㗳稐⼫㭨⚆揔⥜摠㲱᱒㕂᱇㢈栅㊟ᦓ䧔翎剠⊄ᜎ佛⒎揻栱㝜ର䦩௕৴䢋ᎁᨪ㫐弗児᪣猬䕡恂ᠫ蟄䂐嶻㴙熪▸⮄燓栕㖐炘ᣡ摎倆泔䌚㕐ⅿ㰔ᮗ冁⋶❭嚅↻ᢏ㲼ኀ䊞〢瘩㧮Ᲊ列䘂㸞㸇帅㋱偹氫滕䵚䦵⩗຃叓燨䠀"

internal val SKELETON_NAMES_SHI_LATN: String =
    "004S嫆竃䁈ࣄ⧛佰ਈ䁑⣗ⴌ≘㒮ᮚ槬㌊〥　楀ය౓帏㦴✸䃙㿣ᓍ唆瀬㿃脁嬯ᥬ垄㣤ੲᦼ岏Ḳ⻞杲滲ኋ曉涳㧍ࣝ䕠⦔༑棉傓綘␦ᇈ歄໇蒺秿ᾏ᭻䊧ຫᓫᔛ濋᤮⵵溱玮㽡⑸㘧蔘滟篏栀"

internal val SKELETON_NAMES_SHN: String =
    "00BB狈ᝃ恆ࣈ㍿᎐᧩漄⸎⥎犒懀夦楠㢁ᲁ曄ॕధ჆萗㳒ಌ䨢ᧉ荹臹漰䶿᤻倽౷᠗䐳␥ম竁ᓰ⣭గ侨䃂᯹⼛簕⠷࢔䎠瑉益㾺ጡ㙧⓫篌沌ゼ瓇Ⳏ⟶ᔈ蜆崌喡罚㯓仗⿺爹夭沮杋ᅷⴍ嬛苻⫎቟㡸മㅰ䒋澹縃禪嵛㻔嫃厴ᬍ⃽瑴ᣰ㔔愨㜀"

internal val SKELETON_NAMES_SHN_TH: String =
    "00BA狈ᝃ恆ࣈ㍿᎐᧩漐暩嵲㴨ဨ琨ഐ㦱ፘ⠪䥡蘩按父䤡ᣨ沲蛾㹞⧜⃭泎稍栁樂ᾎᮨ搳歜ᤛഝ砚Ⴕ佸㉇⓭㲍堅㯠⮋⛜㛴煥取ᄎ朤癌檍浍➧䂸䁨⯸ኬ㹭䶺熟嚶╿烑纅䜣䊆㑉昩㺘㟗甶㦕茗哥桢༮蟩Ⓛ㪵⌼㺴㐚蒈殒ₛៅ䙊䪅ᴋ砄"

internal val SKELETON_NAMES_SI: String =
    "008a櫈᫂恈ࣈ㭼剤ຐ線弽⢷崢傮緒伒⎊Ꮈန娈暦⮘幌㦈ប瓝窿萓ⳑ䤽⑏伈砂寇萱䊦㻋瘼ට蕡禦⩵礟㵩㮪栏椆湄㉪惆斋惈←住ᘋ嬺ᅥḱක㑃揺簵䛽砘䱐揱暋⅄蒣๿畕ᕷ䑠埇⪝Ꭴ縳⎹㑛䅓卢㑢㓍ບ扷ᝧ䄞疱㲰籖炰䞾䒦砀"

internal val SKELETON_NAMES_SK: String =
    "0041涤卲ⷹ௽᳚炉㜩✭䎺⁒㌺┚㄃↹峢湢慎⼗ᅝ㔐簬匍缟癋⓭ⱂⓀⱑ珯對臊㫲㆙䓄撮⬿⁷䒩ᬨ㍎溗㭒焲儹↾奍ࡥ匈䪳欰乨♬倸猨ስ儅ᕥ䥦意䒇噂摯㑕ョ嶕崆芙㈛Ꭿਉࢵ♜ᖀ䠀"

internal val SKELETON_NAMES_SL: String =
    "004P嫇᫃恆ࣄ⭹叆搶氨䁄ᾰ疷嘍℣ぴ璫ៀ府ฝ਱⌆㞼胔潥ួ硗඼㝕ⳟ㸍㖋ゲༀ㜁ᝲ⊐菏Ꮄⶦ䛄䪞ੱ兙੹侬昈㞁㵍瞕㧖燖懲慢粸扜脮ⲻཎ延媳㖃䖠祛膕㘂菧壛栀"

internal val SKELETON_NAMES_SMN: String =
    "004m䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ᓴቹ哃淹ᒃ巩䮓楆欸ᤚ瞌⭛硙Ȿ人ᖣ㊇烒⦴㰤蛲᜹൹抱㊠㟉⺪巪໕ᅒ☠ᝋ洨䈑ࠀ"

internal val SKELETON_NAMES_SN: String =
    "002u膖筳䷩ㅗ‸丆匒䴥岢撯撵᪕㓋凉沣ⵥ䲅ᥪ㒣↝哋࠹⦘ⶱ愐㕊๧籜綉祇⑮㬯抒᳋伆害腸ạᎼ䎿ᨨ硔৉䦔ᅃᐡ剅眍ሃ檀䜤眡箐菋㌍㴊犃㕜伍ྗ氰ఀ"

internal val SKELETON_NAMES_SO: String =
    "003v勦孂塦ी⼄甲泦孨姏々▇⯜ᘠ⣸㱇祧᫯㝊㼎൞佴瓜⃟滀䱌呴呫㗝弑䀇ࢀຉ෺咞俧㔫菈秏㹹㟍গ璳⹹穉ᦑᣢ㩉唂ᱝ皗ᕒ䁳䫤腲䊸漫㶰᫶ॖ浣珕幥䈮敗籶疸瓷࿊៳翠਀"

internal val SKELETON_NAMES_SO_ET: String =
    "003w勦孂塦ी⼄甲泦孨姏᠂囃峳ঌሿᔐ蜫胷᭰㢵㰧䛽禅砖ཆṆⱇ晼獡㲨᠀าⲮ牵舿䔉៾㯊㦷荵彏∲⻙寒䒉⤆༤憦⪀慍嫩⻍₍⟎἗ዋ㪲ଛ⧋㐉䕚╾妸┺絝孻秠㯼❨㟗枌ᘀ"

internal val SKELETON_NAMES_SO_KE: String =
    "003w勦孂塦ी⼄甲泦孨姏᠂彑橹䣅฿ᔐ蜫胷᭰㢵㰧䛽禅砖ཆṆⱇ晼獠粨᠀าⲮ牵舿䔉៾㯊㦷䎹猧㕙ᫌ臩Ṅ岇঒㓒᥀瓦煔学呎埧ᎋ䱤慙্磅帔庯ൖ妸┻絽孻秠㯼❨㟗枌ᘀ"

internal val SKELETON_NAMES_SQ: String =
    "0063㫇ᭂ恤ऄ㭹勫Ὅ⥍疥瘋茡㢭ᒀ蜰倠䩎稘眖᪪⦌癗䛷⫟尮䑬଀佇拇㮑䪳Ⰵ࠲ᐞ㷷ⅅ枎㐺伿ⶓ⃵䛋ᫎ吩⡘⃎擑䛨䞍ᴮ愿濘㣘葽ኍᗚ悘吥絲甃儢娏₊᜘拖⣣殹撚妇測䜜ᨯ䉥䢾稹峉槺㼲涍䪼ῳ彈甂โ㮖⺣耄"

internal val SKELETON_NAMES_SQ_MK: String =
    "0063㫇ᭂ恤ऄ㭹勫Ὅ⥍疡礟䄫甈㐷禀唂ᡲ᥇聱㵒否䪳莾⋽⭶棡憄∝ḛ㒜ᖆ㈬࢔棰㙹勍琒臼㧪㒝京翙弴䤪㪡乥檛筅荩㉴傾蛣ủ䯠塴狕係樮㊗僜䄅⡉停竉岱ጭ▍೵葮ज़胱╱堭෶ᣍ仮枣ম䑨ῧ䊘䏆焑㨓⒂ᔟ䀬"

internal val SKELETON_NAMES_SR: String =
    "006J暧㫃㡈ऎ猣悭ࢢ⏰歂礟䤁⛢㫔ᛆᨛ㨉⣨䶷嚜值࠯復䩤矞㮳భあᗏਤᑛ艠粨ლᲡ砗䘈ᕂ❙᪈瀊籖暒畼䥏㐓把察篕ᢋ纠罄⒘睐⸜Ꮡ尳狄ฯ᜖汦撽摩ඞ眾ሺ嬑ᾯ洜缠羪⪱㈦⺣ᆤ䆡卣⛂㼁儥™Ặ瑋撨筿菟水"

internal val SKELETON_NAMES_SR_CYRL_BA: String =
    "006t暧䍂䁆्漡ᱍㅖᛑ嚥ぉ刊礅椖堙೛琊莛䒉㺄ൟ蟑ថ薼┇澖伸㧄硠⸢ᤛ烡撲䣡棌☢懬螑炊Ⱨྨ瓵ᄂ㭢ᎄ⋄㧐檖潈ᣆ噽烟ෘ᭼碓掰墊᧙൦❨獦᡺᢫㟨ၺ斳䰚ᒾ⁼∰剹暿⒋簃❅廕檨敠姑㦂礅宂爢䵊慸畷搷菱巿᭟䠀"

internal val SKELETON_NAMES_SR_LATN: String =
    "003+嫆呃恆ऀ⯽变Ḅा⡋冄叧ᘕ⌤偡災䎉ㄩ葪澑䰀ⵍ⪡哏፝ጡⓝ⿂ᖤ洖媇垐漀佁᭍帜䛮᫹懟ᛴ箪Ⴄ籾稂儝悠禁攥䗽Ḝᩳ㕅⯍犼籺悳籛呙⸘砻怯琖ᑮ咄涆䅚㣝悁膣藴萀"

internal val SKELETON_NAMES_SR_LATN_BA: String =
    "004E嫆囄塆ঈ⭽匤᪡屃䁆䬾㣡↌䟣泐⁫ᶷ礰ゆ㲶㌯徶疊㚰槰甜⥪ⴉ皠秚劐䔀幎㬌婖艳䅾狫࣎Ⱈ昻│忀籉㌌㼬ᤡ⻬∐䣅汧点従䥡䶷彃掃ㅰ蔋゛䛋ᘍᾉ㳢荃䉴㤷෎⯢蟂࿇៮ᬀ"

internal val SKELETON_NAMES_SU: String =
    "004g囆囃恆ऄ⭹卸搚ᤸ肂興匲⎌ᩕ三毙䨟アᙄ⓼ห䴀⪊ೕ滍㰻澣脙වᮕ寞泠䣢㩗䠉䭶⢕Ⱙ⻆盃⛋◖䍞⾋汭滆᙭䡦⺓庁椊殆㫾ⷄ彡୯ཾྥ∂䎨❽੐㡣ၔ㽪絵榵扰櫳寤桼㚷侤蝜晀⠀"

internal val SKELETON_NAMES_SV: String =
    "003lⶖ媥ཷ卄䥵璲歐ⰱ⮗䗼≗呁⧉滦涩泬虊㤝༢ᅩ≞㝕➛ᴫ泦㭓㪹䓜楙㹄庝售溁犥໶䲥Ⰳㄼ挢㭂碌廩ⱞ᳉௏卺ᓥ晆䅯㦜揄眡箐菋㌍㴊絬噺坁㕐㶫剠聈択㘥䡀"

internal val SKELETON_NAMES_SV_FI: String =
    "002u㫥塂塦ी⺄眳➝┶絥ೂ༸承碴⳽వ斈毸儗嶅彉ᜓၠ䖘偤嘣椗漤燪༸䷠ॡ勝澁埼⦾ᔄ墣ⵐ㏐ₖ䩋蘉㞒湃憵蛬冨蝪╤紹䱌蘖巀⊺刼䕭䌛楧祚⻋䃪斕⏨฀"

internal val SKELETON_NAMES_SW: String =
    "0031ⷦ狲媙㫔虢䉐徔埊ங᳠⡎⼬㓎溔ᴫᄊ竌繦㐁洌溊擿ࢯ㘸₨厉⸧㤺䴙棖繨㜥㊧ᮏ䤕ॺ⻢䠻ᑥળ买匄籚徜䬩欥㘷廪ᰪ໵⅜Ṭ乘᐀"

internal val SKELETON_NAMES_SW_CD: String =
    "003Aට笓䶙⅌慨❉沋腉蒠↚労燉櫣䦙畒䩥夡ᶚ㗔ⷃᒀᑓ湚啉㈔ᯕࠎ䂱₟ᵈⵦ㮁ᕅ峬煾㴥Ἧᮒༀ亀䈌窰㌈漉㦌禕൨䈏撆ᇾ㕘㶡琫㈍㱳搌䒼䠀"

internal val SKELETON_NAMES_SW_KE: String =
    "003Bⷦ狲媙㫔虢䉐徔埊ங᳠⡎⼬㓎溔ᴫᄊ竌繦㐁洌溊擿ࢯ㘸₨厉⸧㤺䴙棖繨㜥㊧ᮏ䤕ॺ⻢䠻ᑥળ买匄籚徜䬩欥㘷帪封獔狵୪䲮ឃ孀㣤窀䠀"

internal val SKELETON_NAMES_SYR: String =
    "005E㺧᱂恆ो扊薾䦼牷ᑝ桸ᴂ偵ᮂሗ㈽傏ᙣ㜛噩牑腹䔧清ង獰⡆繐぀硰亶኿恀蜦 ᛝ๽厌⺎䭠爘屺අ箆侤≺⇫更㊎墁癬⎗朳ሁ肮す⋖櫌᷏埖㵻῎♴᠄⥹梠狔෺㳟⇂㲾㍓Ⳟ⋊䆦廛歮㧿彲朣個"
