/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_FORMATS_CA: String =
    "00Au䋈呛墆ऄ㉹兿敭冊䜥儚洮ᐑ኱橊Ạ姑窣㙔燒⯾␌ᵶఉ萿蜏⭧荤⩛⭆㒓剬啕潓⏼熃㹑樾᫙᠙⊌ᕒ猸㔝ả盿ⷉ᝞究溚礓ᩢ⋝❿朾໤疵甮及莢綜᳭蒒嫣⵽✡⎭偉㔯䏮橰ᘄ涸穧珲癹ℯ狛廟仺厖膂珇腥噦扒敩莠儇ᄘ侢呰搔ᒁ㉄喂࿃䂊㜣壟宇䭕⦀㻽䧻∹➨㷖禳㉺皜䢺岴␸㥁抡聵䕵巋ᄒ蝙礊ᄓ䴌㊖䚈渙䨡䚡⵩磦杠㠀"

internal val SKELETON_FORMATS_CCP: String =
    "008h㪨呣墆ࣇ汍㳰ࢉ䜥儢䪗☀䱈妢契燷⯽燞脱囋ᄋ㡄滅ះ䤙ᷪ唼匎芪菨䗠磼┇屨㖛ⶌ㩔唰婌ഌ恜ᛚ䉬纮㱬ឃ䱅炲ንᨖ䎽䛿狈ૹ咝❟ᶧ凧ᔸ㉓㔭啘爑ᬡ䚔༷ሪ⩉溥妬ⷒ婉䣮彭䐙蒼␹厓ₒ➸ỻᖭ≹慶ᵻ㬏哱渶᭓丞戼໙粜␀ể㥞恭っⷼ⣗烞悈㭵杠㩈㩠垆ⅺᐚ粳Ⱑ呗瀝戲萻泗噎畛螾ᆞၤ㭥璄ᇁ㚁传萀"

internal val SKELETON_FORMATS_CEB: String =
    "008E㪨ᑣ恦ࣇ摈᣾䢋纎ࣂ☢ᣇ刘䠹䙤泋䌟盏莉㲤営玌ᖆⱌパ䇒溙寝㰟㎈砅➏៳ਊ纽箬拢⹌禉㖀㢋旁喟络臂Ⴡ胯੖厡兂㥬蟏濩萁纳⼞㲗卅玭␊ⶭ᮪擖᥀⣷ㄷᨡᲉ⮊収岱沖⻁⃪ᢷ楟ൂ㤜淉嗘⚛痱⃛㲲徽窦椚揗募⧆ᦟ౭奌䁢⇗ᒾ莧荬䭣菮棡媞乭⪴⾻欺⇯⵿竾岖⁩஽ᵹ色拶滘Ⲑწᛰࠀ"

internal val SKELETON_FORMATS_CHR: String =
    "0087㪨㑃䁦࣋戤ᠼ妡䕣ࡐ侸䰤硏ᜁᵎ哙薨⟺沔嫂㭶䠁ᚑᄑ⪆ᤒ䬆ⅅ㙛ᕰ䋞᰿捆嵙ጂ皅ሬᒣㅉమ獕▶蚚▣ඓ෠縑䋑Ḝር⇟㏝膟࣢挧杘⇏㛻䐹෩⎣䘠淨ΐ⚏⤱ᓩ㘖⩦ॎ藨玗㵂缑茐窃ᐜ㏫㽯綸䇉䰷બ歸礕䄝ᖻ⪑㮃藀㙰ぺ蒌䔨㿕ྞ⡱⯃⦉胄嫧媷砞捋氫⑴汜䓘寤璟䠖ᘫ᭼ࢀ"

internal val SKELETON_FORMATS_CKB: String =
    "008U㊨㑜䂆ࣉ搡砶⡿罟蕇䗊憘⨿䵢ሴ庯狒婽喜璐䓉ᜥ田ⴡ㳽⼰䫀ᘠቛ窒㳷盫⥺㛋⠪葽䎨ᡖ㿏↤徒㨧ᑊ琓ᑝ爉旾瓣嘐๗困㪔怉㓾䜟翮⎋᯿㞟冐౺ⲛ型ᅮ亷爸㈧⫪怸䡓傧剋ᅉ絹焘䈙帣槩㲟⌈嬊㯥⹬㞽仪惼㒬⋘臲䊧纅㻕渑䧂焰挟䌷嶻戅༇橢㫘䒓ᕖ䮞䐿斐自臱䤤灬玍䶵憱菺塌⢗湀⿉蜦䭖腽劭虧㖱䧦ጙ欈᝿䮍便栀"

internal val SKELETON_FORMATS_CS: String =
    "009p㪨呃塦ࣇ汊䗥ࢋ美傑ฦ堤絃ଣඉ䷗៺察ㄅ胨ఢ┎究⋇❽兲ᜟፄ䯙㴮ॗ櫆敉䦦㳡␒㡉䆚ᔸ剙允憅畿ర硿ᡢ朎⁃吤䇃瀩㿝蓸掅䛗⽕⁊蚓⻺眨悗䈝潂〉擬嘤呲婼艏㫄嗊ᱹᴼ淏嶩⑻肮㰚ఙ條┲࿜毲්ௐ睘㔵ཱ㺂嬄漳葠ថ㪽ṻ㥜ᐟ涩ᮖ協Ỳ䴳ද䂁洖弫㉴ႅ艮ᝐ桪罡嵸ᘣ聙爆⒐耀"

internal val SKELETON_FORMATS_CV: String =
    "0092㋈ᑛ恦ࣄ㉺ᄉ㸥䣈࢙ຄ᱘ᧇ氦ၺ烑窤Ẏ暧凗屷␬芓腉永凤㏿焾კ嘴䧧​瞭ቊỪ痻䑩ᒳᾄ磍ቃ䠚碪筎墄⩘硒Ὃੀ⵳ᨚ攓柚綠䌄ᖷ撏柣痓懌廲沱罘቉瞕罐芈眕稢䮬磟㛪ᗧ䑀写䬐㎄㓖⸐䯑绨腍䪺⸑㤺ア䌿➿⟧珄蕉ῠ虾涸⤶⇃㟭琞孄蝺㕳綋彉㗫仪ጳ腰嬣偽Ể七ဣஶ㜪㊫එ偈ᛁ䲣䈖⎇⭐塞ၠዑ曣䳀检簔䋏⇟┬㽖蜳萀"

internal val SKELETON_FORMATS_CY: String =
    "008N㪨ᑃ䡆ᣇ才ჸ৒细冕ᚗᣇ栕琹䃝獵ᔟ肓徠婶䡐⸛໮攺粭㉡窚澵෨蘛್胚ᔴ煟䏇⋩⬚䦝し⦛姜⽝埸䜂⴨ᴕᤶᓧᚅ洒夣䫞羣潼৙ਦ๯⧠൴痄臞ᐱ蒅㩴䨔㙙ⴈ⤁汜ᬣ䂣䪎䳿推㈁蔑示㘤歾ឯ懧砡໣肈嶌斳㾏䘵ⴚ岂楏疵䠋䞃Ỳ睛尟晱虸惈⏑㍝垿⇏⿝瑬⶿狆屗桑◍婼蔒⻤ⴕ䄃ᨀ荀殐∀"
