/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_TA: String =
    "00As犨ᛃ塈ऋ癍㠜桑爅戓葆⎐ᴆഒ扛〬恠⇕世曅⼱⬻␀蜒橫菻㝞䗹壦ቶ桁㔈僶ࡂᛰ塂☙፦⎽䓟昄ት㴆堳ᶩ䱙⟴䂗ᛰ渼ᤖ᥎甸紸✀洵㐣溕礔㩛岰澶唹减䌻挷⇟⩖㣬ౄ愥歋㔟叫梣晆⣣䫆螡昑㜿Ⓔᗝ䒘㣪∐䫙ᘞ渝吻怘㑑൲㡊唻㩽㺱璔⹩昐姻耇垞坴଀"

internal val SKELETON_NAMES_TA_LK: String =
    "00Ar犨㛃塈ए沙系ु〿㠣壸柢ࢤ溦㉋㰄፬።簜忶ㇾự䈞⚉㦵嗍繦䌫䐨ᶁᖰᤣ爃ၷ਒烐䱺宛耽緮⺠こ羂↖吥棧⾙㥥౧欀恉䍉容磰ભ兴嘴徊᧑䚫渧೅悉㾯痙捏敒䆋⠂⋑䌖⍬虜㜅圹㒃伛෶佼⢼蝲簷䊊⃃屨ㆇ㈼䖜䕘䑘ᔌ䂄烓ᡶ泺㕓笠嚲萡㯷䠏✼曨฀"

internal val SKELETON_NAMES_TA_MY: String =
    "00As犨ᙃ恈࣏汉搽ंࠟ砀汞ࡪ柡ന⡉⢣⺦ఢ戯਒䭯悩萖朻ృ礴䉙哧䬵碘成拂喈㩻堮ಥ䦑ჶ⮛耽糶⪠っ客ↆ吡淯⶟㧤ధ欀聉㍊掱磰࠭祸ᒵ徊㧑㛄笓䩡瑄䏟盙孍蕲䆇。⋑䄔獭䛝眅暒兿ᑜ៖珽໰腉壝牨蜝猊堢保烡戃瓇憉堬噕᥇ᑓ⏻⌛௴儠槿予品蛽㈛"

internal val SKELETON_NAMES_TA_SG: String =
    "00Ar犨ᛃ塈ऋ癉㠜桑爅☀⩱萁灀ᢝ廊六䠂喠呭▊晢乶䋃碒ᱛ旛菳㝭罠䡞ሺ桂䲪ྠ㘈涃ᤑ絎䏤菑斛䠡⽞䱦ᔰ宛互㻇儒圌䧡᪭୾珃瀂懅焺獞ᲇ઺徸嘋ཪ᳘斷㯭枵䲦Ằᑣ⫤は拺䂼卼᪒㼜⸏焙蚆能泐盪㱣ཱ䢮አ蛴䃷㡰硴䲒ᆃ⹑榓纱⻎䦺ⶰ⫯眠Ṥ蕿尜"

internal val SKELETON_NAMES_TE: String =
    "0091溨ᝂ恆ঋ癌杹৶笁皅侨盥ৗ⢅ೠ㐯䧅棔瞂ᑔ蝢役⪙䘠ᐈ维ⲋ淽竰厍❴ⱎ樧⩳䦼ⲕ獄䐯䨓ᝀ䔐Ứ勍樑扶薣瞈䩅狮曧潴⋒➦弗㩨倀⪫䙘穱䛢㥸烓啭䊿歆⻎䶍⍜係㮱罇ᅫᨙ唺⦉孺熆臐䏸帒堚塦ഔ嶉妕䊍溰烕ᢟ簙筯羿䣐"

internal val SKELETON_NAMES_TEO: String =
    "003f囆塂恆ऄ㍿剌㻑崋娌ᰬ䵁ዤ䇖灂㬨㹁戊㜡拾㩇㤎绥毪⚟௯窰聠椥ⳍ猐䏙ᵚ࠭皺眚犖Ꮻᠸ桚絓઎㬰嫖௑ឱ尔䙍縜奪ଊ੭欙ᔰ垎弌汶浱䇏䅼柗横人ࢷ䦭碛⊡糊䰳ᝓ೧䰏崿ᾏ䠀"

internal val SKELETON_NAMES_TG: String =
    "003g䋆塂恆ऄ㍹匦搶䦫ᝑ◊墶䪨᳘茀໨煊刃㍎䁳羂ᄺ屜䱝蘰臃藏烋ᝃ也婨㺰䚰䣳作㦰িჴశ睰ᩆ䩴⨢↼䁄ᐇ⠓㡍瓭媳筆蚚ⓒ㞰ნ䪧ụ䬩ᱏ⁑䛌旪㕥Ὁ壥䨷ቖ夺毷䈌Ძ溔澟Ṽᬥ祱㟩喝䔖婎"

internal val SKELETON_NAMES_TH: String =
    "006Y拈ᡂ恆ॄ⭿剌亱紐暩剒ਥ㘫ᤖṖᰐᴗዢ穛䓅៧梺帱Ắᇯ濦⿡┑ঢ়ႛ璆疈攘筢⺎⌜䲧ⱓℑ๹ဋ烅㈽咕煪䡦戱⭺洴㬝哫࣓徙㡠㒏玀⯕疵䰊卫ゲ㍞⬘㲋秭ৄ蛫收㱇䇺䌅ᨔ囿兌嫻奕坏㰿爺亜萱ᵲ凟ཱི徰᠀"

internal val SKELETON_NAMES_TI: String =
    "005L媧㡃䁆࣍渦Ⱁ঴囀≮灺揱╔腕ᯋ䠏垢൨桛䩬㈅ㄟ侍䯷嘾疃买ࡸを෩ჼ⻱ಿ⢱䊬⩑汊⨜巓栟Ꮠ⦣૧怜蝿㬵㎉榻ⴀ㟻䈸䫲㒩≂蜠ဿ極胄搓泤ହᎌ蛎ἂ⪧㪧㋣᭐凉她婖㱔孓䚚⭚薿㖳㰼懹癭巼秲ी"

internal val SKELETON_NAMES_TI_ER: String =
    "005K媧ᡃ塈࣏橋敾࡝砨蜠㘝综⌬⠠䝻焐⥆᜚៘㵭ᖌⳜ⛘濛㰝氄྄㇀䦑⿌ἀ⿸ᔒ㇇浜಄⧚崤◽㤈ल㓸ଏ忶潵€▮⨄萹塇仉᪤脛粀泻෗樓磏ᮐૄ㘽笹萛ᴸ帹庙抄噍㏭⪣⺩⊇ᕩ㚳矫疯䛎䮻╟≾乖"

internal val SKELETON_NAMES_TK: String =
    "004k嫇ᑃ塈ॄ⭹勬䌚世␂㷾ण㷍ᘮै㢄ᔇ᣸䦕剟异肸瘗㢳咟蟓⹴⪰≽惋箞毄儗ᡏࠇ⚦昽ᓓ湀穿㗁䄾瞖ጧ⒬䩓茳࿂䎨涼堓⼧᷈歨禩䉩币⥶荲䄉粛⼋欏ᬵ෢ᝈ巻᪮૵ᴥᅖ䈙晭䢶㣃俯፷帥蓍䐀"

internal val SKELETON_NAMES_TN: String =
    "004u拇㝃塈ई⻻ᦸ縴᏿ᜠ䳆奡䁛ዣᮔ᧍Ậ⯆ၯήय़⮶藰澊⒍䂈喾ᯅ悞ᔡ䰔ࠎ蚑眔२㹩ូ凾瘤犴⧗䜍ᗬㇰⰪ磑㜀㎤ൎ菐䔘᥂䜁䝑❞₲慪Ც瓝⃔沱䘯氷耬蘇枻噜仭䱬嫖䆡㤞悆犆㼧濗堐"

internal val SKELETON_NAMES_TO: String =
    "003m䫆囃恆ऄ⭹变ଠ⢟ඨထ䙅⍣ேᶀ㛱㌨⫧䅍媩聒ᅴ亡啨㯻欥䬃灔ㄠ㋱⡆䗷游၀Ⲳカ弭⪰㗭縸爰⻳绅ⷉ⻗✆᧡㨾ଃ絥爏湁㾓粅珘┧櫜㭺❷窝ḇ峀඙〜嘭皽㲲璸峿⚎⎼㵈眺∎蟹㗠"

internal val SKELETON_NAMES_TOK: String =
    "002Z䋅ᑃ恈ऀ⏿፬嘡栉ሴ刕䪚䤓ᜐ孢⌝䔢䵹◡ऀ塘瘸热奆⯞᳧圄ፗ㤢浛煐໡瀦胕礣㙄灾藬燿ᔢ⵻柵✝殖䕒ੵ竣犁娆敂莨❳藪ᩫ囏᥸懰䮔着ࠀ"

internal val SKELETON_NAMES_TR: String =
    "003Q◞᜼䄏厜夘痏倜㝏庖᪳㫉䋉Ⲝ圭ᢘ㍉渝璌㇤⟟೵笍翈䠔ま䐭⁺䝀艸㙘府听傥婳⇙䳠⶗哈座淤稆蕅ᐔ概ᓆ•吓␩䟜㽔◎Ꮁႀ琎欓䒇噃札㐵尫㈍㱰⒵☔඀ࠀ"

internal val SKELETON_NAMES_TR_CY: String =
    "003Q◞᜼䄏厜夘痏倜㝏庖᪳㫉䋉Ⲝ圭ᢘ㍉渝璌㇤⟟೵笍翈䠔ま䐭⁺䝀艸㙘府听傥婳⇙䳠⶗哈座淤稆蕅ᐔ概ᓆ•吓␩䟜㽔◎Ꮁႀ琎欒蒆㙃✭㐵尫㈍㱰⒵☔඀ࠀ"

internal val SKELETON_NAMES_TS: String =
    "004G廆呂䡆ᤄ㍿剌佱爑ሁ㡐䶘伧⨸坒℘Ⅱ㓻䎊呖⁙皯⓴䗹ⴒ䌦⪭㨪浪洦堑䢃▗姗橿㫟⟎㱽绅哒ᧄ㜸厕䬣㯤䭈౞匥᫯橯獧█㞁徐䛯敧⸼ㄒ汉䭪絭丨⇆ᱰ䮜旀䀾哞៖⸄䗕蛶蘂"

internal val SKELETON_NAMES_TT: String =
    "006o拇瑃䁆ऄㆹ滭ἆᐁፐ᫄礯戤三ⶡ䤁ᑀ㮀涰ᨃ柢偛䱘ⶅაー翾蛖䃯䛦ࡄ胝ಀᦎᗛ␼㚇ब儏吼嘣ฃ䩧寈⊥㇊繟ᄷ⧃Ჯ䃇䐱梷孶氨㛗桖睎⩕᷐廾ឮⓟ渣䘘磥菏⚳㵆抔甤劌ᵔ尕㏝⺵㽟㷰䝮䮗灷⋄罊紏竿堀"

internal val SKELETON_NAMES_TYV: String =
    "004T䋆罂䁈ई⧜滬෈㱪য়䅉㐇稑࡭ႃ㓥༿ဗ熡茪噀㫼䁀䘬湧㯟ⵦ芁儋⋦渆⫮ຩ竤ᐫ堭簈菧伦㔺嚴䄍᜾耼㩳ⶁ㙛縄竑䘂៦敔妑咄ᕚ乩琕က⳼䀺泯絧✰⏇梧笻㦓ᬅ氛吧੊䱦䅲ㆳ㵰嫕㢯萩䵼"

internal val SKELETON_NAMES_TZM: String =
    "004D嫆瑃恤ऄ⟿ᮀ➵㳹䣉嚡Ḫ㉦沲ᅀ僁桠㱑蜞簣㰺䉵膟翈⇞翌帱ཀ舖䈎ヘ⭾刢㵟⮶䢏ႃⵖ苈䳗䓡ᾇ盛㝿㗣⨘兲啲働嗢ኩᆍბ㈈䯕࠻智晻嘊恾怖摛㜒伴灒殸䊸睚⣵㟸㧸ࠀ"
