/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_FORMATS_YI: String =
    "008m㪨瑛䂆ࣉ樠᠝秇茯ຄᶘ⫃琛ࡑ庹䅓茝煒ੀ咐⃊⇴嘑឴眃瞬◹␩湿ㄨ宺婞猨侺敮ଯ滉暐橙千悗ဌ窂ᴨ⥴䊙睷爓玔䈀㜇ゖ祋▗捅薴ῧ荬瞊㭝旿⎺揣汪窵嚴爘䐕まར᠃㎞冗臆僑呏㥡䑅礕䶊緰㺇ⷆ䍾ฤ免ᤓ㶏掠湕檡ᨹ埌㿉䈓䃢Ⓣᆰ懅橙㤎⎣ऀࡉ瀅Ⱟ砟怞ᡄ༸㜲冈㭫屒䝫㞧搾蓄と簡印搵箣今墳഍敽৑✻粊᭴粇㟑廧俐☀"

internal val SKELETON_FORMATS_YO: String =
    "008W⺨ᑣ墆ࣇ汍㳲ࠧ薖Ⰻቜ•㳪⩂ᔖ㋜螴䟝⃦ⷧ玸怤汤⟬䁋宯඗杉⟗ᓰಿᜟ猲ᴺ༁腺Ⲑ峠ኯ੡Ꮋ䧓㟨厕㢜຺㺳ᶤ傦焬㜶䏾䝖枇䇛⽞縮廁綌斊യ烋ᰗ₝㯎᳔㢕䖁乨㼥ᴵኅ蓒᠚㪁圗പ獧ಌ紥䝳ᶶ蜆䄣፦烞♢ᔌ₡沓䨦做矚䘠稏㭼璷羥膽⳯痻莝ᑅ侠棜楆ᣌ侤瞿峁泡皎婟䈥㭺绤″乙想瓺⽻ⶠ㧑柀᠀"

internal val SKELETON_FORMATS_YRL: String =
    "009X㫈味恤ࣈ㉻ሬཀྵ勞₉ઐ澜䢅ヂ棈櫋药爝蕉ា栒㟐♋登ᑭ渮㈡ᬼ缥ை縟ổ艕ᶘ㲯旣噴ᦋ⦓゠倏伋䍶⑂䍡脉᳠ᳪ᣶⒳㥳∺⿟至䔠罀℺玷䀢᜹㲖䋇䡍㶅脔ツ弃懳䧲ᕑᴉ㥃䶊戹䁙哗⦙䅤碠厌඼䖶枝ූ伬蒹◒䦋幵窽乱⵷䔔壑堶㩂䔕樒⬋葧⛌㽩繨䐞樌艏ᐅ⿞撩⟱䜴㬟ᔾዿᗄ噭佼ද枻珬⎏ࣙᮛ檛卨疄ᄯ⼀✀"

internal val SKELETON_FORMATS_YUE: String =
    "0095㚨㋛恨ए沒籦疐䓐煥৯–縏嘀䲎仆嵑脂屩അ䮂ⴣ㋺咤㔕窋皣茍惆笳惒繮嶂ᵾ朧帉〺๩䢠㰺盆ႄ蚯僵⤩ࣚ⹵ㅱῌ蘰Ↄ潁吘㸋ℙ怬⤖䨒᱗䝏㎵䳔ᷔ䗌懝嘪懪♾葵。᜵劬⠡䊖⥅෾加ᶝ痠糝▫㪫䂭࿹㳭⊽利渰จ䕇Ἳ绽䚜月㡚斂擆薶嫽荡潗⚙宠㿾㕣痚猖㹥ೆᤕ化䭩⪃ਮ溃日ၗ䣮猛ⴊ标ᓖಚⲒ胍㰼૾忉⬪簤㱗↔䅵ㅭ㊹↞⛔䴖࿜荶歩⚾⬋㲾"

internal val SKELETON_FORMATS_YUE_HANS: String =
    "0095㚨㋛恨ए沒籦喐䓐煥৯–縏嘀䲎仆契脂偨䂤崚⩇湩ᣪ楾᣽樧䋝๦㨽嗭⹋ヒ翳䵪溁ᖠ簝ፇ䫬⒑塷曩ീ⎙ᚢ⸕羓启㭻〰樍䦆欶ᦘ⫄䥈ᅪ煾藛䔢浧哃⟕溬┡潟緌砐榬敦ଉ岱ሩ⌺ၠ幧䞋孨纯厬橴蘉⽩巼兖䆄㡁瀹䅞翫峥聳⋅栙渲➷⚞掁芙峝┃䟲漘痗愳㭨丑ₜ䢴❊ᰜᩴ㲝ᾔफ़᮫Ɑᰯਜ㩘᫩ᨋ䬵声᝽㞒乕灈炮㬪竪嫚嵲㯼荐ᵙ❳㖛㖤狹ᐭ崼"
