/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_AA: String =
    "002J䋅㑂䡆ᤀ㟻ᩉ⟡尯၂拋ᡘ帑嗬島ᅘ㑉ᣣ蝮祒恝㓘潻੦濉⼵㹪漈窵㐋緹ᕷ䶪ᄃ汾胷蝒ᇶ洡柚薞ⵕ碒㷊池䵉ᚵᨷ嫶䮊罨⫲䯬滨原㎅✍碂䠀"

internal val SKELETON_NAMES_AA_DJ: String =
    "002D䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ଌ突⬹⡱噐ᩢ你㫤⁲៹㵡庡㕐㶣僥嫰耀"

internal val SKELETON_NAMES_AB: String =
    "002G䋅㑂䡆ᤀ㟻ᩉ⟡尯၂唅奰嶀㭹Ḟ⤪⴩穜⟕縶㌇妞ᓭ种⫙像㝪㙶喠嶆䜽奯悊歙芿䑻螥೻㢑㫿➧畍撴嵺夘ᡦ⡫㩁挟⼒㪣䩜渘垛㎇✍砂"

internal val SKELETON_NAMES_AF: String =
    "003w囦呃塦ी⚄瓡蛇⬍䁁ᮒ༸屿卓⩨䤊ఆ橮绋労仩畧✆㖈耰᯼⽔瓏樣ਸ㜃洺㺎㨳灗䂏肧䗬Ῐⲇፒᅡ༒脫ᑒ蚈㊃焵඾ⷎ獴⋣ઢ䴛೪㠼湐ᦣᘮ୻剀篪勎ᄍ᛫䲏崪䟟⿐က"

internal val SKELETON_NAMES_AF_NA: String =
    "003w囦呃塦ी⚄瓡蛇⬍䁁ᮥ㙑ⷾ㕝ඦనᨘျ友ኴ仩畧✆㖈耱᯼ⵔ瓏樳ਸ㜃洦Ẏ㨣灕䂓葕ᅽ໷ᆡ⪔䨘㦔乌眕■Ⴀ苏⧯ㄳ勽ະ梬孄栺唎↔䧡佻䣞紉曵⹥ಇ捵殇犕៿忠ࠀ"

internal val SKELETON_NAMES_AGQ: String =
    "003Z涟㙨撞Ꭿ⡥澲⹗税翧ⵂ涉嫂婉㹋ẗㄺ⓲戭箓䷄厏⺤孊ኹ᮫漚㈇Ꮚᣢ⫟冓ᶂ䫀粡櫥⅁Ⱏᮑᰜ㟈勥孳⽷䰪翇᮳愦寎≲㩲䄠㳔砑〉Ⱅ๲嫴倝崰⤙欨㦞㬡⫔⧧ᣋ健琴嗶狁㕃抠㌇োⷡ砀"

internal val SKELETON_NAMES_AK: String =
    "005R拇ᑃ恆ࣄ㍿厎或ᨔ搀⨀㴤㩳୒䪌屜⪭K㝑㻓檋䄑塌屗Ꮏ蛟䜽䗿⥖䓠聩战䗣癜箚䠄㛁➌玱࡫毂೙㤼⒅悱蕢系帱⳱蕒聣ᒻ唧ਰॕ菅ဩ潚灥䲼竺౼൱ឬ∭৕࿏⇜⾎產䉊ྖ瓮憎㒇ኰ㡥䆬恌㍒葁禷㢺捏䫞孺㽼"

internal val SKELETON_NAMES_AM: String =
    "004u媧㛃䁆्漤砷࢒⺠㤇ኻ樈尭ໃ腂䪑ᥨ㱁【ᅒ䀖碛㦌䭳⢢敧直潹ⲃ暐䚁䁄笋㱏攔清囐怇縴䯍盩类ᑇ䎚㱉ጅ㾠䝨篬对ⷲㆎ舃愱䖓肀愀嫴珥ᙲ柽⴫㤫㨬婽⡳歝䃄渺恦㠙吏஭紺῝䕣毵࿩垐∀"

internal val SKELETON_NAMES_AN: String =
    "002J䋅ᡂ恆ऄ㍿剌伱爉䴡ᖋ壅炬捂⚘ᠲ→⪔癮櫊緛俗䓷薊ᩮ嘆ᴤ檦淃ジශ┗徧ῡ➙៍柪捽慤嚉㗟臎⋘⦟唃栌䀊堆╁宎姑ᄁ耝滨物䘞ᕿ獜䯀"

internal val SKELETON_NAMES_ANN: String =
    "002J䋅ᡂ恆ऄ㍿剌伱爉䴡ᖋ壅炬捂⚘ᠲ→⪔癮櫊緛俗䓷薊ᩮ嘆ᴤ檦淃ジශ┗徧ῡ➙៍柪捽慤嚉㗟臎⋘⦟唃栌䀊堆╁宎姑ज䣮囨物䘞ᕿ獜䯀"

internal val SKELETON_NAMES_APC: String =
    "002J䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ଌ突⬹⡱噐ᩢ你㣤䣩᫋ⱉ䓤ᷦ狅㕁抢㎆䧋涁䠀"

internal val SKELETON_NAMES_AR: String =
    "005r拆硃㡈ॄ⧟滬䍀㕸愇ᮽဇಁ๎₹₹ᶃ璄ৎ嬽①虘ཆ徲汧睲䟾䘕䬊ਸ䨳疊≷⣠ୠ玤爾珆僦㬁ᘍ侙⫙垴⦣䜅彋丣秉ㅰ窌呙㱫㔰哅⽡䁵烙᪵唧䓿虗忿ᴇ♓萹曉李焪㖑柦畠䓐璾ᳲ୎៧⸵砄"

internal val SKELETON_NAMES_ARN: String =
    "002J䋅㑂䡆ᤀ㟻ᩉ⟡尯၂拋ᡘ帑嗬島ᅘ㑉ᣣ蝮祒恝㓘潻੦濉⼵㹪漈窵㐋緹ᕷ䶪ᄃ汾胷蝒ᇶ洡柚薞ⵕ碒㷊池䵉ᚵᨷ嫶䮊煑盽ੜ滨原㎅✍碂䠀"

internal val SKELETON_NAMES_AR_DJ: String =
    "005l拆塃塆ऄ㍹厴⎨捰ቷ᠖ᄂಎⅪ㪳ഄ㳂䥍蜟歠蒠ẍ㹯蓲㟓⟸ጌ㐨䤌漜㑖䔅ࠇ᭝啼漖ᕣ狌ਸ≟㪆數瀆㟸຺㈸盅坂硧ი惨猺ₙ䨫㦻䍩㒔曶綿㏫痲胿婳ി捓Ⲓ呶ⴶ篍⛏㩣Ḽ磽噆♀栀"

internal val SKELETON_NAMES_AR_IL: String =
    "005m拆塃塆ऄ㍹厴⎨㎸礔㾠㸒ਉḲ癁⤫൩刂嗾䟦棩⠩ᅬ痻筞嬿耖㰈聲ࣆ⃝Ṹఁ䏺▛壞␺杶Ⱑ煘肑ᳪ╎膿࠵祙繸⪿吕ᕳౖ狓⩙瑀漗悭㕥䪖⍎薵羗矻筁渔⎷ᯉ㨺㔚ⰶ㯍⋏婽ᬥ硻ᛆ䙠堀"

internal val SKELETON_NAMES_AR_KM: String =
    "005r拆瑃䁆ऄㆿ濘ᖀቔ品窎炅₄᱁㫙঄䠊㨠檛♍禲箌ぁ壓蓯⛎蟌ㄘ懡焙樱❒脃᧗茻䎁嘴摵爜⮈匣஦に卭≡聢灥碟肐ㅰ備䁊榬狑禁ᑣ䍵獙઒荩瞻藥腼藔䆅⟛懲␜፧ড়喼᱖菱⌯䷖ࡉ臹↋䐀"

internal val SKELETON_NAMES_AR_SS: String =
    "005r拆硃㡈ॄ⧟滬䍀㕸愇ᮽဇಁ๎₹₹ᶃ璄ৎ嬽①虘ཆ徲汧睲䟾䘕䬊ਸ䨳疊≷⣠ୠ玤爾珆僦㬁ᘍ侙⫙垴⦣䜅彋丣秉ㅰ窌呙㱫㔰哅⽡䁵烙᪵唧䓿虗忿ᴇ♓萹曉杊㖔斱埦畠䓐璾ᳲ୎៧⸵砄"

internal val SKELETON_NAMES_AR_TD: String =
    "005o拆塃塆ऄ㍹厴⎨㎸脔㝀琤ᰒ⡭擂橔Ꮣᰅ掼柭姂䡚૝旵澽⹿倬႑磥ᆄ㢽㕰ጢ㽴䍷জ䆶䛬呇墳笤㇔䋍孝ᡸ᪰⃰ⱼ愨㘬儛ጭ㵯⤓⁒溶Ἥᶲ捶甿腽䞾㔜荏磧䌓它摞橭本愝紶畳㒁溹㒙䡰"

internal val SKELETON_NAMES_AS: String =
    "00Af狈ᝂ䡆ᤈ㍹儦眛⣞椵縞⠗㱕ࢽ仈り጑䋙㪨嫁㈥䏊◆ⷙ㞬㠵䳷從糓ᢟ䠕合昐␀珘㷔㝮ࢹ橙⼇埠᯼ᮡⱚ᭿ࡋ⎙㣖劣恶໪㈒楗॥漎⸘Ἕ⏠䳅珹䋧⥦೭㛘⳰ΐ䣢キ瓢叇䄸⛝ᅔ╉㝻Ⰷ掫橃氿⑌腙椆ၧ耑苻䤆䴿䦔妣㹪壏㴌Ⴢ攑稼ᡍ纗䟭㧞杲䯵ᩊ娽綨奡䗐⣛俺ถ戄蔖久岟虭ເ"

internal val SKELETON_NAMES_ASA: String =
    "0039䛆ᡂ恆ॄ⭹匤⭙縄奰ㆂ煥笂㘈萌ᮉย媻藶緎杗䱻ູ␅䊙僜ᷥ愢筟聠࠘᭣户㺹䁉䎋徼䘗嬢㖦Ḇᢸ恃☧䜛ᄷ␇⿎㧛଍殎燇㶭⍞暛䔴⏤ฌ灍ᅶ䖮㖇ဟ⍿嬏"

internal val SKELETON_NAMES_AST: String =
    "004J囇ᛃ恆ऄ⭹卻␚෹噀ኁ蘀奧吩ᓤ᭥㭕刑屜ᣋ䣂怨ᨦ᳔㳯ⳑ汱␝抙䪙蔢䔧⠄࡟坦ᾊ์墐⑹窏䷜᫺泵汄䛒䩣ᶓ墏┕㒷᚞䢩䩘凵ᛔ䒕箥畁咥ぽ攃䶦䇓堠㘈ఫ瓕൫⍦ⴛ᤯ỳ䵏䄽㋤擗磲耀"

internal val SKELETON_NAMES_AZ: String =
    "0046䆖媥ྲྀ⨔䅷⯂䑈䇇ⴜ噎㧲㬽≒䌻↗呓䀟眉藾ৣ傀ṑ槩崏聊䫓内儗⇉滌楧磤⸐Ꮛ繢Ⲍ晈瞨哎㉤厒䶥Ⲝ璁儋嘱猦៯䣹嬤ᜦ෗妀緩榪艰劽䒇噃漡剳偧涫ີ蕪䦭㙉ፈ砑儎䑸缀ࠀ"

internal val SKELETON_NAMES_AZ_ARAB: String =
    "002E䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ଌ突⬹⡱噐ᩢ䭠䛤⁎䄏蒵㣖墭〵姈竒聸ࠀ"

internal val SKELETON_NAMES_AZ_ARAB_TR: String =
    "002E䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ଌ突⬹⡱噐ᩢ䭠䓤❲ᐧ蒵㣖墭〵姈竒聸ࠀ"

internal val SKELETON_NAMES_AZ_CYRL: String =
    "005R䆖媥ᥩ䳒沐㒱≘㉉ỉ䓳䇥䒙ಜ嗍᭘峈⾩刲ㄊ墄艮㰛橃⨅岢湾⴮⧯唪ଖ㫳ⴥ岹㡪䄿ᾒ厓及ᕵὶ㝬ぜᐺ联点慱慱恴㣡楷㙈涄㑬ຊ㞭⮋唰೑⻊磽凁綑⿩ᠵ緤曲᜹๓之ἡ㘷帪㈍紲搴ᙖ圫　"
