/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_LAG: String =
    "004A膖嘮䑜傫沤咯價匓ྗ笓媁㫄煡ㄤ戅穓࿗匲媒䄰晶㣻㍒墙屈╞ይ樨⡘寚Ꮦ巈⴪ሁ奠槵糁⮞ⴰ蕸Ứㄸ⊝吻扗啉ⷋ泤蛉ᓼ噾Ⱈ㣆ょ㢌偬㦒㖂㌇嵂加嵐ડ噃ὡ婯捖൪ᛕक़␎㕏嵆䠀"

internal val SKELETON_NAMES_LB: String =
    "003P䆖稓臒᜼婹㹈Ṙ唬ᴤ笤䙹嫼煜乎⸖࿊婳ㅉ᳙䎐ඈ稡⁛噈湤剁夲蒀㒿ᮟ厓腦筊涀༵▒೴竲䬼ૌ᠑䤴欘ᭈᆟᰌ⏊ઍ稁⭹⡉晃眡箒帚猕崆抹㘚ᜪ⣀䀀"

internal val SKELETON_NAMES_LG: String =
    "003f膖筒䆩岩㞙㴿₝ᰋḦ匊儥堯᪕㓋叉汼⵹䲬煢弬壹弳↞㕕ᰧᬒ慙䫌吢、㉱苪௼㪁ⳤ煢䙕沑哎渂⻸宋⇙哬艚⹒⼧羮੕㫒犆ᅈ▌㮀惆䃋੒஫ࢅ䢹㦄俞⦖碒徛㌕㴆犉㘚༬⻖଀"

internal val SKELETON_NAMES_LKT: String =
    "002Z䆖媥ཧ䮓䆏眓肉䇀煢イ抄㎟ป㞗凉蒳ྷ經⾛⷗௃ᴦ嬸⮌ᢓ臤匋℅岤湼䷎松䐰硢䜵Ἀ㨗舧筏縜㜼㔆甌௭ీቁ⯥আ䅀妜堸漨ᄱ⮰ⅲᓹ㵡庡㕐㶣僥嫰耀"

internal val SKELETON_NAMES_LLD: String =
    "0046ⶖ稓燒䲼湜咬宕呍ẗᩋ㩙㯛槕啡⒜㘥㊐兹爸䓍Ⲧ孱၀ᜨ穴㋇萅䅵蒡⩞㼴罸⿄弜㕎⺕籌穱肃姡㻜䪂ၸढ埊⢉ࢹ෌⾗ᭋൈᤪర䱹氽竕䭚䪺䴱ᮚ嘯〫㈍㵲㑼ᚊএᾐࠀ"

internal val SKELETON_NAMES_LN: String =
    "0063膕噯ฅ篕虱擿寠㚹桩㤨婚䨫包ঃ㏃൲䄠䑻ᩪ㼤穲亡₨〸⓲嬘蘹᪗਍૱府牶✤ᒅ泜煹糼晸ᢩ᭷䐫婩厞ᒝ囉৵穒⽧淤穅灩䵬䧭硛ᡘ५度㬓䅒萲㠛ᢜ双⑞䲥䲳⃄憙䓑Ɀ惖〗縵䤱⃈ໂό๟䩈杭㑕尛㈅䁸⒵⛌丂"

internal val SKELETON_NAMES_LN_AO: String =
    "0062膕噯ฅ篕虱擿寠㚹桩㤨婚䨫包ঃ㏃൲䄠䑻ᩪ㼤穲亡₨〸⓲嬘蘹᪗਍૱府牶✤ᒅ泜煹糼晸ᢩ᭷䐫婩厞ᒝ囉৵穒⽧淤穅灩䵬䧭硛ᡘ५度㬓䅒萲㠛ᢜ双⑞䲥䲳⃄憙䓑Ɀ惖〗縵䤱⃈ໂόྜ䪾畘嶨⍔൰耹㴽呬਀"

internal val SKELETON_NAMES_LO: String =
    "0061䊧廂恈࣋橍怜⥩ᝃ䑓岴౟ច㴤⡿ሞ䤑㈊⁕旦ⱳკ㰫㔿╤ℙ穄佼ⲃ蔒萮橅㘒┖⨃㈢㹶ᵶ夂୰ᤇ変౦莽ቴ⭏᭡䒪㞉䶼亡㴰蝉Ⓓ没෺塏召ೝ葌䠙萉熚ᅮ虋㞭Ḙᵬ災経囃崖᫷䖾ഭ螅ಭ幅娷ℸ㦵欌ᆛ熛膋嗷奴䐯┨羊蒯瘄⒅ᥦᏳ㨦"

internal val SKELETON_NAMES_LRC: String =
    "005Q拇ᑃ塈ऄ㍿卤伐舂ᷭ睡㛤ुᤋ㔉廃ᖑ䰂塞懾ṿ䆐䉪䤰惚湾㜦䜾䖛⌐柙䦞扶耂拝嶟䡙ᶘ⌁┸⑹⇿㮒廍否ጡ珚戼㱦ᩁ毖仌ᒷ⅁ᱯ㕟牝䨩ᅈ䭸䓦Ⴝ䬮᪼殳䵉ᘍ䄥员胵羌㩚⼍舌繬઴篹眠坨蜦蓑厎䈟玃砀"

internal val SKELETON_NAMES_LRC_IQ: String =
    "005P拇ᑃ塈ऄ㍿卤伐芑暂旈ઃ⨙亂煢朣စ棶坱篻撳䭄ᆉ䳒㯳膳䆳糴蘱྽জ幷ಊẃ皜ᠲ什ᎄ䥪╹ⅰ寉䭮眓ᆈ稝䐞䌳僨始ྲྀ♣䦽呷㕟獜檣ᅄ存㫶ઽ侪㦟ᤤ䐭⹟ሼᱤ蛷⨶㔧滸⸶繒綥纲䬾峺໻増ᛴ⟗ீ"

internal val SKELETON_NAMES_LT: String =
    "003x䋆竄㡦ࣄ⧚滬ో焂ᕤὌ蛈☶ࣇ竤榨䤡㳀蔡䁤磈䋡᮵壯⟭ᓆ歋ᘆ湮唘ᣓ濈嬋ᠸ↢䙢十᝘潬ᆉᇮ橣㯖菮啾禹勿㤷娧❊䴠嚹↷ᨆ忪慟㟢奏ㇾᓍଢ଼✵Ꮥ⍔䪥䭣爡蝱௵杪ࣩ䧨௑࣐䥀"

internal val SKELETON_NAMES_LU: String =
    "003U䫆᱂恈ࣄ⭼厰⭙縄祃倊椗尌岱慚瞥斡្旍艟⪟缠㳎⽒媧ῢඕᬡ㞠⻩঍撍䊶⦆ࣄ㮦券䁙㎺઴䟥狙㬈煹坮夵䴘戭憹ⰡᬾṐ纖᱿⊺敁᷻仃歉㝱䓃㔟ᣍ犏⚋櫦盡㟒៲痰ఀ"

internal val SKELETON_NAMES_LUO: String =
    "004G涥婳Ⅎ蒼䩢䙐Ṙ唬ᴤ卤入᳹㒜圬ຒヤᬋ቙᪼橬夫▒嗍ⴿ㵌੥ⅉ蒔湬␯姏ἀ㓼撱㤱ἢ呎湧㬒穹勌奐च棑Ჴ圼幚໳⡚ぇ๙碈㌼㬈漣翳芙洀橈樌ᣂᩣ᣷健⑤巆苅ⵁ暦㎆䧋况ႀࠀ"

internal val SKELETON_NAMES_LUY: String =
    "003s嚦呃恆ए摌命ंἰ䢨⦁ᴿ㰔罍⹁᳒䭕嵿⽓ᴁ㢸慮盋揉共᥌㼒ఛೆ圀ᣍ氤ࠦⲗ揠䩥绒稴羼⋟牑ᅰ缔栩簕帔彬䁺ொ䋛宓粅蝂中䗡᪲摉൵唑勖瀭瘏䆄⟕೦屳⊴䙮琐芳蕽舀"

internal val SKELETON_NAMES_LV: String =
    "004h囇㝃䁆ऄ㦿湰ᨄ⤙ᤵ帼⤫ᤙ㼫嚨堊㭸ࣔṠ⥇ᾷᑄ੊഍滮暧皧箐㑥ლℝ樐䔻涜䅹ᤀ堄䄵◳㚸⁋⽱彀⯥坟⚨䟱ᷤ臧䇵㞁姐㬵妲泟䙄㦘䔤䤨ᵖⶍ燓㪳䒱㬶咽弑ᅣᶚ࿲૎ࣕ妪惍⪜⿼ᱵ䟹菀က"
