/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_LONG_IA: String =
    "007B㛈Ể塨ࣄ㎸关ൈ噽ቝ⸒䡡㚨ஷ蓒⾣⃸哥偉缣෦唫搣㉥嗳艬瞂㨖䗴䳚㗝ࡸ壇奙ྟ䪗ধᲲ怤ᳰ仄㈾纅㵥荾ᔕざ₌蒑殡ᙡ〒腗吻⫼匑虑୏䎑腖㾸蒎₣汋ᖓ则庵浈䛚犕೩䙐毝暦聞啲喧杼嬻蘀"

internal val COMPACT_LONG_ID: String =
    "003J↚㐲䷹ᲂ疑峁⦑嗌沦ጤ书偀愎ᨱ䣄ሥ⪠ぴ侇ᰶ␢䋢㠓ᩖ吐ἧおṥᵈ礈ᬈ瞊娂匘࣊臵㋔傡圜堏笭倪⣡㶌ẪᑰḀ"

internal val COMPACT_LONG_IS: String =
    "006v㛨ᭂ恤ऀ㜄琒❁啿ᣃ婚㰅┘ᩯ䅗塝፮昬ᕘ瓈獸艾蟂ㅹ䛌∤ችᾅ哽ᗖ䖘Ή寵⃬儇瞵爬緂ቻ稖聱ැ蛦䱠₭坢緥䒃㢤ᇜ㌼ࡔ⥚挸懼⧝濶莳䎁ㄹ⺯㣖ᒘ䕝垒ଟ糵∄瘰㚳⌎ௗ嫙ॶ䒲〞珃䙶皟㍡生"

internal val COMPACT_LONG_IT: String =
    "004v㛇荂堄ࣄ㛻ᯐᤵ縥萘ᡐ䡩䄍糼礅旽孳苶ᮊ竳欶⵾姁䮈䔟భ䟤≺≓柂ㆊ⧸荍㸳桄㗓涃吂ẘ╒⯀ఘ帪㡵ℼ໠ㆈ箣䗽ᾂ⁤䍢ⶫ括ⶵ₨戥०ᤑ㏠"
