/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_RM: String =
    "0064㋨㩂㠆ऀ㚂䎛岚᪗摀ὶ᠐⸀祔⯙乚廦公撳⑬蟣ີ孬糫仜珱⧉ᆸᏧṦ呺㮊屌ᐩ渡䎏惟礠⢦䬸⎕䀑幐㦯幅᱌⭎࣎ࣾਧᣢ㉖⮍官ⵎ䅙ᅒ峝䰪ṿ䵎敜䮢俹幈珀⏺䝜䠐"

internal val COMPACT_SHORT_RO: String =
    "003S↚㐲䷹ᲂ疑峀票⠷ᮢ当玹甁ॴₑ堈ᬼ扐ㄊ๠竆㱥ᡤ擑બᖓ⊣∝嫖䐕ᬵ㾜᱙曛漆が嫤⵹滈⹂䨖ᰗ⤢ጤ⺐ⷘ氀"

internal val COMPACT_SHORT_ROOT: String =
    "002K↚㐲䷹ᲂ疑峁椮㬴䨹堏ౣ૴⹶䡠搇沘ᡊ⥲‬揎ょ፹浌ဵ眹↌᧕臃勦祟␅⧆㏧ಱ嘠砀"
