/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_LONG_LB: String =
    "004t㛨᫂堄ी㚄縑ᾠ䙖䥉戺䱀偐⪏⫏虥珹㴽㘗插崑ើẺⲥ⪜莧㏱壑⬞ൾ撈ᑖ㆙兢僒燐㉕檛テ睐ḹ婤猣膠洹㄂䨟䕽亟䇪⛃壤浞忞蜚憆蝢笈巗嵢䘌忙ᔸ"

internal val COMPACT_LONG_LLD: String =
    "004P㛇幂堆ࣄ⭸凪ᆭ⴮砰䴠楛Ⱝ㟞眶㷴䆏稘僞᷵祜瘁泮瓺⏍डᄑ吚Ẹ〛♌፯稹ᘢ撠䴇絶᢫件槨㉫⬤Ᏻ⃥⺸⊇┴⣈瑱䨋ⲯ坮脾莍⯷⋣㐣坨笋䩲᧟栀"

internal val COMPACT_LONG_LO: String =
    "004q↚㐲䷹ᲂ疑峁⣱㡫絁彶毽囩⦙娒ὄရ棂⡠兰ᨠ莳㷪棖⸲㗧㰆⌨෈婢䬳ᝃ刘泛♃盍塈哉੬␦㱅ᱮ㽾ᐚ窩ೀ浚垕Ⅳ䏎漁⧀蒕儔氌∎ࠀ"

internal val COMPACT_LONG_LT: String =
    "00Fz㛩廚恦ई㜌繠憃ዤ㖐⫌䊔庢⁛㤏ᡅ䊒✻૳㿃ペ㓉嗸䎈࿺磌䚼俛拷㏨㏻呿俥㻺⵪ⷬ⇁菄㾤㧎冽㙴瘟ㆁ䇩藼峅㮫㐩帹᭝亭䦍㾓湝➷᪎䂧䎎㽯僎刵㋱㿓㺛䘦炋⢲ፅ栂㥬᱀犥ࡕ⮂氝䉀හ䀬䧙⠀汛ञ⟏勝懇藷缮琹䣎⃙ㅰ俍濢煦ᩀ坟影䬂囂⠦㘹⸁甠䫙仢ᰞࡧᴆ脠⯀∌奾嗍䤋掲槪ኣ䇎ᾁ൛Ἀ瘛峼氅ⴾ♂悜喁恷ᐁ≏⯐✗猌ᤥ快ಈ㸇棨ᘨ৾綜獑㟒嬃䜺濕గ蒶提☀"

internal val COMPACT_LONG_LV: String =
    "008X㛈穃䁆ऄ㇝䵉ങ◅Ⰺ⣡ಡ䮉㷢箢ᑦ綤῱╱厗藭䇦㺟侲瓲ⅇ⣕巸蕝磥ട凟媢〈媂磨▤੤胈竰荄㬹割㎙夯㒶愀【浕્କᰙㆰ尀窤焤嶓蛽攷圜墀⒨箺䞐嶗唂碦榒䮛ᰏ怐紀囘௬㙆┼⯓䃪繳埕⫋㖋᜔▅埓涍姛予烽喓ᲀ䮩砸彳煩⟁筇ᄿࠀ"
