/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_TA: String =
    "0037↚㐲䷹ᲂ疑峁祠盕䦺蛹⦁昒ᮁಎ㦡୵臠䢱儗⨂ᤶ⫫ࢅ丈⺶撉儃㖮⩤䱖瞓℡㉗ࣺ⺈素梵䤁㐞ằ⨴ࡎ⨠ࠀ"

internal val COMPACT_SHORT_TE: String =
    "003Y↚㐲䷹ᲂ疑峁祠槍䦆蛹⦁昒ᮁಎ㦡଍膏挻ាฐ⋆桡᩟㪸೙੒੘梆▱荣㡜澂娏匘ᥕ䤒欔⍂氜沄Ⓣඬ᠀挡㶄⢕గ僵ࠀ"

internal val COMPACT_SHORT_TG: String =
    "004O↚㐲䷹ᲂ疑峀祩棂圅盋滋喊ᵵⒹ囐႗⡋呠愣䶧ඈⲢ緷䩞恜ᑤ別ढ㹂₇Ḱ⭌敚䙰曑㣒ਈ咑両⪦氳အ↢੨໠⣇㐹問ဨ䫝২⁂犊㸃簤ࠀ"

internal val COMPACT_SHORT_TI: String =
    "0034↚㐲䷹ᲂ疑峀祩桡箑ᙐ灷ࠄ渠⢘හ瞕↚ᦴ⡂䬄ᚭ兗␰兇殯ᙄ璁尋祌㇪䤀↲蔬撹䴝⹼勍પ䙊澉繑᥀ࠀ"

internal val COMPACT_SHORT_TK: String =
    "003G↚㐲䷹ᲂ疑峀票⠷宔ᥳ戂ૠᢹ刈ᨺ扐ㅊⳉ瓭჊⡙ᆊ൘ጬ㩆㰥ᝯᓽၱ汍兗䠢嬔ᶠ㢹儇⠈㳅ᛢ暞嘂犸虜䫉ᚨ暔ࠀ"

internal val COMPACT_SHORT_TO: String =
    "002H↚㐲䷹ᲂ疑峀ᤠ㬴䨹堏ౣ૴⹶䡠搇沘ᡊ⥲‬央㜇ዥ浌㡦捎๣┥㹰线⢭圂㣄㏧ಱ䤠ࠀ"

internal val COMPACT_SHORT_TR: String =
    "002r↚㐲䷹ᲂ疑峀祩䢷Ⱨ㰄⇐碡丈ᠸ我冓↚ᦔ䧼ㆲ൘␨㡇᰻泌倊㛒⬴㊷ゑ圌壩喓懣斑毃偘妟冒愢Თࢀࠀ"

internal val COMPACT_SHORT_TT: String =
    "003o↚㐲䷹ᲂ疑峀祩棂圅盋滋喂ᬻ⠠㙪䠈ᕠ䤃涷ᖀ⢦燵䭟⒡⃉➡ᴁᰣ蒕䣇ఁ⢩㖗卥乨⍑焣ᨪ怪㉦䭑ౙ᪇↫␊ၙ場䥢協ຐ䟀ࠀ"
