/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_MK: String =
    "004R↚㐲䷹ᲂ疑峀祩棂圅囋斗殄⋪䕷□堪➗䵊ং汸䨈崍㌆䶍㡑ᠬ㦤़ഖ⌠ᑇ్う⠢此䆐Ꮌᐦ氢硑ㆊ೸⁌沂㽤౥弝椻偔ॢ䤮䙂溍帉∈ࠀ"

internal val COMPACT_SHORT_MN: String =
    "004U↚㐲䷹ᲂ疑峀祩桢燢羢榢筥筥苁ឝ堐ἱ搘㨳刑ᑣ疇ᔋ䅲䭣␖⤛硄冪⠀夿Ὢක䔰寑䟑䞵㎮宗䦵栂䅓఑ⴅⳉࣤᥕ吔崆ᥧⴸⰫ䨑嘐∮⌯㹜㸋瓱盃瑄䠖沍゘᫉ᦩကࠀ"

internal val COMPACT_SHORT_MR: String =
    "004I↚㐲䷹ᲂ疑峀祩棁八৒苇䶍忛ତ䁲䭃吆ᨘ捐㩑昀兯则ᕐ成㫆౭㶟㌆Ⳋ榈䈹⦉䴋ㄆ⪃家㊆嶶ㅧ䴖㝺䀲⿔࿟ᬱ⠩䥄滈浓垶ፏ昌古✬㻈㓐㈑婖్㰇䣠ࠀ"

internal val COMPACT_SHORT_MS: String =
    "002K↚㐲䷹ᲂ疑峁椤㬴䨹堏ౣ૴⹶䡠搇沘ᡊ⥲‬揎ょ፹浌ဵ眹↌᧒臃勦礯␅⧆ⷧಱ嘠⠀"

internal val COMPACT_SHORT_MY: String =
    "0051↚㐲䷹ᲂ疓罣⧻㡡秐䥁壢毆況⦝夐啼坎い㋞⁰獘蓙⃳悰綰磃伨㸱歗ࠩ⅀ዀᄆ堍⧣䕨ࢭ䙔溍ẚ౉技䕒䰽ᆨ䕤᳉〩唖Ⲡ膚ቆ༗↣⒰᝱恎॓஋搡ᥰ๘଒ऀ"
