/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_EL: String =
    "004C↚㐲䷹ᲂ疑峀祩棜匹図滵䚺噘汫ഊ姅亰䂡櫓仳囸⡜皌㨆⫡शⰌ䦖ℤ坫⟚䒷ᖒ∠喁䷍⢦ᰲ祠⇂䨹廳薠⢙償琘峍ৢዔ〉㩋熎耀"

internal val COMPACT_SHORT_EN: String =
    "004H⛆ᛃ墦ऀ⍿჌凡聊徤仩䑡ⲅ⤁ྸ朥㶗㽶⽝⦝㽞翸䡉䶋濘㿃㈗嶈㲱煼瑇羕䕼奺ຟ忈䝩火猣秨ᒗ仒Ↄ࿌⚀惉៯ⴀ痁ᩫ娚怽䢸㷲䫂梞ᗘ嬋䠀"

internal val COMPACT_SHORT_EN_GB: String =
    "004T⛇幂怄ࣄ⭼働壮Ꮍ丐഑ॸ枵≫⏫癍㭀昝濦䷜縡㛽潷嬋穰ᰰ㉧↍䁮㡡二ຌ涨䪵䰗╢㉒毹ᐯ井偦㒜炲ᤥ冽癘૬㖳ᥕ⥚㨰⢨嫡⡋掾蘋♣蚀ࠀ"

internal val COMPACT_SHORT_EN_IN: String =
    "004b⛇᫃堄ऄ⍹农ࣿら᷋昃⩊膡ླྀ蘝嬏敻利₶⏴秂ᓺ庋泯Ὂ䶤㚈ᡁ璂禑ዎ⩚ᾶ⸓憷⬓㌹䴬曉禃僷㫳☀淙䘫⑫祌ⲝ緵穓窊藠⾕匯垾௺筧蚀䠀"

internal val COMPACT_SHORT_ES: String =
    "002/↚㐲䷹ᲂ疑峀票⠷⇳簀叧ᰴ◀橊䠢哰瀁ᇎぬ㩆爅䀦氜⼹㧂Ẩᛇᤵ⧟ᤳ⮙ἳ⧔䗥⹨紮煛☆憬忎ᅠ䥼⠠"

internal val COMPACT_SHORT_ES_419: String =
    "002v↚㐲䷹ᲂ疑峀票⠷⇳簀叧ᰴ◀橊䠢哰瀁ᇎぬ㩆爅䀦氜⼹㧂ẛ漢㩊㛋力ᡕ㯥済ኟ䒹儕⿖ㅤ䥗粕憢␐㞀ࠀ"

internal val COMPACT_SHORT_ES_MX: String =
    "002v↚㐲䷹ᲂ疑峀票⠷⇳簀叧ᰴ◀橊䠢哰瀁ᇎぬ㩆爅䀦氜⼹㧂㺛༢㩊㛋力ᡕ㯥済ኟ䒹儕⿖ㅤ䥗粕憢␐㞀ࠀ"

internal val COMPACT_SHORT_ES_US: String =
    "002v↚㐲䷹ᲂ疑峀票⠷⇳簀叧ᰴ◀橊䠢哰瀁ᇎぬ㩆爅䀦氜⼹㧂ẛ漢㩊㛳力ᡕ䗥済ኟ䒹儕⿖ㅤ䥗粕憢␐㞀ࠀ"

internal val COMPACT_SHORT_ET: String =
    "0037↚㐲䷹ᲂ疑峀票⠷ᮢ箴ਅ栁↌ሤ䂴塒剉凙甑剀䄓ሊ怒㑤乒㉍ၹ桅停䦾ᵄन㡃ᰧ楺仨缕㣰稖屗竤幈嵩砐ࠀ"

internal val COMPACT_SHORT_EU: String =
    "002f↚㐲䷹ᲂ疑専આ፼窆୤イత㦅ഌἹ氌仰䪰ᎂ䁇墀蒸帏ᾐ⇂瓳਄瞜峉ᑧ偖澁㹇㏧ಲ⬸௠ࠀ"
