/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_BA: String =
    "000u涤匲㩦笃⦑惄牧㾰剫泏纀మ乓㜮徔䝪琐Έ藥⿷䷗窎⓳穾䲿䒵晊眨㠀"

internal val NUMBER_SYMBOLS_BE: String =
    "000w涤匲㩦笃⦑惄牧㾰剫汏纀మ乓㜮徔䝪琐䟪Ṩ䗥㟷䧓窎◳穾䲿䒕晚眤㰀"

internal val NUMBER_SYMBOLS_BG: String =
    "000u涤匲㩦笃⦑惄牧㾰剫汏纀మ乓㜮徔䝪琐Έ藥⿷䷗窎⓳穾䲿䒵晊眤㠀"

internal val NUMBER_SYMBOLS_BGC: String =
    "001Aⶤ卒窏茇⻌ᚗḾ㑝肰䉲䣩㵳狅珫த㴏南❬᚛怺㝟ῗ僫䡘㎯ỗ势洜‷泩窯臃燲保䆒䝴枤回㕯ᨷ਀ࠀ"

internal val NUMBER_SYMBOLS_BRX: String =
    "000r涤匲㩦笃⦑惄牧㾰剫泵栬㷗卫浗窎ᔛ穵脗䒥䙁莮㩏皗粓揋㗤仠䠀"

internal val NUMBER_SYMBOLS_BS: String =
    "000u涤匲㩦笃⦑惄牧㾰剫汵桬㷗卫浗窎ᔛ稏敝愗䒡蓱䏾壇⚼㟑⿯ặ兛椈ࠀ"
