/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_AF: String =
    "000u涤匲㩦笃⦑惄牧㾰剫汏纀మ乓㜮徔䝪琐Έ藥⿷䷗窎⓳穾䲿䒵晊眨㠀"

internal val NUMBER_SYMBOLS_AM: String =
    "001U涤匲㩦笃⦑惄牧㾰剫泵栬㷗卫浗窎ᔛ穵脗䒡糹䏾壅⟼槧䥃潣⧯䅣罢槭妃䮎彃均⧧㮡羷㠗浴弼繌䝬᝽搼編䓭緋㗥廲ୀ⠀"

internal val NUMBER_SYMBOLS_AR: String =
    "001H涤匲㩦笃⦑惄牧㾰剫泵格㱰班炁శ䲨घ氷䰋穾腓藢緹⮎䓹ᗖ痎痝䯣⬆⌚㾛㽛㾻ῖ᷍竖脫䐠ࠀ"

internal val NUMBER_SYMBOLS_AR_BH: String =
    "001TỢ㑃㡀ࠄ⺊䶸ࢆ䧋⌘⢀爂೑࠽䩀⠠ॅᗡব悟敤唅ৠ晽争尴昴♔制䜆ᵭ膈翟㫘ᙢ∴必ᅕ智玹糏ᶸ炼➕㯙ᎏ⎩୼㍒搁ࠀ"

internal val NUMBER_SYMBOLS_AR_DZ: String =
    "001H涤匲㩦笃⦑惄牧㾰剫汵桼㱰班炁శ䲨घ氷䰋穾腓藢緹⮎䓹ᗖ痎痝䯣⬆⌚㾛㽛㾻ῖ᷍竖脫䐠ࠀ"

internal val NUMBER_SYMBOLS_AS: String =
    "001Aⶥ㭒端茇滌ភḾ㑟肰䙲䣹㵳狅菫௤㴏南杬ល怾㝟ῗ僫䡘㎯ỗ势洜‷泩窯臃燲保䆒䝴枤回㕯ᨷ਀ࠀ"

internal val NUMBER_SYMBOLS_AST: String =
    "000r涤匲㩦笃⦑惄牧㾰剫汵桬㷗卫浗窎ᔛ穵脗䒡糹䏾壅➽坅眭㾒揂ࠀ"

internal val NUMBER_SYMBOLS_AZ: String =
    "000s涤匲㩦笃⦑惄牧㾰剫汵桬㷗卫浗窎ᔛ穵脗䒡糹䏾壅➼㟑⿯ặ兛椀ࠀ"

internal val NUMBER_SYMBOLS_AZ_ARAB: String =
    "001Qⶖ᪓ᅕ媉ᗽ羇疍掛㼷瞯䒾畭曛䆾蝻毶⽼滪蒭苨ᒔ䑫糩घ⨵棺᭵䙆莦㍟ᨿ☎牜၃儙㯾峁➾㟐⽿㧛㜥㾄᠀"
