/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_DA: String =
    "000s涤匲㩦笃⦑惄牧㾰剫汵桬㷗卫浗窎ᔛ穵脗䒡糹䏾壅➼㟑⿯ຊᔡࠀ"

internal val NUMBER_SYMBOLS_DE: String =
    "000u涤匲㩦笃⦑惄牧㾰剫汵桬㷗卫浗窎ᔛ稏敝愗䒡蛑䏾壇⚼㟑⿯ặ兛椈ࠀ"

internal val NUMBER_SYMBOLS_DE_AT: String =
    "000v涤匲㩦笃⦑惄牧㾰剫汏纀ಎ乏㜩得㏊➵㸈⟵ጴ⛲忻⣭腇᛹脿⩟晊眭㾐∂"

internal val NUMBER_SYMBOLS_DE_CH: String =
    "000u涤匲㩦笃⦑惄牧㾰剫法棬㷗卫浗窎ᔛ稏敝愗䒡蛑䏾壇⚼㟑⿯ặ兛椈ࠀ"

internal val NUMBER_SYMBOLS_DZ: String =
    "001hễዄ塀ঀ㱿傖ⴞ↪㬗€穣恫ᓊ⡨኿怘᧹蝅䷶㘴倦⋁勯篭ᬋ垸歆螈ᵿ樛柱ज़虪᲼礰幤御㳫挩煳ረ蒟䨯㸭䡾ᨧ夒爈纴䟪手⪺ㇸ"
