// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_MAI: String =
    "\u001Fजन॰\u001Eफर॰\u001Eमार्च\u001Eअप्रैल\u001Eमई\u001Eजून\u001Eजुल॰\u001Eअग॰\u001Eसित॰\u001Eअक्तू॰\u001Eनव॰\u001Eदिस॰\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_MI: String =
    "Hānuere\u001EPēpuere\u001EMāehe\u001EĀperira\u001EMei\u001EHune\u001EHūrae\u001EĀkuhata\u001EHepetema\u001EOketopa\u001ENoema\u001ETīhema\u001F\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_ML: String =
    "\u001F\u001F\u001Fതിങ്കളാഴ്‌ച\u001Eചൊവ്വാഴ്‌ച\u001Eബുധനാഴ്‌ച\u001Eവ്യാഴാഴ്‌ച\u001Eവെള്ളിയാഴ്‌ച\u001Eശനിയാഴ്‌ച\u001Eഞായറാഴ്‌ച\u001F\u001Fതി\u001Eചൊ\u001Eബു\u001Eവ്യാ\u001Eവെ\u001Eശ\u001Eഞാ\u001F0"

internal val LOCALE_STANDALONE_MN: String =
    "Нэгдүгээр сар\u001EХоёрдугаар сар\u001EГуравдугаар сар\u001EДөрөвдүгээр сар\u001EТавдугаар сар\u001EЗургаадугаар сар\u001EДолоодугаар сар\u001EНаймдугаар сар\u001EЕсдүгээр сар\u001EАравдугаар сар\u001EАрван нэгдүгээр сар\u001EАрван хоёрдугаар сар\u001F\u001F\u001FДаваа\u001EМягмар\u001EЛхагва\u001EПүрэв\u001EБаасан\u001EБямба\u001EНям\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_MNI: String =
    "জানুৱারি\u001Eফেব্রুৱারি\u001Eমার্চ\u001Eএপ্রিল\u001Eমে\u001Eজুন\u001Eজুলাই\u001Eওগষ্ট\u001Eসেপ্টেম্বর\u001Eওক্টোবর\u001Eনবেম্বর\u001Eডিসেম্বর\u001Fজানু\u001Eফেব্রু\u001Eমার\u001Eএপ্রি\u001Eমে\u001Eজুন\u001Eজুলা\u001Eআগ\u001Eসেপ্ট\u001Eওক্টো\u001Eনভে\u001Eডিসে\u001Fজা\u001Eফে\u001Eমার\u001Eএপ\u001Eমে\u001Eজুন\u001Eজুল\u001Eআ\u001Eসে\u001Eও\u001Eনব\u001Eডি\u001F\u001F\u001Fনিং\u001Eলৈ\u001Eয়ুম\u001Eশগ\u001Eইরা\u001Eথাং\u001Eনো\u001F0"

internal val LOCALE_STANDALONE_MN_MONG_MN: String =
    "\u001F1 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E2 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E3᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E4 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E5 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E6 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E7 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E8 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E9 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E10 ᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E11᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001E12᠊ᠷ ᠰᠠᠷ᠎ᠠ\u001F\u001F\u001Fᠳᠠ\u001Eᠮᠢᠭ\u001Eᡀᠠ\u001Eᠫᠦᠷ\u001Eᠪᠠ\u001Eᠪᠢᠮ\u001Eᠨᠢ\u001Fᠳᠠ\u001Eᠮᠢᠭ\u001Eᡀᠠ\u001Eᠫᠥᠷ\u001Eᠪᠠ\u001Eᠪᠢᠮ\u001Eᠨᠢ\u001F0"

internal val LOCALE_STANDALONE_MT: String =
    "\u001F\u001FJn\u001EFr\u001EMz\u001EAp\u001EMj\u001EĠn\u001ELj\u001EAw\u001ESt\u001EOb\u001ENv\u001EDċ\u001F\u001F\u001FTn\u001ETl\u001EEr\u001EĦm\u001EĠm\u001ESb\u001EĦd\u001F0"

internal val LOCALE_STANDALONE_MYV: String =
    "\u001Fякш\u001Eдав\u001Eэйз\u001Eчад\u001Eпан\u001Eашт\u001Eмед\u001Eума\u001Eташ\u001Eожо\u001Eсун\u001Eаца\u001F\u001Fатяньчи\u001Eвастаньчи\u001Eкуншкачи\u001Eкалоньчи\u001Eсюконьчи\u001Eшлямочи\u001Eтаргочи\u001F\u001F\u001F0"
