/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_TK: String =
    "Ýanwar\u001EFewral\u001EMart\u001EAprel\u001EMaý\u001EIýun\u001EIýul\u001EAwgust\u001ESentýabr\u001EOktýabr\u001ENoýabr\u001EDekabr\u001FÝan\u001EFew\u001EMar\u001EApr\u001EMaý\u001EIýun\u001EIýul\u001EAwg\u001ESen\u001EOkt\u001ENoý\u001EDek\u001F\u001FDuşenbe\u001ESişenbe\u001EÇarşenbe\u001EPenşenbe\u001EAnna\u001EŞenbe\u001EÝekşenbe\u001FDuş\u001ESiş\u001EÇar\u001EPen\u001EAnn\u001EŞen\u001EÝek\u001F\u001F100"

internal val LOCALE_STANDALONE_TO: String =
    "Sānuali\u001EFēpueli\u001EMaʻasi\u001EʻEpeleli\u001EMē\u001ESune\u001ESiulai\u001EʻAokosi\u001ESepitema\u001EʻOkatopa\u001ENōvema\u001ETīsema\u001F\u001F\u001F\u001F\u001F\u001F0"
