/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_KAA: String =
    "Январь\u001EФевраль\u001EМарт\u001EАпрель\u001EМай\u001EИюнь\u001EИюль\u001EАвгуст\u001EСентябрь\u001EОктябрь\u001EНоябрь\u001EДекабрь\u001FЯнв\u001EФев\u001EМар\u001EАпр\u001EМай\u001EИюн\u001EИюл\u001EАвг\u001EСен\u001EОкт\u001EНоя\u001EДек\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KGP: String =
    "\u001F\u001F\u001F\u001F\u001F\u001Fc3f0"

internal val LOCALE_STANDALONE_KK: String =
    "Қаңтар\u001EАқпан\u001EНаурыз\u001EСәуір\u001EМамыр\u001EМаусым\u001EШілде\u001EТамыз\u001EҚыркүйек\u001EҚазан\u001EҚараша\u001EЖелтоқсан\u001F\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KL: String =
    "januaari\u001Efebruaari\u001Emarsi\u001Eapriili\u001Emaaji\u001Ejuuni\u001Ejuuli\u001Eaggusti\u001Eseptembari\u001Eoktobari\u001Enovembari\u001Edecembari\u001F\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KM: String =
    "\u001F\u001F\u001Fចន្ទ\u001Eអង្គារ\u001Eពុធ\u001Eព្រហស្បតិ៍\u001Eសុក្រ\u001Eសៅរ៍\u001Eអាទិត្យ\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KOK: String =
    "\u001Fजाने\u001Eफेब्रु\u001Eमार्च\u001Eएप्री\u001Eमे\u001Eजून\u001Eजुल\u001Eऑग\u001Eसप्टें\u001Eऑक्टो\u001Eनोव्हें\u001Eडिसे\u001F\u001F\u001F\u001Fसो\u001Eमं\u001Eबु\u001Eब\u001Eशु\u001Eशे\u001Eआ\u001F0"

internal val LOCALE_STANDALONE_KS: String =
    "جنؤری\u001Eفرؤری\u001Eمارٕچ\u001Eاپریل\u001Eمئی\u001Eجوٗن\u001Eجوٗلایی\u001Eاگست\u001Eستمبر\u001Eاکتوٗبر\u001Eنومبر\u001Eدسمبر\u001Fجنؤری\u001Eفرؤری\u001Eمارٕچ\u001Eاپریل\u001Eمئی\u001Eجوٗن\u001Eجوٗلایی\u001Eاگست\u001Eستمبر\u001Eاکتوٗبر\u001Eنومبر\u001Eدسمبر\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KSH: String =
    "\u001FJan.\u001EFäb.\u001EMäz.\u001EApr.\u001EMai\u001EJun.\u001EJul.\u001EOuj.\u001ESäp.\u001EOkt.\u001ENov.\u001EDez.\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_KS_DEVA: String =
    "जनवरी\u001Eफ़रवरी\u001Eमार्च\u001Eअप्रैल\u001Eमई\u001Eजून\u001Eजुलाई\u001Eअगस्त\u001Eसतुंबर\u001Eअकतुम्बर\u001Eनवूमबर\u001Eदसूमबर\u001Fजनवरी\u001Eफ़रवरी\u001Eमार्च\u001Eअप्रैल\u001Eमई\u001Eजून\u001Eजुलाई\u001Eअगस्त\u001Eसतुंबर\u001Eअकतुम्बर\u001Eनवूमबर\u001Eदसमबर\u001F\u001Fचंदिरवार\u001Eबुवार\u001Eबोदवार\u001Eब्रेसवार\u001Eजुम्मा\u001Eबटवार\u001Eआथवार\u001Fचंदिरवार\u001Eबुवार\u001Eबोदवार\u001Eब्रेसवार\u001Eजुम्मा\u001Eबटवार\u001Eआथवार\u001F\u001F0"
