// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_XH: String =
    "Janyuwari\u001EFebruwari\u001EMatshi\u001EEpreli\u001EMeyi\u001EJuni\u001EJulayi\u001EAgasti\u001ESeptemba\u001EOkthoba\u001ENovemba\u001EDisemba\u001FJan\u001EFeb\u001EMat\u001EEpr\u001EMey\u001EJun\u001EJul\u001EAga\u001ESep\u001EOkt\u001ENov\u001EDis\u001F\u001F\u001FMvu\u001EBin\u001ETha\u001ESin\u001EHla\u001EMgq\u001ECaw\u001FMv\u001ESb\u001ESt\u001ESin\u001EHl\u001EMg\u001EC\u001F0"
