// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_PCM: String =
    "\u001FJén\u001EFẹ́b\u001EMach\u001EÉpr\u001EMee\u001EJun\u001EJul\u001EỌ́gọ\u001ESẹp\u001EỌkt\u001ENọv\u001EDis\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_PL: String =
    "styczeń\u001Eluty\u001Emarzec\u001Ekwiecień\u001Emaj\u001Eczerwiec\u001Elipiec\u001Esierpień\u001Ewrzesień\u001Epaździernik\u001Elistopad\u001Egrudzień\u001F\u001FS\u001EL\u001EM\u001EK\u001EM\u001EC\u001EL\u001ES\u001EW\u001EP\u001EL\u001EG\u001F\u001F\u001FP\u001EW\u001EŚ\u001EC\u001EP\u001ES\u001EN\u001Fc055"

internal val LOCALE_STANDALONE_PS: String =
    "جنوري\u001Eفېبروري\u001Eمارچ\u001Eاپریل\u001Eمۍ\u001Eجون\u001Eجولای\u001Eاګست\u001Eسپتمبر\u001Eاکتوبر\u001Eنومبر\u001Eدسمبر\u001Fجنوري\u001Eفبروري\u001Eمارچ\u001Eاپریل\u001Eمۍ\u001Eجون\u001Eجولای\u001Eاګست\u001Eسپتمبر\u001Eاکتوبر\u001Eنومبر\u001Eدسمبر\u001Fج\u001Eف\u001E3\u001E4\u001E5\u001E6\u001E7\u001E8\u001E9\u001E10\u001E11\u001E12\u001F\u001F\u001F\u001F0"
