/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.durations.internal.data

internal val DURATION_UNITS_JA: String =
    "00edweg\u0011W\u0009a\u0015D\u0014}.\u001A\u000Eq\u0016xy\u001D\u000A\u001293E#-\u0002YCRiQ)*\u0009R;\u0015!E#\u0002a]\u0001LSS>\u0003d5Fm\u0011S#6z\u001Ab|~y8U\u0008\u0003\u0018/z\u007F\u001B+|TX>.\"\u0012\u0013\u0007\u001B^9/^\u00119UC g\u0003\u0005!G\u00184\u0017qWG_F\u0007-Pax\u0013\u0011e\u001BwE#\u0013@+4\u0015S\u0007\u000BQ&l4ki!e-}X\u0019\u000A:{-Sv\u0009H\u0009qy?KH\u001B\u000Bz\u001Cv\u001C\u0009\u001F\u00044\u001CZ \u001Bb\u0003k\u0013~\u0011X,X\u000C@\u0008>\u0012ZQoo\u0004GOG?7jWg9NZ\u000Bbck\u0013}QGFhq|}+-\u0012)&\u00099M5|tU H\u0006\u0016swo|TV\u0015wWa/yh\u0004[kn_[\\%WU\u0015TWWd1F8\u0016\u0015\u0007\u0014\u001B\u001C>(19\u0012+\u0013L\u000DJ\u000AB\u0011tq"

internal val DURATION_UNITS_JGO: String =
    "00UC&fVT6\"+Id\u0014z+.\u0012\u0005Y\u00135\u000F*+\u0016AgS|\u001B\u001FxT%XzoCY\u0002sQ\u0009\u001A#%C[^1\u0003iUr\u000A}T\u0018NhAw8\u0014\u0015\u0017Oh\u000CJde)a<\u000Cb)J\u0015UXP\u0004\u0003so\u001A KS\u000A\u0009\"eY\u0007':\u0014ZtwI\u0013u\u000F%K\u0001Y^R9_4\u001FIaKc\u0011ML\u0018\u0001m(\u001D3\u0011z=\u00190\u0013\u0012I?^(\u000CGr\u0019i\u0005\u0009>\u001D\u0016j\u0018QC-&\u001A\u0002+\u000FH)\u000D\u0010f\u001A9.C\u0011#s4^Y\u000ED\u0013!3}U\u000Db\u0009Rz37E~\u001AqJ\u001A%EfuKzeE%uHQ\u000C\u0009Ff9*\u0016ndRR\u0013\u000Et/#\u001B'\u001D\u0009F\u0001\u0001"

internal val DURATION_UNITS_JV: String =
    "00cvwek\u0011W\u0009a\u000DD\u0014m0!\"=*J\u0009\\WarWe\u0008yZTe\u000EP36N~.]iTDQT~\u007F\u0002/Cq1a>\u0018\u001Bv@wU\u000C9\u0007BH\u0008Wrh\u0003\u0017\u007F,f%!=\u00090\u000E\u0011^a'um)\u0019KO >A\u0009\u007F{N\u000A\\\u0011\u000D7UM.\u001Dma\u0006A}`)\u0017u\u0004\u0004~\u001A9g\u001C+;\u001D%]HA\u000Dn^\u0009\u000D=\u00183\u0014!\u0012NJm[0Cw\u0003/\u00104\u0011hl5\u000FIc\u0006\u0002k|h<\u001D5s\u0017321:\u0013q}cMd\u0003.`\u00094\u000BKSs\u000E<,[[Y\u0015F!{+\u0011T\u0015\u0007\u000FJ\u001CK1\u0009B\u0006u\"\u0012\"K3\$sx[\u000By+gc0[\u0010\u0016>,KE}SJ:q"
