/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.durations.internal.data

internal val DURATION_UNITS_OC: String =
    "00TvweL1w\u0009A\u0011#V}/AL9\u0013\u0001UV'\u000B!\u0003DE\u001D-{w\u0005l\u000A'0e~\u001E\u001C#\u0010~]~c-\u0008a;~\u001D\u0008t{;5(\u000D\u0013nU\u000B\u000B\u001C>,&B&\u0009g+af\u000E\u0010?\u0011%}a8hUukC^>\u000C&Z\u00176?bn8F\u0014]>Cz\u0005E\u0003/\u0002ct^dKD\$Fo[c\u000DYh:9N|f=snVmi\u007F#yn\u0009=\u0007@g|\u000E#a&s?U\u000C\u000A%\u0016#E<v8(6VWmSsYC\u0005T'y(RWm\u000AgW{^]Xx,sXY\u000D"

internal val DURATION_UNITS_OR: String =
    "01J7wfy\u0015w\u000Da\u000DD(qIc B\u001E\u0006\u0012og\u0002\u001F\u000A\u0011<;q\u001Fkc\u0014\\C'\u0001e\u00129\u0005\u000F7%uoq8m\u000D\u000C\u0014i/\u0012\u001C\\\u0003N\u001A^^\u0011J!/9Y|\u000D`*LTIPC\u00171#3\u00031\u000FIVD\u0001u?\u001DO84m6RE&P\u0007'Oft\u0006F,Z\u0008\u00033C(C\u001C6|Ahrjy\u0012_3/Tjm1*38\u0009S~Tez\u001CjPl1J?M3!:%9J}\u001C\\sJ\u0002\u000AOtP\u00101X\u0005\u000CKsD7j5\u000B\u001F]\u00077^][o\\m`\u001Eg31:2U\u000Df|^nG\u0008\u0018_2\u0006\$=q\u0014\u00028``K=\u0013DQ\u001D9a\u001F~GJmG4e.\"\u0014T\u000D@U|\u000Bl\u0010DiN\u0014e1)\u0008\u007F\u001157P8KIn})\u0017\u0017v2\u0018\u000C6isf=3rXx\u0014\u001B`1m\$wbN\u000CH3O>\u001F\u000454=y#\\6\u0003BV/y\u000DcoW\u0013qr\u0009\u0008\u000F[M-\u000EAN\u0001\u0007\u000A\u0002c!9Lo\u0017}|g\u000Br^Z85DY\u0011W-VR3\u000D\u0011;T@\u0006Ez44\u0004\u0002@\u0001er6?V*\u0016C\u001D!\u000BG\u000DW\u00036\u0017E\u001BJ\u001BG\u000C7\u0002L{O\u000E%J\u000D\u0001RRfP\u0011\u0001F\u001Fe:\u0002M\$m\u0003*~\u000EO@=\u0009\u001E\u0008G/9m"

internal val DURATION_UNITS_OS: String =
    "00b8wUlQU\u000A\u0001\u0011 \u0013,3=D]e)P&\u000A%\u000A\u0011\u0005-~\u0013-\u007FwH!u\u0002~QBF\u0007\u001868,W\u001EFNTB\u0009_\u000D\u000C>N?8\u001Bj)gw28\u0014l,1f4(\u0016mb*\u000F\u00056w\u000D#g\"%a#[\u000DFEIgh! E]N\u00051\u001C\u0013v\u0003Rm_s!\u000FB5b\u001F3\u0008I\u0008aC\u0013tG\u001D2'9o\u0004!.N\u000E\u0013\u001B\u000FE\u0006^\u00149\u0007h%&:Z\u001D\u000CEN\u0003]a|ny`)\u001CMqb\u000E2dBPg?-7\"%2\u000CCWE.RKx'?\u000DV\u001C|\\]'\u0005Sj4\u001DE\"-bK|Be\u007Fjd~\"cL1+>Ly&oBR\u001059+it\u0014\u0017\u0006<\u0013-FR\u0005eX\u0014\u000A9.\u001C|>[I_\u001A\u001CUFR[\u0011EPx\u0007F=G\u001A#k\u001CJ\u001D0\u0003#?_\u0007_\u0007`\u0008Zq@}\u000D"

internal val DURATION_UNITS_OSA: String =
    "00X9&fVT6\"+Id\u0014z+.\u0012\u0005Y\u00135\u000F*+\u0016Ag\u0013T_-\u001D\u0014\u0013N!0\u0001)D\u001D\u0004r\u000A\u0009\u0014k\u0009\u0003*\u0013\u0016L\u0011\u0017B8\u0009Pf:=o=\u00064:\u001D\u00135\u000A\u00096\u0002=}<\u0002C\u0006e\u0015MX!,6\u001Dy\u001BW+dS@bBDS(%\u000E)\"yB_\u0008*3}\u0004\u0015m\u0001y\\\u0016\u000DD\u000BbJ\u0015c#\u0004~\u001CA&\u0019d3}_.\u001AP\u0015\u0001*:\u0017'&LA\u0002\u000CQ3y%\u001Bv#i\u0019\u0009\u000C\u0009\\Ip\u0007Fy\u0005V9\u0001KX\u0002\u0018\u000A\u000A:o\u0014\u000E\u0007\u0001N\u0013\$\u000Dm\"\u00172<\u0012\u0003{U\u00125\u000D\\\u001E\u0018\u0016bEjD\u000By%)ZQ\u0011\$^\u0007#.LC{\u0015=QKx8\u0004aEM\u0009[\u0018\u0004y#%+%P\u0010/\u0008A2\u001BT\u0019Qq\u0005O\u000Dq\u0007'Et\u0001cPR\u0016v\u000DJ\u0015w\u000A\u0002\u001Be\u0006\u000C\$elKGJ8\u0012\u0005tI\u0001"
