// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.plurals

import dev.carcara.kotlinx.locale.Locale
import dev.carcara.kotlinx.locale.currency.Currency
import dev.carcara.kotlinx.locale.currency.CurrencyAmount
import dev.carcara.kotlinx.locale.currency.cldr.plurals.internal.data.currencyPluralNamesRegistry
import dev.carcara.kotlinx.locale.currency.cldr.runtime.CurrencyPluralNameSource
import dev.carcara.kotlinx.locale.currency.cldr.runtime.PayloadCurrencyPluralNames
import dev.carcara.kotlinx.locale.currency.cldr.runtime.formatPluralName
import dev.carcara.kotlinx.locale.currency.cldr.runtime.pluralName
import dev.carcara.kotlinx.locale.currency.code
import dev.carcara.kotlinx.locale.number.NumberGrouping
import dev.carcara.kotlinx.locale.number.PluralType
import dev.carcara.kotlinx.locale.number.SignDisplay
import dev.carcara.kotlinx.locale.number.pluralCategory

/**
 * The currency names in words this build carries.
 *
 * The fallback chain and the pattern substitution live in
 * `kotlinx-locale-currency-cldr-runtime`; all this object contributes is the
 * table, the count-less names it falls back to, and the plural rules that
 * choose between the forms.
 */
public object CldrCurrencyPlurals : CurrencyPluralNameSource by PayloadCurrencyPluralNames(
    currencyPluralNamesRegistry,
    dev.carcara.kotlinx.locale.currency.cldr.CldrCurrency,
    dev.carcara.kotlinx.locale.number.cldr.CldrNumberPlurals,
)

/**
 * [this] written for [locale] with the currency named in words.
 *
 * ```
 * CurrencyAmount(Currency.USD, 2_00).formatPluralName()            // "2.00 US dollars"
 * CurrencyAmount(Currency.USD, 2_00).formatPluralName(cs)          // "2,00 amerického dolaru"
 * CurrencyAmount(Currency.HUF, 1_00).formatPluralName(hu)          // "1 magyar forint"
 * ```
 *
 * The number is written the way [locale] writes any number, which is not
 * always the way it writes money: Malayalam groups `12,34,567.89 യു.എസ്. ഡോളർ`
 * where the symbol form groups in threes. Only the decimal and group
 * separators stay the currency pair, and ICU does the same.
 *
 * The form the name takes is chosen from the digits that come out rather than
 * from the amount, so [fractionDigits] changes it: at CLDR's two digits a
 * dollar reads `1.00 US dollars`, and at none it reads `1 US dollar`. Both are
 * plural names in CLDR's sense of the word, which is the form the plural rules
 * select rather than the form for more than one.
 *
 * [signDisplay] decides whether a sign appears. Its accounting values do not
 * bring parentheses with them here, because those live in CLDR's accounting
 * currency pattern and this form does not use a currency pattern at all.
 * [cash] applies CLDR's cash fraction digits and cash rounding.
 */
public fun CurrencyAmount.formatPluralName(
    locale: Locale = Locale.current,
    signDisplay: SignDisplay = SignDisplay.AUTO,
    cash: Boolean = false,
    fractionDigits: Int? = null,
    grouping: NumberGrouping = NumberGrouping.AUTO,
): String = CldrCurrencyPlurals.formatPluralName(this, locale, signDisplay, cash, fractionDigits, grouping)

/**
 * The name [locale] gives this currency beside a count of [count]: `US dollar`
 * for 1 and `US dollars` for 2. Falls back to the ISO code.
 *
 * A whole count, because that is where the answer is a property of the number
 * alone. A printed `1.00` takes a different form from a printed `1` in much of
 * Europe, and [formatPluralName] is the call that knows which is about to be
 * written.
 */
public fun Currency.pluralName(count: Long, locale: Locale = Locale.current): String = CldrCurrencyPlurals.pluralName(
    this,
    dev.carcara.kotlinx.locale.number.cldr.CldrNumberPlurals.pluralCategory(count, locale, PluralType.CARDINAL),
    locale,
)
