/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.internal.data

internal val CURRENCY_FORMATS_AB: String =
    "001A↘ᔌ仆᭓▽䩓㜧弁㦮晐蜨㲰祪䭙⪬㻐↘Ⱑ渡櫓䶠᫜ "

internal val CURRENCY_FORMATS_AF: String =
    "001a↘ᔌ仆᭓▽䩓㜢䞴ࠡ䈲䭹⧵崕㪎惙⡧㠀ℇ卐ᑈᆍ㳔⣘唔⪐แᇢ㠀"

internal val CURRENCY_FORMATS_AGQ: String =
    "0014↘ᔌ仆᭓▽䩓㜢䞴ࠡ䈲䭹⪾慁㑯堲“㔡Ⰲ⠀"

internal val CURRENCY_FORMATS_AK: String =
    "001Y↘ᔌ仆᭓▽䩓㜧弁㦮晐蜨㲹⮬婔⏨ᐌ䡦ᣂ稇ଊ㶨∊挓⨈ᩁ耚⡀ࠀ"

internal val CURRENCY_FORMATS_AN: String =
    "001P↘ᔌ仆᭓▽䩓㜧弁㦮晐蜨㲰祪䭙⪬㻐↘Ⱑ渡櫓䶠ᥔᔲ殭䣦㳁ࠀ"

internal val CURRENCY_FORMATS_AR: String =
    "002N↘ᔌ仆᭓▽䩓㜧弁禣䭟㽞つ൒蕥ᚳ慀濠䀴ᡈ㲺氋祵倃䨊㽦⡜竫າྙ婇刭⣉ॼ満ࠀ"

internal val CURRENCY_FORMATS_AR_BH: String =
    "0022旜耹恓䂶祵苧凍媛涷Ꭿ缼㙤忌皯募㚁儛膺⅃䒣荗⥟㒢帶瀙后ẜᔁᡧ舴竡瘒㶆愧䳖㗀ᦢ沁䘦ࠀ"

internal val CURRENCY_FORMATS_AR_DZ: String =
    "002N↘ᔌ仆᭓▽䩓㜣弃禣䭟㽞つ൒蕥ᚳ慀濠䀴ᡈ㲺氋祵倃䨊㽦⡜竫າྙ婇刭⣉ॼ満ࠀ"

internal val CURRENCY_FORMATS_AS: String =
    "001+䗘✶㡼撱腢蟅䧳切涫坖῟㐟ᦨ䙚曻㡼盁腺蒾晇㘂楟䒡蛐儡䫥ᚲ䰜䨆䜀ࠖ⟆扫ᠬຼ⚦ঐ⩸吀"

internal val CURRENCY_FORMATS_ASA: String =
    "001A↘ᔌ仆᭓▽䩓㜧弁㦮晐眬姖㌨ᓴ༆䬋༖偤䡠ࠀ"

internal val CURRENCY_FORMATS_AST: String =
    "001A↘ᔌ仆᭓▽䩓㜣弃㦮晐眬姖㌨ᓴ༆䬋༖偤䡠ࠀ"

internal val CURRENCY_FORMATS_AZ_ARAB: String =
    "001U旞聽惛䆶筽苷叭廛疷⏯羼䝤翌皯募㚁兇亾嚐ᶍ窇荂Ⲇ᎔䋊ⵃ䚁䣈传ࠀ"
