/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.internal.data

internal val CURRENCY_COMPACT_VEC: String =
    "00Fl㻩㱃㡈ऀ⺂䊣䨠䰥悌ଉ᭛世ᥦो秡朞ᱢ媣ᘎ笻晟䖍泂羶䉶杇⇙瓕➇翟猳杅撬㻖㞫灼䖴燐㮿㶸⨚秥绻ᙧ䝞矍燢⯓⟔搟㛠㽛㹓畀㑎ᮚ莰㴩ᕽ䰖ᓒ㓃瓁惤禗䷅䃁䭽蜬䑠⺹⭮㳔堕投敚⾺嫟Ⴘ✳狖繹孪佴䲙斢㹚睁咥ྺ⒓✠瀟⾀叕璑濎䭵楼帹䍖傟↽ᮤ䲰⸗㭉埠ࠀ"

internal val CURRENCY_COMPACT_VI: String =
    "003Y↚㐲䷹ᲂ疑峀票⣤灁ᣒ蒁䣞ሐ⣄伱悡િᰈ㑤凓ঈ喒抠䥣ᩖ怀⩬僖ࢊ呑拀⤳䩗Ⰸ帑஛ᩙഈ㑐㚅䰬傚⢁᠀ࠀ"
