// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.internal.data

internal val CURRENCY_FORMATS_MFE: String =
    "0123456789\u001F.\u001F \u001F.\u001F \u001F-\u001F1\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00"

internal val CURRENCY_FORMATS_MG: String =
    "0123456789\u001F.\u001F,\u001F.\u001F,\u001F-\u001F1\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤#,##0.00\u001F¤#,##0.00"

internal val CURRENCY_FORMATS_MNI: String =
    "০১২৩৪৫৬৭৮৯\u001F.\u001F,\u001F.\u001F,\u001F-\u001F1\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00"

internal val CURRENCY_FORMATS_MNI_MTEI: String =
    "꯰꯱꯲꯳꯴꯵꯶꯷꯸꯹\u001F.\u001F,\u001F.\u001F,\u001F-\u001F1\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤ #,##0.00"

internal val CURRENCY_FORMATS_MR: String =
    "०१२३४५६७८९\u001F.\u001F,\u001F.\u001F,\u001F-\u001F1\u001F¤#,##0.00\u001F¤ #,##0.00\u001F¤#,##0.00;(¤#,##0.00)\u001F¤ #,##0.00;(¤ #,##0.00)"

internal val CURRENCY_FORMATS_MS_ARAB_BN: String =
    "0123456789\u001F,\u001F.\u001F,\u001F.\u001F-\u001F1\u001F¤ #,##0.00\u001F¤ #,##0.00\u001F¤#,##0.00;(¤#,##0.00)\u001F¤ #,##0.00;(¤ #,##0.00)"

internal val CURRENCY_FORMATS_MY: String =
    "၀၁၂၃၄၅၆၇၈၉\u001F.\u001F,\u001F.\u001F,\u001F-\u001F1\u001F#,##0.00 ¤\u001F#,##0.00 ¤\u001F¤ #,##0.00\u001F¤ #,##0.00"
