/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.skeletons.internal.data

internal val SKELETON_NAMES_GA: String =
    "ré\u001Ebliain\u001Eráithe\u001Emí\u001E\u001E\u001Elá den tseachtain\u001Elá\u001E\u001E\u001Ea.m./p.m.\u001Euair\u001Enóiméad\u001Esoicind\u001E\u001E\u001F1ú ráithe\u001E2ú ráithe\u001E3ú ráithe\u001E4ú ráithe\u001FR1\u001ER2\u001ER3\u001ER4\u001FH\u001EH\u001F{1} 'ag' {0}\u001E{1} 'ag' {0}\u001E{1}, {0}\u001E{1}, {0}\u001F\u001F1ú ráithe\u001E2ú ráithe\u001E3ú ráithe\u001E4ú ráithe"

internal val SKELETON_NAMES_GD: String =
    "linn\u001Ebliadhna\u001Ecairteal\u001Emìos\u001E\u001E\u001Elatha na seachdaine\u001Elatha\u001E\u001E\u001Em/f\u001Euair a thìde\u001Emionaid\u001Ediog\u001E\u001E\u001F1d chairteal\u001E2na cairteal\u001E3s cairteal\u001E4mh cairteal\u001FC1\u001EC2\u001EC3\u001EC4\u001FH\u001EH\u001F{1} 'aig' {0}\u001E{1} 'aig' {0}\u001E{1}, {0}\u001E{1}, {0}\u001F\u001F1d chairteal\u001E2na cairteal\u001E3s cairteal\u001E4mh cairteal"

internal val SKELETON_NAMES_GL: String =
    "era\u001Eano\u001Etrimestre\u001Emes\u001E\u001E\u001Edía da semana\u001Edía\u001E\u001E\u001Ea.m./p.m.\u001Ehora\u001Eminuto\u001Esegundo\u001E\u001E\u001F1.º trimestre\u001E2.º trimestre\u001E3.º trimestre\u001E4.º trimestre\u001FT1\u001ET2\u001ET3\u001ET4\u001FH\u001EH\u001F{1}, {0}\u001E{1}, {0}\u001E{1}, {0}\u001E{1}, {0}\u001F\u001F1.º trimestre\u001E2.º trimestre\u001E3.º trimestre\u001E4.º trimestre"

internal val SKELETON_NAMES_GSW: String =
    "Epoche\u001EJaar\u001EQuarter\u001EMonet\u001E\u001E\u001EWuchetag\u001ETag\u001E\u001E\u001ETageshälfti\u001ESchtund\u001EMinuute\u001ESekunde\u001E\u001E\u001F1. Quartal\u001E2. Quartal\u001E3. Quartal\u001E4. Quartal\u001FQ1\u001EQ2\u001EQ3\u001EQ4\u001FH\u001EH\u001F{1} {0}\u001E{1} {0}\u001E{1} {0}\u001E{1} {0}\u001F\u001F1. Quartal\u001E2. Quartal\u001E3. Quartal\u001E4. Quartal"

internal val SKELETON_NAMES_GU: String =
    "યુગ\u001Eવર્ષ\u001Eત્રિમાસિક\u001Eમહિનો\u001E\u001E\u001Eઅઠવાડિયાનો દિવસ\u001Eદિવસ\u001E\u001E\u001EAM/PM\u001Eકલાક\u001Eમિનિટ\u001Eસેકંડ\u001E\u001E\u001F1લો ત્રિમાસ\u001E2જો ત્રિમાસ\u001E3જો ત્રિમાસ\u001E4થો ત્રિમાસ\u001FQ1\u001EQ2\u001EQ3\u001EQ4\u001Fh\u001EhB\u001F{1} {0}\u001E{1} {0}\u001E{1} {0}\u001E{1} {0}\u001F\u001F1લો ત્રિમાસ\u001E2જો ત્રિમાસ\u001E3જો ત્રિમાસ\u001E4થો ત્રિમાસ"

internal val SKELETON_NAMES_GUZ: String =
    "Ebiro\u001EOmwaka\u001EQuarter\u001EOmotienyi\u001E\u001E\u001ERituko r’ewiki\u001ERituko\u001E\u001E\u001EMambia gose Morogoba\u001EEnsa\u001EEdakika\u001EEsekendi\u001E\u001E\u001FErobo entang’ani\u001EErobo yakabere\u001EErobo yagatato\u001EErobo yakane\u001FE1\u001EE2\u001EE3\u001EE4\u001FH\u001EhB\u001F{1} {0}\u001E{1} {0}\u001E{1} {0}\u001E{1} {0}\u001F\u001FErobo entang’ani\u001EErobo yakabere\u001EErobo yagatato\u001EErobo yakane"
