/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * Emits the source object that binds a generated table to its domain interface,
 * together with the convenience extensions over it.
 *
 * The shipped `-cldr-full` artifacts and anything the Gradle plugin generates both
 * come from here, so `Country.BR.displayName(locale)` means the same thing in a
 * full build and in a build narrowed to three locales, and switching between
 * them is a dependency change plus one import.
 *
 * This is the only emitter that writes anything other than data. What it writes
 * is a delegation and a set of one-line extensions, all of it derived from the
 * object name and the package, which is why it cannot drift from the format it
 * delegates to.
 */
public class BindingSpec(
    /** Where the object and its extensions go, e.g. `com.example.locale`. */
    public val packageName: String,
    /** The object's name, e.g. `CldrCountry` or `GeneratedCountryNames`. */
    public val objectName: String,
    /** Where the generated table lives, normally `<packageName>.internal.data`. */
    public val registryPackage: String,
    /** What the header credits the data to. */
    public val source: String,
)

/**
 * The header plus a sorted import block.
 *
 * Sorting here rather than in the templates is what keeps the registry import,
 * whose package is a parameter, in the position ktlint expects.
 */
internal fun preamble(spec: BindingSpec, imports: List<String>, fileAnnotation: String? = null): String = buildString {
    append(LICENSE_HEADER + "// GENERATED by :codegen from ")
    append(spec.source)
    append(". Do not edit.\n")
    append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
    // Between the credit and the package, with a blank line after it: a file
    // annotation trailing the comment block reads as part of it to ktlint.
    fileAnnotation?.let {
        append(it)
        append("\n\n")
    }
    append("package ")
    append(spec.packageName)
    append("\n\n")
    for (import in imports.sorted()) {
        append("import ")
        append(import)
        append("\n")
    }
}

/** `CldrCountry`-shaped binding: the source object plus the country extensions. */
public fun emitCountryBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "CountryNames.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.country.Country",
                "dev.carcara.kotlinx.locale.country.CountryNameSource",
                "dev.carcara.kotlinx.locale.country.cldr.runtime.PayloadCountryNames",
                "dev.carcara.kotlinx.locale.country.countryForDisplayNameOrNull",
                "dev.carcara.kotlinx.locale.country.displayName",
                "${spec.registryPackage}.countryNamesRegistry",
            ),
        ) + """
        |
        |/**
        | * The country names this build carries.
        | *
        | * The lookup lives in `kotlinx-locale-country-cldr-runtime`; all this object
        | * contributes is the table.
        | */
        |public object ${spec.objectName} : CountryNameSource by PayloadCountryNames(countryNamesRegistry)
        |
        |/**
        | * The country name for [locale], resolved through the locale's inheritance
        | * chain; falls back to the alpha-2 code when there is no name.
        | */
        |public fun Country.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        |/**
        | * The country whose display name in [locale] matches [name],
        | * case-insensitively, or `null`.
        | */
        |public fun Country.Companion.forDisplayNameOrNull(name: String, locale: Locale = Locale.current): Country? =
        |    ${spec.objectName}.countryForDisplayNameOrNull(name, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/**
 * `CldrCurrency`-shaped binding: the source object plus the currency extensions.
 *
 * [hasFormats] decides whether the number patterns are wired in, and with them
 * `CurrencyAmount.format` and `parseFormatted`. False is not a formatter over an
 * empty table: the entry points are absent, so a build that asked for the
 * symbols and calls `format` fails to compile rather than rendering a hole. That
 * is the failure this generator prefers, and it is why the symbols and the
 * patterns are two flags rather than one.
 */
public fun emitCurrencyBinding(outputRoot: File, spec: BindingSpec, numberObject: String?, hasFormats: Boolean) {
    val file = outputRoot.packageFile(spec.packageName, "CurrencyNames.kt")
    // Built here rather than spliced into the template, so the placeholders are
    // resolved once at emit time and the generated file carries none of them.
    val compactArguments = if (numberObject == null) {
        ""
    } else {
        "\n        |        currencyCompactRegistry," +
            "\n        |        FormattedNumberSelector {" +
            "\n        |            ${numberObject}Plurals.pluralCategoryOrNull(it, PluralType.CARDINAL, Locale.current)" +
            "\n        |                ?: PluralCategory.OTHER" +
            "\n        |        },"
    }
    // Each block is trimmed on its own and the pieces are concatenated, rather
    // than interpolated into one template: a margin-prefixed block spliced into
    // another leaves the indentation of the splice point behind as a line of
    // trailing whitespace, which ktlint then rejects in the consumer's build.
    val sourceObject = if (hasFormats) {
        """
        |/**
        | * The currency symbols, display names and number formats this build carries.
        | *
        | * The delegation is written out rather than expressed with `by` because both
        | * interfaces declare `supportedLocales`, and being explicit about which one
        | * answers beats resolving the clash with a one-line override.
        | */
        |public object ${spec.objectName} : CurrencyNameSource, CurrencyFormatSource {
        |
        |    private val names = PayloadCurrencyNames(currencyNamesRegistry)
        |    private val formats = PayloadCurrencyFormats(
        |        currencyFormatsRegistry,
        |        currencyNamesRegistry,$compactArguments
        |    )
        |
        |    // The two tables cover the same locale set, so either answer is the same.
        |    override val supportedLocales: Set<Locale>
        |        get() = formats.supportedLocales
        |
        |    override fun currencySymbolOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencySymbolOrNull(currencyCode, locale)
        |
        |    override fun currencySymbolOrNull(currencyCode: String, locale: Locale, style: CurrencySymbolStyle): String? =
        |        names.currencySymbolOrNull(currencyCode, locale, style)
        |
        |    override fun currencyNameOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencyNameOrNull(currencyCode, locale)
        |
        |    override fun formatOrNull(
        |        minorUnits: Long,
        |        currencyCode: String,
        |        locale: Locale,
        |        options: CurrencyFormatOptions,
        |    ): String? = formats.formatOrNull(minorUnits, currencyCode, locale, options)
        |
        |    override fun parseToMinorUnitsOrNull(text: String, currencyCode: String, locale: Locale): Long? =
        |        formats.parseToMinorUnitsOrNull(text, currencyCode, locale)
        |
        |    override fun currencyCodeOrNull(text: String, locale: Locale): String? =
        |        formats.currencyCodeOrNull(text, locale)
        |}
        |
        """.trimMargin()
    } else {
        """
        |/**
        | * The currency symbols and display names this build carries.
        | *
        | * One interface rather than two, so `by` says all of it: without the pattern
        | * tables there is no second `supportedLocales` to disambiguate, and no
        | * formatter to delegate to.
        | */
        |public object ${spec.objectName} : CurrencyNameSource by PayloadCurrencyNames(currencyNamesRegistry)
        |
        """.trimMargin()
    }
    val formatExtensions = if (!hasFormats) {
        ""
    } else {
        """
        |
        |/**
        | * Formats the amount with the pattern and symbols of [locale].
        | *
        | * The currency is written per [style]. [signDisplay] decides whether a sign
        | * appears and whether CLDR's accounting pattern is used, which is what puts
        | * `(${'$'}1,234.56)` on a negative in en. [cash] applies the cash fraction digits
        | * and cash rounding, so a Swiss franc rounds to 0.05. [fractionDigits]
        | * overrides CLDR's digit count, which is what a headline figure wants when it
        | * should read `£18,500` rather than `£18,500.00`. [notation] selects compact
        | * money: `${'$'}1.2M`.
        | */
        |public fun CurrencyAmount.format(
        |    locale: Locale = Locale.current,
        |    style: CurrencySymbolStyle = CurrencySymbolStyle.SYMBOL,
        |    signDisplay: SignDisplay = SignDisplay.AUTO,
        |    cash: Boolean = false,
        |    fractionDigits: Int? = null,
        |    notation: NumberNotation = NumberNotation.STANDARD,
        |): String = ${spec.objectName}.format(this, locale, style, signDisplay, cash, fractionDigits, notation)
        |
        |/**
        | * Parses a formatted string — `R${'$'} 1.234,56`, `(${'$'}1,234.56)`, `200 Ft` — back
        | * into an amount, using [locale]'s separators, digits and currency symbol.
        | *
        | * The printed number is taken at face value and scaled to ISO minor units, so
        | * the formatting digits do not distort the result: HUF prints without decimals
        | * but has two ISO decimals, and `"200 Ft"` parses to 20000 minor units.
        | * Returns `null` when the text holds anything other than one number in this
        | * locale's conventions.
        | */
        |public fun CurrencyAmount.Companion.parseFormattedOrNull(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount? = ${spec.objectName}.parseFormattedOrNull(currency, text, locale)
        |
        |/** Like [parseFormattedOrNull] but throws on invalid input. */
        |public fun CurrencyAmount.Companion.parseFormatted(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount = requireNotNull(parseFormattedOrNull(currency, text, locale)) {
        |    "Cannot parse ${'$'}{currency.code} amount: '${'$'}text'"
        |}
        |
        |/**
        | * Parses a formatted string whose currency is not known in advance, reading
        | * the currency out of the text itself: `"US${'$'} 1.234,56"` in pt-BR is USD.
        | *
        | * The currency is looked up, not guessed. It reads the spellings [locale]
        | * writes, which CLDR disambiguates within a locale, and answers `null` where
        | * the text would fit more than one currency or none. Narrow symbols are not
        | * among them, because `${'$'}` on its own names over twenty currencies in some
        | * locales; pass the currency explicitly to read an amount written that way.
        | */
        |public fun CurrencyAmount.Companion.parseFormattedOrNull(
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount? = ${spec.objectName}.parseFormattedOrNull(text, locale)
        |
        """.trimMargin()
    }
    file.writeText(
        preamble(
            spec,
            buildList {
                if (hasFormats) add("dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi")
                if (numberObject != null) {
                    add(spec.registryPackage + ".currencyCompactRegistry")
                    add("dev.carcara.kotlinx.locale.number.PluralCategory")
                    add("dev.carcara.kotlinx.locale.number.PluralType")
                    add("dev.carcara.kotlinx.locale.number.cldr.runtime.FormattedNumberSelector")
                }
                addAll(
                    listOf(
                        "dev.carcara.kotlinx.locale.Locale",
                        "dev.carcara.kotlinx.locale.currency.Currency",
                        "dev.carcara.kotlinx.locale.currency.CurrencyNameSource",
                        // Named by `Currency.symbol`, which every build emits,
                        // rather than only by the formatting extensions.
                        "dev.carcara.kotlinx.locale.currency.CurrencySymbolStyle",
                        "dev.carcara.kotlinx.locale.currency.cldr.runtime.PayloadCurrencyNames",
                        "dev.carcara.kotlinx.locale.currency.displayName",
                        "dev.carcara.kotlinx.locale.currency.symbol",
                        "${spec.registryPackage}.currencyNamesRegistry",
                    ),
                )
                if (hasFormats) {
                    addAll(
                        listOf(
                            "dev.carcara.kotlinx.locale.currency.CurrencyAmount",
                            "dev.carcara.kotlinx.locale.currency.CurrencyFormatSource",
                            "dev.carcara.kotlinx.locale.currency.CurrencyFormatOptions",
                            "dev.carcara.kotlinx.locale.number.NumberNotation",
                            "dev.carcara.kotlinx.locale.number.SignDisplay",
                            "dev.carcara.kotlinx.locale.currency.cldr.runtime.PayloadCurrencyFormats",
                            "dev.carcara.kotlinx.locale.currency.code",
                            "dev.carcara.kotlinx.locale.currency.format",
                            "dev.carcara.kotlinx.locale.currency.parseFormattedOrNull",
                            "${spec.registryPackage}.currencyFormatsRegistry",
                        ),
                    )
                }
            },
            // Not only for the compact build. Constructing PayloadCurrencyFormats
            // at all resolves its default arguments, and one of them is a
            // FormattedNumberSelector, which is marked internal because it exists
            // for the formatter modules to share. A build with the patterns and
            // without compact money never mentions the type and still needs the
            // opt-in; leaving it out compiled here and failed in the sample. A
            // build without the patterns constructs nothing that asks for it.
            fileAnnotation = "@file:OptIn(InternalKotlinxLocaleApi::class)".takeIf { hasFormats },
        ) + "\n" + sourceObject + """
        |
        |/**
        | * The currency symbol for [locale], e.g. `US${'$'}` for USD in pt-BR; falls back
        | * to the ISO code.
        | *
        | * [style] picks between CLDR's spellings. A locale that declares none of the
        | * alternative it is asked for answers its plain symbol.
        | */
        |public fun Currency.symbol(
        |    locale: Locale = Locale.current,
        |    style: CurrencySymbolStyle = CurrencySymbolStyle.SYMBOL,
        |): String = ${spec.objectName}.symbol(this, locale, style)
        |
        |/** The display name for [locale]; falls back to the ISO code. */
        |public fun Currency.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        """.trimMargin() + formatExtensions,
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/** `CldrDateTime`-shaped binding: the source object plus the datetime extensions. */
public fun emitDateTimeBinding(outputRoot: File, spec: BindingSpec, hasStandalone: Boolean = false, weekData: String = "") {
    val file = outputRoot.packageFile(spec.packageName, "LocalizedFormat.kt")
    val standaloneArgument = if (hasStandalone) ", localeStandaloneRegistry" else ""
    val standaloneAccessor = if (hasStandalone) "localeStandaloneRegistry" else "emptyMap()"
    file.writeText(
        preamble(
            spec,
            buildList {
                addAll(
                    listOf(
                        "dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi",
                        "dev.carcara.kotlinx.locale.Locale",
                        "dev.carcara.kotlinx.locale.datetime.DateTimeFormatSource",
                        "dev.carcara.kotlinx.locale.datetime.DurationStyle",
                        "dev.carcara.kotlinx.locale.datetime.FormatStyle",
                        "dev.carcara.kotlinx.locale.datetime.NameContext",
                        "dev.carcara.kotlinx.locale.datetime.TextStyle",
                        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.PayloadDateTimeFormats",
                        "dev.carcara.kotlinx.locale.datetime.displayName",
                        "dev.carcara.kotlinx.locale.datetime.durationPattern",
                        "dev.carcara.kotlinx.locale.datetime.format",
                        "${spec.registryPackage}.localeDataRegistry",
                        "kotlinx.datetime.DayOfWeek",
                        "kotlinx.datetime.LocalDate",
                        "kotlinx.datetime.LocalDateTime",
                        "kotlinx.datetime.LocalTime",
                        "kotlinx.datetime.Month",
                    ),
                )
                if (hasStandalone) add("${spec.registryPackage}.localeStandaloneRegistry")
                if (weekData.isNotEmpty()) {
                    addAll(
                        listOf(
                            "dev.carcara.kotlinx.locale.datetime.WeekInfo",
                            "dev.carcara.kotlinx.locale.datetime.cldr.runtime.PayloadWeekInfo",
                            "dev.carcara.kotlinx.locale.datetime.weekInfo",
                            "dev.carcara.kotlinx.locale.datetime.weekInfoForRegion",
                        ),
                    )
                }
            },
            // Only when the week data is here: the table's type is internal API,
            // and the two entry points over it are not. A build without the table
            // has nothing to opt into and should not carry a stray annotation.
            fileAnnotation = "@file:OptIn(InternalKotlinxLocaleApi::class)".takeIf { weekData.isNotEmpty() },
        ) + """
        |
        |internal val dateTimeSource: PayloadDateTimeFormats =
        |    PayloadDateTimeFormats(localeDataRegistry$standaloneArgument)
        |
        |/**
        | * The date and time patterns this build carries.
        | *
        | * The parser and formatter live in `kotlinx-locale-datetime-cldr-runtime`; all
        | * this object contributes is the table.
        | */
        |public object ${spec.objectName} : DateTimeFormatSource by dateTimeSource {
        |
        |    /**
        |     * The pattern table itself, for an engine layered over this one.
        |     *
        |     * Skeleton formatting needs it: matching scores against the four
        |     * standard date and four standard time patterns as well as against the
        |     * skeleton table, and rendering the winner needs the month and weekday
        |     * names. Exposing the table beats making
        |     * `kotlinx-locale-datetime-cldr-skeletons` carry a second copy of it.
        |     */
        |    @InternalKotlinxLocaleApi
        |    public val records: Map<String, String> get() = localeDataRegistry
        |
        |    /**
        |     * The stand-alone names, for the same engine.
        |     *
        |     * A skeleton pattern can name them directly: Catalan's `yMMM` is
        |     * `LLL 'del' y`, and rendering `L` from the format names gives
        |     * `de maig` where CLDR means `maig`.
        |     */
        |    @InternalKotlinxLocaleApi
        |    public val standaloneRecords: Map<String, String> get() = $standaloneAccessor
        |}
        |
        |/**
        | * Formats this date with the locale's standard date pattern of the given [style].
        | *
        | * ```
        | * LocalDate(2026, 7, 27).format(FormatStyle.LONG, Locale.forLanguageTag("pt-BR"))
        | * // "27 de julho de 2026"
        | * ```
        | */
        |public fun LocalDate.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this time with the locale's standard time pattern of the given [style].
        | *
        | * Time-zone fields present in the FULL and LONG patterns are omitted, since a
        | * [LocalTime] carries no zone information.
        | */
        |public fun LocalTime.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this date-time by combining the locale's date and time patterns with
        | * its "glue" pattern (e.g. `Sunday, July 27, 2026, 3:05 PM` for `en`).
        | */
        |public fun LocalDateTime.format(dateStyle: FormatStyle, timeStyle: FormatStyle, locale: Locale): String =
        |    ${spec.objectName}.format(this, dateStyle, timeStyle, locale)
        |
        |/** Formats this date-time using the same [style] for the date and time parts. */
        |public fun LocalDateTime.format(style: FormatStyle, locale: Locale): String = format(style, style, locale)
        |
        |/** The localized name of this month in the "format" context, e.g. `julho`. */
        |public fun Month.displayName(style: TextStyle, locale: Locale): String = ${spec.objectName}.displayName(this, style, locale)
        |
        |/** The localized name of this day of week in the "format" context, e.g. `segunda-feira`. */
        |public fun DayOfWeek.displayName(style: TextStyle, locale: Locale): String =
        |    ${spec.objectName}.displayName(this, style, locale)
        |
        |/**
        | * The localized name of this month in [context].
        | *
        | * [NameContext.STANDALONE] is what a calendar header or a month picker
        | * wants: Czech July is `červenec` alone and `července` inside a date.
        | */
        |public fun Month.displayName(style: TextStyle, context: NameContext, locale: Locale): String =
        |    ${spec.objectName}.displayName(this, style, context, locale)
        |
        |/** The localized name of this day of week in [context]; see [Month.displayName]. */
        |public fun DayOfWeek.displayName(style: TextStyle, context: NameContext, locale: Locale): String =
        |    ${spec.objectName}.displayName(this, style, context, locale)
        |
        |/**
        | * The separator pattern [locale] writes an elapsed duration with.
        | *
        | * ```
        | * durationPattern(DurationStyle.MINUTE_SECOND)                              // "m:ss"
        | * durationPattern(DurationStyle.MINUTE_SECOND, Locale.forLanguageTag("fi")) // "m.ss"
        | * ```
        | *
        | * A pattern rather than a formatted string, because whether ninety seconds
        | * reads as `1:30` or `0:01:30` is the caller's decision. CLDR does not answer
        | * it and neither do ECMA-402 or ICU, all of which take the components from
        | * the caller, the same way relative wording takes its unit.
        | *
        | * Expect almost no variation. In the CLDR release this build carries, only
        | * Finnish and Danish differ from root, both writing a full stop where root
        | * writes a colon. What does vary is the digits, which the numbering system
        | * already decides.
        | *
        | * Falls back to root's `h:mm`, `h:mm:ss` and `m:ss`.
        | */
        |public fun durationPattern(style: DurationStyle, locale: Locale = Locale.current): String =
        |    dateTimeSource.durationPattern(style, locale)
        |
        """.trimMargin() + weekDataSection(spec, weekData),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/**
 * The week data half of the date-time binding.
 *
 * A constant rather than a table, the way the time zone metadata is: none of it
 * varies by language, so there is nothing to key it by and nothing for narrowing
 * to drop. Empty when the build carries no week data, which is what a narrowed
 * source set that did not ask for it looks like.
 */
private fun weekDataSection(spec: BindingSpec, weekData: String): String {
    if (weekData.isEmpty()) return ""
    return """
        |
        |/**
        | * Where each territory starts its week, how many days of it must fall in the
        | * new year for that to count as week one, and which days it rests.
        | *
        | * A constant rather than a table: CLDR keys this by territory, not by
        | * language, so there is nothing per-locale to key it by.
        | */
        |@InternalKotlinxLocaleApi
        |internal val weekInfoTable: PayloadWeekInfo = PayloadWeekInfo(
        |    "${kotlinEscape(weekData)}",
        |)
        |
        |/**
        | * Where [locale]'s territory starts its week, and which days it rests.
        | *
        | * ```
        | * weekInfo(Locale.forLanguageTag("en-GB")).firstDayOfWeek  // MONDAY
        | * weekInfo(Locale.forLanguageTag("pt-PT")).firstDayOfWeek  // SUNDAY
        | * ```
        | *
        | * The two fields vary independently, so neither implies the other. Portugal
        | * starts its week on Sunday like the United States, and still wants four of
        | * its days in the new year like the rest of Europe.
        | *
        | * A locale that names no region is maximised the way likely subtags maximise
        | * it, so `en` answers for the United States. Falls back to CLDR's world
        | * default: Monday, one day, and a Saturday to Sunday weekend.
        | */
        |public fun weekInfo(locale: Locale = Locale.current): WeekInfo = weekInfoTable.weekInfo(locale)
        |
        |/**
        | * The same, for an ISO 3166-1 alpha-2 region code.
        | *
        | * Named for what it assumes rather than distinguished by its argument: a
        | * caller that already holds a country code has the territory, and which
        | * days a country rests is not a question about anybody's language.
        | */
        |public fun weekInfoForRegion(regionCode: String): WeekInfo = weekInfoTable.weekInfoForRegion(regionCode)
        |
    """.trimMargin()
}

/**
 * `CldrDateTimeSkeletons`-shaped binding: the source object plus the skeleton
 * extensions.
 *
 * [dateTimeObject] is the fully qualified datetime binding whose table this
 * reads. It is a parameter rather than a constant because the Gradle plugin
 * names its own objects, and a narrowed build has to bind its skeletons to its
 * own patterns rather than to the shipped ones.
 */
public fun emitSkeletonBinding(outputRoot: File, spec: BindingSpec, dateTimeObject: String) {
    val file = outputRoot.packageFile(spec.packageName, "SkeletonFormat.kt")
    val dateTimePackage = dateTimeObject.substringBeforeLast('.')
    val dateTimeName = dateTimeObject.substringAfterLast('.')
    val imports = listOf(
        "dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi",
        "dev.carcara.kotlinx.locale.Locale",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.PayloadSkeletonFormats",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.SkeletonFormatSource",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.format",
        "kotlinx.datetime.LocalDate",
        "kotlinx.datetime.LocalDateTime",
        "kotlinx.datetime.LocalTime",
        "${spec.registryPackage}.skeletonAppendFormatsRegistry",
        "${spec.registryPackage}.skeletonFormatsRegistry",
        "${spec.registryPackage}.skeletonNamesRegistry",
    ) + listOfNotNull(dateTimeObject.takeIf { dateTimePackage != spec.packageName })

    file.writeText(
        preamble(spec, imports, fileAnnotation = "@file:OptIn(InternalKotlinxLocaleApi::class)") + """
        |
        |/**
        | * The skeleton tables this build carries.
        | *
        | * The matcher lives in `kotlinx-locale-datetime-cldr-runtime`; all this
        | * object contributes is the tables, plus the pattern table it borrows from
        | * [$dateTimeName] rather than carrying twice.
        | */
        |internal val skeletonSource: PayloadSkeletonFormats = PayloadSkeletonFormats(
        |    skeletonFormatsRegistry,
        |    skeletonAppendFormatsRegistry,
        |    skeletonNamesRegistry,
        |    $dateTimeName.records,
        |    $dateTimeName.standaloneRecords,
        |)
        |
        |public object ${spec.objectName} : SkeletonFormatSource by skeletonSource {
        |
        |    /**
        |     * The source itself, for the interval layer.
        |     *
        |     * `kotlinx-locale-datetime-cldr-intervals` has to pick a pattern for the
        |     * requested skeleton before it can split one, and building a matcher
        |     * sorts a locale's whole candidate pool. Handing over this object lets
        |     * the two share one pool per locale instead of building two.
        |     */
        |    @InternalKotlinxLocaleApi
        |    public val skeletons: PayloadSkeletonFormats get() = skeletonSource
        |}
        |
        |/**
        | * Formats this date with the fields [skeleton] names, arranged the way
        | * [locale] arranges them.
        | *
        | * ```
        | * LocalDate(2026, 7, 27).format("yMMMd", Locale.forLanguageTag("pt-BR"))
        | * // "27 de jul. de 2026"
        | * ```
        | */
        |public fun LocalDate.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/** Formats this time with the fields [skeleton] names. */
        |public fun LocalTime.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/**
        | * Formats this date-time with the fields [skeleton] names, joining the date
        | * and time halves with the locale's own glue pattern when the skeleton spans
        | * both.
        | */
        |public fun LocalDateTime.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/**
        | * The pattern [locale] uses for [skeleton], or `null` when the skeleton names
        | * a field that cannot be rendered.
        | *
        | * Useful on its own: the pattern drives `kotlinx-datetime`'s `DateTimeFormat`,
        | * which is how a skeleton buys locale aware parsing and not only formatting.
        | */
        |public fun skeletonPatternOrNull(skeleton: String, locale: Locale = Locale.current): String? =
        |    ${spec.objectName}.skeletonPatternOrNull(skeleton, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

internal fun File.packageFile(packageName: String, fileName: String): File =
    resolve(packageName.replace('.', '/')).apply { mkdirs() }.resolve(fileName)
