/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import java.io.File

/** The record separators the payload format uses, shared by the writers and the runtime decoders. */
public const val FIELD_SEPARATOR: String = "\u001F"
public const val LIST_SEPARATOR: String = "\u001E"
public const val KEY_SEPARATOR: String = "\u001D"

public fun kotlinEscape(value: String): String = buildString(value.length + 8) {
    for (ch in value) {
        when {
            ch == '\\' -> append("\\\\")
            ch == '"' -> append("\\\"")
            ch == '$' -> append("\\$")
            ch.code < 0x20 || ch.code == 0x7F -> append("\\u%04X".format(ch.code))
            else -> append(ch)
        }
    }
}

/** CLDR file id (en_GB, sr_Cyrl_BA, ca_ES_VALENCIA) -> canonical tag (en-GB, sr-Cyrl-BA, ca-ES-valencia). */
public fun canonicalTag(cldrId: String): String {
    val parts = cldrId.split('_')
    return buildList(parts.size) {
        add(parts[0].lowercase())
        for (part in parts.drop(1)) {
            add(
                when {
                    part.length == 4 && part.all(Char::isLetter) ->
                        part.lowercase().replaceFirstChar(Char::uppercaseChar)
                    (part.length == 2 && part.all(Char::isLetter)) ||
                        (part.length == 3 && part.all(Char::isDigit)) -> part.uppercase()
                    else -> part.lowercase()
                },
            )
        }
    }.joinToString("-")
}

/**
 * Emits a locale-tag-keyed payload registry into [outputDir]: deduplicated string
 * constants bucketed into one file per first letter of the owning tag, plus a
 * registry map file.
 *
 * Every locale-keyed table in the library is this shape. The datetime table used
 * to have an emitter of its own that differed only in two hard-coded prefixes,
 * which is why it does not any more.
 *
 * Only files this emitter owns are deleted before writing. The shipped layout
 * gives each table its own directory, but a source set generated by the Gradle
 * plugin puts them all in one, so deleting every `.kt` here would wipe the
 * neighbours.
 */
public class KeyedPayloadEmitter(
    private val outputDir: File,
    private val packageName: String,
    private val filePrefix: String,
    private val constPrefix: String,
    private val registryProperty: String,
    private val source: String,
    private val versionConst: Pair<String, String>? = null,
) {
    private fun header(): String = LICENSE_HEADER + """
        |// GENERATED by :codegen from $source. Do not edit.
        |// Regenerate with: ./gradlew :codegen:generateLocaleData
        |package $packageName
        |
    """.trimMargin()

    private fun constNameFor(tag: String): String = constPrefix + "_" + tag.uppercase().replace('-', '_')

    public fun emit(payloadByTag: Map<String, String>) {
        outputDir.mkdirs()
        outputDir.listFiles { f: File -> f.extension == "kt" && f.name.startsWith(filePrefix) }
            ?.forEach(File::delete)

        val constByPayload = LinkedHashMap<String, String>()
        val constByTag = LinkedHashMap<String, String>()
        for ((tag, payload) in payloadByTag) {
            val const = constByPayload.getOrPut(payload) { constNameFor(tag) }
            constByTag[tag] = const
        }

        val ownersByBucket = LinkedHashMap<Char, MutableList<Pair<String, String>>>()
        for ((payload, const) in constByPayload) {
            val ownerTag = const.removePrefix(constPrefix + "_").lowercase()
            ownersByBucket.getOrPut(ownerTag.first()) { ArrayList() }.add(const to payload)
        }
        for ((bucket, consts) in ownersByBucket) {
            outputDir.resolve("${filePrefix}_$bucket.kt").writeText(
                buildString {
                    append(header())
                    for ((const, payload) in consts.sortedBy { it.first }) {
                        append("\ninternal val ")
                        append(const)
                        append(": String =\n    \"")
                        append(kotlinEscape(payload))
                        append("\"\n")
                    }
                },
            )
        }

        outputDir.resolve("${filePrefix}Registry.kt").writeText(
            buildString {
                append(header())
                versionConst?.let { (name, value) ->
                    append("\ninternal const val ")
                    append(name)
                    append(": String = \"")
                    append(kotlinEscape(value))
                    append("\"\n")
                }
                append("\ninternal val ")
                append(registryProperty)
                append(": Map<String, String> = buildMap(")
                append(constByTag.size)
                append(") {\n")
                for ((tag, const) in constByTag.entries.sortedBy { it.key }) {
                    append("    put(\"")
                    append(kotlinEscape(tag))
                    append("\", ")
                    append(const)
                    append(")\n")
                }
                append("}\n")
            },
        )

        println(
            "[codegen] emitted $registryProperty: ${constByTag.size} locales " +
                "(${constByPayload.size} unique payloads) to $outputDir",
        )
    }
}
