/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import java.io.File

private const val COUNTRY_PACKAGE = "dev.carcara.kotlinx.locale.country"

/**
 * Emits the Country enum into the -types layer: the entry list and nothing
 * else. Every behaviour is an extension declared in -core or in an
 * implementation module, which is what keeps this emitter writing data only
 * and lets the Gradle plugin narrow the entry set without copying logic.
 */
public fun emitCountryEnum(outputFile: File, cldrTag: String, countries: List<CountryInfo>) {
    outputFile.parentFile.mkdirs()
    val entries = buildString {
        for (country in countries) {
            append("    /** ")
            append(country.englishName)
            append(" */\n    ")
            append(country.alpha2)
            append("(\"")
            append(country.alpha3)
            append("\", ")
            append(country.numeric)
            append("),\n")
        }
    }
    outputFile.writeText(
        LICENSE_HEADER + """
        |// GENERATED by :codegen from CLDR $cldrTag. Do not edit.
        |// Regenerate with: ./gradlew :codegen:generateLocaleData
        |package $COUNTRY_PACKAGE
        |
        |/**
        | * The countries of ISO 3166-1, keyed by alpha-2 code.
        | *
        | * Each entry carries only the codes ISO assigns it. Everything else is an
        | * extension: `alpha2` and the `for*` lookups come from
        | * `kotlinx-locale-country-core`, and `displayName` from whichever
        | * implementation module you put on the classpath.
        | */
        |public enum class Country(
        |    /** The ISO 3166-1 alpha-3 code, e.g. `USA`. */
        |    public val alpha3: String,
        |    /** The ISO 3166-1 numeric code, e.g. 840. */
        |    public val numericCode: Int,
        |) {
        |$entries    ;
        |
        |    public companion object
        |}
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${countries.size} countries to $outputFile")
}
