package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * Emits the source object that binds a generated table to its domain interface,
 * together with the convenience extensions over it.
 *
 * The shipped `-cldr-full` artifacts and anything the Gradle plugin generates both
 * come from here, so `Country.BR.displayName(locale)` means the same thing in a
 * full build and in a build narrowed to three locales, and switching between
 * them is a dependency change plus one import.
 *
 * This is the only emitter that writes anything other than data. What it writes
 * is a delegation and a set of one-line extensions, all of it derived from the
 * object name and the package, which is why it cannot drift from the format it
 * delegates to.
 */
public class BindingSpec(
    /** Where the object and its extensions go, e.g. `com.example.locale`. */
    public val packageName: String,
    /** The object's name, e.g. `CldrCountry` or `GeneratedCountryNames`. */
    public val objectName: String,
    /** Where the generated table lives, normally `<packageName>.internal.data`. */
    public val registryPackage: String,
    /** What the header credits the data to. */
    public val source: String,
)

/**
 * The header plus a sorted import block.
 *
 * Sorting here rather than in the templates is what keeps the registry import,
 * whose package is a parameter, in the position ktlint expects.
 */
internal fun preamble(spec: BindingSpec, imports: List<String>, fileAnnotation: String? = null): String = buildString {
    append("// GENERATED by :codegen from ")
    append(spec.source)
    append(". Do not edit.\n")
    append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
    // Between the credit and the package, with a blank line after it: a file
    // annotation trailing the comment block reads as part of it to ktlint.
    fileAnnotation?.let {
        append(it)
        append("\n\n")
    }
    append("package ")
    append(spec.packageName)
    append("\n\n")
    for (import in imports.sorted()) {
        append("import ")
        append(import)
        append("\n")
    }
}

/** `CldrCountry`-shaped binding: the source object plus the country extensions. */
public fun emitCountryBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "CountryNames.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.country.Country",
                "dev.carcara.kotlinx.locale.country.CountryNameSource",
                "dev.carcara.kotlinx.locale.country.cldr.runtime.PayloadCountryNames",
                "dev.carcara.kotlinx.locale.country.countryForDisplayNameOrNull",
                "dev.carcara.kotlinx.locale.country.displayName",
                "${spec.registryPackage}.countryNamesRegistry",
            ),
        ) + """
        |
        |/**
        | * The country names this build carries.
        | *
        | * The lookup lives in `kotlinx-locale-country-cldr-runtime`; all this object
        | * contributes is the table.
        | */
        |public object ${spec.objectName} : CountryNameSource by PayloadCountryNames(countryNamesRegistry)
        |
        |/**
        | * The country name for [locale], resolved through the locale's inheritance
        | * chain; falls back to the alpha-2 code when there is no name.
        | */
        |public fun Country.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        |/**
        | * The country whose display name in [locale] matches [name],
        | * case-insensitively, or `null`.
        | */
        |public fun Country.Companion.forDisplayNameOrNull(name: String, locale: Locale = Locale.current): Country? =
        |    ${spec.objectName}.countryForDisplayNameOrNull(name, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/** `CldrCurrency`-shaped binding: the source object plus the currency extensions. */
public fun emitCurrencyBinding(outputRoot: File, spec: BindingSpec, numberObject: String?) {
    val file = outputRoot.packageFile(spec.packageName, "CurrencyNames.kt")
    // Built here rather than spliced into the template, so the placeholders are
    // resolved once at emit time and the generated file carries none of them.
    val compactArguments = if (numberObject == null) {
        ""
    } else {
        "\n        |        currencyCompactRegistry," +
            "\n        |        FormattedNumberSelector {" +
            "\n        |            ${numberObject}Plurals.pluralCategoryOrNull(it, PluralType.CARDINAL, Locale.current)" +
            "\n        |                ?: PluralCategory.OTHER" +
            "\n        |        },"
    }
    file.writeText(
        preamble(
            spec,
            buildList {
                if (numberObject != null) {
                    add(spec.registryPackage + ".currencyCompactRegistry")
                    add("dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi")
                    add("dev.carcara.kotlinx.locale.number.PluralCategory")
                    add("dev.carcara.kotlinx.locale.number.PluralType")
                    add("dev.carcara.kotlinx.locale.number.cldr.runtime.FormattedNumberSelector")
                }
                addAll(
                    listOf(
                        "dev.carcara.kotlinx.locale.Locale",
                        "dev.carcara.kotlinx.locale.currency.Currency",
                        "dev.carcara.kotlinx.locale.currency.CurrencyAmount",
                        "dev.carcara.kotlinx.locale.currency.CurrencyFormatSource",
                        "dev.carcara.kotlinx.locale.currency.CurrencyNameSource",
                        "dev.carcara.kotlinx.locale.currency.CurrencyFormatOptions",
                        "dev.carcara.kotlinx.locale.currency.CurrencySymbolStyle",
                        "dev.carcara.kotlinx.locale.number.NumberNotation",
                        "dev.carcara.kotlinx.locale.number.SignDisplay",
                        "dev.carcara.kotlinx.locale.currency.cldr.runtime.PayloadCurrencyFormats",
                        "dev.carcara.kotlinx.locale.currency.cldr.runtime.PayloadCurrencyNames",
                        "dev.carcara.kotlinx.locale.currency.code",
                        "dev.carcara.kotlinx.locale.currency.displayName",
                        "dev.carcara.kotlinx.locale.currency.format",
                        "dev.carcara.kotlinx.locale.currency.parseFormattedOrNull",
                        "dev.carcara.kotlinx.locale.currency.symbol",
                        "${spec.registryPackage}.currencyFormatsRegistry",
                        "${spec.registryPackage}.currencyNamesRegistry",
                    ),
                )
            },
            // Compact money reaches the plural selector, which is marked
            // internal because it exists for the formatter modules to share.
            fileAnnotation = if (numberObject == null) null else "@file:OptIn(InternalKotlinxLocaleApi::class)",
        ) + """
        |
        |/**
        | * The currency symbols, display names and number formats this build carries.
        | *
        | * The delegation is written out rather than expressed with `by` because both
        | * interfaces declare `supportedLocales`, and being explicit about which one
        | * answers beats resolving the clash with a one-line override.
        | */
        |public object ${spec.objectName} : CurrencyNameSource, CurrencyFormatSource {
        |
        |    private val names = PayloadCurrencyNames(currencyNamesRegistry)
        |    private val formats = PayloadCurrencyFormats(
        |        currencyFormatsRegistry,
        |        currencyNamesRegistry,$compactArguments
        |    )
        |
        |    // The two tables cover the same locale set, so either answer is the same.
        |    override val supportedLocales: Set<Locale>
        |        get() = formats.supportedLocales
        |
        |    override fun currencySymbolOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencySymbolOrNull(currencyCode, locale)
        |
        |    override fun currencyNameOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencyNameOrNull(currencyCode, locale)
        |
        |    override fun formatOrNull(
        |        minorUnits: Long,
        |        currencyCode: String,
        |        locale: Locale,
        |        options: CurrencyFormatOptions,
        |    ): String? = formats.formatOrNull(minorUnits, currencyCode, locale, options)
        |
        |    override fun parseToMinorUnitsOrNull(text: String, currencyCode: String, locale: Locale): Long? =
        |        formats.parseToMinorUnitsOrNull(text, currencyCode, locale)
        |}
        |
        |/** The currency symbol for [locale], e.g. `US${'$'}` for USD in pt-BR; falls back to the ISO code. */
        |public fun Currency.symbol(locale: Locale = Locale.current): String = ${spec.objectName}.symbol(this, locale)
        |
        |/** The display name for [locale]; falls back to the ISO code. */
        |public fun Currency.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        |/**
        | * Formats the amount with the pattern and symbols of [locale].
        | *
        | * The currency is written per [style]. [signDisplay] decides whether a sign
        | * appears and whether CLDR's accounting pattern is used, which is what puts
        | * `(${'$'}1,234.56)` on a negative in en. [cash] applies the cash fraction digits
        | * and cash rounding, so a Swiss franc rounds to 0.05. [fractionDigits]
        | * overrides CLDR's digit count, which is what a headline figure wants when it
        | * should read `£18,500` rather than `£18,500.00`. [notation] selects compact
        | * money: `${'$'}1.2M`.
        | */
        |public fun CurrencyAmount.format(
        |    locale: Locale = Locale.current,
        |    style: CurrencySymbolStyle = CurrencySymbolStyle.SYMBOL,
        |    signDisplay: SignDisplay = SignDisplay.AUTO,
        |    cash: Boolean = false,
        |    fractionDigits: Int? = null,
        |    notation: NumberNotation = NumberNotation.STANDARD,
        |): String = ${spec.objectName}.format(this, locale, style, signDisplay, cash, fractionDigits, notation)
        |
        |/**
        | * Parses a formatted string — `R${'$'} 1.234,56`, `(${'$'}1,234.56)`, `200 Ft` — back
        | * into an amount, using [locale]'s separators, digits and currency symbol.
        | *
        | * The printed number is taken at face value and scaled to ISO minor units, so
        | * the formatting digits do not distort the result: HUF prints without decimals
        | * but has two ISO decimals, and `"200 Ft"` parses to 20000 minor units.
        | * Returns `null` when the text holds anything other than one number in this
        | * locale's conventions.
        | */
        |public fun CurrencyAmount.Companion.parseFormattedOrNull(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount? = ${spec.objectName}.parseFormattedOrNull(currency, text, locale)
        |
        |/** Like [parseFormattedOrNull] but throws on invalid input. */
        |public fun CurrencyAmount.Companion.parseFormatted(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount = requireNotNull(parseFormattedOrNull(currency, text, locale)) {
        |    "Cannot parse ${'$'}{currency.code} amount: '${'$'}text'"
        |}
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/** `CldrDateTime`-shaped binding: the source object plus the datetime extensions. */
public fun emitDateTimeBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "LocalizedFormat.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi",
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.datetime.DateTimeFormatSource",
                "dev.carcara.kotlinx.locale.datetime.FormatStyle",
                "dev.carcara.kotlinx.locale.datetime.TextStyle",
                "dev.carcara.kotlinx.locale.datetime.cldr.runtime.PayloadDateTimeFormats",
                "dev.carcara.kotlinx.locale.datetime.displayName",
                "dev.carcara.kotlinx.locale.datetime.format",
                "${spec.registryPackage}.localeDataRegistry",
                "kotlinx.datetime.DayOfWeek",
                "kotlinx.datetime.LocalDate",
                "kotlinx.datetime.LocalDateTime",
                "kotlinx.datetime.LocalTime",
                "kotlinx.datetime.Month",
            ),
        ) + """
        |
        |/**
        | * The date and time patterns this build carries.
        | *
        | * The parser and formatter live in `kotlinx-locale-datetime-cldr-runtime`; all
        | * this object contributes is the table.
        | */
        |public object ${spec.objectName} : DateTimeFormatSource by PayloadDateTimeFormats(localeDataRegistry) {
        |
        |    /**
        |     * The pattern table itself, for an engine layered over this one.
        |     *
        |     * Skeleton formatting needs it: matching scores against the four
        |     * standard date and four standard time patterns as well as against the
        |     * skeleton table, and rendering the winner needs the month and weekday
        |     * names. Exposing the table beats making
        |     * `kotlinx-locale-datetime-cldr-skeletons` carry a second copy of it.
        |     */
        |    @InternalKotlinxLocaleApi
        |    public val records: Map<String, String> get() = localeDataRegistry
        |}
        |
        |/**
        | * Formats this date with the locale's standard date pattern of the given [style].
        | *
        | * ```
        | * LocalDate(2026, 7, 27).format(FormatStyle.LONG, Locale.forLanguageTag("pt-BR"))
        | * // "27 de julho de 2026"
        | * ```
        | */
        |public fun LocalDate.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this time with the locale's standard time pattern of the given [style].
        | *
        | * Time-zone fields present in the FULL and LONG patterns are omitted, since a
        | * [LocalTime] carries no zone information.
        | */
        |public fun LocalTime.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this date-time by combining the locale's date and time patterns with
        | * its "glue" pattern (e.g. `Sunday, July 27, 2026, 3:05 PM` for `en`).
        | */
        |public fun LocalDateTime.format(dateStyle: FormatStyle, timeStyle: FormatStyle, locale: Locale): String =
        |    ${spec.objectName}.format(this, dateStyle, timeStyle, locale)
        |
        |/** Formats this date-time using the same [style] for the date and time parts. */
        |public fun LocalDateTime.format(style: FormatStyle, locale: Locale): String = format(style, style, locale)
        |
        |/** The localized name of this month in the "format" context, e.g. `julho`. */
        |public fun Month.displayName(style: TextStyle, locale: Locale): String = ${spec.objectName}.displayName(this, style, locale)
        |
        |/** The localized name of this day of week in the "format" context, e.g. `segunda-feira`. */
        |public fun DayOfWeek.displayName(style: TextStyle, locale: Locale): String =
        |    ${spec.objectName}.displayName(this, style, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/**
 * `CldrDateTimeSkeletons`-shaped binding: the source object plus the skeleton
 * extensions.
 *
 * [dateTimeObject] is the fully qualified datetime binding whose table this
 * reads. It is a parameter rather than a constant because the Gradle plugin
 * names its own objects, and a narrowed build has to bind its skeletons to its
 * own patterns rather than to the shipped ones.
 */
public fun emitSkeletonBinding(outputRoot: File, spec: BindingSpec, dateTimeObject: String) {
    val file = outputRoot.packageFile(spec.packageName, "SkeletonFormat.kt")
    val dateTimePackage = dateTimeObject.substringBeforeLast('.')
    val dateTimeName = dateTimeObject.substringAfterLast('.')
    val imports = listOf(
        "dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi",
        "dev.carcara.kotlinx.locale.Locale",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.PayloadSkeletonFormats",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.SkeletonFormatSource",
        "dev.carcara.kotlinx.locale.datetime.cldr.runtime.format",
        "kotlinx.datetime.LocalDate",
        "kotlinx.datetime.LocalDateTime",
        "kotlinx.datetime.LocalTime",
        "${spec.registryPackage}.skeletonAppendFormatsRegistry",
        "${spec.registryPackage}.skeletonFormatsRegistry",
        "${spec.registryPackage}.skeletonNamesRegistry",
    ) + listOfNotNull(dateTimeObject.takeIf { dateTimePackage != spec.packageName })

    file.writeText(
        preamble(spec, imports, fileAnnotation = "@file:OptIn(InternalKotlinxLocaleApi::class)") + """
        |
        |/**
        | * The skeleton tables this build carries.
        | *
        | * The matcher lives in `kotlinx-locale-datetime-cldr-runtime`; all this
        | * object contributes is the tables, plus the pattern table it borrows from
        | * [$dateTimeName] rather than carrying twice.
        | */
        |public object ${spec.objectName} : SkeletonFormatSource by PayloadSkeletonFormats(
        |    skeletonFormatsRegistry,
        |    skeletonAppendFormatsRegistry,
        |    skeletonNamesRegistry,
        |    $dateTimeName.records,
        |)
        |
        |/**
        | * Formats this date with the fields [skeleton] names, arranged the way
        | * [locale] arranges them.
        | *
        | * ```
        | * LocalDate(2026, 7, 27).format("yMMMd", Locale.forLanguageTag("pt-BR"))
        | * // "27 de jul. de 2026"
        | * ```
        | */
        |public fun LocalDate.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/** Formats this time with the fields [skeleton] names. */
        |public fun LocalTime.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/**
        | * Formats this date-time with the fields [skeleton] names, joining the date
        | * and time halves with the locale's own glue pattern when the skeleton spans
        | * both.
        | */
        |public fun LocalDateTime.format(skeleton: String, locale: Locale = Locale.current): String =
        |    ${spec.objectName}.format(this, skeleton, locale)
        |
        |/**
        | * The pattern [locale] uses for [skeleton], or `null` when the skeleton names
        | * a field that cannot be rendered.
        | *
        | * Useful on its own: the pattern drives `kotlinx-datetime`'s `DateTimeFormat`,
        | * which is how a skeleton buys locale aware parsing and not only formatting.
        | */
        |public fun skeletonPatternOrNull(skeleton: String, locale: Locale = Locale.current): String? =
        |    ${spec.objectName}.skeletonPatternOrNull(skeleton, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

internal fun File.packageFile(packageName: String, fileName: String): File =
    resolve(packageName.replace('.', '/')).apply { mkdirs() }.resolve(fileName)
