/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import java.io.File

private const val CATALOG_PACKAGE = "dev.carcara.kotlinx.locale.catalog"

/**
 * CLDR macroregion codes that appear in locale ids. They are digits, so they
 * cannot be Kotlin identifiers, and backticking them would produce JVM field
 * names Java callers cannot reference. CLDR's own English names instead.
 *
 * Codegen fails rather than guessing if CLDR grows one that is not listed.
 */
private val MACROREGION_NAMES = mapOf(
    "001" to "WORLD",
    "150" to "EUROPE",
    "419" to "LATIN_AMERICA",
)

/**
 * Emits the locale catalog into the -types layer: one enum per language,
 * implementing `LocaleRef`, with an entry per regional locale that language
 * covers and the bare language on the companion.
 *
 * The bare language is the companion rather than a `BASE` entry because a class
 * name in expression position resolves to its companion, so `PT` *is* the `pt`
 * locale and `PT.BR` is `pt-BR`. A type cannot be a value of itself, and this is
 * as close as Kotlin gets. It also keeps the name uniform: every segment of a
 * reference is upper case, `PT.BR` and not `Pt.BR`.
 *
 * A language whose bare tag was filtered out gets no companion, so naming it
 * does not compile — the same protection the entries already give.
 *
 * The nesting follows the *identifier* structure, not the CLDR parent chain.
 * Those differ — `en-150`'s parent is `en-001` and `zh-Hant-MO`'s is
 * `zh-Hant-HK` — and the parent chain is runtime data that belongs to the
 * implementation modules, where it already lives.
 *
 * Two levels, so a reference is always `LANGUAGE.REST`: only 33 of the 322
 * languages carry a script, and a third level would pay for those in every
 * other reference.
 */
public fun emitLocaleCatalog(outputDir: File, cldrTag: String, localeTags: List<String>) {
    outputDir.mkdirs()
    outputDir.listFiles { f: File -> f.extension == "kt" }?.forEach(File::delete)

    val tagsByLanguage = LinkedHashMap<String, MutableList<String>>()
    for (tag in localeTags.sorted()) {
        tagsByLanguage.getOrPut(tag.substringBefore('-')) { ArrayList() }.add(tag)
    }

    for ((language, tags) in tagsByLanguage) {
        val className = language.uppercase()
        val hasBare = tags.any { it == language }
        val members = LinkedHashMap<String, String>()
        for (tag in tags) {
            if (tag == language) continue
            val member = memberNameFor(language, tag)
            val clash = members.put(member, tag)
            check(clash == null) { "$language: '$member' names both $clash and $tag" }
        }
        outputDir.resolve("$className.kt").writeText(
            buildString {
                append(LICENSE_HEADER + "// GENERATED by :codegen from CLDR ")
                append(cldrTag)
                append(". Do not edit.\n")
                append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
                append("package ")
                append(CATALOG_PACKAGE)
                append("\n\nimport dev.carcara.kotlinx.locale.LocaleRef\n")
                append("\n/**\n * The CLDR locales whose language subtag is `")
                append(language)
                append("`.\n *\n * ")
                if (hasBare) {
                    append(className)
                    append(" itself is the bare language, `")
                    append(language)
                    append("`; the entries are the locales below it.\n */\n")
                } else {
                    append("The bare language `")
                    append(language)
                    append("` is not in this build, so `")
                    append(className)
                    append("` names no locale on its own.\n */\n")
                }
                append("public enum class ")
                append(className)
                append("(override val tag: String) : LocaleRef {\n")
                for ((member, tag) in members) {
                    append("    ")
                    append(member)
                    append("(\"")
                    append(kotlinEscape(tag))
                    append("\"),\n")
                }
                append("    ;\n")
                if (hasBare) {
                    append("\n    /** The bare language, `")
                    append(language)
                    append("`. */\n")
                    append("    public companion object : LocaleRef {\n")
                    append("        override val tag: String = \"")
                    append(kotlinEscape(language))
                    append("\"\n")
                    append("    }\n")
                }
                append("}\n")
            },
        )
    }

    println("[codegen] emitted ${tagsByLanguage.size} language catalogs (${localeTags.size} locales) to $outputDir")
}

/** `pt-BR` -> `BR`, `zh-Hans-CN` -> `HANS_CN`, `es-419` -> `LATIN_AMERICA`. */
private fun memberNameFor(language: String, tag: String): String =
    tag.removePrefix(language).removePrefix("-").split('-').joinToString("_") { part ->
        if (part.first().isDigit()) {
            MACROREGION_NAMES[part]
                ?: error("No identifier name for region '$part' in locale tag '$tag'; add it to MACROREGION_NAMES")
        } else {
            part.uppercase()
        }
    }
