/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import dev.carcara.kotlinx.locale.codegen.pipeline.CodecReport
import dev.carcara.kotlinx.locale.codegen.pipeline.PayloadCodec
import dev.carcara.kotlinx.locale.codegen.pipeline.PayloadCodecValidator
import dev.carcara.kotlinx.locale.codegen.pipeline.PayloadShape
import dev.carcara.kotlinx.locale.codegen.pipeline.RecordFormat
import java.io.File

/**
 * The record separators the payload format uses, shared by the writers and the
 * runtime decoders.
 *
 * `RecordFormat` owns them now, because the codecs that take a record apart are
 * the code that has to agree on them. They keep these names here because the
 * extraction half of the generator writes records by hand and reads them back in
 * its own tests.
 */
public const val FIELD_SEPARATOR: String = RecordFormat.FIELD
public const val LIST_SEPARATOR: String = RecordFormat.ENTRY
public const val KEY_SEPARATOR: String = RecordFormat.KEY

public fun kotlinEscape(value: String): String = buildString(value.length + 8) {
    for (ch in value) {
        when {
            ch == '\\' -> append("\\\\")
            ch == '"' -> append("\\\"")
            ch == '$' -> append("\\$")
            ch.code < 0x20 || ch.code == 0x7F -> append("\\u%04X".format(ch.code))
            else -> append(ch)
        }
    }
}

/**
 * The inverse of [kotlinEscape]: the string a generated literal stands for.
 *
 * Anything measuring what a generated source costs has to read the value rather
 * than the text that spells it, because the escape is six characters and the
 * character it names is one, and it is the character that reaches the artifact.
 * `EscapeRoundTripTest` holds the two together.
 */
public fun kotlinUnescape(literal: String): String = buildString(literal.length) {
    var index = 0
    while (index < literal.length) {
        val ch = literal[index]
        if (ch != '\\') {
            append(ch)
            index++
            continue
        }
        when (val escape = literal[index + 1]) {
            'u' -> {
                append(literal.substring(index + 2, index + 6).toInt(16).toChar())
                index += 6
            }
            'n' -> {
                append('\n')
                index += 2
            }
            'r' -> {
                append('\r')
                index += 2
            }
            't' -> {
                append('\t')
                index += 2
            }
            else -> {
                append(escape)
                index += 2
            }
        }
    }
}

/** CLDR file id (en_GB, sr_Cyrl_BA, ca_ES_VALENCIA) -> canonical tag (en-GB, sr-Cyrl-BA, ca-ES-valencia). */
public fun canonicalTag(cldrId: String): String {
    val parts = cldrId.split('_')
    return buildList(parts.size) {
        add(parts[0].lowercase())
        for (part in parts.drop(1)) {
            add(
                when {
                    part.length == 4 && part.all(Char::isLetter) ->
                        part.lowercase().replaceFirstChar(Char::uppercaseChar)
                    (part.length == 2 && part.all(Char::isLetter)) ||
                        (part.length == 3 && part.all(Char::isDigit)) -> part.uppercase()
                    else -> part.lowercase()
                },
            )
        }
    }.joinToString("-")
}

/**
 * Emits a locale-tag-keyed payload registry into [outputDir]: deduplicated string
 * constants bucketed into one file per first letter of the owning tag, plus a
 * registry map file.
 *
 * Every locale-keyed table in the library is this shape. The datetime table used
 * to have an emitter of its own that differed only in two hard-coded prefixes,
 * which is why it does not any more.
 *
 * Only files this emitter owns are deleted before writing. The shipped layout
 * gives each table its own directory, but a source set generated by the Gradle
 * plugin puts them all in one, so deleting every `.kt` here would wipe the
 * neighbours.
 */
public class KeyedPayloadEmitter(
    private val outputDir: File,
    private val packageName: String,
    private val filePrefix: String,
    private val constPrefix: String,
    private val registryProperty: String,
    private val source: String,
    private val versionConst: Pair<String, String>? = null,
    /**
     * How this table's records are laid out, which is all the codec is told
     * about it.
     */
    private val shape: PayloadShape = PayloadShape.Resolved,
    /**
     * The rewrite applied to the records on the way out, defaulting to none.
     *
     * The emitter runs it last and validates it before writing a byte, so a
     * codec that loses data fails the build rather than the locale. Passing
     * [PayloadCodec.Identity] is how a build turns the pipeline off, and it is
     * what every caller gets until one asks for something else.
     */
    private val codec: PayloadCodec = PayloadCodec.Identity,
    /**
     * Where the two packed forms go, when a build asks for them.
     *
     * Null means one form for every target, written into [outputDir], which is
     * what the identity codec and the key elision codec want. Non-null means the
     * data is packed, and packed data cannot be shared: the same bytes want
     * seven bits a character where a target bills by character value and fifteen
     * where it bills by the each. The registry then becomes an `expect` in
     * common with an `actual` in each of these.
     */
    private val packedRoots: Map<String, PayloadCodec>? = null,
) {
    private fun header(): String = LICENSE_HEADER + """
        |// GENERATED by :codegen from $source. Do not edit.
        |// Regenerate with: ./gradlew :codegen:generateLocaleData
        |package $packageName
        |
    """.trimMargin()

    /**
     * The registry's header, which needs the opt-in when a codec left tables
     * behind: the reserved key naming them is internal API, and a file-level
     * annotation has to precede the package declaration.
     */
    private fun registryHeader(withTables: Boolean): String {
        if (!withTables) return header()
        return LICENSE_HEADER + """
            |// GENERATED by :codegen from $source. Do not edit.
            |// Regenerate with: ./gradlew :codegen:generateLocaleData
            |@file:OptIn(dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi::class)
            |
            |package $packageName
            |
            |import dev.carcara.kotlinx.locale.internal.CODEC_TABLES_KEY
            |
        """.trimMargin()
    }

    private fun constNameFor(tag: String): String = constPrefix + "_" + tag.uppercase().replace('-', '_')

    /**
     * Writes the table, after handing it to the codec.
     *
     * Returns what the codec did, so a caller that runs many tables can add the
     * numbers up. The record deduplication below happens after encoding rather
     * than before, because a codec that hoists the keys out can make two locales
     * that differed only in their key order into the same record, and that is a
     * constant saved.
     */
    public fun emit(payloadByTag: Map<String, String>): CodecReport {
        packedRoots?.let { return emitPacked(payloadByTag, it) }
        val report = PayloadCodecValidator.require(codec, shape, filePrefix, payloadByTag)
        val encoded = report.encoded

        outputDir.mkdirs()
        outputDir.listFiles { f: File -> f.extension == "kt" && f.name.startsWith(filePrefix) }
            ?.forEach(File::delete)

        val constByPayload = LinkedHashMap<String, String>()
        val constByTag = LinkedHashMap<String, String>()
        for ((tag, payload) in encoded.payloadByTag) {
            val const = constByPayload.getOrPut(payload) { constNameFor(tag) }
            constByTag[tag] = const
        }

        val ownersByBucket = LinkedHashMap<Char, MutableList<Pair<String, String>>>()
        for ((payload, const) in constByPayload) {
            val ownerTag = const.removePrefix(constPrefix + "_").lowercase()
            ownersByBucket.getOrPut(ownerTag.first()) { ArrayList() }.add(const to payload)
        }
        for ((bucket, consts) in ownersByBucket) {
            outputDir.resolve("${filePrefix}_$bucket.kt").writeText(
                buildString {
                    append(header())
                    for ((const, payload) in consts.sortedBy { it.first }) {
                        append("\ninternal val ")
                        append(const)
                        append(": String =\n    \"")
                        append(kotlinEscape(payload))
                        append("\"\n")
                    }
                },
            )
        }

        outputDir.resolve("${filePrefix}Registry.kt").writeText(
            buildString {
                append(registryHeader(encoded.sharedTables.isNotEmpty()))
                versionConst?.let { (name, value) ->
                    append("\ninternal const val ")
                    append(name)
                    append(": String = \"")
                    append(kotlinEscape(value))
                    append("\"\n")
                }
                append("\ninternal val ")
                append(registryProperty)
                append(": Map<String, String> = buildMap(")
                append(constByTag.size)
                append(") {\n")
                for ((tag, const) in constByTag.entries.sortedBy { it.key }) {
                    append("    put(\"")
                    append(kotlinEscape(tag))
                    append("\", ")
                    append(const)
                    append(")\n")
                }
                // A codec's shared tables ride in the registry under a reserved
                // key rather than in a property of their own, so that a table
                // which elides its keys and one which does not are the same type
                // and every source reads them the same way. Written only when a
                // codec produced them, which keeps the identity codec's output
                // byte for byte what it was.
                if (encoded.sharedTables.isNotEmpty()) {
                    append("    put(CODEC_TABLES_KEY, \"")
                    append(kotlinEscape(codec.id + FIELD_SEPARATOR + encoded.sharedTables.joinToString(FIELD_SEPARATOR)))
                    append("\")\n")
                }
                append("}\n")
            },
        )

        println("[codegen] emitted $registryProperty: ${report.describe()} to $outputDir")
        return report
    }

    /**
     * One `expect` in common, one `actual` per packing.
     *
     * Every target sees the same registry property and the same reader; only the
     * bytes behind it differ, and only in how they were written down.
     */
    private fun emitPacked(payloadByTag: Map<String, String>, roots: Map<String, PayloadCodec>): CodecReport {
        var last: CodecReport? = null
        for ((sourceSet, packedCodec) in roots) {
            val report = PayloadCodecValidator.require(packedCodec, shape, filePrefix, payloadByTag)
            val dir =
                File(outputDir.path.replace("${File.separator}commonMain${File.separator}", "${File.separator}$sourceSet${File.separator}"))
            dir.mkdirs()
            dir.listFiles { f: File -> f.extension == "kt" && f.name.startsWith(filePrefix) }?.forEach(File::delete)

            val constByPayload = LinkedHashMap<String, String>()
            val constByTag = LinkedHashMap<String, String>()
            for ((tag, payload) in report.encoded.payloadByTag) {
                constByTag[tag] = constByPayload.getOrPut(payload) { constNameFor(tag) }
            }
            val byBucket = LinkedHashMap<Char, MutableList<Pair<String, String>>>()
            for ((payload, const) in constByPayload) {
                byBucket.getOrPut(const.removePrefix(constPrefix + "_").lowercase().first()) { ArrayList() }
                    .add(const to payload)
            }
            for ((bucket, consts) in byBucket) {
                dir.resolve("${filePrefix}_$bucket.kt").writeText(
                    buildString {
                        append(header())
                        for ((const, payload) in consts.sortedBy { it.first }) {
                            append("\ninternal val ").append(const).append(": String =\n    \"")
                            append(kotlinEscape(payload)).append("\"\n")
                        }
                    },
                )
            }
            // A different file name from the common expect: two files of the
            // same name in one compilation would generate one JVM facade class
            // twice. Only one packing compiles per target, so both may share it.
            dir.resolve("${filePrefix}RegistryPacked.kt").writeText(
                buildString {
                    append(registryHeader(report.encoded.sharedTables.isNotEmpty()))
                    append("\ninternal actual val ").append(registryProperty)
                    append(": Map<String, String> = buildMap(").append(constByTag.size + 1).append(") {\n")
                    for ((tag, const) in constByTag.entries.sortedBy { it.key }) {
                        append("    put(\"").append(kotlinEscape(tag)).append("\", ").append(const).append(")\n")
                    }
                    // The key universes and the bitmap pool the elision step
                    // hoisted out. Not packed: they are read to find where a key
                    // sits, which has to work before anything is inflated.
                    if (report.encoded.sharedTables.isNotEmpty()) {
                        append("    put(CODEC_TABLES_KEY, \"")
                        append(
                            kotlinEscape(
                                packedCodec.id + FIELD_SEPARATOR +
                                    report.encoded.sharedTables.joinToString(FIELD_SEPARATOR),
                            ),
                        )
                        append("\")\n")
                    }
                    append("}\n")
                },
            )
            println("[codegen] emitted $registryProperty into $sourceSet: ${report.describe()}")
            last = report
        }

        // The common half: the declaration every reader compiles against.
        outputDir.mkdirs()
        outputDir.listFiles { f: File -> f.extension == "kt" && f.name.startsWith(filePrefix) }
            ?.forEach(File::delete)
        outputDir.resolve("${filePrefix}Registry.kt").writeText(
            buildString {
                append(header())
                versionConst?.let { (name, value) ->
                    append("\ninternal const val ").append(name).append(": String = \"")
                    append(kotlinEscape(value)).append("\"\n")
                }
                append("\n/** Packed and compressed; read it through `decodePayload`. */\n")
                append("internal expect val ").append(registryProperty).append(": Map<String, String>\n")
            },
        )
        return last ?: error("no packed roots were configured for $filePrefix")
    }

    public companion object
}
