/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_WO: String =
    "00hJ终彂恆ई⭻Ꮨࢭ尫䑉㥫ຳ⧴哒〶筷㕔䵬អ❊඀Ṍ匴ℳ蕒媕ᭆ㉕ẫṻ坬㑂芋䭃㊮莏䄦⥜ᳫ傋⊣荸疌⇗㔪⅊䮬䊼䫮⚣ຯ䉯䙻䋶㨄穡࿁㷺䋤瀫笼狁瓖舟⻺᎗膰ஓᐷ䴷᳜ໃ禴㐢ዸ䕘䢞ᝥज़⢉૛れⲊ䭎Ἅ紀捂敩嚫㽁甲㛠"
