/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_UK: String =
    "00d1窪櫃塄ॏ炝汾⥛蒅杂ᅅ⤻്汗便㭘蒀穕嶚痑〷晵羜䒀洴㦢⣶扳傌䆹⠚媘೦娍फ़䠭ㆹ಄⨱䴬犯㙶ᳬ㥢䃩凮⥌䝀し肬㤾梎㧳▶ຝㆿㄬᇻ縻䬩㴃擉ແ䉔ᱠ舫㊯㸇❗砾坟῝౭簪ⳙ燗懢䢮簏∑穜茼煠㤻蒍㻃眷煶毪粦牰∱␓㳒ᣎ⼈㵻艊粣▸䚃ᴴ彤烝壆葓殃䋙荐協籯๱᫣⮽糹氍㗟䘫䝧⭼俒吗ᬸ定᠚猔䡐䮐ဝ₢ᑹઙ焬༬࣠᭓沨㙂瀞⊉⫶腺䦭舊"

internal val PERSON_NAMES_UR: String =
    "00Mq暩䍃䁄्樦耈珔቎⤖ᶅᴔ≘傐倝栯忱揉縚忡䌛㭊ᐈᄝ毮曩䡓㤆ሃ蝙⍵႔ዌⳝ㻒䑂㤕♡ዏ砄䐪荐脦⊰ࢱ皜橇ᒒ፜ᙸᰡᠸ嗌④㿄穥㟛᧿繟嫦㽢蛚萱纽艎䒴↝๟稸檤⤊䲧㭛㪄澗喪搄綴灕戃猂欴ጌ蚫藇妈䏅䏗嬬蜃蔲ᮥ孷⧴伽翞ゕぅ䨂臹蕯⼟㕌萖᭒椃兴⨸㪘Ⱖᄔ⭰☐ᮟᵇધࡎ嚁㛏⁍填膃ࠀ"

internal val PERSON_NAMES_UZ: String =
    "00M/曉䯃塄ঌ㍹ၰ䢶綅⽡䔴猟伒䵳᭰艔㵓㓓㳬⤰㧼螿଎全ౡ悼蕉滹ፑᰤᑭሔ樐઒匭耣㢊剅ᮊძ䣀ቚ‼຺䀹恉䈕‫椡㣶ᬬ掚珱狍⫖ᑖ藱ᒽ绮ᇐ䯯╨懭ଔ៑㑺⚽彭嘟㛫耹梠嫟ᯭ࣮棒澏淞᧹徛ᇛ擏᭘懷ধ艏潇⊙ຑ㈰◈犺䠉吔᭸粼翘㾲弛䜐楪䩳檅⾩ᤖ⃫൮克䴧溼બῄᡓ溨䣈䖓⮝俯嘏⎢䘀"
