/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_BA: String =
    "00O4櫊ୃ塆ࣈ㍾ᇨࡣ爕☤浪抿憀ሲ緙皂䰈╿樆䩄ᚽ晞攞ព䂓穠卞ヷ⿤籔擒瘵嶹⩍ጙ喖䧸೚甩ᣏᐲ芨兣猥胅ㅂ睬䲮䌷ᶎ摯㰑䭤摙ㄘ孏䁍蚂肓搼⽕杌燾槯扼㣡⅟濡㈔䉼㺈జ㼐䭞⪯槻䉁哥焜歮䙆Ꮥ䯾䍪䞍潝层ಧ羇ၑ䗲㡪㥵㿴㣆䐶卥䑐翖徖捎௬㗔ࣃ᳻㽛秫᣽䜳⟤㋧ᣪਲ਼ስ椣㠣搲ᄹ檺ᅅ౳᪕ⵠ⑎⨳腣䖻悞"

internal val PERSON_NAMES_BAL_LATN: String =
    "00hK纨廂恆ऋ汎氍㢣㟠ⲫ㛵唃焣Ⱘ燉皷ㄔ惼䰽㱶ࡉ᤬呤汧㦖拑ब㩁憞䗏㰘䜸䥍秪ῇ䮒幆屎㊝ጸ⯷胛㰵挙㈒窅Ⱶ䓺∴ᭀ᡺⮿⋑㾾ࣵ栟⯖穫瓑叧擙䳚㞾ຩ螢檞搃莘䍊䜩昄桲圖棊㐑油梁䁜㸐琡摎⤩剠櫈蚷ⰺዟ䱵㗺໱ᆷ⠠"

internal val PERSON_NAMES_BE: String =
    "00MO滉䫃恄ࣈ㭹ჷࡡ爕☄掕㈣梽摢㋢缷⍻ⵆộ䦁ℏ㴿絫࠽者劁蛗໿ᩬ呣။溺瀰⥊撉䩖窀㒥㛴甥ᆖ䀰峧䥝䶇弔攅嵊ឆ⳥⤶ṇ༕㛑昸嶭壓ྟ䂻➜峪୸嫱䥒慛ଷ肶励䙺䍨烣壛㾣⚰付ड़䕴蝛嚱虜翄勼⿤叿⬴䣓㈌搁矏婘硏㿶涀➅៱䙩᪩఻ᨓ䦙榢磣䁧෺値⬞⳩ኂ⒈䋭涔欂斻஀"

internal val PERSON_NAMES_BG: String =
    "00O9皩捃恄࣋癏⠆䂣㟠⳨╬腐縙抈ⷝ㝆⮛⧓᫽ᣤ᠝ᷱ腹㻔㎪ਝ㐁⮪୞䜓炥彇䃄䉖䭮䤻፜ၢ崕䄨㛱耇ኬ⦻䄿味色宨列䭥洂縼垽᧨耴禴䑽莋䨿繃僘₦簓罨抆塡㎶㱸虡㎈ᠤ坺㻴紏㦃楑啿᜝舰叨禽࿫掅ⵆ参ᵫ艑葤シ藯䋛溢圆┍෇䐷哩ᐔ慧ദఞ⃆虧≱㬏㡚窘኶૘䓬‏୒丸㿌㤣ᕙἦ焠搲斗囜艛⡧㽡㠀"

internal val PERSON_NAMES_BLO: String =
    "00Pd檩䫃恄࣋癏⠕哨忰ᩴ␨垁喴沣䧝囍㯩楓㨍ಊຏ揃籑㿢到஻⋖⇊呚兄畷ஞ吵㶬仑Ⲹ䄼椭㹅浫孆ㅨ櫒㖉勍㤭彊ፂ㪥⥖䉪㚃ଟ⤇㭀⸲ᒫ蘧デ索㇯ᢵ朽䱎慢繌䌳膺巟斅券କⒼ兵擦䤺涺嶽䷰☪Ἃ淆熶莉⡐䦔僉஦伮‖猴⣧蒒望蕲催䅬䨓ূ僡幰粼猅犟ౖ઴苈戁厷ⱟ疑㟜฀"

internal val PERSON_NAMES_BN: String =
    "00bS终⭂塆ै㛾᭴ឡぞ墓幞㹺ῦ᧑༟䑺ᔥ崄櫔娘渋杣䮻䫹㹢ኣ䧭吆撮᛭愍孩Ⰲឩ藞䈓ሺ棇ẕἄ䒉ᚉঌ䊎絳┍ᢨ瀪⇥䘣叩䕫姪ួ肮螺㴟惴䲈捿績慩樫佳䇗藱⹌㐱咀䔡⍤㎲亶ⶳ滟剧壚◞࠱䳈ᙻ⳧ચ䣊耽೤⬂䀲䦎ⴅ窂㺘苭畕省斸ᔀ"

internal val PERSON_NAMES_BR: String =
    "00hG终廂恆ऄ㎻ᆘભ尭摉∱䭙䰿᥃⬣䓛ⵒ橲ᣵ᧸⤄䰲㮸勮嘊℔㬤፛∗哶盻榢↮䃕⦲硨䀒㩅䇱䕈䅪ិ仛㦭姝䁪斫ᙞ䚏ᝂ禺⚛瞚炻䲀█槲ᴿ㝆暆攸涭徥艡嶿䐈䧸倃咩咶萲ᆈ紱䶣㠷帶䁔縑岋䂜咣倨瓨皳⪰㿪㎮耴㹈喾ী"

internal val PERSON_NAMES_BRX: String =
    "00hT终廂恆ऄ㎻ᆘભ尭摉㱣亳ま⪎婂莶劥䱶槪௰娙ࡤ潱῝␔㨨ⴈ㊶⩯⇦攷䭆㮨峗纲箴䄤沅⧲䕊ㅪិ䫛㦵姎堔彫䦳濎㧐㱎㾮翮昨穠໧炽ୟ垆暆攸ⶫᝏ绁㉿肱ளᠧᣆ䓓蓌⠭ឋ⪚ᅛ⎨姁ተ拲ᄀ᠈㴄緒ᘇ㢄甬㥫慛宨ਚዋ䙴㗒൯側"

internal val PERSON_NAMES_BS: String =
    "00Rn溩ୃ塄ঋ瑋䨁懊ᴺಒ乂縐⍁㜟䎤ニᇹ毕㑀⡷瑿䏳处ᴔᗔᓜ惛拴嗄䤩榊禶ⵦ৺婸ઞ䀢॒㵐蜜ᄿ篁ၺ䪈客⵱綀箞㮁㑆ሏ㰓㭀畗⚋௝构櫹㓋ཤ祑㐿㱋孵ᬯ簰硑猧㙀㻉䌥‖㭉䠐✿▷橛㨿ऎ㎷椚ᅙ蝇䃡㉔䍞呱䏽䯓磲㮊珽⋐㟳ᷚ嘈繝ാ់⚌榁᥄茊三弜眄朊ও祼ஂぐ࿪ᬀ淐旙卩崎虨㐀"
