package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * Emits the source object that binds a generated table to its domain interface,
 * together with the convenience extensions over it.
 *
 * The shipped `-cldr` artifacts and anything the Gradle plugin generates both
 * come from here, so `Country.BR.displayName(locale)` means the same thing in a
 * full build and in a build narrowed to three locales, and switching between
 * them is a dependency change plus one import.
 *
 * This is the only emitter that writes anything other than data. What it writes
 * is a delegation and a set of one-line extensions, all of it derived from the
 * object name and the package, which is why it cannot drift from the format it
 * delegates to.
 */
public class BindingSpec(
    /** Where the object and its extensions go, e.g. `com.example.locale`. */
    public val packageName: String,
    /** The object's name, e.g. `CldrCountry` or `GeneratedCountryNames`. */
    public val objectName: String,
    /** Where the generated table lives, normally `<packageName>.internal.data`. */
    public val registryPackage: String,
    /** What the header credits the data to. */
    public val source: String,
)

/**
 * The header plus a sorted import block.
 *
 * Sorting here rather than in the templates is what keeps the registry import,
 * whose package is a parameter, in the position ktlint expects.
 */
private fun preamble(spec: BindingSpec, imports: List<String>): String = buildString {
    append("// GENERATED by :codegen from ")
    append(spec.source)
    append(". Do not edit.\n")
    append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
    append("package ")
    append(spec.packageName)
    append("\n\n")
    for (import in imports.sorted()) {
        append("import ")
        append(import)
        append("\n")
    }
}

/** `CldrCountry`-shaped binding: the source object plus the country extensions. */
public fun emitCountryBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "CountryNames.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.country.Country",
                "dev.carcara.kotlinx.locale.country.CountryNameSource",
                "dev.carcara.kotlinx.locale.country.cldr.format.PayloadCountryNames",
                "dev.carcara.kotlinx.locale.country.countryForDisplayNameOrNull",
                "dev.carcara.kotlinx.locale.country.displayName",
                "${spec.registryPackage}.countryNamesRegistry",
            ),
        ) + """
        |
        |/**
        | * The country names this build carries.
        | *
        | * The lookup lives in `kotlinx-locale-country-cldr-format`; all this object
        | * contributes is the table.
        | */
        |public object ${spec.objectName} : CountryNameSource by PayloadCountryNames(countryNamesRegistry)
        |
        |/**
        | * The country name for [locale], resolved through the locale's inheritance
        | * chain; falls back to the alpha-2 code when there is no name.
        | */
        |public fun Country.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        |/**
        | * The country whose display name in [locale] matches [name],
        | * case-insensitively, or `null`.
        | */
        |public fun Country.Companion.forDisplayNameOrNull(name: String, locale: Locale = Locale.current): Country? =
        |    ${spec.objectName}.countryForDisplayNameOrNull(name, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/** `CldrCurrency`-shaped binding: the source object plus the currency extensions. */
public fun emitCurrencyBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "CurrencyNames.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.currency.Currency",
                "dev.carcara.kotlinx.locale.currency.CurrencyAmount",
                "dev.carcara.kotlinx.locale.currency.CurrencyFormatSource",
                "dev.carcara.kotlinx.locale.currency.CurrencyNameSource",
                "dev.carcara.kotlinx.locale.currency.CurrencySymbolStyle",
                "dev.carcara.kotlinx.locale.currency.cldr.format.PayloadCurrencyFormats",
                "dev.carcara.kotlinx.locale.currency.cldr.format.PayloadCurrencyNames",
                "dev.carcara.kotlinx.locale.currency.code",
                "dev.carcara.kotlinx.locale.currency.displayName",
                "dev.carcara.kotlinx.locale.currency.format",
                "dev.carcara.kotlinx.locale.currency.parseFormattedOrNull",
                "dev.carcara.kotlinx.locale.currency.symbol",
                "${spec.registryPackage}.currencyFormatsRegistry",
                "${spec.registryPackage}.currencyNamesRegistry",
            ),
        ) + """
        |
        |/**
        | * The currency symbols, display names and number formats this build carries.
        | *
        | * The delegation is written out rather than expressed with `by` because both
        | * interfaces declare `supportedLocales`, and being explicit about which one
        | * answers beats resolving the clash with a one-line override.
        | */
        |public object ${spec.objectName} : CurrencyNameSource, CurrencyFormatSource {
        |
        |    private val names = PayloadCurrencyNames(currencyNamesRegistry)
        |    private val formats = PayloadCurrencyFormats(currencyFormatsRegistry, currencyNamesRegistry)
        |
        |    // The two tables cover the same locale set, so either answer is the same.
        |    override val supportedLocales: Set<Locale>
        |        get() = formats.supportedLocales
        |
        |    override fun currencySymbolOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencySymbolOrNull(currencyCode, locale)
        |
        |    override fun currencyNameOrNull(currencyCode: String, locale: Locale): String? =
        |        names.currencyNameOrNull(currencyCode, locale)
        |
        |    override fun formatOrNull(
        |        minorUnits: Long,
        |        currencyCode: String,
        |        locale: Locale,
        |        style: CurrencySymbolStyle,
        |        accounting: Boolean,
        |        cash: Boolean,
        |    ): String? = formats.formatOrNull(minorUnits, currencyCode, locale, style, accounting, cash)
        |
        |    override fun parseToMinorUnitsOrNull(text: String, currencyCode: String, locale: Locale): Long? =
        |        formats.parseToMinorUnitsOrNull(text, currencyCode, locale)
        |}
        |
        |/** The currency symbol for [locale], e.g. `US${'$'}` for USD in pt-BR; falls back to the ISO code. */
        |public fun Currency.symbol(locale: Locale = Locale.current): String = ${spec.objectName}.symbol(this, locale)
        |
        |/** The display name for [locale]; falls back to the ISO code. */
        |public fun Currency.displayName(locale: Locale = Locale.current): String = ${spec.objectName}.displayName(this, locale)
        |
        |/**
        | * Formats the amount with the pattern and symbols of [locale].
        | *
        | * The currency is written per [style]; [accounting] selects the accounting
        | * pattern (e.g. `(${'$'}1,234.56)` for negatives in en); [cash] applies the cash
        | * fraction digits and cash rounding (e.g. CHF rounds to 0.05). The number of
        | * fraction digits shown is CLDR's, which can differ from the ISO minor units.
        | */
        |public fun CurrencyAmount.format(
        |    locale: Locale = Locale.current,
        |    style: CurrencySymbolStyle = CurrencySymbolStyle.SYMBOL,
        |    accounting: Boolean = false,
        |    cash: Boolean = false,
        |): String = ${spec.objectName}.format(this, locale, style, accounting, cash)
        |
        |/**
        | * Parses a formatted string — `R${'$'} 1.234,56`, `(${'$'}1,234.56)`, `200 Ft` — back
        | * into an amount, using [locale]'s separators, digits and currency symbol.
        | *
        | * The printed number is taken at face value and scaled to ISO minor units, so
        | * the formatting digits do not distort the result: HUF prints without decimals
        | * but has two ISO decimals, and `"200 Ft"` parses to 20000 minor units.
        | * Returns `null` when the text holds anything other than one number in this
        | * locale's conventions.
        | */
        |public fun CurrencyAmount.Companion.parseFormattedOrNull(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount? = ${spec.objectName}.parseFormattedOrNull(currency, text, locale)
        |
        |/** Like [parseFormattedOrNull] but throws on invalid input. */
        |public fun CurrencyAmount.Companion.parseFormatted(
        |    currency: Currency,
        |    text: String,
        |    locale: Locale = Locale.current,
        |): CurrencyAmount = requireNotNull(parseFormattedOrNull(currency, text, locale)) {
        |    "Cannot parse ${'$'}{currency.code} amount: '${'$'}text'"
        |}
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

/** `CldrDateTime`-shaped binding: the source object plus the datetime extensions. */
public fun emitDateTimeBinding(outputRoot: File, spec: BindingSpec) {
    val file = outputRoot.packageFile(spec.packageName, "LocalizedFormat.kt")
    file.writeText(
        preamble(
            spec,
            listOf(
                "dev.carcara.kotlinx.locale.Locale",
                "dev.carcara.kotlinx.locale.datetime.DateTimeFormatSource",
                "dev.carcara.kotlinx.locale.datetime.FormatStyle",
                "dev.carcara.kotlinx.locale.datetime.TextStyle",
                "dev.carcara.kotlinx.locale.datetime.cldr.format.PayloadDateTimeFormats",
                "dev.carcara.kotlinx.locale.datetime.displayName",
                "dev.carcara.kotlinx.locale.datetime.format",
                "${spec.registryPackage}.localeDataRegistry",
                "kotlinx.datetime.DayOfWeek",
                "kotlinx.datetime.LocalDate",
                "kotlinx.datetime.LocalDateTime",
                "kotlinx.datetime.LocalTime",
                "kotlinx.datetime.Month",
            ),
        ) + """
        |
        |/**
        | * The date and time patterns this build carries.
        | *
        | * The parser and formatter live in `kotlinx-locale-datetime-cldr-format`; all
        | * this object contributes is the table.
        | */
        |public object ${spec.objectName} : DateTimeFormatSource by PayloadDateTimeFormats(localeDataRegistry)
        |
        |/**
        | * Formats this date with the locale's standard date pattern of the given [style].
        | *
        | * ```
        | * LocalDate(2026, 7, 27).format(FormatStyle.LONG, Locale.forLanguageTag("pt-BR"))
        | * // "27 de julho de 2026"
        | * ```
        | */
        |public fun LocalDate.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this time with the locale's standard time pattern of the given [style].
        | *
        | * Time-zone fields present in the FULL and LONG patterns are omitted, since a
        | * [LocalTime] carries no zone information.
        | */
        |public fun LocalTime.format(style: FormatStyle, locale: Locale): String = ${spec.objectName}.format(this, style, locale)
        |
        |/**
        | * Formats this date-time by combining the locale's date and time patterns with
        | * its "glue" pattern (e.g. `Sunday, July 27, 2026, 3:05 PM` for `en`).
        | */
        |public fun LocalDateTime.format(dateStyle: FormatStyle, timeStyle: FormatStyle, locale: Locale): String =
        |    ${spec.objectName}.format(this, dateStyle, timeStyle, locale)
        |
        |/** Formats this date-time using the same [style] for the date and time parts. */
        |public fun LocalDateTime.format(style: FormatStyle, locale: Locale): String = format(style, style, locale)
        |
        |/** The localized name of this month in the "format" context, e.g. `julho`. */
        |public fun Month.displayName(style: TextStyle, locale: Locale): String = ${spec.objectName}.displayName(this, style, locale)
        |
        |/** The localized name of this day of week in the "format" context, e.g. `segunda-feira`. */
        |public fun DayOfWeek.displayName(style: TextStyle, locale: Locale): String =
        |    ${spec.objectName}.displayName(this, style, locale)
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${spec.objectName} to $file")
}

private fun File.packageFile(packageName: String, fileName: String): File =
    resolve(packageName.replace('.', '/')).apply { mkdirs() }.resolve(fileName)
