// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_HA: String =
    "10:other=00B\u001E11:other=000B\u001E12:other=0T\u001E13:other=00T\u001E14:other=000T\u001E3:other=0K\u001E4:other=00D\u001E5:other=000D\u001E6:other=0M\u001E7:other=00M\u001E8:other=000M\u001E9:other=0B"

internal val COMPACT_SHORT_HE: String =
    "10:other=00B‏\u001E11:other=000B‏\u001E12:other=0T‏\u001E13:other=00T‏\u001E14:other=000T‏\u001E3:other=0K‏\u001E4:other=00K‏\u001E5:other=000K‏\u001E6:other=0M‏\u001E7:other=00M‏\u001E8:other=000M‏\u001E9:other=0B‏"

internal val COMPACT_SHORT_HI: String =
    "10:other=00 अ॰\u001E11:other=0 ख॰\u001E12:other=00 ख॰\u001E13:other=0 नील\u001E14:other=00 नील\u001E3:other=0 हज़ार\u001E4:other=00 हज़ार\u001E5:other=0 लाख\u001E6:other=00 लाख\u001E7:other=0 क॰\u001E8:other=00 क॰\u001E9:other=0 अ॰"

internal val COMPACT_SHORT_HR: String =
    "10:other=00 mlr'.'\u001E11:other=000 mlr'.'\u001E12:other=0 bil'.'\u001E13:other=00 bil'.'\u001E14:other=000 bil'.'\u001E3:other=0 tis'.'\u001E4:other=00 tis'.'\u001E5:other=000 tis'.'\u001E6:other=0 mil'.'\u001E7:other=00 mil'.'\u001E8:other=000 mil'.'\u001E9:other=0 mlr'.'"

internal val COMPACT_SHORT_HU: String =
    "10:other=00 Mrd\u001E11:other=000 Mrd\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0 E\u001E4:other=00 E\u001E5:other=000 E\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0 Mrd"

internal val COMPACT_SHORT_HY: String =
    "10:other=00 մլրդ\u001E11:other=000 մլրդ\u001E12:other=0 տրլն\u001E13:other=00 տրլն\u001E14:other=000 տրլն\u001E3:other=0 հզր\u001E4:other=00 հզր\u001E5:other=000 հզր\u001E6:other=0 մլն\u001E7:other=00 մլն\u001E8:other=000 մլն\u001E9:other=0 մլրդ"
