// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_ZH: String =
    "10:other=000亿\u001E11:other=0000亿\u001E12:other=0万亿\u001E13:other=00万亿\u001E14:other=000万亿\u001E3:other=0\u001E4:other=0万\u001E5:other=00万\u001E6:other=000万\u001E7:other=0000万\u001E8:other=0亿\u001E9:other=00亿"

internal val COMPACT_SHORT_ZH_HANT: String =
    "10:other=000億\u001E11:other=0000億\u001E12:other=0兆\u001E13:other=00兆\u001E14:other=000兆\u001E3:other=0\u001E4:other=0萬\u001E5:other=00萬\u001E6:other=000萬\u001E7:other=0000萬\u001E8:other=0億\u001E9:other=00億"
