// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_LONG_UG: String =
    "10:other=00 مىليارد\u001E11:other=000 مىليارد\u001E12:other=0 تىرىليون\u001E13:other=00 تىرىليون\u001E14:other=000 تىرىليون\u001E3:other=0 مىڭ\u001E4:other=00 مىڭ\u001E5:other=000 مىڭ\u001E6:other=0 مىليون\u001E7:other=00 مىليون\u001E8:other=000 مىليون\u001E9:other=0 مىليارد"

internal val COMPACT_LONG_UK: String =
    "10:few=00 мільярди\u001E10:many=00 мільярдів\u001E10:one=00 мільярд\u001E10:other=00 мільярда\u001E11:few=000 мільярди\u001E11:many=000 мільярдів\u001E11:one=000 мільярд\u001E11:other=000 мільярда\u001E12:few=0 трильйони\u001E12:many=0 трильйонів\u001E12:one=0 трильйон\u001E12:other=0 трильйона\u001E13:few=00 трильйони\u001E13:many=00 трильйонів\u001E13:one=00 трильйон\u001E13:other=00 трильйона\u001E14:few=000 трильйони\u001E14:many=000 трильйонів\u001E14:one=000 трильйон\u001E14:other=000 трильйона\u001E3:many=0 тисяч\u001E3:one=0 тисяча\u001E3:other=0 тисячі\u001E4:many=00 тисяч\u001E4:one=00 тисяча\u001E4:other=00 тисячі\u001E5:many=000 тисяч\u001E5:one=000 тисяча\u001E5:other=000 тисячі\u001E6:few=0 мільйони\u001E6:many=0 мільйонів\u001E6:one=0 мільйон\u001E6:other=0 мільйона\u001E7:few=00 мільйони\u001E7:many=00 мільйонів\u001E7:one=00 мільйон\u001E7:other=00 мільйона\u001E8:few=000 мільйони\u001E8:many=000 мільйонів\u001E8:one=000 мільйон\u001E8:other=000 мільйона\u001E9:few=0 мільярди\u001E9:many=0 мільярдів\u001E9:one=0 мільярд\u001E9:other=0 мільярда"

internal val COMPACT_LONG_UR: String =
    "10:other=00 ارب\u001E11:other=0 کھرب\u001E12:other=00 کھرب\u001E13:other=00 ٹریلین\u001E14:other=000 ٹریلین\u001E3:other=0 ہزار\u001E4:other=00 ہزار\u001E5:other=0 لاکھ\u001E6:other=00 لاکھ\u001E7:other=0 کروڑ\u001E8:other=00 کروڑ\u001E9:other=0 ارب"

internal val COMPACT_LONG_UZ: String =
    "10:other=00 milliard\u001E11:other=000 milliard\u001E12:other=0 trillion\u001E13:other=00 trillion\u001E14:other=000 trillion\u001E3:other=0 ming\u001E4:other=00 ming\u001E5:other=000 ming\u001E6:other=0 million\u001E7:other=00 million\u001E8:other=000 million\u001E9:other=0 milliard"

internal val COMPACT_LONG_UZ_CYRL: String =
    "10:other=00 миллиард\u001E11:other=000 миллиард\u001E12:other=0 трилион\u001E13:other=00 трилион\u001E14:other=000 трилион\u001E3:other=0 минг\u001E4:other=00 минг\u001E5:other=000 минг\u001E6:other=0 миллион\u001E7:other=00 миллион\u001E8:other=000 миллион\u001E9:other=0 миллиард"
