// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_SHORT_EL: String =
    "10:other=00 δισ'.'\u001E11:other=000 δισ'.'\u001E12:other=0 τρισ'.'\u001E13:other=00 τρισ'.'\u001E14:other=000 τρισ'.'\u001E3:other=0 χιλ'.'\u001E4:other=00 χιλ'.'\u001E5:other=000 χιλ'.'\u001E6:other=0 εκ'.'\u001E7:other=00 εκ'.'\u001E8:other=000 εκ'.'\u001E9:other=0 δισ'.'"

internal val COMPACT_SHORT_EN: String =
    "10:one=00B\u001E10:other=00B\u001E11:one=000B\u001E11:other=000B\u001E12:one=0T\u001E12:other=0T\u001E13:one=00T\u001E13:other=00T\u001E14:one=000T\u001E14:other=000T\u001E3:one=0K\u001E3:other=0K\u001E4:one=00K\u001E4:other=00K\u001E5:one=000K\u001E5:other=000K\u001E6:one=0M\u001E6:other=0M\u001E7:one=00M\u001E7:other=00M\u001E8:one=000M\u001E8:other=000M\u001E9:one=0B\u001E9:other=0B"

internal val COMPACT_SHORT_EN_GB: String =
    "10:one=00bn\u001E10:other=00bn\u001E11:one=000bn\u001E11:other=000bn\u001E12:one=0tn\u001E12:other=0tn\u001E13:one=00tn\u001E13:other=00tn\u001E14:one=000tn\u001E14:other=000tn\u001E3:one=0k\u001E3:other=0k\u001E4:one=00k\u001E4:other=00k\u001E5:one=000k\u001E5:other=000k\u001E6:one=0m\u001E6:other=0m\u001E7:one=00m\u001E7:other=00m\u001E8:one=000m\u001E8:other=000m\u001E9:one=0bn\u001E9:other=0bn"

internal val COMPACT_SHORT_EN_IN: String =
    "10:one=0KCr\u001E10:other=0KCr\u001E11:one=00KCr\u001E11:other=00KCr\u001E12:one=0LCr\u001E12:other=0LCr\u001E13:one=00LCr\u001E13:other=00LCr\u001E14:one=000LCr\u001E14:other=000LCr\u001E3:one=0K\u001E3:other=0K\u001E4:one=00K\u001E4:other=00K\u001E5:one=0L\u001E5:other=0L\u001E6:one=00L\u001E6:other=00L\u001E7:one=0Cr\u001E7:other=0Cr\u001E8:one=00Cr\u001E8:other=00Cr\u001E9:one=000Cr\u001E9:other=000Cr"

internal val COMPACT_SHORT_ES: String =
    "10:other=00 mil M\u001E11:other=000 mil M\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0 mil\u001E4:other=00 mil\u001E5:other=000 mil\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0000 M"

internal val COMPACT_SHORT_ES_419: String =
    "10:other=00 mil M\u001E11:other=000 mil M\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0 K\u001E4:other=00 k\u001E5:other=000 k\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0000 M"

internal val COMPACT_SHORT_ES_MX: String =
    "10:other=00 mil M\u001E11:other=000 mil M\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0 k\u001E4:other=00 k\u001E5:other=000 k\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0000 M"

internal val COMPACT_SHORT_ES_US: String =
    "10:other=00 mil M\u001E11:other=000 mil M\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0 K\u001E4:other=00 K\u001E5:other=000 K\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0000 M"

internal val COMPACT_SHORT_ET: String =
    "10:other=00 mld\u001E11:other=000 mld\u001E12:other=0 trln\u001E13:other=00 trln\u001E14:other=000 trln\u001E3:other=0 tuh\u001E4:other=00 tuh\u001E5:other=000 tuh\u001E6:other=0 mln\u001E7:other=00 mln\u001E8:other=000 mln\u001E9:other=0 mld"

internal val COMPACT_SHORT_EU: String =
    "10:other=00000 M\u001E11:other=000000 M\u001E12:other=0 B\u001E13:other=00 B\u001E14:other=000 B\u001E3:other=0\u001E4:other=0\u001E5:other=0\u001E6:other=0 M\u001E7:other=00 M\u001E8:other=000 M\u001E9:other=0000 M"
