// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_LONG_IA: String =
    "10:one=00 milliardo\u001E10:other=00 milliardos\u001E11:one=000 milliardo\u001E11:other=000 milliardos\u001E12:one=0 billion\u001E12:other=0 billiones\u001E13:one=00 billion\u001E13:other=00 billiones\u001E14:one=000 billion\u001E14:other=000 billiones\u001E3:one=0 mille\u001E3:other=0 milles\u001E4:one=00 mille\u001E4:other=00 milles\u001E5:one=000 mille\u001E5:other=000 milles\u001E6:one=0 million\u001E6:other=0 milliones\u001E7:one=00 million\u001E7:other=00 milliones\u001E8:one=000 million\u001E8:other=000 milliones\u001E9:one=0 milliardo\u001E9:other=0 milliardos"

internal val COMPACT_LONG_ID: String =
    "10:other=00 miliar\u001E11:other=000 miliar\u001E12:other=0 triliun\u001E13:other=00 triliun\u001E14:other=000 triliun\u001E3:other=0 ribu\u001E4:other=00 ribu\u001E5:other=000 ribu\u001E6:other=0 juta\u001E7:other=00 juta\u001E8:other=000 juta\u001E9:other=0 miliar"

internal val COMPACT_LONG_IS: String =
    "10:one=00 milljarður\u001E10:other=00 milljarðar\u001E11:one=000 milljarður\u001E11:other=000 milljarðar\u001E12:one=0 billjón\u001E12:other=0 billjónir\u001E13:one=00 billjón\u001E13:other=00 billjónir\u001E14:one=000 billjón\u001E14:other=000 billjónir\u001E3:one=0 þúsund\u001E3:other=0 þúsund\u001E4:one=00 þúsund\u001E4:other=00 þúsund\u001E5:one=000 þúsund\u001E5:other=000 þúsund\u001E6:one=0 milljón\u001E6:other=0 milljónir\u001E7:one=00 milljón\u001E7:other=00 milljónir\u001E8:one=000 milljón\u001E8:other=000 milljónir\u001E9:one=0 milljarður\u001E9:other=0 milljarðar"

internal val COMPACT_LONG_IT: String =
    "10:one=00 miliardi\u001E10:other=00 miliardi\u001E11:one=000 miliardi\u001E11:other=000 miliardi\u001E12:one=0 mille miliardi\u001E12:other=0 mila miliardi\u001E13:one=00 mila miliardi\u001E13:other=00 mila miliardi\u001E14:one=000 mila miliardi\u001E14:other=000 mila miliardi\u001E3:one=mille\u001E3:other=0 mila\u001E4:one=00 mila\u001E4:other=00 mila\u001E5:one=000 mila\u001E5:other=000 mila\u001E6:one=0 milione\u001E6:other=0 milioni\u001E7:one=00 milioni\u001E7:other=00 milioni\u001E8:one=000 milioni\u001E8:other=000 milioni\u001E9:one=0 miliardo\u001E9:other=0 miliardi"
