// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val COMPACT_LONG_AF: String =
    "10:other=00 miljard\u001E11:other=000 miljard\u001E12:other=0 biljoen\u001E13:other=00 biljoen\u001E14:other=000 biljoen\u001E3:other=0 duisend\u001E4:other=00 duisend\u001E5:other=000 duisend\u001E6:other=0 miljoen\u001E7:other=00 miljoen\u001E8:other=000 miljoen\u001E9:other=0 miljard"

internal val COMPACT_LONG_AK: String =
    "10:other=ɔpepepem 00\u001E11:other=ɔpepepem 000\u001E12:other=ɔpepepepem 0\u001E13:other=ɔpepepepem 00\u001E14:other=ɔpepepepem 000\u001E3:other=apem 0\u001E4:other=mpem 00\u001E5:other=mpem 000\u001E6:other=ɔpepem 0\u001E7:other=ɔpepem 00\u001E8:other=ɔpepem 000\u001E9:other=ɔpepepem 0"

internal val COMPACT_LONG_AM: String =
    "10:other=00 ቢሊዮን\u001E11:other=000 ቢሊዮን\u001E12:other=0 ትሪሊዮን\u001E13:other=00 ትሪሊዮን\u001E14:other=000 ትሪሊዮን\u001E3:other=0 ሺ\u001E4:other=00 ሺ\u001E5:other=000 ሺ\u001E6:other=0 ሚሊዮን\u001E7:other=00 ሚሊዮን\u001E8:other=000 ሚሊዮን\u001E9:other=0 ቢሊዮን"

internal val COMPACT_LONG_AR: String =
    "10:other=00 مليار\u001E11:other=000 مليار\u001E12:other=0 ترليون\u001E13:other=00 ترليون\u001E14:other=000 ترليون\u001E3:few=0 آلاف\u001E3:other=0 ألف\u001E4:other=00 ألف\u001E5:other=000 ألف\u001E6:few=0 ملايين\u001E6:other=0 مليون\u001E7:few=00 ملايين\u001E7:other=00 مليون\u001E8:other=000 مليون\u001E9:other=0 مليار"

internal val COMPACT_LONG_AS: String =
    "10:other=00 শত কোটি\u001E11:other=000 শত কোটি\u001E12:other=0 শত পৰাৰ্দ্ধ\u001E13:other=00 শত পৰাৰ্দ্ধ\u001E14:other=000 শত পৰাৰ্দ্ধ\u001E3:other=0 হাজাৰ\u001E4:other=00 হাজাৰ\u001E5:other=0 লাখ\u001E6:other=0 নিযুত\u001E7:other=00 নিযুত\u001E8:other=000 নিযুত\u001E9:other=0 শত কোটি"

internal val COMPACT_LONG_AST: String =
    "10:other=00G\u001E11:other=000G\u001E12:other=0T\u001E13:other=00T\u001E14:other=000T\u001E3:one=0 millar\u001E3:other=0 millares\u001E4:other=00 millares\u001E5:other=000 millares\u001E6:one=0 millón\u001E6:other=0 millones\u001E7:other=00 millones\u001E8:other=000 millones\u001E9:other=0G"

internal val COMPACT_LONG_AZ: String =
    "10:other=00 milyard\u001E11:other=000 milyard\u001E12:other=0 trilyon\u001E13:other=00 trilyon\u001E14:other=000 trilyon\u001E3:other=0 min\u001E4:other=00 min\u001E5:other=000 min\u001E6:other=0 milyon\u001E7:other=00 milyon\u001E8:other=000 milyon\u001E9:other=0 milyard"
