/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val CURRENCY_COMPACT_UG: String =
    "10:one:a=¤ 00مىليارد\u001E10:other=¤00مىليارد\u001E10:other:a=¤ 00مىليارد\u001E11:one:a=¤ 000مىليارد\u001E11:other=¤000مىليارد\u001E11:other:a=¤ 000مىليارد\u001E12:one:a=¤ 0T\u001E12:other=¤0T\u001E12:other:a=¤ 0T\u001E13:one:a=¤ 00T\u001E13:other=¤00T\u001E13:other:a=¤ 00T\u001E14:one:a=¤ 000T\u001E14:other=¤000T\u001E14:other:a=¤ 000T\u001E3:one:a=¤ 0مىڭ\u001E3:other=¤0مىڭ\u001E3:other:a=¤ 0مىڭ\u001E4:one:a=¤ 00مىڭ\u001E4:other=¤00مىڭ\u001E4:other:a=¤ 00مىڭ\u001E5:one:a=¤ 000مىڭ\u001E5:other=¤000مىڭ\u001E5:other:a=¤ 000مىڭ\u001E6:one:a=¤ 0مىليون\u001E6:other=¤0مىليون\u001E6:other:a=¤ 0مىليون\u001E7:one:a=¤ 00مىليون\u001E7:other=¤00مىليون\u001E7:other:a=¤ 00مىليون\u001E8:one:a=¤ 000مىليون\u001E8:other=¤000مىليون\u001E8:other:a=¤ 000مىليون\u001E9:one:a=¤ 0مىليارد\u001E9:other=¤0مىليارد\u001E9:other:a=¤ 0مىليارد"

internal val CURRENCY_COMPACT_UK: String =
    "10:other=00 млрд ¤\u001E11:other=000 млрд ¤\u001E12:other=0 трлн ¤\u001E13:other=00 трлн ¤\u001E14:other=000 трлн ¤\u001E3:other=0 тис'.' ¤\u001E4:other=00 тис'.' ¤\u001E5:other=000 тис'.' ¤\u001E6:other=0 млн ¤\u001E7:other=00 млн ¤\u001E8:other=000 млн ¤\u001E9:other=0 млрд ¤"

internal val CURRENCY_COMPACT_UR: String =
    "10:one=¤00 ارب\u001E10:one:a=¤ 00 ارب\u001E10:other=¤00 ارب\u001E10:other:a=¤ 00 ارب\u001E11:one=¤0 کھرب\u001E11:one:a=¤ 0 کھرب\u001E11:other=¤0 کھرب\u001E11:other:a=¤ 0 کھرب\u001E12:one=¤00 کھرب\u001E12:one:a=¤ 00 کھرب\u001E12:other=¤00 کھرب\u001E12:other:a=¤ 00 کھرب\u001E13:one=¤00 ٹریلین\u001E13:one:a=¤ 00 ٹریلین\u001E13:other=¤00 ٹریلین\u001E13:other:a=¤ 00 ٹریلین\u001E14:one=¤000 ٹریلین\u001E14:one:a=¤ 000 ٹریلین\u001E14:other=¤000 ٹریلین\u001E14:other:a=¤ 000 ٹریلین\u001E3:one=¤0 ہزار\u001E3:one:a=¤ 0 ہزار\u001E3:other=¤0 ہزار\u001E3:other:a=¤ 0 ہزار\u001E4:one=¤00 ہزار\u001E4:one:a=¤ 00 ہزار\u001E4:other=¤00 ہزار\u001E4:other:a=¤ 00 ہزار\u001E5:one=¤0 لاکھ\u001E5:one:a=¤ 0 لاکھ\u001E5:other=¤0 لاکھ\u001E5:other:a=¤ 0 لاکھ\u001E6:one=¤00 لاکھ\u001E6:one:a=¤ 00 لاکھ\u001E6:other=¤00 لاکھ\u001E6:other:a=¤ 00 لاکھ\u001E7:one=¤0 کروڑ\u001E7:one:a=¤ 0 کروڑ\u001E7:other=¤0 کروڑ\u001E7:other:a=¤ 0 کروڑ\u001E8:one=¤00 کروڑ\u001E8:one:a=¤ 00 کروڑ\u001E8:other=¤00 کروڑ\u001E8:other:a=¤ 00 کروڑ\u001E9:one=¤0 ارب\u001E9:one:a=¤ 0 ارب\u001E9:other=¤0 ارب\u001E9:other:a=¤ 0 ارب"

internal val CURRENCY_COMPACT_UZ: String =
    "10:other=00 mlrd ¤\u001E11:other=000 mlrd ¤\u001E12:other=0 trln ¤\u001E13:other=00 trln ¤\u001E14:other=000 trln ¤\u001E3:other=0 ming ¤\u001E4:other=00 ming ¤\u001E5:other=000 ming ¤\u001E6:other=0 mln ¤\u001E7:other=00 mln ¤\u001E8:other=000 mln ¤\u001E9:other=0 mlrd ¤"

internal val CURRENCY_COMPACT_UZ_CYRL: String =
    "10:one=00млрд ¤\u001E10:one:a=00млрд ¤\u001E10:other=00млрд ¤\u001E10:other:a=00млрд ¤\u001E11:one=000млрд ¤\u001E11:one:a=000млрд ¤\u001E11:other=000млрд ¤\u001E11:other:a=000млрд ¤\u001E12:one=0трлн ¤\u001E12:one:a=0трлн ¤\u001E12:other=0трлн ¤\u001E12:other:a=0трлн ¤\u001E13:one=00трлн ¤\u001E13:one:a=00трлн ¤\u001E13:other=00трлн ¤\u001E13:other:a=00трлн ¤\u001E14:one=000трлн ¤\u001E14:one:a=000трлн ¤\u001E14:other=000трлн ¤\u001E14:other:a=000трлн ¤\u001E3:one=0минг ¤\u001E3:one:a=0минг ¤\u001E3:other=0минг ¤\u001E3:other:a=0минг ¤\u001E4:one=00минг ¤\u001E4:one:a=00минг ¤\u001E4:other=00минг ¤\u001E4:other:a=00минг ¤\u001E5:one=000минг ¤\u001E5:one:a=000минг ¤\u001E5:other=000минг ¤\u001E5:other:a=000минг ¤\u001E6:one=0млн ¤\u001E6:one:a=0млн ¤\u001E6:other=0млн ¤\u001E6:other:a=0млн ¤\u001E7:one=00млн ¤\u001E7:one:a=00млн ¤\u001E7:other=00млн ¤\u001E7:other:a=00млн ¤\u001E8:one=000млн ¤\u001E8:one:a=000млн ¤\u001E8:other=000млн ¤\u001E8:other:a=000млн ¤\u001E9:one=0млрд ¤\u001E9:one:a=0млрд ¤\u001E9:other=0млрд ¤\u001E9:other:a=0млрд ¤"
