// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_UK: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FЕ\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_UR_IN: String =
    "arabext\u001F۰۱۲۳۴۵۶۷۸۹\u001F٫\u001F٬\u001F٫\u001F٬\u001F‎-‎\u001F‎+‎\u001F%\u001F‰\u001F~\u001F×۱۰^\u001F×\u001F∞\u001FNaN\u001F;\u001F٫\u001F1"

internal val NUMBER_SYMBOLS_UZ: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001Fson emas\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_UZ_CYRL: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001Fҳақиқий сон эмас\u001F;\u001F:\u001F1"
