// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_LMO: String =
    "latn\u001F0123456789\u001F,\u001F'\u001F,\u001F'\u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_LO: String =
    "latn\u001F0123456789\u001F,\u001F.\u001F,\u001F.\u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001Fບໍ່​ແມ່ນ​ໂຕ​ເລກ\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_LT: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F−\u001F+\u001F%\u001F‰\u001F∼\u001F×10^\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_LV: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNS\u001F;\u001F:\u001F2"
