// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val NUMBER_SYMBOLS_BA: String =
    "latn\u001F0123456789\u001F.\u001F \u001F.\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_BE: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F≈\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F2"

internal val NUMBER_SYMBOLS_BEW: String =
    "latn\u001F0123456789\u001F,\u001F.\u001F,\u001F.\u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F.\u001F1"

internal val NUMBER_SYMBOLS_BG: String =
    "latn\u001F0123456789\u001F,\u001F \u001F,\u001F \u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F2"

internal val NUMBER_SYMBOLS_BGC: String =
    "deva\u001F०१२३४५६७८९\u001F.\u001F,\u001F.\u001F,\u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_BQI: String =
    "latn\u001F0123456789\u001F.\u001F,\u001F.\u001F,\u001F‎−\u001F‎+\u001F%\u001F‰\u001F~\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_BRX: String =
    "latn\u001F0123456789\u001F.\u001F,\u001F.\u001F,\u001F-\u001F+\u001F%\u001F‰\u001F~\u001FE\u001Fx\u001F∞\u001FNaN\u001F;\u001F:\u001F1"

internal val NUMBER_SYMBOLS_BS: String =
    "latn\u001F0123456789\u001F,\u001F.\u001F,\u001F.\u001F-\u001F+\u001F%\u001F‰\u001F≈\u001FE\u001F×\u001F∞\u001FNaN\u001F;\u001F:\u001F1"
