// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val ORDINAL_INDEX_KK: String =
    "r19"

internal val ORDINAL_INDEX_KM: String =
    "r20"

internal val ORDINAL_INDEX_KO: String =
    "r21"

internal val ORDINAL_INDEX_KY: String =
    "r22"
