/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val ordinalRuleSetsRegistry: Map<String, String> = buildMap(33) {
    put("r0", ORDINAL_RULES_R0)
    put("r1", ORDINAL_RULES_R1)
    put("r10", ORDINAL_RULES_R10)
    put("r11", ORDINAL_RULES_R11)
    put("r12", ORDINAL_RULES_R12)
    put("r13", ORDINAL_RULES_R13)
    put("r14", ORDINAL_RULES_R14)
    put("r15", ORDINAL_RULES_R15)
    put("r16", ORDINAL_RULES_R16)
    put("r17", ORDINAL_RULES_R17)
    put("r18", ORDINAL_RULES_R18)
    put("r19", ORDINAL_RULES_R19)
    put("r2", ORDINAL_RULES_R2)
    put("r20", ORDINAL_RULES_R20)
    put("r21", ORDINAL_RULES_R21)
    put("r22", ORDINAL_RULES_R22)
    put("r23", ORDINAL_RULES_R23)
    put("r24", ORDINAL_RULES_R24)
    put("r25", ORDINAL_RULES_R25)
    put("r26", ORDINAL_RULES_R26)
    put("r27", ORDINAL_RULES_R27)
    put("r28", ORDINAL_RULES_R28)
    put("r29", ORDINAL_RULES_R29)
    put("r3", ORDINAL_RULES_R3)
    put("r30", ORDINAL_RULES_R30)
    put("r31", ORDINAL_RULES_R31)
    put("r32", ORDINAL_RULES_R32)
    put("r4", ORDINAL_RULES_R4)
    put("r5", ORDINAL_RULES_R5)
    put("r6", ORDINAL_RULES_R6)
    put("r7", ORDINAL_RULES_R7)
    put("r8", ORDINAL_RULES_R8)
    put("r9", ORDINAL_RULES_R9)
}
