// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.number.cldr.internal.data

internal val PLURAL_INDEX_PA: String =
    "c5 o0"

internal val PLURAL_INDEX_PL: String =
    "c28 o0"

internal val PLURAL_INDEX_PT: String =
    "c21 o0"

internal val PLURAL_INDEX_PT_PT: String =
    "c22 "
