/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.relative.internal.data

internal val RELATIVE_TIME_QU: String =
    "00T5绉ᡃ塤ऄ㉹ᇗ䙩熕᭖牑ଠ婌⦡絓➡ፕᐨጋ捔䲵咇淾䀏⁯㣀イคㅍ㺬㴅ࡔ猐⬩᩺眇篼岏㉎枳⢸屺〨඲ẳ喘為熷挶ᤩ槲ᴨ䒳ႝ枞Ṛ膿奙ᐅ秩㣴屿樑曆═䆀嘄皼奒ᐙঘ⠗஌严ᖺ榫溫ಈ璖େ牁䥱⸐ၤ舰㳸澖斡䡘獎檭蘳糙獣㏊㧀瀆ᇃ㜺≆Ầ䒛ᣍ䎺ᑞ皚▭匇旣䆲莿茇蔥㠷㺲㦈癩綱綵蚝换学㷜蝂稏䛇㻇繌繯"
