/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.relative.internal.data

internal val RELATIVE_TIME_PA: String =
    "01Cn纪嫓悆ࣃ牋฻৺ᣒ䠂Ὤ㶈࠱ᡘ䧋礘ࠉ峊妽േ梪示㶫㚒愳璪㕸澇菳⯨⢷ట䩗㊐眈⚁ཱ⪋䈕䨓⥆簢䂄搬浥䊭⒝噣⺷羀籟ⱍ䪫癖䘭㮚⒃㐺嬳ᗧᰧ伓欭欎皭汝蕲崜᪕寛ᱳូ䅲焅橀㚣␭㏦傒䰽缏摃ᢶ縠䪆㓭㲰ᡏ㓓祎൪᳦撛姑༥烏⟑⦺㨢尷㦡媇稪棇楌າᡴန聐㡖嫎㫉ᬚ⸻膍ਃ挡彅䈘ᖞⓃ⁾仲蒳㴷㘛㾦㽿⹭♳ష艻㮲⚃灵㳳Ⓞ㰿╸ㅈ磈❁㻨✉྽屰犣匬瘦጑䌄咁浔佾璄奬督睟撕⾴⨛➬⿒菲ᯩ๗Ⲣ⠘园䀻⢅掲伸⨿䷝挭肈啲矝㩬㽘栿⃍䏣⇢⇢懢懢凲凲嗲嗰哱員蓦䑆៼茋耄"

internal val RELATIVE_TIME_PA_ARAB: String =
    "007N㋇塂恆ऄ㉼卢舐暥䑁₀洳⡉⒢猑ሮự᠅⎢兦篔䚒茘疧ḱ䷸⇾⟹惋藚䝞簮⧇橬㈙ᤤ煦䀴妓坒཯䛬徨橞䩦䣗☦璘培熪ॱᎀ咥椂䨱ࡣ綷杹ௗ混㢂ㅨ⑋ᦀউᰁ᱁ணᅗ枾弐堰䌀ᥔ᠂ीᢠ⥅⦯䆧径剦଺糉Ლ氒蒢披ওᲥㆭᕷ㕭䟱瑸ࡧ䇊篁偰ሰࣱ䑿捤恥⅛茳俖朗್ᣮ璬笝᷋ᬰᕲᔊ犱耀"

internal val RELATIVE_TIME_PCM: String =
    "00PY纩嫂恆ः牉崟栕સ胙層ශ㪩⺑⫘Ⲉ摸ࠇ籧⷏⠇㓍㹟桌嘧沚⭱ᮡ䐒渕篞ᗯຄೱ臻⭀䰵匡潬䯑儲燲丫惲᥇㒶䟮ᯚ䌇⪙။疗渀喅ⶩ桨᠞⯧㶔䋃⢀⯋ᡈ⹄㢵䭊ἔ燇⢙硈筶㳄వ濦䨪こዶ恖敢䍼噖娓絅嶹඙況砄匌崅᪪瀆⡱䩸₡㚀垞䤐㵛戃唗㐧擛፝嗋悃籘凱㹝肮快䶱㨑笗㩃ㄱ緒盂蒁ḽ滇ℚ爚ᵭ◴᫝ᆔ莀⺩䔜ᔼ生㙭彦䶽㢙䎖縻虷稟烷猢⓿朞柽嫾昀ࠀ"

internal val RELATIVE_TIME_PL: String =
    "00uf绊ớ恆ऄ㊸匨᲍敒ቖ኏ੜ䩄ᮎ屿ぜੵᒮ墘㏾帶湾栤蚋ਏ朹䏣⾡祈筡攕檰㋑峥摷ඬ掱喧䚏䂖㷒厢灲撿䚸䎊඿ὼⲚᙨ䷔ද䌔⌼䃮Ṝ≳櫝㥹则㏫棦淰斸ኜ催ᒙ焘㿋ኰ刱寡荳Ⱁ伶卶ⱺ䢗⒝珤ᠷ痪炪臫祝晤⟻坏⛬፱琒涒硈ᠽ▩₟ᱮྷ穚尨痂᪢ⲍ䎎㗖侕嵢腤綺棾蝩㊧莽䰒拡⺅䤖搮ࡸ⬒圬㽲⏤禿埓䧩Ⅶশ桿⛒帇ⵚ撧᫯檝薯巺撏⚶⫟䕣沨⫌啇ᬱ擢≬猻ᵊ嘏俒奔癴䪡䟦㱞╕玑芔᫯⯫箇胂಑䇟ᐗ蘒㽃俞⣣珒棶匰瓀濵㛌埒挛゗笇⛙害჌灗捕氩Ᵽ旁廞傗䋂婾咻攖㖱⥦澉ច樲ᆷ树呏ⶢ์ࠀ⩕氥仂༙糀ᰃ噘⠚䃙ᦻ䐈㉁椙䀴᭖入蒆ာ䵰⢃ጸ 㲢擎封⮁者ຢ᳛吏⯓ᲇ౪♂磲ᮈ⦿偸巫ⰺ䏉壄艚䕹琛紌ജ摮ࡍ⍤ᆹ呩⾏㚜纊藉⊇蒉㇫䳓滸ⴴ椡冢绻搗⹹ᶀ洔腶⁆ొᒟ㗯⫎ሽ⩲碌㢖なब巼"

internal val RELATIVE_TIME_PS: String =
    "00t3纫᫛恆ः瑎瑲䯯㎺ᰑ࿈㨖㚡〕Ⱁීํ澘泗᳜䗷䣥瘭ᡀ嵕㌜䏳㒓燼琟䰐䋝᷂㿜₀聿କ娡䊿⢃᝛㹘ຓ艷漋佶ዩ磺腳ా嬫ㅎ◘䱫ᔔ第磶ố㚙摍᫇ㆺⲬᬊ⬩⒱孻泡࡮䴺ᔆṇ搔㙐䃝㶖蝛亃ṅㅟ䴣廗┫抸㝇Ẳど癩耋䕒娖兵㝔磁塋另撦䘠氅∊仮ख⺉剜䍐ㄝ㹓䱔瀱㩵硛┠綖垉⏮㊷ᚋ౥蘛਻卥▾嫬᩹澇澹摌床蔕㚥璯㥧䬇ニ䐰䗶橋ᆧ䬇✦│筿⁳懭䮳瑅䣌置䳇汻秥洧䂚䌔䎏厎ఴ筯娕癤Ⱒ欘漤䑗ᲄ孂⬐硔竣冧ᧇ筂┮哄⦜椿⇯撴➚ᄜ殴幣蟙櫇䝔䪄ሗ敽䶡❒䒟ㆤ蓊寉䳿䄎䤬槾䊘厓粨⹕ⷙ㉂僯䙅᧩㩌ᅊ㩉䞯䆌蔯嵻⼶偫ᯖ⹝ᧉ枲ⱱ忰ఀ"

internal val RELATIVE_TIME_PS_PK: String =
    "00t3绋᭛恆ई㉻ቨ俨處Ꭲ脑紉഑䗪ႂ㊀ポ恰伌脬宮⛹䷘㜢䢪嵖␷晸凼䜶෢ࠜ㽊碊箶 ࿨稴伌滩壣଍猱恾䷥䳭㛀撽♟庡࿴磩⽒縦⋩䱵Ṱ䈒悝斱敕䮑庆㍉䪞ⱇḴ蝩†៓ⵟ⣀᜗ઓ舿༜滙煵樳ಉ㕊䋡纆䴇䕒ᶬ䍗᧨穧幄⑒楯簺肥໕ᆚ䏱夣ⴳ绳ᜠ〉⺠嫝砢㨨撢殥傔筩☡宏棤⇜ⷓᓿ崽᫚蒪糑㵌䟚棖秽䖾剒ჯ嬙伷䎙瑔劊蔛㔥懝⨟粼⸷甇書峄珕᎖堾௭腑㯰㖇篈旪棆溗珄菤᭓痒ㇴ燝㠗ဓ忔岚忞ᥤᥛᓤ擌妝ፐ⤠䢘綵঵莡燱堵ⳣ呄㷼៌濞䈯㘞ೈ蕫䳺濗⎓૵ㄈጪ♳䎖䩽㳂⺦臿Ὃ᪄䜲囂蓣繍ೳ᧩㉏廱ℕ䫱ᝌ崳腤丘剧፿Ỹ⸭蟍ⶓፆ⺜唣疓ⱞ臄脇䠀"

internal val RELATIVE_TIME_PT: String =
    "00aR纩塛墆ࣇ汉Ⲿ槴ⵋ⨠㵉ख㴪㕔䚥緗㶷㝼縉娀䩽ࣵせ獡ཥ和凄瑁禐戆⍘๢季⣸焚僸ଌ磺䛶琖ࡐ政㞟椨਀㽇⅞娓僕≻㺛⼥』垛俋绛峢拠脊ૈ婴坩槆ᕘ癇䅒臝狽懿傹䗰綀戕䚁᪔Ḯ僆帒芹㣒㨄恿ো虋浀䅭梖䀘ᫎ೰癕䒁䵴牽䉶⽥皧㢾施倠ᮛ瓞蚁⬇疹㼮Ⳁ橫柅ᲂ⡠ᒚ䢮┝厡蛓祍缟ဌ塭Ꭺ橗ᓯ㼩佭皇岎䳩珇䨶ᤪ愃◸澳ၨ暣⎟㸩䪉彽䵅⊃礜垈ཿᢝ਎涘䀖㋗䬲䧁ᝣ䤨ᢤ⣥在ᔼ⎎廉泯ᲁṇ垂看愧࠺ᴣ伢ॴ䇇称秷䊄㧡欂㗞歾喻埦囯莆犼"

internal val RELATIVE_TIME_PT_AO: String =
    "00bi櫉塚恦ऄ㉹劻盄䲯ᩘ⨗㸂嫀䁕Ḝ宺緛᧼₥㑋⟥ἡ墓⡝櫌晌笊⋟纣ਣッ犢憫ᔡ纓彎瀈缟篷㷫溜ယ暦჊㭻寳痸⟘ᩚ夻䞰ૉ໓㑪羼㔙∨䭴膫ⱽ灱茨㛆沯ਓ᫶䷴ዟ柎㗗糌莧⇇禖ὶ㽀༺奯䅾㻅盋勪睆䪚✡熱㛽㮫⤖䍣圷橮ℜ⁍挚ㆱ㋩剉硩ᦿ䝋⧢矎䲓䅺▿皲ヺ㶓菉ὤ汿ऊၫ⧅儍教庎៏䘚礶㧏確ạἷ䔞緂㶘㫞盱溹䋮兞‮⌚ㇰ匼噃㦥芔ᾍ浭൱ᡜㆶ㭤ឪ⿶芵浡ソ扔宋浑৉䖬ᭊ๠粧螟ᓲゕ媶尼ங及䯺丂蝱㞈奦河眷緞ධ縠䒕㓖㒕禊屏ᚩ⎿竭茈恂㸳⁐ភ糜⤓眰祒碝荈ሜࠬ⹺殂ᛈ㝐泈ᐜ埉ᗠᤡ㓘橦棞变樾厄䃨⵾⥖ࠍ㾘䢹ᱥ䱝⻘燄傗簂"
