/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.plurals.internal.data

internal val CURRENCY_PLURAL_NAMES_OC_ES: String =
    "oc\u001F00\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OKA_CA: String =
    "oka\u001F00\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OM: String =
    "root\u001F1oDoolaara Beermudaa\u001EDoolaarota Beermudaa\u001EDoolaara Beliizee\u001EDoolaarota Beliizee\u001EDoolaara Kanaadaa\u001EDoolaarota Kanaadaa\u001EKoloonii Kostaa Rikaa\u001EKoloonota Kostaa Rikaa\u001EDoolaara Ameerikaa\u001EDoolarota Ameerikaa\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OM_ET: String =
    "om\u001F00\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OR: String =
    "root\u001F1pUAE ଦିରହାମ୍\u001EUAE ଦିରହାମ୍\u001Eଲେସୋଥୋ ଲୋଟି\u001Eଲେସୋଥୋ ଲୋଟିସ୍\u001Eସୋଲୋମୋନ୍ ଦ୍ଵୀପପୁଞ୍ଜ ଡଲାର୍\u001Eସୋଲୋମୋନ ଦ୍ଵୀପପୁଞ୍ଜ ଡଲାର୍\u001Eସୁଦାନୀଜ ପାଉଣ୍ଡ୍\u001Eସୁଦାନୀୟ ପାଉଣ୍ଡ୍\u001Eସ୍ଵାଜି ଲିଲାଞ୍ଜେନି\u001Eସ୍ଵାଜି ଇମାଲଞ୍ଜେନି\u001Eକ‍୍ୟାରବିଅନ୍‌ ଗିଲ୍ଡର୍‌\u001Eକ‍୍ୟାରବିଅନ୍‌ ଗିଲ୍ଡର୍‌\u001Eପଶ୍ଚିମ ଆଫ୍ରିକୀୟ CFA ଫ୍ରାଙ୍କ୍\u001Eପଶ୍ଚିମ ଆଫ୍ରିକିୟ CFA ଫ୍ରାଙ୍କ୍\u001E(ମୁଦ୍ରାର ଅଜଣା ଏକକ)\u001E(ଅଜଣା ମୁଦ୍ରା)\u001Eଜିମ୍ବାୱିଅନ୍‌ ଗୋଲ୍ଡ୍‌\u001Eଜିମ୍ବାୱିଅନ୍‌ ଗୋଲ୍ଡ୍‌\u001F02\u001F010123456789\u001D.\u001D,\u001D-\u001D1\u001D#,##,##0.###"

internal val CURRENCY_PLURAL_NAMES_OR_IN: String =
    "or\u001F00\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OS: String =
    "root\u001F1qбразилиаг реал\u001Eбразилиаг реалы\u001Eевро\u001Eевройы\u001Eбритайнаг фунт\u001Eбритайнаг фунты\u001Eлар\u001Eлары\u001Eсом\u001Eсомы\u001EАИШ-ы доллар\u001EАИШ-ы доллары\u001Eнӕзонгӕ валютӕ\u001Eнӕзонгӕ валютӕйы\u001F02\u001F010123456789\u001D,\u001D \u001D-\u001D1\u001D#,##0.###"

internal val CURRENCY_PLURAL_NAMES_OSA_US: String =
    "osa\u001F00\u001F02\u001F02"

internal val CURRENCY_PLURAL_NAMES_OS_GE: String =
    "os\u001F00\u001F02\u001F02"
