/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * CLDR's own person name test data, turned into a fixture.
 *
 * Better than an ICU golden for this domain, and worth saying why: these files
 * ship in the same release as the tables, so unlike a golden extracted from an
 * ICU build made from a nearby CLDR snapshot they carry no version skew at all.
 * What they cannot check is the order derivation, because every case names its
 * order outright.
 */
class PersonNameCase(
    val locale: String,
    /** Field name, possibly with a `-modifier` suffix, to value. */
    val fields: List<Pair<String, String>>,
    val nameLocale: String,
    val order: String,
    val length: String,
    val usage: String,
    val formality: String,
    val expected: String,
)

fun parsePersonNameCases(cldrDir: File): List<PersonNameCase> {
    val dir = cldrDir.resolve("common/testData/personNameTest")
    check(dir.isDirectory) { "CLDR person name test data is not checked out at $dir" }

    val cases = ArrayList<PersonNameCase>()
    for (file in dir.listFiles()!!.filter { it.extension == "txt" && !it.name.startsWith("_") }.sortedBy { it.name }) {
        val locale = canonicalTag(file.nameWithoutExtension)
        var fields = ArrayList<Pair<String, String>>()
        var nameLocale = ""
        var expected: String? = null
        for (raw in file.readLines()) {
            val line = raw.substringBefore('#').trim()
            if (line.isEmpty()) continue
            val parts = line.split(';').map(String::trim)
            when (parts[0]) {
                "name" -> {
                    val key = parts.getOrNull(1).orEmpty()
                    val value = parts.getOrNull(2).orEmpty()
                    if (key == "locale") nameLocale = canonicalTag(value) else fields.add(key to value)
                }
                "expectedResult" -> expected = parts.getOrNull(1).orEmpty()
                "parameters" -> {
                    val result = expected ?: continue
                    cases.add(
                        PersonNameCase(
                            locale = locale,
                            fields = fields.toList(),
                            nameLocale = nameLocale,
                            order = parts.getOrNull(1).orEmpty(),
                            length = parts.getOrNull(2).orEmpty(),
                            usage = parts.getOrNull(3).orEmpty(),
                            formality = parts.getOrNull(4).orEmpty(),
                            expected = result,
                        ),
                    )
                }
                "endName" -> {
                    fields = ArrayList()
                    nameLocale = ""
                    expected = null
                }
            }
        }
    }
    println("[codegen] parsed ${cases.size} CLDR person name cases")
    check(cases.size > 30_000) { "expected CLDR's whole person name fixture, got ${cases.size}" }
    return cases
}

/**
 * Emits the fixture into the consuming module's own tests.
 *
 * Chunked into several constants for the same reason the phone edge cases are: a
 * single string literal this size does not survive every target's compiler, and
 * the shared conformance module is linked into every other module's test binary,
 * so thirty-seven thousand cases there would be carried by every domain.
 */
fun emitPersonNameCases(outputFile: File, cldrTag: String, cases: List<PersonNameCase>) {
    outputFile.parentFile.mkdirs()
    val chunks = cases.chunked(2000)

    fun encode(case: PersonNameCase): String = listOf(
        case.locale,
        case.fields.joinToString(KEY_SEPARATOR) { (name, value) -> "$name=$value" },
        case.nameLocale,
        case.order,
        case.length,
        case.usage,
        case.formality,
        case.expected,
    ).joinToString(FIELD_SEPARATOR)

    outputFile.writeText(
        buildString {
            append(LICENSE_HEADER + "// GENERATED by :codegen from CLDR $cldrTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.personname.conformance\n\n")
            append("public const val PERSON_NAME_CASE_VERSION: String = \"${kotlinEscape(cldrTag)}\"\n\n")
            for ((index, chunk) in chunks.withIndex()) {
                append("private val chunk$index: String =\n    \"")
                append(kotlinEscape(chunk.joinToString(LIST_SEPARATOR, transform = ::encode)))
                append("\"\n\n")
            }
            append("/**\n")
            append(" * Every case CLDR ships, decoded on first use.\n")
            append(" *\n")
            append(" * Each entry is locale, fields, name locale, order, length, usage,\n")
            append(" * formality, expected result. The fields are `name=value` pairs.\n")
            append(" */\n")
            append("public val personNameCases: List<List<String>> by lazy {\n")
            append("    listOf(${chunks.indices.joinToString(", ") { "chunk$it" }})\n")
            append("        .flatMap { it.split('\\u001E') }\n")
            append("        .map { it.split('\\u001F') }\n")
            append("}\n")
        },
    )
    println("[codegen] emitted ${cases.size} CLDR person name cases to $outputFile")
}
