package dev.carcara.kotlinx.locale.codegen

import java.io.File

private const val CURRENCY_PACKAGE = "dev.carcara.kotlinx.locale.currency"

/** One Currency enum entry: ISO 4217 identity plus CLDR fraction behavior. */
class CurrencyGen(val iso: Iso4217Currency, val fractions: CurrencyFractions)

/**
 * Emits the Currency enum into the -types layer: the entry list and nothing
 * else. The four `cldr*` fields ride along because `isoToCldrUnits` needs them
 * with no locale in play, which makes them per-entry data rather than locale
 * data.
 */
fun emitCurrencyEnum(outputFile: File, cldrTag: String, isoPublished: String, currencies: List<CurrencyGen>) {
    outputFile.parentFile.mkdirs()
    val entries = buildString {
        for (currency in currencies) {
            append("    /** ")
            append(currency.iso.name)
            append(" */\n    ")
            append(currency.iso.code)
            append("(")
            append(currency.iso.numericCode ?: -1)
            append(", ")
            append(currency.iso.minorUnits)
            append(", ")
            append(currency.fractions.digits)
            append(", ")
            append(currency.fractions.rounding)
            append(", ")
            append(currency.fractions.cashDigits)
            append(", ")
            append(currency.fractions.cashRounding)
            append("),\n")
        }
    }
    outputFile.writeText(
        """
        |// GENERATED by :codegen from ISO 4217 list one ($isoPublished) and CLDR $cldrTag. Do not edit.
        |// Regenerate with: ./gradlew :codegen:generateLocaleData
        |package $CURRENCY_PACKAGE
        |
        |/**
        | * The active currencies of ISO 4217, keyed by alphabetic code.
        | *
        | * Each entry carries the ISO numeric code and minor units together with the
        | * CLDR fraction behavior (formatting digits, rounding increments and their
        | * cash variants), which CLDR intentionally lets diverge from ISO — e.g. ALL
        | * has 2 ISO minor units but is formatted with 0 digits.
        | *
        | * Everything else is an extension: `code`, `minorUnitDigits`, the unit
        | * conversions and the `for*` lookups come from `kotlinx-locale-currency-core`,
        | * and `symbol` and `displayName` from whichever implementation module you put
        | * on the classpath.
        | */
        |public enum class Currency(
        |    /** The ISO 4217 numeric code, e.g. 840 for USD; -1 when ISO assigns none. */
        |    public val numericCode: Int,
        |    /** The ISO 4217 minor units ("decimals"); -1 when the standard lists N.A. */
        |    public val defaultFractionDigits: Int,
        |    /** The number of fraction digits CLDR uses when formatting this currency. */
        |    public val cldrFractionDigits: Int,
        |    /** CLDR rounding increment in units of the last CLDR fraction digit; 0 means none. */
        |    public val cldrRoundingIncrement: Int,
        |    /** The number of fraction digits CLDR uses for cash amounts. */
        |    public val cldrCashFractionDigits: Int,
        |    /** CLDR cash rounding increment, e.g. 5 for CHF (0.05); 0 means none. */
        |    public val cldrCashRoundingIncrement: Int,
        |) {
        |$entries    ;
        |
        |    public companion object
        |}
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${currencies.size} currencies to $outputFile")
}

/**
 * Fully resolved number-formatting payloads per locale, for the currency
 * formatter: digits, separators, minus sign, and the four currency patterns.
 */
fun buildCurrencyFormatPayloads(flattener: Flattener, extras: ExtrasResolver): Map<String, String> {
    val payloads = LinkedHashMap<String, String>()
    for (id in listOf("root") + flattener.localeIds) {
        val format = extras.resolveCurrencyFormat(id)
        payloads[canonicalTag(id)] = listOf(
            format.digits,
            format.decimal,
            format.group,
            format.currencyDecimal,
            format.currencyGroup,
            format.minusSign,
            format.minimumGroupingDigits.toString(),
            format.standardPattern,
            format.standardAlphaPattern,
            format.accountingPattern,
            format.accountingAlphaPattern,
        ).joinToString(FIELD_SEPARATOR)
    }
    return payloads
}

/**
 * Sparse per-locale currency-name payloads: the parent tag, the symbols this
 * locale's own file declares, and the display names it declares.
 */
fun buildCurrencyNamePayloads(flattener: Flattener, extras: ExtrasResolver): Map<String, String> {
    fun entries(map: Map<String, String>): String = map.entries
        .sortedBy { it.key }
        .joinToString(LIST_SEPARATOR) { (code, value) -> code + KEY_SEPARATOR + value }

    val payloads = LinkedHashMap<String, String>()
    for (id in listOf("root") + flattener.localeIds) {
        val partial = extras.partial(id)
        val parentTag = flattener.dataChain(id).getOrNull(1)?.let(::canonicalTag).orEmpty()
        payloads[canonicalTag(id)] = parentTag + FIELD_SEPARATOR +
            entries(partial.currencySymbols) + FIELD_SEPARATOR +
            entries(partial.currencyNames)
    }
    return payloads
}

/** country alpha-2 -> space-separated current legal-tender codes, preferred first. */
fun emitCountryCurrencies(
    outputFile: File,
    cldrTag: String,
    countries: List<CountryInfo>,
    supplemental: SupplementalData,
    currencyCodes: Set<String>,
) {
    outputFile.parentFile.mkdirs()
    val mapping = LinkedHashMap<String, String>()
    for (country in countries) {
        val codes = supplemental.regionCurrencies[country.alpha2]
            ?.filter { it in currencyCodes }
            .orEmpty()
        if (codes.isNotEmpty()) mapping[country.alpha2] = codes.joinToString(" ")
    }
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from CLDR $cldrTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package $CURRENCY_PACKAGE.internal\n")
            append("\nimport dev.carcara.kotlinx.locale.InternalKotlinxLocaleApi\n")
            append("\n/** country alpha-2 -> space-separated current legal-tender codes, preferred first. */\n")
            append("@InternalKotlinxLocaleApi\n")
            append("public val countryCurrencyCodes: Map<String, String> = buildMap(")
            append(mapping.size)
            append(") {\n")
            for ((alpha2, codes) in mapping) {
                append("    put(\"")
                append(alpha2)
                append("\", \"")
                append(codes)
                append("\")\n")
            }
            append("}\n")
        },
    )
    println("[codegen] emitted currency mappings for ${mapping.size} countries to $outputFile")
}
