package dev.carcara.kotlinx.locale.codegen

import java.io.File

private const val CURRENCY_PACKAGE = "dev.carcara.kotlinx.locale.currency"

/** One Currency enum entry: ISO 4217 identity plus CLDR fraction behavior. */
class CurrencyGen(val iso: Iso4217Currency, val fractions: CurrencyFractions)

/**
 * Emits the public Currency enum. Only the entry list is data-driven; the members
 * and companion are a fixed template delegating to hand-written internals.
 */
fun emitCurrencyEnum(outputFile: File, cldrTag: String, isoPublished: String, currencies: List<CurrencyGen>) {
    outputFile.parentFile.mkdirs()
    val entries = buildString {
        for (currency in currencies) {
            append("    /** ")
            append(currency.iso.name)
            append(" */\n    ")
            append(currency.iso.code)
            append("(")
            append(currency.iso.numericCode ?: -1)
            append(", ")
            append(currency.iso.minorUnits)
            append(", ")
            append(currency.fractions.digits)
            append(", ")
            append(currency.fractions.rounding)
            append(", ")
            append(currency.fractions.cashDigits)
            append(", ")
            append(currency.fractions.cashRounding)
            append("),\n")
        }
    }
    outputFile.writeText(
        """
        |// GENERATED by :codegen from ISO 4217 list one ($isoPublished) and CLDR $cldrTag. Do not edit.
        |// Regenerate with: ./gradlew :codegen:generateLocaleData
        |package $CURRENCY_PACKAGE
        |
        |import dev.carcara.kotlinx.locale.Locale
        |import dev.carcara.kotlinx.locale.country.Country
        |import dev.carcara.kotlinx.locale.currency.internal.currencyDisplayNameFor
        |import dev.carcara.kotlinx.locale.currency.internal.currencySymbolFor
        |import dev.carcara.kotlinx.locale.currency.internal.primaryCurrencyOf
        |import dev.carcara.kotlinx.locale.currency.internal.rescaleFraction
        |
        |/**
        | * The active currencies of ISO 4217, keyed by alphabetic code.
        | *
        | * Each entry carries the ISO numeric code and minor units together with the
        | * CLDR fraction behavior (formatting digits, rounding increments and their
        | * cash variants), which CLDR intentionally lets diverge from ISO — e.g. ALL
        | * has 2 ISO minor units but is formatted with 0 digits. [isoToCldrUnits] and
        | * [cldrToIsoUnits] convert amounts between the two scales.
        | */
        |public enum class Currency(
        |    /** The ISO 4217 numeric code, e.g. 840 for USD; -1 when ISO assigns none. */
        |    public val numericCode: Int,
        |    /** The ISO 4217 minor units ("decimals"); -1 when the standard lists N.A. */
        |    public val defaultFractionDigits: Int,
        |    /** The number of fraction digits CLDR uses when formatting this currency. */
        |    public val cldrFractionDigits: Int,
        |    /** CLDR rounding increment in units of the last CLDR fraction digit; 0 means none. */
        |    public val cldrRoundingIncrement: Int,
        |    /** The number of fraction digits CLDR uses for cash amounts. */
        |    public val cldrCashFractionDigits: Int,
        |    /** CLDR cash rounding increment, e.g. 5 for CHF (0.05); 0 means none. */
        |    public val cldrCashRoundingIncrement: Int,
        |) {
        |$entries    ;
        |
        |    /** The ISO 4217 alphabetic code, e.g. `USD`. */
        |    public val code: String
        |        get() = name
        |
        |    /**
        |     * The fraction digits of ISO minor-unit amounts such as
        |     * [CurrencyAmount.minorUnits]: [defaultFractionDigits], or 0 when ISO
        |     * defines no minor units.
        |     */
        |    public val minorUnitDigits: Int
        |        get() = if (defaultFractionDigits >= 0) defaultFractionDigits else 0
        |
        |    /**
        |     * The CLDR currency symbol for [locale] (e.g. `US${'$'}` for USD in pt-BR),
        |     * resolved through the locale's inheritance chain; falls back to [code].
        |     */
        |    public fun symbol(locale: Locale = Locale.current): String =
        |        currencySymbolFor(this, locale) ?: code
        |
        |    /** The CLDR display name for [locale]; falls back to [code]. */
        |    public fun displayName(locale: Locale = Locale.current): String =
        |        currencyDisplayNameFor(this, locale) ?: code
        |
        |    /**
        |     * Converts an amount in ISO minor units to the CLDR fraction scale,
        |     * rounding half-even when CLDR uses fewer digits than ISO.
        |     * For ALL (ISO 2 decimals, CLDR 0): `12345 -> 123`.
        |     */
        |    public fun isoToCldrUnits(minorUnits: Long): Long =
        |        rescaleFraction(minorUnits, minorUnitDigits, cldrFractionDigits)
        |
        |    /**
        |     * Converts an amount in the CLDR fraction scale back to ISO minor units.
        |     * For ALL: `123 -> 12300`.
        |     */
        |    public fun cldrToIsoUnits(cldrUnits: Long): Long =
        |        rescaleFraction(cldrUnits, cldrFractionDigits, minorUnitDigits)
        |
        |    public companion object {
        |        private val byCode: Map<String, Currency> by lazy { entries.associateBy(Currency::code) }
        |        private val byNumeric: Map<Int, Currency> by lazy {
        |            entries.filter { it.numericCode >= 0 }.associateBy(Currency::numericCode)
        |        }
        |
        |        /** The currency with the given ISO 4217 alphabetic code, case-insensitively, or `null`. */
        |        public fun forCodeOrNull(code: String): Currency? = byCode[code.uppercase()]
        |
        |        /** Like [forCodeOrNull] but throws on unknown codes. */
        |        public fun forCode(code: String): Currency =
        |            requireNotNull(forCodeOrNull(code)) { "Unknown ISO 4217 code: '${'$'}code'" }
        |
        |        /** The currency with the given ISO 4217 numeric code, or `null`. */
        |        public fun forNumericCodeOrNull(code: Int): Currency? = byNumeric[code]
        |
        |        /** Like [forNumericCodeOrNull] but throws on unknown codes. */
        |        public fun forNumericCode(code: Int): Currency =
        |            requireNotNull(forNumericCodeOrNull(code)) { "Unknown ISO 4217 numeric code: ${'$'}code" }
        |
        |        /** The primary legal-tender currency of [country] per CLDR, or `null`. */
        |        public fun forCountryOrNull(country: Country): Currency? = primaryCurrencyOf(country)
        |
        |        /** The primary currency of [locale]'s region, or `null`. */
        |        public fun forLocaleOrNull(locale: Locale = Locale.current): Currency? =
        |            Country.forLocaleOrNull(locale)?.let(::forCountryOrNull)
        |    }
        |}
        |
        """.trimMargin(),
    )
    println("[codegen] emitted ${currencies.size} currencies to $outputFile")
}

/**
 * Fully resolved number-formatting payloads per locale, for the currency
 * formatter: digits, separators, minus sign, and the four currency patterns.
 */
fun buildCurrencyFormatPayloads(flattener: Flattener, extras: ExtrasResolver): Map<String, String> {
    val payloads = LinkedHashMap<String, String>()
    for (id in listOf("root") + flattener.localeIds) {
        val format = extras.resolveCurrencyFormat(id)
        payloads[canonicalTag(id)] = listOf(
            format.digits,
            format.decimal,
            format.group,
            format.currencyDecimal,
            format.currencyGroup,
            format.minusSign,
            format.minimumGroupingDigits.toString(),
            format.standardPattern,
            format.standardAlphaPattern,
            format.accountingPattern,
            format.accountingAlphaPattern,
        ).joinToString(FIELD_SEPARATOR)
    }
    return payloads
}

/**
 * Sparse per-locale currency-name payloads: the parent tag, the symbols this
 * locale's own file declares, and the display names it declares.
 */
fun buildCurrencyNamePayloads(flattener: Flattener, extras: ExtrasResolver): Map<String, String> {
    fun entries(map: Map<String, String>): String = map.entries
        .sortedBy { it.key }
        .joinToString(LIST_SEPARATOR) { (code, value) -> code + KEY_SEPARATOR + value }

    val payloads = LinkedHashMap<String, String>()
    for (id in listOf("root") + flattener.localeIds) {
        val partial = extras.partial(id)
        val parentTag = flattener.dataChain(id).getOrNull(1)?.let(::canonicalTag).orEmpty()
        payloads[canonicalTag(id)] = parentTag + FIELD_SEPARATOR +
            entries(partial.currencySymbols) + FIELD_SEPARATOR +
            entries(partial.currencyNames)
    }
    return payloads
}

/** country alpha-2 -> space-separated current legal-tender codes, preferred first. */
fun emitCountryCurrencies(
    outputFile: File,
    cldrTag: String,
    countries: List<CountryInfo>,
    supplemental: SupplementalData,
    currencyCodes: Set<String>,
) {
    outputFile.parentFile.mkdirs()
    val mapping = LinkedHashMap<String, String>()
    for (country in countries) {
        val codes = supplemental.regionCurrencies[country.alpha2]
            ?.filter { it in currencyCodes }
            .orEmpty()
        if (codes.isNotEmpty()) mapping[country.alpha2] = codes.joinToString(" ")
    }
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from CLDR $cldrTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package $CURRENCY_PACKAGE.internal.data\n")
            append("\n/** country alpha-2 -> space-separated current legal-tender codes, preferred first. */\n")
            append("internal val countryCurrencyCodes: Map<String, String> = buildMap(")
            append(mapping.size)
            append(") {\n")
            for ((alpha2, codes) in mapping) {
                append("    put(\"")
                append(alpha2)
                append("\", \"")
                append(codes)
                append("\")\n")
            }
            append("}\n")
        },
    )
    println("[codegen] emitted currency mappings for ${mapping.size} countries to $outputFile")
}
