package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * Unicode's own grapheme cluster conformance cases, turned into a fixture.
 *
 * `GraphemeBreakTest.txt` is the normative test for UAX #29, and since CLDR 44
 * the copy in `common/properties/segments` is the same file the UCD publishes.
 * Every case is one string with a mark at each position saying whether a break
 * belongs there, so passing all of them is the definition of implementing the
 * algorithm rather than approximating it.
 *
 * Taken from the CLDR checkout rather than fetched, so it is pinned by the same
 * tag as everything else and cannot drift from the properties.
 */
class GraphemeBreakCase(
    /** The whole string, as code points. */
    val codePoints: List<Int>,
    /** Offsets in code points where a break belongs, ascending, including 0 and the end. */
    val breaks: List<Int>,
)

fun parseGraphemeBreakCases(cldrDir: File): List<GraphemeBreakCase> {
    val file = cldrDir.resolve("common/properties/segments/GraphemeBreakTest.txt")
    check(file.isFile) { "GraphemeBreakTest.txt is not checked out at $file" }

    val cases = ArrayList<GraphemeBreakCase>()
    for (raw in file.readLines()) {
        val line = raw.substringBefore('#').trim()
        if (line.isEmpty()) continue

        val codePoints = ArrayList<Int>()
        val breaks = ArrayList<Int>()
        for (token in line.split(' ').filter(String::isNotEmpty)) {
            when (token) {
                // U+00F7 division sign: a break belongs here.
                "÷" -> breaks.add(codePoints.size)
                // U+00D7 multiplication sign: no break here.
                "×" -> Unit
                else -> codePoints.add(token.toInt(16))
            }
        }
        if (codePoints.isNotEmpty()) cases.add(GraphemeBreakCase(codePoints, breaks))
    }

    println("[codegen] grapheme break: ${cases.size} conformance cases")
    check(cases.size > 1000) { "expected Unicode's whole grapheme fixture, got ${cases.size}" }
    return cases
}

/**
 * Emits the cases into the module that implements the algorithm.
 *
 * Each case is the code points in base 36 and the break offsets after a colon,
 * which keeps a fixture of this size to a few tens of kilobytes of source.
 */
fun emitGraphemeBreakCases(outputFile: File, ucdVersion: String, cases: List<GraphemeBreakCase>, table: String) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from Unicode $ucdVersion. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.conformance\n\n")
            append("public const val GRAPHEME_BREAK_VERSION: String = \"${kotlinEscape(ucdVersion)}\"\n\n")
            append("/**\n")
            append(" * The property table itself, so the conformance test can install it.\n")
            append(" *\n")
            append(" * The shipped artifacts carry their own copy through the bundle; this one\n")
            append(" * exists so the algorithm can be tested without depending on any of them.\n")
            append(" */\n")
            append("public val graphemeBreakTable: String = \"${kotlinEscape(table)}\"\n\n")
            append("/**\n")
            append(" * Every case of Unicode's `GraphemeBreakTest.txt`.\n")
            append(" *\n")
            append(" * Each entry is the code points, then a colon, then the offsets in code\n")
            append(" * points where a break belongs. Both are base 36.\n")
            append(" */\n")
            append("public val graphemeBreakCases: List<String> = listOf(\n")
            for (case in cases) {
                val points = case.codePoints.joinToString(",") { it.toString(36) }
                val breaks = case.breaks.joinToString(",") { it.toString(36) }
                append("    \"$points:$breaks\",\n")
            }
            append(")\n")
        },
    )
    println("[codegen] emitted ${cases.size} grapheme break cases to $outputFile")
}
