package dev.carcara.kotlinx.locale.codegen

import com.ibm.icu.text.DateIntervalFormat
import com.ibm.icu.util.DateInterval
import com.ibm.icu.util.GregorianCalendar
import com.ibm.icu.util.TimeZone
import com.ibm.icu.util.ULocale
import java.io.File

/**
 * Goldens for interval formatting, asked of ICU's own `DateIntervalFormat`.
 *
 * The cases are chosen to reach one greatest-difference field each, because that
 * is the axis the data is keyed on and the axis a wrong split shows up in. A
 * pair differing only in the day exercises the entry that writes the month once;
 * a pair differing in the year exercises the one that writes everything twice.
 *
 * The identical pair is here deliberately. UTS #35 says an interval whose ends
 * agree in every field the skeleton names formats once, and it is the case most
 * likely to come out as the same text twice with a dash in it.
 */
private val INTERVAL_GOLDEN_CASES: List<Triple<String, IntArray, IntArray>> = listOf(
    Triple("yMMMd", intArrayOf(2026, 7, 22), intArrayOf(2026, 7, 22)),
    Triple("yMMMd", intArrayOf(2026, 7, 18), intArrayOf(2026, 7, 22)),
    Triple("yMMMd", intArrayOf(2026, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("yMMMd", intArrayOf(2025, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("yMd", intArrayOf(2026, 7, 18), intArrayOf(2026, 7, 22)),
    Triple("yMd", intArrayOf(2026, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("yMd", intArrayOf(2025, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("MMMd", intArrayOf(2026, 7, 18), intArrayOf(2026, 7, 22)),
    Triple("MMMd", intArrayOf(2026, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("Md", intArrayOf(2026, 7, 18), intArrayOf(2026, 7, 22)),
    Triple("yMMM", intArrayOf(2026, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("yMMM", intArrayOf(2025, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("yMMMEd", intArrayOf(2026, 7, 18), intArrayOf(2026, 7, 22)),
    Triple("MMMEd", intArrayOf(2026, 5, 18), intArrayOf(2026, 7, 22)),
    Triple("y", intArrayOf(2025, 5, 18), intArrayOf(2026, 7, 22)),
)

class IcuIntervalGoldenEntry(val tag: String, val results: List<String>)

private fun millisOf(date: IntArray): Long {
    val calendar = GregorianCalendar(TimeZone.GMT_ZONE)
    calendar.clear()
    calendar.set(date[0], date[1] - 1, date[2], 12, 0, 0)
    return calendar.timeInMillis
}

fun extractIcuIntervalGolden(localeTags: Set<String>): List<IcuIntervalGoldenEntry> {
    ULocale.setDefault(ULocale.ROOT)
    java.util.Locale.setDefault(java.util.Locale.ROOT)

    val available = ULocale.getAvailableLocales().mapTo(HashSet()) { it.toLanguageTag() }
    val entries = ArrayList<IcuIntervalGoldenEntry>()
    var missing = 0

    for (tag in localeTags.sorted()) {
        if (tag !in available) {
            missing++
            continue
        }
        // Pin the calendar, so a locale carrying its own preference does not
        // answer for one this library does not implement.
        val locale = ULocale.forLanguageTag("$tag-u-ca-gregory")
        val results = INTERVAL_GOLDEN_CASES.map { (skeleton, start, end) ->
            val formatter = DateIntervalFormat.getInstance(skeleton, locale)
            formatter.timeZone = TimeZone.GMT_ZONE
            formatter.format(DateInterval(millisOf(start), millisOf(end)))
        }
        entries.add(IcuIntervalGoldenEntry(tag, results))
    }

    println(
        "[codegen] interval goldens cover ${entries.size} locales x ${INTERVAL_GOLDEN_CASES.size} cases; $missing are absent from ICU4J",
    )
    check(entries.size > 500) { "expected the interval goldens to cover most locales, got ${entries.size}" }
    return entries
}

fun emitIcuIntervalGolden(outputFile: File, icuTag: String, entries: List<IcuIntervalGoldenEntry>) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from ICU $icuTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.datetime.cldr.intervals.conformance\n\n")
            append("public const val ICU_INTERVAL_GOLDEN_VERSION: String = \"${kotlinEscape(icuTag)}\"\n\n")
            append("/** Skeleton, then start and end as `yyyy-MM-dd`, in the order every record answers. */\n")
            append("public val icuIntervalGoldenCases: List<Triple<String, String, String>> = listOf(\n")
            for ((skeleton, start, end) in INTERVAL_GOLDEN_CASES) {
                val from = "%04d-%02d-%02d".format(start[0], start[1], start[2])
                val to = "%04d-%02d-%02d".format(end[0], end[1], end[2])
                append("    Triple(\"$skeleton\", \"$from\", \"$to\"),\n")
            }
            append(")\n\n")
            append("/** Locale tag to its answers, positional against [icuIntervalGoldenCases]. */\n")
            append("public val icuIntervalGolden: Map<String, List<String>> =\n")
            append("    buildMap(${entries.size}) {\n")
            for (entry in entries) {
                append("        put(\"${kotlinEscape(entry.tag)}\", ")
                append("\"${kotlinEscape(entry.results.joinToString(LIST_SEPARATOR))}\".split('\\u001E'))\n")
            }
            append("    }\n")
        },
    )
    println("[codegen] emitted ${entries.size} ICU interval golden locales to $outputFile")
}
