package dev.carcara.kotlinx.locale.codegen

import com.ibm.icu.number.LocalizedNumberFormatter
import com.ibm.icu.number.Notation
import com.ibm.icu.number.NumberFormatter
import com.ibm.icu.number.Precision
import com.ibm.icu.text.DecimalFormat
import com.ibm.icu.text.DecimalFormatSymbols
import com.ibm.icu.text.NumberFormat
import com.ibm.icu.util.ULocale
import java.io.File
import java.math.BigDecimal

/**
 * Goldens for the number engine, generated by asking ICU4J the same questions.
 *
 * The skeleton goldens exist because UTS #35 states the matching rules tersely.
 * These exist for a stronger reason: on several of the questions below the
 * specification states nothing at all, and this library picked an answer. A
 * sentence in a KDoc saying "we round half to even" is a claim; a fixture that
 * fails the build when it stops being true is the same claim with something
 * holding it up.
 *
 * What is pinned here, in the order it matters:
 *
 * The compact default precision. UTS #35 says the significant digits are
 * "typically" two or three and then that APIs may override, which is why two
 * implementations of the same document disagree about the same number. The
 * option sets below run every compact value through ICU's own default.
 *
 * Re-selecting the magnitude after rounding, so 999999 is `1M` and not `1000K`.
 * The specification's ten steps do not describe this. ICU does it, so this
 * library does it, and this is where that is written down in a form the build
 * reads.
 *
 * The rounding mode. Half to even, which is ICU's default and
 * `java.text.DecimalFormat`'s, against ECMA-402's half away from zero. The
 * fraction-digit option sets carry the values where the two differ.
 *
 * The plural category compact selects on. Step 8 of the algorithm runs over the
 * divided and rounded value rather than the original, so 1500 in Polish takes
 * the `few` pattern by way of 1.5 rather than the `other` pattern by way of
 * 1500. The value list is built to hit every category any locale distinguishes.
 */

/**
 * The locales the number goldens cover.
 *
 * The shared golden set, plus the ones that are here for a specific reason:
 * `lt sl cy hi ar ru pl cs` between them exercise every plural category compact
 * selection can land on, and `eu gl rm bs_Cyrl de_CH` are five of the ten
 * locales whose compact table uses a literal `"0"` pattern to override a
 * parent's entry back to standard notation.
 */
val ICU_NUMBER_GOLDEN_LOCALES: List<String> = (
    ICU_GOLDEN_LOCALES + listOf(
        "lt", "sl", "cy", "eu", "gl", "rm", "bs_Cyrl", "de_CH", "es_419",
        "hu", "ro", "sr", "el", "da", "bg", "ca", "sk", "hr", "et", "lv",
        "fa", "bn", "ta", "mr", "am", "is", "sq", "nb", "sw", "ms",
    )
    ).distinct()

/**
 * The values every option set is asked about.
 *
 * Written as strings rather than as numbers because the scale is load bearing:
 * `1.50` and `1.5` are the same quantity and different plural categories in
 * Czech, and a double would lose the difference before ICU ever saw it.
 *
 * The magnitudes run 10^2 to 10^12 with the boundary values at each step,
 * because a compact table has an entry per magnitude and a bug in the divide
 * shows up at the edges rather than in the middle.
 */
val ICU_NUMBER_GOLDEN_VALUES: List<String> = listOf(
    "0", "1", "-1", "2", "5", "12", "-12",
    "0.001", "0.075", "0.125", "0.5", "-0.5", "1.005", "1.5", "2.5", "1.50",
    "100", "999", "1000", "1100", "1500", "1950", "2000", "5000", "9999",
    "12000", "12345", "99999", "100000", "123456", "999999",
    "1000000", "1200000", "1500000", "1999999", "12000000", "999999999",
    "1000000000", "1200000000", "1000000000000", "1200000000000",
    "1234.56", "-1234.56", "1234567.891",
)

/** One option set: a name, and the ICU call that answers it. */
class IcuNumberOptionSet(
    val name: String,
    /** True when the set uses one of the compact notations. */
    val compact: Boolean = false,
    val format: (ULocale, BigDecimal) -> String,
)

/** An option set that runs through the modern `NumberFormatter` pipeline. */
private fun formatter(
    name: String,
    compact: Boolean = false,
    configure: (LocalizedNumberFormatter) -> LocalizedNumberFormatter,
): IcuNumberOptionSet = IcuNumberOptionSet(name, compact) { locale, value ->
    configure(NumberFormatter.withLocale(locale)).format(value).toString()
}

/**
 * An option set that runs through the legacy percent instance.
 *
 * `NumberFormatter.unit(NoUnit.PERCENT)` is not the call to compare against
 * here. It decouples the unit from the pattern, so it keeps the decimal
 * pattern's three fraction digits and writes 0.001 as `0.001%`. What this
 * library implements is the CLDR percent pattern, `#,##0%`, which multiplies by
 * 100 and carries its own precision, and `getPercentInstance` is the ICU call
 * that means the same thing. Feeding it the fraction rather than the scaled
 * value keeps the comparison on the pattern and the rounding instead of on the
 * scale question the two entry points exist to keep apart.
 */
private fun percentInstance(name: String, fractionDigits: Int? = null): IcuNumberOptionSet = IcuNumberOptionSet(name) { locale, value ->
    val format = NumberFormat.getPercentInstance(locale) as DecimalFormat
    if (fractionDigits != null) {
        format.minimumFractionDigits = fractionDigits
        format.maximumFractionDigits = fractionDigits
    }
    format.format(value)
}

/**
 * The option sets, each of which is a question the library answers and ICU
 * answers independently.
 *
 * The percent sets format an already-scaled value through ICU's
 * `NoUnit.PERCENT`, which does not multiply. That is deliberate: whether a
 * percent API multiplies is the one place the two reference implementations
 * disagree outright, and this library names both readings rather than picking
 * one, so a golden that folded the scale in would be testing a decision instead
 * of the pattern and the rounding.
 */
val ICU_NUMBER_OPTION_SETS: List<IcuNumberOptionSet> = listOf(
    formatter("standard") { it },
    formatter("grouping-never") { it.grouping(NumberFormatter.GroupingStrategy.OFF) },
    formatter("grouping-always") { it.grouping(NumberFormatter.GroupingStrategy.ON_ALIGNED) },
    formatter("fraction-0") { it.precision(Precision.minMaxFraction(0, 0)) },
    formatter("fraction-2") { it.precision(Precision.minMaxFraction(2, 2)) },
    formatter("fraction-1-4") { it.precision(Precision.minMaxFraction(1, 4)) },
    formatter("sign-always") { it.sign(NumberFormatter.SignDisplay.ALWAYS) },
    formatter("sign-never") { it.sign(NumberFormatter.SignDisplay.NEVER) },
    formatter("sign-except-zero") { it.sign(NumberFormatter.SignDisplay.EXCEPT_ZERO) },
    formatter("sign-negative") { it.sign(NumberFormatter.SignDisplay.NEGATIVE).precision(Precision.minMaxFraction(0, 0)) },
    percentInstance("percent"),
    percentInstance("percent-fraction-2", fractionDigits = 2),
    formatter("compact-short", compact = true) { it.notation(Notation.compactShort()) },
    formatter("compact-long", compact = true) { it.notation(Notation.compactLong()) },
    formatter("compact-short-sign-always", compact = true) {
        it.notation(Notation.compactShort()).sign(NumberFormatter.SignDisplay.ALWAYS)
    },
)

class IcuNumberGoldenEntry(
    val tag: String,
    /** Option set name to its answers, positional against [ICU_NUMBER_GOLDEN_VALUES]. */
    val answers: Map<String, List<String>>,
)

/**
 * Whether ICU's number tables for [tag] say the same as the ones we resolved.
 *
 * Same reasoning as the skeleton goldens: ICU 78.3 is built from a CLDR
 * snapshot near but not identical to `release-48-2`, and comparing an engine
 * against a golden generated from different input reports a data difference as
 * an algorithm failure. The symbols and the two patterns are checked for every
 * option set; the compact table is checked on top of that for the sets that
 * read it, so a locale whose compact entries moved between the two releases is
 * still covered for everything else.
 */
private fun icuAgreesOnNumbers(tag: String, symbolPayload: String?, patternPayload: String?): Boolean {
    if (symbolPayload == null || patternPayload == null) return false
    val locale = ULocale.forLanguageTag(tag)
    val symbols = DecimalFormatSymbols.getInstance(locale)
    val ours = symbolPayload.split(FIELD_SEPARATOR)
    if (ours.size < 18) return false

    fun same(icu: String?, mine: String): Boolean = icu != null && icu.normalizedSpaces() == mine.normalizedSpaces()

    if (!same(symbols.decimalSeparatorString, ours[2])) return false
    if (!same(symbols.groupingSeparatorString, ours[3])) return false
    if (!same(symbols.minusSignString, ours[6])) return false
    if (!same(symbols.plusSignString, ours[7])) return false
    if (!same(symbols.percentString, ours[8])) return false
    if (symbols.digitStrings.joinToString("") != ours[1]) return false

    val decimal = NumberFormat.getInstance(locale) as? DecimalFormat ?: return false
    val percent = NumberFormat.getPercentInstance(locale) as? DecimalFormat ?: return false
    val patterns = patternPayload.split(FIELD_SEPARATOR)
    if (patterns.size < 2) return false
    if (!same(decimal.toPattern(), patterns[0])) return false
    if (!same(percent.toPattern(), patterns[1])) return false
    return decimal.minimumGroupingDigits == ours[17].toIntOrNull()
}

/**
 * Whether ICU's compact tables for [tag] match the ones we emitted.
 *
 * Read out of the clone's resource bundles rather than through the formatter,
 * because there is no public ICU4J call that hands back the table. Our key is
 * `magnitude:count`, ICU's is the power of ten written out, so magnitude 3 is
 * ICU's `1000`.
 */
private fun icuAgreesOnCompact(resolver: IcuResolver, cldrId: String, payload: String, path: String): Boolean {
    val system = resolver.string(cldrId, "NumberElements", "default") ?: "latn"
    val ours = HashMap<String, String>()
    for (entry in payload.split(LIST_SEPARATOR)) {
        if (entry.isEmpty()) continue
        val split = entry.indexOf('=')
        if (split > 0) ours[entry.substring(0, split)] = entry.substring(split + 1)
    }

    // Walked from ICU's side rather than ours, because the interesting
    // disagreements are entries ICU resolves and we answer by falling back.
    // Reading only our own keys would let those through, and they are exactly
    // what the goldens would then fail on.
    for (magnitude in 3..MAXIMUM_COMPACT_MAGNITUDE) {
        val power = "1" + "0".repeat(magnitude)
        for (count in PLURAL_COUNTS) {
            val icu = resolver.string(cldrId, "NumberElements", system, path, "decimalFormat", power, count)
                ?: resolver.string(cldrId, "NumberElements", "latn", path, "decimalFormat", power, count)
                ?: continue
            // What this library would answer: the exact key, or the `other`
            // entry of the same magnitude, which is the lookup's own fallback.
            val mine = ours["$magnitude:$count"] ?: ours["$magnitude:other"] ?: return false
            if (icu.normalizedSpaces() != mine.normalizedSpaces()) return false
        }
    }
    return true
}

/** The largest power of ten any CLDR compact table declares, with room to spare. */
private const val MAXIMUM_COMPACT_MAGNITUDE = 14

private val PLURAL_COUNTS = listOf("zero", "one", "two", "few", "many", "other")

/** ICU and CLDR point releases disagree on which no-break space they use. */
private fun String.normalizedSpaces(): String = replace('\u00A0', ' ').replace('\u202F', ' ')

fun extractIcuNumberGolden(
    icuDir: File,
    numberSymbols: Map<String, String>,
    numberPatterns: Map<String, String>,
    compactShort: Map<String, String>,
    compactLong: Map<String, String>,
): List<IcuNumberGoldenEntry> {
    // Same reason as the skeleton goldens: ICU resolves a locale it does not
    // carry against the default locale, so an unpinned JVM would answer in
    // whatever the build machine was set to.
    ULocale.setDefault(ULocale.ROOT)
    java.util.Locale.setDefault(java.util.Locale.ROOT)

    val available = ULocale.getAvailableLocales().mapTo(HashSet()) { it.toLanguageTag() }
    val resolver = IcuResolver(icuDir.resolve("icu4c/source/data/locales"))
    val values = ICU_NUMBER_GOLDEN_VALUES.map(::BigDecimal)

    val missing = ArrayList<String>()
    val disagreeing = ArrayList<String>()
    val compactDropped = ArrayList<String>()
    val entries = ArrayList<IcuNumberGoldenEntry>()

    for (cldrId in ICU_NUMBER_GOLDEN_LOCALES) {
        val tag = canonicalTag(cldrId)
        if (tag !in available) {
            missing.add(tag)
            continue
        }
        if (!icuAgreesOnNumbers(tag, numberSymbols[tag], numberPatterns[tag])) {
            disagreeing.add(tag)
            continue
        }
        val compactAgrees =
            icuAgreesOnCompact(resolver, cldrId, compactShort[tag].orEmpty(), "patternsShort") &&
                icuAgreesOnCompact(resolver, cldrId, compactLong[tag].orEmpty(), "patternsLong")
        if (!compactAgrees) compactDropped.add(tag)

        val locale = ULocale.forLanguageTag(tag)
        val answers = LinkedHashMap<String, List<String>>()
        for (set in ICU_NUMBER_OPTION_SETS) {
            if (set.compact && !compactAgrees) continue
            answers[set.name] = values.map { set.format(locale, it) }
        }
        entries.add(IcuNumberGoldenEntry(tag, answers))
    }

    println(
        "[codegen] number goldens cover ${entries.size} locales " +
            "(${ICU_NUMBER_OPTION_SETS.size} option sets x ${values.size} values); " +
            "${missing.size} are absent from ICU4J, ${disagreeing.size} have symbols or patterns " +
            "ICU disagrees with, and ${compactDropped.size} kept everything but the compact sets",
    )
    check(entries.size >= 30) { "expected the number goldens to cover at least 30 locales, got ${entries.size}" }
    return entries
}

fun emitIcuNumberGolden(outputFile: File, icuTag: String, entries: List<IcuNumberGoldenEntry>) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from ICU $icuTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.conformance\n\n")
            append("public const val ICU_NUMBER_GOLDEN_VERSION: String = \"${kotlinEscape(icuTag)}\"\n\n")
            append("/** The values every golden record answers, in order, written as the scale matters. */\n")
            append("public val icuNumberGoldenValues: List<String> = listOf(\n")
            for (value in ICU_NUMBER_GOLDEN_VALUES) append("    \"${kotlinEscape(value)}\",\n")
            append(")\n\n")
            append("/** Locale tag to option set name to answers, positional against [icuNumberGoldenValues]. */\n")
            append("public val icuNumberGoldenData: Map<String, Map<String, List<String>>> = buildMap(${entries.size}) {\n")
            for (entry in entries.sortedBy { it.tag }) {
                append("    put(\n")
                append("        \"${kotlinEscape(entry.tag)}\",\n")
                append("        mapOf(\n")
                for ((name, answers) in entry.answers) {
                    append("            \"${kotlinEscape(name)}\" to\n")
                    append("                \"${kotlinEscape(answers.joinToString(LIST_SEPARATOR))}\".split('\\u001E'),\n")
                }
                append("        ),\n")
                append("    )\n")
            }
            append("}\n")
        },
    )
    println("[codegen] emitted ${entries.size} ICU number golden entries to $outputFile")
}
