package dev.carcara.kotlinx.locale.codegen

import java.io.File

/**
 * Golden fixtures for the country and currency modules, extracted from ICU's
 * region/, curr/ and locales/ resource bundles — the same independent
 * cross-check idea as the datetime module's [IcuGoldenEntry] data.
 */

/** A diverse spread of countries whose ICU names the golden test verifies. */
val ICU_GOLDEN_COUNTRIES = listOf(
    "US", "GB", "BR", "DE", "FR", "JP", "CN", "IN", "RU", "EG",
    "MX", "CH", "ZA", "KR", "TR", "UA", "SA", "AR",
)

/** The currencies whose ICU symbols and names the golden test verifies. */
val ICU_GOLDEN_CURRENCIES = listOf(
    "USD", "EUR", "JPY", "GBP", "BRL", "CHF", "INR", "CNY", "RUB",
    "EGP", "MXN", "KRW", "TRY", "ZAR", "SAR", "ARS", "UAH",
)

class IcuCountryGoldenEntry(
    val tag: String,
    /** alpha2 -> ICU display name; absent when ICU defines none for the locale. */
    val names: Map<String, String>,
)

class IcuCurrencyGoldenEntry(
    val tag: String,
    /** code -> ICU symbol (index 0 of the Currencies array). */
    val symbols: Map<String, String>,
    /** code -> ICU display name (index 1 of the Currencies array). */
    val names: Map<String, String>,
    val decimal: String?,
    val group: String?,
    val currencyPattern: String?,
)

fun extractIcuCountryGolden(icuDir: File): List<IcuCountryGoldenEntry> {
    val resolver = IcuResolver(icuDir.resolve("icu4c/source/data/region"))
    return goldenLocales(icuDir.resolve("icu4c/source/data/region")).map { id ->
        val names = LinkedHashMap<String, String>()
        for (code in ICU_GOLDEN_COUNTRIES) {
            resolver.string(id, "Countries", code)?.let { names[code] = it }
        }
        IcuCountryGoldenEntry(canonicalTag(id), names)
    }
}

fun extractIcuCurrencyGolden(icuDir: File): List<IcuCurrencyGoldenEntry> {
    val currencyResolver = IcuResolver(icuDir.resolve("icu4c/source/data/curr"))
    val localesResolver = IcuResolver(icuDir.resolve("icu4c/source/data/locales"))
    return goldenLocales(icuDir.resolve("icu4c/source/data/curr")).map { id ->
        val symbols = LinkedHashMap<String, String>()
        val names = LinkedHashMap<String, String>()
        for (code in ICU_GOLDEN_CURRENCIES) {
            val entry = currencyResolver.list(id, "Currencies", code)
            entry?.getOrNull(0)?.let { symbols[code] = it }
            entry?.getOrNull(1)?.let { names[code] = it }
        }
        val system = localesResolver.string(id, "NumberElements", "default") ?: "latn"
        fun element(vararg path: String): String? =
            localesResolver.string(id, "NumberElements", system, *path)
                ?: localesResolver.string(id, "NumberElements", "latn", *path)
        IcuCurrencyGoldenEntry(
            tag = canonicalTag(id),
            symbols = symbols,
            names = names,
            decimal = element("symbols", "decimal"),
            group = element("symbols", "group"),
            currencyPattern = element("patterns", "currencyFormat"),
        )
    }
}

/** The golden locales that actually have a bundle in [dir]. */
private fun goldenLocales(dir: File): List<String> =
    ICU_GOLDEN_LOCALES.filter { id ->
        dir.resolve("$id.txt").exists().also {
            if (!it) println("[codegen] WARNING: ICU golden locale $id missing from ${dir.name}, skipping")
        }
    }

/** The full ICU numeric-code table, emitted so every platform re-runs the cross-check. */
fun extractIcuNumericCodes(icuDir: File): Map<String, Int> {
    val file = icuDir.resolve("icu4c/source/data/misc/currencyNumericCodes.txt")
    val codeMap = (parseIcuBundle(file).second.entries["codeMap"] as? IcuTable)
        ?: error("${file.name}: missing codeMap table")
    val result = LinkedHashMap<String, Int>()
    for ((code, value) in codeMap.entries) {
        (value as? IcuString)?.value?.toIntOrNull()?.let { result[code] = it }
    }
    check(result.size > 250) { "implausibly small ICU numeric code table (${result.size})" }
    return result
}

fun emitIcuCountryGolden(outputFile: File, icuTag: String, entries: List<IcuCountryGoldenEntry>) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(buildString {
        append("// GENERATED by :codegen from ICU $icuTag. Do not edit.\n")
        append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
        append("package dev.carcara.kotlinx.locale.country\n\n")
        append("internal const val ICU_VERSION: String = \"${kotlinEscape(icuTag)}\"\n\n")
        append("internal class IcuCountryGolden(\n")
        append("    val tag: String,\n")
        append("    val names: Map<String, String>,\n")
        append(")\n\n")
        append("internal val icuCountryGoldenData: List<IcuCountryGolden> = listOf(\n")
        for (entry in entries) {
            append("    IcuCountryGolden(\n")
            append("        tag = \"${kotlinEscape(entry.tag)}\",\n")
            append("        names = mapOf(\n")
            for ((code, name) in entry.names) {
                append("            \"${kotlinEscape(code)}\" to \"${kotlinEscape(name)}\",\n")
            }
            append("        ),\n")
            append("    ),\n")
        }
        append(")\n")
    })
    println("[codegen] emitted ${entries.size} ICU country golden entries to $outputFile")
}

fun emitIcuCurrencyGolden(
    outputFile: File,
    icuTag: String,
    entries: List<IcuCurrencyGoldenEntry>,
    numericCodes: Map<String, Int>,
) {
    outputFile.parentFile.mkdirs()
    fun stringOrNull(value: String?): String = if (value == null) "null" else "\"${kotlinEscape(value)}\""
    fun map(values: Map<String, String>): String = buildString {
        append("mapOf(\n")
        for ((key, value) in values) {
            append("            \"${kotlinEscape(key)}\" to \"${kotlinEscape(value)}\",\n")
        }
        append("        )")
    }
    outputFile.writeText(buildString {
        append("// GENERATED by :codegen from ICU $icuTag. Do not edit.\n")
        append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
        append("package dev.carcara.kotlinx.locale.currency\n\n")
        append("internal const val ICU_VERSION: String = \"${kotlinEscape(icuTag)}\"\n\n")
        append("internal class IcuCurrencyGolden(\n")
        append("    val tag: String,\n")
        append("    val symbols: Map<String, String>,\n")
        append("    val names: Map<String, String>,\n")
        append("    val decimal: String?,\n")
        append("    val group: String?,\n")
        append("    val currencyPattern: String?,\n")
        append(")\n\n")
        append("internal val icuCurrencyGoldenData: List<IcuCurrencyGolden> = listOf(\n")
        for (entry in entries) {
            append("    IcuCurrencyGolden(\n")
            append("        tag = \"${kotlinEscape(entry.tag)}\",\n")
            append("        symbols = ${map(entry.symbols)},\n")
            append("        names = ${map(entry.names)},\n")
            append("        decimal = ${stringOrNull(entry.decimal)},\n")
            append("        group = ${stringOrNull(entry.group)},\n")
            append("        currencyPattern = ${stringOrNull(entry.currencyPattern)},\n")
            append("    ),\n")
        }
        append(")\n\n")
        append("/** ICU's independently maintained ISO 4217 numeric-code table. */\n")
        append("internal val icuCurrencyNumericCodes: Map<String, Int> = mapOf(\n")
        for ((code, numeric) in numericCodes) {
            append("    \"${kotlinEscape(code)}\" to $numeric,\n")
        }
        append(")\n")
    })
    println(
        "[codegen] emitted ${entries.size} ICU currency golden entries and " +
            "${numericCodes.size} numeric codes to $outputFile",
    )
}
