/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import com.ibm.icu.text.DateTimePatternGenerator
import com.ibm.icu.util.ULocale
import java.io.File

/**
 * Goldens for the skeleton matcher, generated by asking ICU4J the same questions.
 *
 * This is the only place ICU is called rather than read. `:codegen` runs at
 * build time and is never published, so the dependency cannot reach a consumer;
 * what ships is the answers. The matcher itself is written from scratch, and
 * these fixtures are what hold it to ICU's behaviour in the corners UTS #35
 * states tersely — how a missing field is weighed against a wrong width, which
 * of `M` and `L` a locale's pattern imposes, and when a requested width loses to
 * the one the locale wrote.
 *
 * Generated whole rather than sampled: every locale against every skeleton, so
 * that a locale which inherits an unusual `availableFormats` is covered by
 * construction rather than by whoever picked the sample.
 */

/**
 * Requests the goldens cover, on top of every skeleton id CLDR declares.
 *
 * The declared ids exercise the exact-match path. These exercise the rest of it:
 * hour-cycle resolution, a width the locale did not declare, a field no
 * candidate covers so the append formats have to run, and a request spanning
 * both halves so the date-time glue has to run.
 */
private val EXTRA_GOLDEN_SKELETONS = listOf(
    "j", "jj", "jm", "jms", "jmm", "J", "Jm", "Jms", "C", "Cm", "Cms",
    "yMMMdjm", "yMMMdjms", "yMMMEdjm", "yMdjm", "yMMMMdjms",
    "yQQQQHm", "yMMMdQQQ", "GyMMMdE", "yMMMMdE",
    "MMMMEEEEd", "yMMMMEEEEd", "hmsa", "Hmsa", "Bhm", "bhm",
    "yyyyMMdd", "yyMM", "MMd", "ddMM", "yMMMMM", "EEEEE", "GGGGyMd",
    "dE", "Gy", "y", "M", "d", "E", "h", "H", "m", "s", "a", "Q",
)

class IcuSkeletonGoldenEntry(val tag: String, val patterns: List<String>)

/**
 * Whether ICU's own tables for [cldrId] say the same as the ones we resolved.
 *
 * ICU 78.3 is built from a CLDR snapshot close to, but not identical with, the
 * `release-48-2` tag this library pins: ICU's `en_HK` carries no `Md` at all
 * where CLDR 48.2 declares one, and its `ckb` carries no field display names.
 * Comparing the matcher against a golden generated from different input would
 * report a data difference as an algorithm failure, so those locales are left
 * out — and counted, so the gap is visible.
 */
private fun icuAgreesOnTables(
    resolver: IcuResolver,
    cldrId: String,
    dateTime: ResolvedLocaleData,
    skeletons: ResolvedSkeletonData,
    /** The ids this locale's own CLDR file declares, before inheritance. */
    declared: Map<String, String>,
): Boolean {
    fun same(a: String?, b: String): Boolean = a == null || a.normalizedSpaces() == b.normalizedSpaces()

    // Only the entries the matcher actually carries. The ones filtered out are
    // the week-numbering ids, which ICU stores as a plural-form table rather
    // than a string and which would read as "absent" here.
    val carried = skeletons.availableFormats.filterKeys { isSupportedSkeleton(it, skeletons.availableFormats.getValue(it)) }
    for ((skeleton, pattern) in carried) {
        if (!same(resolver.string(cldrId, "calendar", "gregorian", "availableFormats", skeleton), pattern)) return false
    }

    // An id the locale declares for itself has to be one ICU also resolves.
    // ICU's it_CH carries no availableFormats block at all, so where CLDR 48.2
    // declares Swiss Italian MM.y, ICU answers Italy's MM/y by widening its yM
    // entry — a gap that shows up only once the matcher runs, never in a
    // value-to-value comparison of the entries both sides do have.
    for (skeleton in declared.keys) {
        if (skeleton !in carried) continue
        resolver.string(cldrId, "calendar", "gregorian", "availableFormats", skeleton) ?: return false
    }
    for ((index, name) in skeletons.fieldNames.withIndex()) {
        if (name.isEmpty()) continue
        if (!same(resolver.string(cldrId, "fields", DATE_FIELD_TYPES[index], "dn"), name)) return false
    }

    // DateTimePatterns is one flat list: four time patterns, four date ones,
    // then a legacy glue entry and the four real ones. The matcher scores
    // against the eight standard patterns and joins with the atTime glue, so a
    // locale ICU spells any of those differently is not comparable.
    val patterns = resolver.list(cldrId, "calendar", "gregorian", "DateTimePatterns")
    if (patterns != null) {
        for (i in 0..3) {
            if (!same(patterns.getOrNull(i), dateTime.timeFormats[i])) return false
            if (!same(patterns.getOrNull(i + 4), dateTime.dateFormats[i])) return false
        }
    }
    val atTime = resolver.list(cldrId, "calendar", "gregorian", "DateTimePatterns%atTime")
    if (atTime != null) {
        for (i in 0..3) if (!same(atTime.getOrNull(i), skeletons.glueAtTimeFormats[i])) return false
    }
    return true
}

/** ICU and CLDR point releases disagree on which no-break space they use. */
private fun String.normalizedSpaces(): String = replace('\u00A0', ' ').replace('\u202F', ' ')

/**
 * Every skeleton the goldens ask about: the union of the ids CLDR declares
 * across all locales, plus [EXTRA_GOLDEN_SKELETONS], sorted so the emitted list
 * is stable.
 */
fun goldenSkeletons(skeletonFormats: Map<String, String>): List<String> {
    val declared = LinkedHashSet<String>()
    for (payload in skeletonFormats.values) {
        for (entry in payload.split(LIST_SEPARATOR)) {
            val separator = entry.indexOf(KEY_SEPARATOR)
            if (separator > 0) declared.add(entry.substring(0, separator))
        }
    }
    return (declared + EXTRA_GOLDEN_SKELETONS).sorted()
}

fun extractIcuSkeletonGolden(
    icuDir: File,
    skeletons: List<String>,
    /** CLDR file id to its resolved skeleton data, for every locale in the build. */
    resolved: Map<String, ResolvedSkeletonData>,
    /** The same locales' resolved pattern data, which the matcher also reads. */
    dateTime: Map<String, ResolvedLocaleData>,
    /** The same locales' own declared skeleton ids, before inheritance. */
    declaredFormats: Map<String, Map<String, String>>,
): List<IcuSkeletonGoldenEntry> {
    // ICU resolves a locale it does not carry against the *default* locale, not
    // against root, so on an unpinned JVM every such locale silently answers in
    // whatever the build machine was set to. Pinning the default to root makes
    // the fallback the inheritance chain, which is the thing being compared.
    ULocale.setDefault(ULocale.ROOT)
    java.util.Locale.setDefault(java.util.Locale.ROOT)

    // ICU4J carries a subset of the locales CLDR publishes, and answers for the
    // rest out of whatever ancestor it does carry. Comparing those would not be
    // testing the matcher, it would be reporting that we have data for
    // Abkhazian and the jar does not, so they are left out — and counted, so
    // the narrowing is visible rather than silent.
    val icuLocales = ULocale.getAvailableLocales().mapTo(HashSet()) { it.toLanguageTag() }
    val resolver = IcuResolver(icuDir.resolve("icu4c/source/data/locales"))

    val missing = ArrayList<String>()
    val disagreeing = ArrayList<String>()
    val covered = ArrayList<String>()
    for ((cldrId, data) in resolved) {
        val tag = canonicalTag(cldrId)
        when {
            tag !in icuLocales -> missing.add(tag)
            !icuAgreesOnTables(
                resolver,
                cldrId,
                dateTime.getValue(cldrId),
                data,
                declaredFormats.getValue(cldrId),
            ) -> disagreeing.add(tag)
            else -> covered.add(tag)
        }
    }
    println(
        "[codegen] skeleton goldens cover ${covered.size} locales; " +
            "${missing.size} are absent from ICU4J and ${disagreeing.size} have tables ICU disagrees with",
    )

    return covered.map { tag ->
        // Pinned to the gregorian calendar: ICU would otherwise generate persian
        // patterns for Iran and Afghanistan and buddhist ones for Thailand, and
        // this library is gregorian only.
        val generator = DateTimePatternGenerator.getInstance(
            ULocale.forLanguageTag("$tag-u-ca-gregory"),
        )
        IcuSkeletonGoldenEntry(
            tag = tag,
            patterns = skeletons.map { skeleton ->
                // ICU throws on a skeleton it cannot parse rather than declining;
                // an empty golden means "nothing to hold the matcher to here".
                runCatching { generator.getBestPattern(skeleton) }.getOrDefault("")
            },
        )
    }
}

/**
 * Writes the fixtures as one record per locale rather than one object per
 * (locale, skeleton).
 *
 * The cross product is around eighty thousand answers. As objects that is a
 * source file no compiler should be asked to read; as one delimited string per
 * locale it is the same shape as the data tables the library already ships, and
 * the test splits it back apart.
 */
fun emitIcuSkeletonGolden(outputDir: File, icuTag: String, skeletons: List<String>, entries: List<IcuSkeletonGoldenEntry>) {
    outputDir.mkdirs()
    outputDir.listFiles { f: File -> f.extension == "kt" && f.name.startsWith("IcuSkeletonGolden") }
        ?.forEach(File::delete)

    val header = LICENSE_HEADER + "// GENERATED by :codegen from ICU $icuTag. Do not edit.\n" +
        "// Regenerate with: ./gradlew :codegen:generateLocaleData\n" +
        "package ${packageOf(outputDir.resolve("IcuSkeletonGoldenData.kt"))}\n"

    // Deduplicate: locales that resolve to the same patterns for every skeleton
    // share one constant, which is most of them.
    val constByPayload = LinkedHashMap<String, String>()
    val constByTag = LinkedHashMap<String, String>()
    for (entry in entries) {
        val payload = entry.patterns.joinToString(LIST_SEPARATOR)
        val const = constByPayload.getOrPut(payload) { "ICU_SKELETONS_" + entry.tag.uppercase().replace('-', '_') }
        constByTag[entry.tag] = const
    }

    val byBucket = LinkedHashMap<Char, MutableList<Pair<String, String>>>()
    for ((payload, const) in constByPayload) {
        val owner = const.removePrefix("ICU_SKELETONS_").lowercase()
        byBucket.getOrPut(owner.first()) { ArrayList() }.add(const to payload)
    }
    for ((bucket, constants) in byBucket) {
        outputDir.resolve("IcuSkeletonGoldenData_$bucket.kt").writeText(
            buildString {
                append(header)
                for ((const, payload) in constants.sortedBy { it.first }) {
                    append("\ninternal val ")
                    append(const)
                    append(": String =\n    \"")
                    append(kotlinEscape(payload))
                    append("\"\n")
                }
            },
        )
    }

    outputDir.resolve("IcuSkeletonGoldenData.kt").writeText(
        buildString {
            append(header)
            append("\npublic const val ICU_SKELETON_GOLDEN_VERSION: String = \"")
            append(kotlinEscape(icuTag))
            append("\"\n")
            append("\n/** The skeletons every golden record answers, in order. */\n")
            append("public val icuGoldenSkeletons: List<String> = listOf(\n")
            for (skeleton in skeletons) {
                append("    \"")
                append(kotlinEscape(skeleton))
                append("\",\n")
            }
            append(")\n")
            append("\n/** Locale tag to its patterns, positional against [icuGoldenSkeletons]. */\n")
            append("public val icuSkeletonGoldenData: Map<String, List<String>> = buildMap(")
            append(constByTag.size)
            append(") {\n")
            for ((tag, const) in constByTag.entries.sortedBy { it.key }) {
                append("    put(\"")
                append(kotlinEscape(tag))
                append("\", ")
                append(const)
                append(".split('\\u001E'))\n")
            }
            append("}\n")
        },
    )

    println(
        "[codegen] emitted ${constByTag.size} ICU skeleton golden locales " +
            "(${constByPayload.size} unique payloads, ${skeletons.size} skeletons) to $outputDir",
    )
}
