package dev.carcara.kotlinx.locale.codegen

import com.ibm.icu.util.Calendar
import com.ibm.icu.util.ULocale
import java.io.File

/**
 * Goldens for week data, asked of ICU's own `Calendar`.
 *
 * Keyed by locale rather than by territory, which is deliberate even though the
 * data is territory-keyed. What can go wrong here is not the four values, which
 * are copied out of one small block; it is the resolution, which has to find a
 * territory from a locale that need not name one. Asking ICU per locale exercises
 * the region subtag, the likely-subtags overlay and the world default in the same
 * pass, and those are the three places an answer can be plausible and wrong.
 *
 * It also catches one specific misreading for free. `supplementalData.xml` carries
 * an `alt="variant"` row putting Britain's first day on Sunday, written after the
 * row that lists GB among the Monday territories. ICU says Monday, so taking the
 * variant fails here rather than shipping.
 */

/** ICU numbers days Sunday 1 through Saturday 7; ISO numbers them Monday 1 through Sunday 7. */
private fun isoDayOf(icuDay: Int): Int = (icuDay + 5) % 7 + 1

class IcuWeekDataGoldenEntry(
    val tag: String,
    val firstDay: Int,
    val minimalDays: Int,
    /** Bit `n - 1` set for ISO day `n`. */
    val weekendMask: Int,
)

fun extractIcuWeekDataGolden(localeTags: Set<String>): List<IcuWeekDataGoldenEntry> {
    ULocale.setDefault(ULocale.ROOT)
    java.util.Locale.setDefault(java.util.Locale.ROOT)

    val available = ULocale.getAvailableLocales().mapTo(HashSet()) { it.toLanguageTag() }
    val entries = ArrayList<IcuWeekDataGoldenEntry>()
    var missing = 0

    for (tag in localeTags.sorted()) {
        if (tag !in available) {
            missing++
            continue
        }
        // Pin the calendar so a locale carrying its own `-u-ca-` preference does
        // not answer for a calendar this library does not implement.
        val calendar = Calendar.getInstance(ULocale.forLanguageTag("$tag-u-ca-gregory"))

        var mask = 0
        for (icuDay in Calendar.SUNDAY..Calendar.SATURDAY) {
            // ICU models the onset and cease of a weekend as times of day, where
            // CLDR names whole days. Anything that is not a plain weekday counts.
            if (calendar.getDayOfWeekType(icuDay) != Calendar.WEEKDAY) {
                mask = mask or (1 shl (isoDayOf(icuDay) - 1))
            }
        }

        entries.add(
            IcuWeekDataGoldenEntry(
                tag = tag,
                firstDay = isoDayOf(calendar.firstDayOfWeek),
                minimalDays = calendar.minimalDaysInFirstWeek,
                weekendMask = mask,
            ),
        )
    }

    println("[codegen] week data goldens cover ${entries.size} locales; $missing are absent from ICU4J")
    check(entries.size > 500) { "expected the week data goldens to cover most locales, got ${entries.size}" }
    // The canary, stated as an assertion rather than left to the runtime test:
    // if these three ever agree, the resolution has collapsed to one answer.
    val byTag = entries.associateBy(IcuWeekDataGoldenEntry::tag)
    check(byTag["en-US"]?.firstDay == 7) { "ICU should start the American week on Sunday" }
    check(byTag["en-GB"]?.firstDay == 1) { "ICU should start the British week on Monday" }
    // Portugal is the useful third case rather than a second European Monday: it
    // starts on Sunday like the United States but wants four days in the year
    // like its neighbours, so the two fields genuinely vary independently.
    check(byTag["pt-PT"]?.firstDay == 7) { "ICU should start the Portuguese week on Sunday" }
    check(byTag["pt-PT"]?.minimalDays == 4) { "Portugal should want four days in week one" }
    return entries
}

fun emitIcuWeekDataGolden(outputFile: File, icuTag: String, entries: List<IcuWeekDataGoldenEntry>) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
        buildString {
            append("// GENERATED by :codegen from ICU $icuTag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.datetime.cldr.conformance\n\n")
            append("public const val ICU_WEEK_DATA_GOLDEN_VERSION: String = \"${kotlinEscape(icuTag)}\"\n\n")
            append("/**\n")
            append(" * Locale tag to the first day of its week, its minimum days in week one,\n")
            append(" * and its weekend as a bit set over ISO day numbers.\n")
            append(" */\n")
            append("public val icuWeekDataGolden: Map<String, Triple<Int, Int, Int>> =\n")
            append("    buildMap(${entries.size}) {\n")
            for (entry in entries) {
                append(
                    "        put(\"${kotlinEscape(entry.tag)}\", " +
                        "Triple(${entry.firstDay}, ${entry.minimalDays}, ${entry.weekendMask}))\n",
                )
            }
            append("    }\n")
        },
    )
    println("[codegen] emitted ${entries.size} ICU week data golden locales to $outputFile")
}
