/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.codegen

import com.google.i18n.phonenumbers.NumberParseException
import com.google.i18n.phonenumbers.PhoneNumberUtil
import java.io.File

/**
 * Goldens for the phone engine, generated by asking libphonenumber itself.
 *
 * The same arrangement as the ICU fixtures, and for a stronger reason. The ICU
 * goldens hold an implementation of a written specification to the reference
 * implementation of that specification. Here there is no specification at all
 * beyond ITU-T E.164's numbering plans: what "valid" means for a Brazilian
 * mobile is whatever libphonenumber's metadata says, and what the parser does
 * with `(11) 96123-4567` is whatever `PhoneNumberUtil` does with it. So this
 * library is not implementing a document, it is reimplementing a program, and
 * the only honest way to claim it agrees is to run both and compare.
 *
 * Generated over every territory rather than a sample, using each type's own
 * example number, so a territory whose parsing rule this library reads wrongly
 * fails here rather than in a consumer's signup form.
 */

/** One territory's answers, positional against the types it declares. */
class PhoneGoldenEntry(
    val territoryId: String,
    val callingCode: Int,
    /** `type=example=e164=international=national=rfc3966=validity`, one per declared type. */
    val cases: List<String>,
)

private val GOLDEN_TYPES = listOf(
    PhoneNumberUtil.PhoneNumberType.FIXED_LINE,
    PhoneNumberUtil.PhoneNumberType.MOBILE,
    PhoneNumberUtil.PhoneNumberType.TOLL_FREE,
    PhoneNumberUtil.PhoneNumberType.PREMIUM_RATE,
    PhoneNumberUtil.PhoneNumberType.SHARED_COST,
    PhoneNumberUtil.PhoneNumberType.VOIP,
    PhoneNumberUtil.PhoneNumberType.PERSONAL_NUMBER,
    PhoneNumberUtil.PhoneNumberType.PAGER,
    PhoneNumberUtil.PhoneNumberType.UAN,
    PhoneNumberUtil.PhoneNumberType.VOICEMAIL,
)

fun extractPhoneGolden(): List<PhoneGoldenEntry> {
    val util = PhoneNumberUtil.getInstance()
    val entries = ArrayList<PhoneGoldenEntry>()
    var cases = 0

    for (region in util.supportedRegions.sorted()) {
        val callingCode = util.getCountryCodeForRegion(region)
        val rows = ArrayList<String>()
        for (type in GOLDEN_TYPES) {
            val example = util.getExampleNumberForType(region, type) ?: continue
            val e164 = util.format(example, PhoneNumberUtil.PhoneNumberFormat.E164)
            // Round-tripped through the parser rather than formatted from the
            // example directly, because parsing is half of what is being
            // compared and a golden that skipped it would only test formatting.
            val parsed = try {
                util.parse(e164, region)
            } catch (_: NumberParseException) {
                continue
            }
            rows += listOf(
                type.name,
                e164,
                util.format(parsed, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL),
                util.format(parsed, PhoneNumberUtil.PhoneNumberFormat.NATIONAL),
                util.format(parsed, PhoneNumberUtil.PhoneNumberFormat.RFC3966),
                util.getNumberType(parsed).name,
                if (util.isValidNumber(parsed)) "1" else "0",
                util.getRegionCodeForNumber(parsed) ?: "",
            ).joinToString("=")
            cases++
        }
        if (rows.isNotEmpty()) entries.add(PhoneGoldenEntry(region, callingCode, rows))
    }

    println("[codegen] phone goldens cover ${entries.size} territories and $cases numbers")
    check(entries.size > 200) { "expected the goldens to cover most territories, got ${entries.size}" }
    return entries
}

fun emitPhoneGolden(outputFile: File, tag: String, entries: List<PhoneGoldenEntry>) {
    outputFile.parentFile.mkdirs()
    outputFile.writeText(
        buildString {
            append(LICENSE_HEADER + "// GENERATED by :codegen from libphonenumber $tag. Do not edit.\n")
            append("// Regenerate with: ./gradlew :codegen:generateLocaleData\n")
            append("package dev.carcara.kotlinx.locale.phone.conformance\n\n")
            append("public const val PHONE_GOLDEN_VERSION: String = \"${kotlinEscape(tag)}\"\n\n")
            append("/** One case: type, E.164, international, national, RFC 3966, reported type, validity, region. */\n")
            append("public class PhoneGoldenCase(\n")
            append("    public val type: String,\n")
            append("    public val e164: String,\n")
            append("    public val international: String,\n")
            append("    public val national: String,\n")
            append("    public val rfc3966: String,\n")
            append("    public val reportedType: String,\n")
            append("    public val isValid: Boolean,\n")
            append("    public val region: String,\n")
            append(")\n\n")
            append("/** Territory id to the cases libphonenumber answers for it. */\n")
            append("public val phoneGoldenData: Map<String, List<PhoneGoldenCase>> = buildMap(${entries.size}) {\n")
            for (entry in entries) {
                append("    put(\"${kotlinEscape(entry.territoryId)}\", decodePhoneGolden(\"")
                append(kotlinEscape(entry.cases.joinToString(LIST_SEPARATOR)))
                append("\"))\n")
            }
            append("}\n\n")
            append("private fun decodePhoneGolden(record: String): List<PhoneGoldenCase> =\n")
            append("    record.split('\\u001E').map { row ->\n")
            append("        val f = row.split('=')\n")
            append("        PhoneGoldenCase(f[0], f[1], f[2], f[3], f[4], f[5], f[6] == \"1\", f[7])\n")
            append("    }\n")
        },
    )
    println("[codegen] emitted ${entries.size} phone golden territories to $outputFile")
}

/**
 * Fails generation when the pinned clone and the jar on the classpath differ.
 *
 * Same reasoning as the ICU check: the clone supplies the metadata this library
 * ships and the jar supplies the answers it is held to, so a skew between them
 * would produce a fixture that disagrees with the data it is testing.
 */
fun crossCheckPhoneVersion(repoDir: File) {
    val expected = PHONE_REPO.tag.removePrefix("v")
    val versionFile = repoDir.resolve("java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java")
    check(versionFile.isFile) { "libphonenumber sources missing; widen PHONE_REPO.sparsePaths" }
    // The jar has no version constant, so the metadata it carries is compared
    // instead: if the two releases described different territories, they are
    // different releases.
    val jarRegions = PhoneNumberUtil.getInstance().supportedRegions.size
    val cloneRegions = parseXml(repoDir.resolve("resources/PhoneNumberMetadata.xml"))
        .documentElement.childElements("territories").first()
        .childElements("territory").count { it.getAttribute("id") != "001" }
    check(jarRegions == cloneRegions) {
        "the pinned libphonenumber clone describes $cloneRegions territories but the jar on the codegen " +
            "classpath describes $jarRegions. The metadata this library ships and the answers it is held " +
            "to have to come from one release; align gradle/libs.versions.toml with Repos.kt (expected $expected)."
    }
    println("[codegen] libphonenumber $expected clone and jar agree on $jarRegions territories")
}
