/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.durations.internal.data

internal val DURATION_UNITS_PA: String =
    "01Ho绋塂恆ऄ㉻Ꮠᆋ᮹䂔梮መ὜ᓬ璉⸈ᥗറ⏸଼檊㲝⊄䩪㦭嫂挆柙蓃Ⳮ᧴㇃ᙰ椺⥬ါჱ㺟ᰒ厯ᘒ劬厸ᠾన䦎籘權录䓂䎮⵪⇽៭滢宫㲧䑺䤈ぷᄇ罀㿱室⾧粒გ甊ᖶណㅙ翉∽⬽斑圜檲猙㥺稝᝜憓殉痢劌⚤莋㍟㰁ಮ腵垞⛁ᗻ淰ሎ咹䊪୪ູ㝫崸栱殈㪡狯䟴樅翚栻宻᪏༛ᚺ᳿ᐜ膟泇㬢苅䈷㊼៹絒⼻⧲狌㫺乶䈚嶧愨⳦ᚯയ⵰浈㌊蓰ᯗ䚡汨ศଔঊࣅࡢ亳ସ湤㕣綠ཌ໹⏛嬙༤㚍虇匕⪀布㨬䡥ᨊ惾⨫碩尡奴➟ズ⡰"

internal val DURATION_UNITS_PCM: String =
    "00vh盋ᡓ墆ै㩿ၬ撁模㭠榶ㄌ⹭倠噩Მ⸤⩆䫃搄○哈ᚡὬ箉擄煍ጛ⸢億滣䯻睿翚楤෱擥蕽☪唏篧比媰熙㧻ႂ朿㙞䤤㶫㳞琞㔩ూ଍಍椷ᇄ掁ᤶ㩟ዤᮾ蛞檘脣厺杵甴怉⼔Ḭ偸娖ᲊ⣍䴼䨴⫦䤊窤獌ሸ⫂䎑㪸ಾᡅ彝弣幡疿择椕緬ⴣ䎽㙇眃䪜❠滰Ꭺ岉劮⻵ᅈ᷑祏䇴蓀咕䀑构扯岶㉮ᥴ糜曡យ䊭睭ᭁᬚ屿ᯁ䡺庌‴䪩஦宨瓷༐氛䏺仭ᗃ囑៨潓繚◂䲛皬⑭Ⲁ蟜疪佤滀⨗䗂ጃ⛗⊕䴣萃ᆢゔმᚻஂᙇᅰ᭤懼㕋❛ᚽශ潼树䍸乶䐐玒䦶ᬂ茙湉⁩傗㸀埙⫸舩ূ爑ᘴ戼₲㇤⑇空笙ㆌ䇮㧪∶ठཟ睍ঔᓻ࿡祡佄俆伌耾㦷䛁䢑浬౪䅻ᏸ♁堀"

internal val DURATION_UNITS_PL: String =
    "00dI滊塓恦ऄ㉾ጀ፡䂒犬 㚴䭅ᆢᶰ⠹ੳ怲䧷㙄燍弚㦰ី师⍌蟧胩熬窸⊵峺祿膸ᕂዥ傋灷㏵爑䊇⵪環䡵៊砜傧ಒ㨈㷬癹廕ᾱᮘ䥪怐㍐࿙䍹⟚⇕柜⒖㴊䁳舥稽縚Ẫ懼腟嶀伧䤍䙀務叚殅悚䮇掦Ⅽᕖⱷ劇㫗㹽䱵眝໫䲶ᷚ᮹ጛ肎帤哣埪䪉ᨰፀ㘎臶圚ணጠ扈繢冞㻅膓⻯粒๪羿肦䁉⌠䫙痥ᒟᯕ䥂⥬壢ẘ筭ᚲ珞慬蚶樒澘沌䙟掂緛聯㯍潄㫌䴨ḱதࡆ唬瓜㣩䶎㦊⃹䕽Ⳉ厊‼ⷕ晼⫪ᩧ蕢蚛箱ॏ᮪㾁⒠嗼㪯ᦉ㫘䢥恺⢣殶␦䤑ᴔ塦༔㠴ⴅᯱ萖挐㨐蓚耩⪴糟莯匇ᰢ䴂Ⳇ㿫ᚘॳ沯窢ό⽲歄㿑㑳䝿篖烡ᛧ⊵罽㟹曡㠀"

internal val DURATION_UNITS_PS: String =
    "00iT狊᱓塨ई㩿፠㾨䍡ᆉ⣒㲩┱䣻㫀⢤ᬒྨ獃棛䅲㸱០耇ά捝唰ෂ億㯯⬻ⁿ却瑲仾冔䙂叩竮荰⍘藊攲ⵔ䪑⭉࠼瘩橻ᔤ彡䒞祪㢉ᢾ硅ᜂ㕔ἡ㈒纲堆⏢⁷ᴙ珗堃莜⢫䗂怟䢘瑗挿稅ᚻ撝䀃䈓㺡漾曉ᛣᑛṩ搀ሲ⿷瑂艐᪫楠፾Ṕ᳛䅶虇Ꮈ㣻罘㽞翃㽦蚕沤椅䘑噡⺚竐喆糉凯Ẋ䏾䅜莊ઇ縤缥枻刼毗稙㭭昴ῡ㕺粙ㇲㅇ緇凵⪪廉奨䉜哮氯茳ဤᕎ蚼❯ㄅ肌䟭୚绠⎛䅕ℍ䨊ᯌ৖圏䯀毘砿侓唏ᯁ擛ఁᑳ桅⋔⼁畿䫯螑䕈巶㽐畠梄捡䡘他㗍㴡悏涟੨䬵綥䃫ࡰ⻐ᝢ᡿〧庂晥螢㕹冢ฒਯ⼴㞧兕⚩佂ཕᴅ耄"

internal val DURATION_UNITS_PS_PK: String =
    "00iT狊᱓恈ई㩿ጠ⏠嚕婄牂㫐䤎␝ᭊ喃ⳁ⧐䘘ൗ儁䱿்⇮㫎䌋粴喭Ẹ埖଻ⁿ匰繷ᗽഴ㙄凤荵䖹綬䉒炙Ⓔ⥌妤䨝帕祝⨥㷈䜳恒ᰗ᠖㟈奀⇎勄㵎⽐㘀橽歖㯃紊舠㍫嘠㪻ቅᶝ偶㋽蛓Ꮕ箭僖ਵ样苜殫抡爧卋扪ࠇᖓ䗮殈ⴺ㊠☄㫵潓絓玷䈀緿᏶莌壥蚷綯ᆌ刭䡷甉⨔瞪噎䬱㯤䎋䒔聪篬䃌Ῡឹॺ羥䆏㟉毫ⷛ㵲ᣟ崓臆る垯虝唥䊪⻲宨槊繃䜹摡⾠䏫菴磫㕈Ὸ燴⑫㋞ᙱ㹋ᬡ握੹値ᯃ磷灶┏槨筃泰⼦椊⬘耓侔ᇀ荟碛蟤㝛᥹埔牘₡ẘ砶থ即ᕍ帣腦梚壍㔩㘺⠬ᔰ૚䰟㈉㶠㾙䛸啖㩨円䦊燌厩媕⺪㫘䧑ⵃ䘀"

internal val DURATION_UNITS_PT: String =
    "00do滉孛塨ࣈ㉺勜坠舥ረᓔ䬄䣊慐▫➠时⚩坘㣙僴牅㐨症潧㦣⦣淃聿ᚦ住翗膅␐漉䝲⫔憸ᦨ㒪敍熮⢬瑋㼅᝱᪢慾嬬ഡ䰌⚔滖佄皯剥⒕筑綒耖↚㨿㏉㪱∂㵭㪾媶ᑢແ㣲ㅴ肭᭖ᔄ墤ᢋ೨濱拤㆚䵂⃵蝶⑾圡示渥㟍琸萧碮悎漬捃䴭縶甝䜥埃ᵲ掶㊩翣児脼໛嘥㩋绗Ḙ䏴㚝荾䵆屪⴬匙瀒懶厓僫⧪᨟ມ䇮唱┌⮮ᯋ䰻偯᱿璊敳ᭉヾ࿨嵘姮亢䅣䪝ቀᖹ萮䀛丰౬爐ᡤ⁳琊僦䨄㔏ँ࿡籷㾇㤵ᖽ䢸䣠"

internal val DURATION_UNITS_PT_AO: String =
    "00ds滉孛塨ࣈ㉺勜坠舥ረᓔ䬄䣊敀▫➠时⚩坘㣙烰產屐症潧㦣⦣淃聿ᚦ住篫薅␐漉䝲⫔憸ᦨ㒪敍熮⢬瑋㼅᝱᪢慾嬬ഡ䰌⚔滖佄皯剥⒕筑綒耖↚㨿㏉㪱∂㵭㪾媶ᑢແ㣲ㅴ肭᭖ᔄ墤ᢋ೨濱拤㆚䵂⃵蝶⑾圡示渥㟍琸萧碮悎漬捃䴭縶甝䜥埃ᵲ掶㊩翣児脼໛昫㲇涮㐴翨攺绽勍ე扉ḻ堡㧯ἦ᧖䯔ⰾ╒篕≦䀘俜⼗ၫၷ∯繉㖹傤峷⦺⳶౳斪匍汚੩瓢䇀睱⠃⮐悋ᣣ兠㍌ᜣ⩐ₑ愎໸ⷤ聀揹搋仞桜⡰"
