/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.durations.internal.data

internal val DURATION_UNITS_VEC: String =
    "00bI狉呛恦ࣄ㉺僙៑ᶌ唘खూத摖芝༟堭䗧崮㹍䶚⤨ᵧ㶋蟫喐ಾ㞷濐榤犞眯缓䗟了儰疩䰈芿妄ቡⳇ敂莮㗉ⶕ啂㦝丢藳揌寪欼䅃ᗷ⤁䵫㑉຅᤬〇ሖ盤様ᝑ篘㫐疡ማ菬⊭墮破䪏汆䪑Ḩ಴睦熗噂蚂癲檟荘揔沢⟉偼⪁癟䰡恺䧵ᓱ⻍蓗⃑婝猁猬㶤㕤䜵羼圔彽➢恽㢽姮⫗䈁嘳唷䓘㓁㺙䆙莐䑗䔫ᐟ簏竑璟⌇ඪ犕綟扖ᶩ䎔ᴉ検᳴却䣑侅઎嗧㒏㣞䣾哾⛰䋷ዶൺ卼ॹ坼ॹ仼઼ढ़祝檮灭䠟㒧ᨩ䩜桓㤦橛楯䤨搮㣦曩䥩಺ᥚ࠮䐖䀻蜀䠀"

internal val DURATION_UNITS_VI: String =
    "00HXᷤ昮ᕷ簯㸞罭卖ᕪእ∰㪠㬝䂵फ⬐㞗䏒ᙅ涉ତ╵䯓梼㢏㨃㰡磢虪㈘紌ધ㚤艰玹㜢औ峃凧嬎ὔ⥾ᦇ兽璌⸝㒂䪆⹋἞蓸䗗ḃ糉㫦ങ䮻ⵠ✌匨ୱ櫲堤猢㒖㘷↓䳒⨄痂मⴖᙯ⣈烬㠋䷦᫱艈䂛䃲脀ࠀ"
