package dev.carcara.kotlinx.locale.gradle

import dev.carcara.kotlinx.locale.codegen.GeneratedTable
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Holds the feature set to the table set.
 *
 * A feature declares the closure of tables generating it needs, which is what
 * makes a half-configured source set impossible to ask for. Two things can still
 * go wrong and neither is a compile error here: a table nobody can reach, and a
 * feature whose closure is missing something the source it generates refers to.
 * The first is checked below. The second is checked by
 * [GeneratedSourceCompilesTest], which generates a source set per feature and
 * runs the Kotlin compiler over it.
 */
class LocaleFeatureTest {

    @Test
    fun everyTableIsReachableFromSomeFeature() {
        // The enums and the locale catalog are not features: they carry the
        // entity sets rather than locale data, and a narrowed build takes them
        // from the published -types artifacts rather than generating its own.
        val entityTables = setOf(
            GeneratedTable.LOCALE_CATALOG,
            GeneratedTable.COUNTRY_ENUM,
            GeneratedTable.CURRENCY_ENUM,
            GeneratedTable.COUNTRY_CURRENCIES,
        )
        val unreachable = GeneratedTable.entries - LocaleFeature.REACHABLE_TABLES - entityTables
        assertEquals(
            emptySet(),
            unreachable.toSet(),
            "a table no feature asks for can never be generated by a consumer's build. " +
                "Add it to the feature that reads it, or to the entity list above if it is not locale data.",
        )
    }

    @Test
    fun everyFeatureNamesItselfTheWayTheDslDoes() {
        for (feature in LocaleFeature.entries) {
            assertTrue(
                feature.dslName.count { it == '.' } == 1,
                "${feature.name} should name itself as it is written, block.flag, not '${feature.dslName}'",
            )
            assertTrue(feature.tables.isNotEmpty(), "${feature.dslName} generates no table")
        }
    }

    @Test
    fun aFeatureThatReadsAnotherTableCarriesItInItsOwnClosure() {
        // A currency pattern substitutes the symbol into itself, so formats
        // without names would render a hole rather than fail.
        assertTrue(GeneratedTable.CURRENCY_NAMES in LocaleFeature.CURRENCY_FORMATS.tables)
        // Matching a skeleton scores against the standard patterns and rendering
        // the winner needs the calendar names.
        assertTrue(GeneratedTable.DATE_TIME in LocaleFeature.DATETIME_SKELETONS.tables)
    }
}
