/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.carcara.kotlinx.locale.gradle

import at.asitplus.testballoon.matrix.matrixConfig
import at.asitplus.testballoon.matrix.matrixSuite
import de.infix.testBalloon.framework.core.TestConfig
import de.infix.testBalloon.framework.core.testScope
import dev.carcara.kotlinx.locale.codegen.GeneratedTable
import dev.carcara.kotlinx.locale.test.assertEquals
import dev.carcara.kotlinx.locale.test.assertTrue

/**
 * Holds the feature set to the table set.
 *
 * A feature declares the closure of tables generating it needs, which is what
 * makes a half-configured source set impossible to ask for. Two things can still
 * go wrong and neither is a compile error here: a table nobody can reach, and a
 * feature whose closure is missing something the source it generates refers to.
 * The first is checked below. The second is checked by
 * [GeneratedSourceCompilesTest], which generates a source set per feature and
 * runs the Kotlin compiler over it.
 */
val LocaleFeatureTest by matrixSuite(matrixConfig { testConfig = TestConfig.testScope(isEnabled = false) }) {

    test("everyTableIsReachableFromSomeFeature") {
        // The enums and the locale catalog are not features: they carry the
        // entity sets rather than locale data, and a narrowed build takes them
        // from the published -types artifacts rather than generating its own.
        val entityTables = setOf(
            GeneratedTable.LOCALE_CATALOG,
            GeneratedTable.COUNTRY_ENUM,
            GeneratedTable.CURRENCY_ENUM,
            GeneratedTable.COUNTRY_CURRENCIES,
        )
        val unreachable = GeneratedTable.entries - LocaleFeature.REACHABLE_TABLES - entityTables
        assertEquals(
            emptySet(),
            unreachable.toSet(),
            "a table no feature asks for can never be generated by a consumer's build. " +
                "Add it to the feature that reads it, or to the entity list above if it is not locale data.",
        )
    }

    test("everyFeatureNamesItselfTheWayTheDslDoes") {
        for (feature in LocaleFeature.entries) {
            assertTrue(
                feature.dslName.count { it == '.' } == 1,
                "${feature.name} should name itself as it is written, block.flag, not '${feature.dslName}'",
            )
            assertTrue(feature.tables.isNotEmpty(), "${feature.dslName} generates no table")
        }
    }

    test("aFeatureThatReadsAnotherTableCarriesItInItsOwnClosure") {
        // A currency pattern substitutes the symbol into itself, so formats
        // without names would render a hole rather than fail.
        assertTrue(GeneratedTable.CURRENCY_NAMES in LocaleFeature.CURRENCY_FORMATS.tables)
        // Matching a skeleton scores against the standard patterns and rendering
        // the winner needs the calendar names.
        assertTrue(GeneratedTable.DATE_TIME in LocaleFeature.DATETIME_SKELETONS.tables)
    }
}
