package dev.carcara.kotlinx.locale.gradle

import dev.carcara.kotlinx.locale.codegen.BindingTarget
import dev.carcara.kotlinx.locale.codegen.LocaleDataBundle
import dev.carcara.kotlinx.locale.codegen.RegistryPackages
import dev.carcara.kotlinx.locale.codegen.SourceRoots
import dev.carcara.kotlinx.locale.codegen.generateSources
import org.gradle.api.DefaultTask
import org.gradle.api.file.ArchiveOperations
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.FileSystemOperations
import org.gradle.api.provider.Property
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Nested
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import javax.inject.Inject

/**
 * Writes a locale data set narrowed to the locales this build declares.
 *
 * The work is the same emitters the shipped artifacts are generated by, run
 * against the same bundle, so a narrowed source answers identically to a full
 * one for the locales it kept. What differs is the entry set and the package.
 *
 * Cacheable, and worth caching: reading a 2.8 MB bundle and writing a few
 * hundred kilobytes of Kotlin is slower than fetching the result.
 */
@CacheableTask
abstract class GenerateLocaleSources : DefaultTask() {

    /**
     * The `kotlinx-locale-codegen-data` artifact, resolved from the consumer's
     * repositories.
     *
     * NONE rather than the implicit ABSOLUTE: only the bundle's content decides
     * the output, so keying on the path in the dependency cache would cost every
     * cross-machine hit.
     */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val cldrData: ConfigurableFileCollection

    @get:Input
    abstract val locales: SetProperty<String>

    @get:Input
    abstract val fallbackLocale: Property<String>

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val objectPrefix: Property<String>

    @get:Nested
    abstract val features: Property<GeneratedFeatures>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @get:Inject
    abstract val archives: ArchiveOperations

    @get:Inject
    abstract val files: FileSystemOperations

    @TaskAction
    fun generate() {
        val root = outputDirectory.get().asFile
        // The emitters delete the files they own, but a feature that was turned
        // off since the last run leaves a source file nothing would remove, and
        // it would still compile into the consumer's module.
        files.delete { spec -> spec.delete(root) }
        root.mkdirs()

        val bundle = readBundle().narrowTo(
            // Sorted so the output does not depend on the set's iteration order,
            // which is what makes the task's result reproducible.
            tags = locales.get().sorted().toSet(),
            fallbackTag = fallbackLocale.get(),
        )

        val requested = features.get()
        val basePackage = packageName.get()
        val prefix = objectPrefix.get()
        val registryPackages = RegistryPackages.under(basePackage)

        generateSources(
            bundle = bundle,
            roots = SourceRoots(
                countryNames = root.takeIf { requested.countryNames },
                currencyNames = root.takeIf { requested.currencyNames || requested.currencyFormats },
                currencyFormats = root.takeIf { requested.currencyFormats },
                dateTime = root.takeIf { requested.dateTimePatterns },
                countryBinding = binding(root, basePackage, "${prefix}CountryNames", requested.countryNames),
                currencyBinding = binding(root, basePackage, "${prefix}Currency", requested.currencyNames || requested.currencyFormats),
                dateTimeBinding = binding(root, basePackage, "${prefix}DateTime", requested.dateTimePatterns),
            ),
            packages = registryPackages,
        )

        logger.lifecycle(
            "[kotlinx-locale] generated ${bundle.localeTags.size} locales " +
                "(fallback ${fallbackLocale.get()}) into $basePackage",
        )
    }

    private fun binding(root: File, basePackage: String, objectName: String, enabled: Boolean): BindingTarget? =
        if (enabled) BindingTarget(root = root, packageName = basePackage, objectName = objectName) else null

    /**
     * The bundle out of the resolved artifact.
     *
     * Read through the injected [ArchiveOperations] rather than a zip API of our
     * own, because a task action may not touch `Project` and this is the
     * replacement for `project.zipTree`.
     */
    private fun readBundle(): LocaleDataBundle {
        val candidates = cldrData.files.filter { it.isFile }
        check(candidates.isNotEmpty()) {
            "No kotlinx-locale-codegen-data on the classpath. The plugin adds it by default, so " +
                "either this build declares no repository that has it, or something replaced the " +
                "kotlinxLocaleCldrData dependency."
        }
        for (candidate in candidates) {
            // A plain bundle is accepted as well as the published artifact, which
            // is what lets a build point at a bundle it produced itself.
            if (candidate.name.endsWith(".txt")) {
                return candidate.bufferedReader().use(LocaleDataBundle::readFrom)
            }
            val entries = archives.zipTree(candidate)
                .matching { pattern -> pattern.include("**/cldr-data.txt") }
                .files
            val bundle = entries.singleOrNull() ?: continue
            return bundle.bufferedReader().use(LocaleDataBundle::readFrom)
        }
        error(
            "None of ${candidates.joinToString { it.name }} is or contains a cldr-data.txt. " +
                "Is the kotlinxLocaleCldrData dependency the right artifact?",
        )
    }
}

/**
 * The feature set, as one nested input.
 *
 * Grouped rather than left as four separate task properties so that the task's
 * inputs read the same way the DSL does, and so adding a feature is one field
 * rather than one field plus one wiring line.
 */
interface GeneratedFeatures {
    @get:Input
    val countryNames: Boolean

    @get:Input
    val currencyNames: Boolean

    @get:Input
    val currencyFormats: Boolean

    @get:Input
    val dateTimePatterns: Boolean
}
