/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.personname.cldr.internal.data

internal val PERSON_NAMES_OR: String =
    "{given} {given2} {surname} {credentials}\u001E{given-informal} {surname}\u001E{title} {surname}\u001E{given-informal}\u001E{given-monogram-allCaps}{given2-monogram-allCaps}{surname-monogram-allCaps}\u001E{given-informal-monogram-allCaps}{surname-monogram-allCaps}\u001E{given} {given2-initial} {surname} {credentials}\u001E{given-informal} {surname}\u001E{title} {surname}\u001E{given-informal}\u001E{surname-monogram-allCaps}\u001E{given-informal-monogram-allCaps}\u001E{given-initial} {given2-initial} {surname}\u001E{given-informal} {surname-initial}\u001E{title} {surname}\u001E{given-informal}\u001E{surname-monogram-allCaps}\u001E{given-informal-monogram-allCaps}\u001E{surname} {given} {given2} {credentials}\u001E{surname} {given-informal}\u001E{title} {surname}\u001E{given-informal}\u001E{surname-monogram-allCaps}{given-monogram-allCaps}{given2-monogram-allCaps}\u001E{surname-monogram-allCaps}{given-informal-monogram-allCaps}\u001E{surname} {given} {given2-initial} {credentials}\u001E{surname} {given-informal}\u001E{title} {surname}\u001E{given-informal}\u001E{surname-monogram-allCaps}\u001E{given-informal-monogram-allCaps}\u001E{surname} {given-initial} {given2-initial}\u001E{surname} {given-initial}\u001E{title} {surname}\u001E{given-informal}\u001E{surname-monogram-allCaps}\u001E{given-informal-monogram-allCaps}\u001E{surname-core}, {given} {given2} {surname-prefix}\u001E{surname}, {given-informal}\u001E{surname-core}, {given} {given2-initial} {surname-prefix}\u001E{surname}, {given-informal}\u001E{surname-core}, {given-initial} {given2-initial} {surname-prefix}\u001E{surname}, {given-informal}\u001Fund or\u001Fko si ta te vi yue zh\u001Fmedium\u001Fformal\u001F \u001F \u001F{0}.\u001F{0} {1}"
