/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_HI_LATN: String =
    "\u001FJan\u001EFeb\u001EMar\u001EApr\u001EMay\u001EJun\u001EJul\u001EAug\u001ESept\u001EOct\u001ENov\u001EDec\u001F\u001F\u001F\u001F\u001Fc000"

internal val LOCALE_STANDALONE_HNJ: String =
    "\u001F\u001F\u001F𞄈𞄦\u001E𞄆𞄨𞄰\u001E𞄗𞄄𞄤𞄰𞄦\u001E𞄙𞄤𞄱𞄨\u001E𞄑𞄤𞄱𞄨\u001E𞄊𞄧𞄳\u001E𞄎𞄤𞄲\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_HR: String =
    "siječanj\u001Eveljača\u001Eožujak\u001Etravanj\u001Esvibanj\u001Elipanj\u001Esrpanj\u001Ekolovoz\u001Erujan\u001Elistopad\u001Estudeni\u001Eprosinac\u001F\u001F\u001F\u001F\u001Fp\u001Eu\u001Es\u001Eč\u001Ep\u001Es\u001En\u001Fc3aa"

internal val LOCALE_STANDALONE_HR_BA: String =
    "siječanj\u001Eveljača\u001Eožujak\u001Etravanj\u001Esvibanj\u001Elipanj\u001Esrpanj\u001Ekolovoz\u001Erujan\u001Elistopad\u001Estudeni\u001Eprosinac\u001F\u001F\u001F\u001F\u001F\u001Fc3aa"

internal val LOCALE_STANDALONE_HSB: String =
    "januar\u001Efebruar\u001Eměrc\u001Eapryl\u001Emeja\u001Ejunij\u001Ejulij\u001Eawgust\u001Eseptember\u001Eoktober\u001Enowember\u001Edecember\u001Fjan\u001Efeb\u001Eměr\u001Eapr\u001Emej\u001Ejun\u001Ejul\u001Eawg\u001Esep\u001Eokt\u001Enow\u001Edec\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_HY: String =
    "հունվար\u001Eփետրվար\u001Eմարտ\u001Eապրիլ\u001Eմայիս\u001Eհունիս\u001Eհուլիս\u001Eօգոստոս\u001Eսեպտեմբեր\u001Eհոկտեմբեր\u001Eնոյեմբեր\u001Eդեկտեմբեր\u001F\u001F\u001F\u001F\u001F\u001F0"
