/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_DA: String =
    "\u001F\u001F\u001F\u001F\u001F\u001F200"

internal val LOCALE_STANDALONE_DE: String =
    "\u001FJan\u001EFeb\u001EMär\u001EApr\u001EMai\u001EJun\u001EJul\u001EAug\u001ESep\u001EOkt\u001ENov\u001EDez\u001F\u001F\u001FMo\u001EDi\u001EMi\u001EDo\u001EFr\u001ESa\u001ESo\u001F\u001F0"

internal val LOCALE_STANDALONE_DE_AT: String =
    "\u001FJän\u001EFeb\u001EMär\u001EApr\u001EMai\u001EJun\u001EJul\u001EAug\u001ESep\u001EOkt\u001ENov\u001EDez\u001F\u001F\u001FMo\u001EDi\u001EMi\u001EDo\u001EFr\u001ESa\u001ESo\u001F\u001F0"

internal val LOCALE_STANDALONE_DOI: String =
    "\u001F\u001F\u001F\u001F\u001Fसो\u001Eम.\u001Eबु.\u001Eबी.\u001Eशु.\u001Eश.\u001Eऐ\u001F0"

internal val LOCALE_STANDALONE_DSB: String =
    "januar\u001Efebruar\u001Eměrc\u001Eapryl\u001Emaj\u001Ejunij\u001Ejulij\u001Eawgust\u001Eseptember\u001Eoktober\u001Enowember\u001Edecember\u001Fjan\u001Efeb\u001Eměr\u001Eapr\u001Emaj\u001Ejun\u001Ejul\u001Eawg\u001Esep\u001Eokt\u001Enow\u001Edec\u001F\u001F\u001F\u001F\u001F0"

internal val LOCALE_STANDALONE_DZ: String =
    "སྤྱི་ཟླ་དངཔ་\u001Eསྤྱི་ཟླ་གཉིས་པ་\u001Eསྤྱི་ཟླ་གསུམ་པ་\u001Eསྤྱི་ཟླ་བཞི་པ\u001Eསྤྱི་ཟླ་ལྔ་པ་\u001Eསྤྱི་ཟླ་དྲུག་པ\u001Eསྤྱི་ཟླ་བདུན་པ་\u001Eསྤྱི་ཟླ་བརྒྱད་པ་\u001Eསྤྱི་ཟླ་དགུ་པ་\u001Eསྤྱི་ཟླ་བཅུ་པ་\u001Eསྤྱི་ཟླ་བཅུ་གཅིག་པ་\u001Eསྤྱི་ཟླ་བཅུ་གཉིས་པ་\u001Fཟླ་༡\u001Eཟླ་༢\u001Eཟླ་༣\u001Eཟླ་༤\u001Eཟླ་༥\u001Eཟླ་༦\u001Eཟླ་༧\u001Eཟླ་༨\u001Eཟླ་༩\u001Eཟླ་༡༠\u001Eཟླ་༡༡\u001Eཟླ་༡༢\u001F༡\u001E༢\u001E༣\u001E༤\u001E༥\u001E༦\u001E༧\u001E༨\u001E༩\u001E༡༠\u001E༡༡\u001E༡༢\u001F\u001F\u001F\u001F0"
