/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.timezone.cldr.internal.data

internal val TIME_ZONE_FORMATS_OC: String =
    "+HH:mm\u001F-HH:mm\u001FUTC{0}\u001FUTC\u001FGMT+?\u001Fora de {0}\u001F{0} (ora estandard)\u001F{0} (ora d’estiu)\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_OM: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001FSa’aatii {0}\u001FSa’aatii Istaandardii {0}\u001FSa’aatii Guyyaa {0}\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_OR: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} ସମୟ\u001F{0} ମାନାଙ୍କ ସମୟ\u001F{0} ଦିବାଲୋକ ସମୟ\u001F{1} ({0})"

internal val TIME_ZONE_FORMATS_OS: String =
    "+HH:mm\u001F-HH:mm\u001FGMT{0}\u001FGMT\u001FGMT+?\u001F{0} рӕстӕг\u001F{0} (+0)\u001F{0} (+1)\u001F{1} ({0})"
