/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_OS: String =
    "006eCe\u0009\u0017W\u000E\u0001\u000D#\\g(\u0019\u0010#\$n\u0003:C\u0011&\u0013\u0017\u001C&\u0013\"!*\u001C8{J\u0001Ff_\u001E0y\"&~&?c\u001A<v|Xc(hJ}\u0012\u0012s]i[u4]\u0012l^:6!!nz\u001E\u001E)`uBV]\u0019E\u0007<|x\u0019\u001A?\u000Fhoigwe<)9j<5wZ6jeyr_\u001Ay \u000AJF<V|h\u000Dd\u0009F1t_iNjIo\u0005C\u001B'N\u0012\u000DR@k\u001DA\u0019!:m]EEhhE>p\u001E\u00097\u00027/l[H\u001E3kaH\u000DN\u0012D,:^-j\u00043a\u0012zj\u000C\u0001ar\\\u0018Agt'\u0001C\u0011S.M'C\u001AC[s%|Q\u0017\u000Avm-Z5['\u0013\u0001\u001C\"W\\id\u0005\u000E\u00094Fu\u001DI\u00100Q\u0017"
