/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_VAI: String =
    "009gWU\u000AUY\u000Dc\u0011\u007FJs@e\u0003\u000Bo\\7bx[OT8\u0003i1'>\u0005\u000F0\u001F~+E[\u0005\"\u0005n\u0011W\u0017&KL#i5Q9A+K\u000BR) \u007F@u\u0015hj\u007F[\u0019 \u000C\u0003\"e_s=fs/\u0005x\u0007Rd0a\u000E}Q\u00196w\u0005@\u0004xq\u000Da!\u007F\u0005(9&K3\u000F!X^\u001Aq*Hh  B:a\u0008\u0015:q\u001F.G\u000DI8Y\u00077\u0016(q0Y\u0002oq\u0013fR)dnE\u000C@Eu\u0013?j\u0001;IlgO\$YH|%Z\u0017duG|W\u000F@]@mlnI%\u000C3K\u0015\$g\u0016*!\u0012&6\u0005anIC\u001A\"JK%A^\u0011(\u000D\u001E%XMq|\u0008dqX*u7{4\u001A}\u0006\u001AHqMZ(c)y`1\\m\u0002@\u001E\u0012|Zd`[E\\# w3<k\u0009d.W4)oR\u000EWk_,\u000DV\u0012\u0015\u000FZk\$Q\u0017n*d\u00164P\u0013\u00136k)=V\u000E\$j\u001C\u001E!\u001CuJr\u001F=*q'iN\$ny=u=2\u001B\u0015\u0008cyV\u0018f\u0007R\$k\u0007\u0009A\u000E&% G&Y\u000D(HQfu:*jLL\u001EA"

internal val LOCALE_VAI_LATN: String =
    "006rOe\u0008Uq\u000Dc\u0011C\\\u007F-1\u001E1*\\6:9:\"i\$\u0011B\"\u0016X#\u0017\u0019s[/bYD\u000Bc\u0008&\u0008\u0019\$\u001E2ly\u0005Df>\u0001#\u0003B(PLmh\u001F\u000Dws.*kRvS\u000A\u0011\u0016&\u0011M\u000E5S!x-ZbO=u(}rnr\u0015\u0005+\u000B\u000B\u001B\u0007\u0017\u000F7-Y~2S@hz]gedE@(\u0005?E4i6TMqK\"R\u000C\u000F6`j&\u0017\u0009~p2(H+.h\u000F\u0004]2#vVf(:*/8nI\$.\u0007\u0016T\u000Ej*M\u000E9'\u001D~F>/V\u0003wvY,\u0009\u0010\u0010l>N\u0006~\$\u0018Dh833\u007F(\"\u001Eg5\u0014xu8.y\u001AV/N\u0014_\u0007pE\u000C.N\u0004h}Q|qQW\u000D]\u0018q{\u0001w(a\u0009"

internal val LOCALE_VEC: String =
    "006r?d\\UW\u000E\u0001\u0011CxmC1=\"['d+h[_YS&\u0016a]\u00090_74\u0014\$:\u0011x4}!\u0015`\$xUts24GCDlHAh\u000F!7>|4]\u001E9b\u001Et8EF&yf1\u0018PDxCz%\u0013?#8M\u0009F\u0002V]N#V\u000AV\u0017l2<c\u0017U\u000AC\u0015@5r(\\\u0010d=f5(#i\"\u0005S\u0008\u0005\u0011F\u0011\u0011S\u0007/g)&o1\u0008WCdf\\a&_RI|C\u0002,\u0017\u0007Gr?\"\u001B~]\u001F'\u007F\u0012\u000F{&\u0004\u0017M\u001D'\u007FnQMB\u0015\u000B,Lqu\\\u000Dc\$\u007F}Z.\u000Cx\u0018\u001B1e\u0013aL=4.t\u0005\u000CrVx\u000E(cJ2Ox\u000Ad\u0005VnH\u000Bj\u0011\u001F1)v}6R\u001B;O\\(/b~0&\u000D[\u0018+\u0006\u001FVf\u007FO\u001F\u001E\u0007HU'\u0019a:UyPu;\u0017f\u000B}=N8|s\u0008q/+)\"/:M\u000C\u0012{\u000D\u0012'\u001D\u0015w\u0007b\u001CYI\u001EQ_"

internal val LOCALE_VI: String =
    "009l;e*WW\u000Da\u0011C\\\u007F+!\u000D\u0011#epz\u001Bq5\u000BpJ\u0012=1]\u0011.+\u0017%JZe\u001583\u0015\u0010)\u0019qCu)\u0017B\u0018)u]\u0014>D\\{,\u000B\u001D\u0016&i\u0001@\u0018oYz_\u0005+//?\u0010UJ\u000E\u0016\u0002D3\u0001)!\u0008%\u0001EA\u000EI\u0002z\u0001\u00191\u0003\u001A@jN\u001C6KAt c!P\u0011U<A~\u0008:MYx\u0016\u0019 u5`3I\u000B\u0017\u0009\u0019\u0005UMMBE\u0009ZU\u00146^\u0016X\u001C\u0008\u0017:B4\u0007x\u001D>K8lzv\u001B0XSr| NA\u0014G|>\u000Bg\u001B4y/TlHRj/?f_I?\"Tn\u001C=T\u0018G9f\u001FE%\u001CG:\u0015\u001C8VuNmd4\u000A:\u000AZ\u0009l(3R\u0015@fC\u0013Z\u0016XsC\u001F\u0004%i\u0016m/E\u0019\u0017fu@+i}T\u007F\u007FX3\u0015\u00102kOx\u0014.n\u007FV\u000EGyEMpKCY[t/\u0013r@xt\u0014X9\u0014o\\<d\u0001\u0004nn\u000AY_\u001CQ\u001BT@i\u000CB?Y\u0013F9k\"KW<Cw\u001C\u0012F([xG4W`\u0013{)2Up!\u0017\\\u001D'\u000F(\"Iw?\u0014ozAa"

internal val LOCALE_VMW: String =
    "008Z[e\u001AWW\u000Da\u0011C8mK)\u001EaA:(\u001Cv[n%s\u0009F\u000B/Dg\u001C\u0016.\$ER;.\u0016t\"xXS]o\u000D_>\u001BawP\u001C7Fg\u0011\"TT8u\u0009>`;Pk\u0001-|\u0010A:>vT\u0009'\"\u0005|TLf\u0018\u000Fxh\"r\u000Eq\u001E[L>\u0018\u0009Z\u0007Muo],F(ie\u00016V6C\u0009\u001DT\u0015\u0019\u0001h\u001Bd\u0001\u0013,\u0009\u0001UA%ehh6\u001Db\u0006hX;,7ruy\u0013\u000F\u0017in-i\u0001z' aS4!\u0003CG\u000CQ0=!IX\u0003\u0009\$\u0007_qD/%1&<gF|\u0007\u000F|\u001C\u0009\u001C\u0009`\u000B\u001FPNREugX\u0013\u0018MXc\u000Fv\u0010\u0012j\u0014CBWS+\\86kkvxP\u0018j\u0004~\u0019v\u000Fa,_=6<Hw6Ct\u0015},3}YX\u0007\u0010I]&\u0019eFh c|eN\u000C\"-\u0014-V\u0001>,\u0011w#q"
