/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_WAE: String =
    "008X;U\u0019\u0017W\u000A\u0001\u0011\u007Fet\u0018c\u0003*En7P%^\u0011&\u0005CQBi\u0016^\u0011\u0017Zr.G\u000D5+\u0016QP}\u000E.p!lui4|\u0008Z\u0010{\u0013tNF\$3D4w4T>J`_.\u001Ee\u000C%Y\u0010\u0014\u000Ci[A-\u0016{8\u0016C\u001B\u000EN\$QUB%>&C\u000AZmm3B\"\u0016%.\u0015w\u0014J\\x_,%n\$\u0002\u001A\$[`*\u001Fn\u0004w>\u0012i&gk>\u0002+\u001A;I\u001D%\u0014,mq\$\\Y\"'7\u0004GPMV\u0014R7,a5\u0008I!\u0011\u0009DZ\u001AIx;\u0004\u000E\u0018)D\u000Au\u000BT=\u0005!\u001B)\u0006V+Y`fC\u000C?Yx~c8?)(\u001B+n52j/]|enid\u001F9\u001E\u0015t\u001D9Q)1\u0012.hkiR&\u000D\u0003\u0010B\u0018d6vuM\u000AN*@G\$C|}Uc:#y&\u0012!J15C\u001B=dJ\u001E\u00128\u0018o7:VSF;U\u000CW\u00016m\u001D7o\u000F\u001C@}c\u00044<58|h09=\u0012ha1\u0002c9X\u0001I\u0014hwf]\u0007-%\u0004\u0012&QjU~~-E)1\u000A ^Pnz}fu\u000D\u007F\u001BlF99e9\u0002"

internal val LOCALE_WO: String =
    "008HCe\u000AUw\u000Da\u0011C\\\u007F*a\u000FISO*X|[\u0002\u0003\u0016J3e(\u0001\u0002\u00106%\u0013JK'\u0012#)+j\$k+n-\u001D\u0012\u000E}\u0013\$c9\u0017f+W<\u0006yo\u007FzrO#\u0014W7pKqXWR-\u000FC,\u000E-#Y)\u0011,JjU[\u001BA\u000EP\u0004\u0013/t&\u001C\$*W= \u0007W+%a+n\\^\u000EU.+x#%V\u0013MF\u0006)vH\u0019M\u000C\u001D2\u000B\u0011\u00174'\u0015qC\u0007\u0005-\u0019\"EN\u00192\u0002Di\u0004Pb\u0011cb:\u001EyS=e\u0011j3\u001FA;\u000C-*#8\u0008E]v0WxNBT6l.K )\u001At[@+R\u00094(\u0004;e;\u000E_:\u0008\u0010\u0015mj*.P#Oh\u0007.FF~Mu\\`.\u001FI1O|74\u0004 ]W\u0002q!dYZ:/+xWz/_Dl2@)/|1\u000Fxp9\u001C=/m\u0018u\u0019\u0005 \u0007i\u001B(JG94OcAH\u000A\u001FD}\u000EOPR{\u0015\u0002K7\u000B\u00178q\u0018u=-II87\u000E ^xqSx&@\u0006@d*\u000F%pA\u0005"
