/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_UK: String =
    "003U'd\u000AQu\u0009a\u0015C\u001C\u007F(Q#\u001Feb\u000F.\u0006NAc'61I&6bD\u000C\u000B\u0019\u0019C_2:\u0009lqRVpU8pp\u0015\u0017/\u0015%\u0004 8\u0002\u001Ewt(bEf}\u0009U\u0007tgHz\u0009hF7u\u0016uv\u000Fp\u0001(\u0017Y|pe\u0012peMhRSd\u0005T\u0005tE&]\u0019{'p^pL\u0016O\u001E\u0015M\u001E>q2TA0l\u000B\u001CBRK\u0001Y;\u00064q\u0009N\u0003\u001C*q\u0015+=0t\u0018kn\u001C\u0017'a\u0011"

internal val LOCALE_STANDALONE_UZ: String =
    "0020\u0017d\u0007\u0011U\u0001a\u000D#\\s&w\u0005W\u0015#\u001D\u000B\u0001>\u001F\u001D\u0012B\u0011j:'a-{>9Qdf\u007Fz\u0018m\u000Bd5kI\u001B\u0014W\\\u0004\u0018h7\u0005Zu<IX\u0009Ls{L\u000A{3ujt1n\u0019YxVVA\u0015=11^4Q!B2Lu\u0006\u0004x\u0011\u0011qQ/\u0014D\u0007\u000C"
