/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_WAE: String =
    "007a;TY\u0017W\u000A\u0001\u0011\u007Fet\u0018c\u0001\u001A\u000A'[~3k*\u0007\u0009\u0017\u0006\u000F\"\u0006qSZr\u0006W9*V-U\u007F\u0002\u0016~q\u000F|wk\u0014l\u0010[\u007F<ZU&\u0009'?'y8^\\|eZ;l\u0017\u0004-G{\u001BU\u000CC@'\u0014Y\$\u0012^U:\u000B)\u0015HUUb3\u001C\u00104w)\u000D3UNAP6\u0013Vp\\%'JZg\$[\\'Vc@\\hKK\u001CULI4H\u0006)Nc\u001F3Jh\u0017\u0006yD\u0009tA\u0003mx(\u001C\u001E,gc\u000E8YbbI\"\u0012i\u000EE73<)';2J\u0003>o1V\u0019:\u0001\u0015\u0016\u00037gZPds\u0002XpK_*)d\u0009Sh;*F.=h^`TW=2z\u0016O)v\u0017Q!\u0006\u001B.\u0016i\u000B\u0015\u000D\u0003 B\u000Ca>y;\u000Dq\u0017Q\u001ErMs_}W\u0001'Up\u0006`t\u0012\u000C8\u001F\u000907-\"18W{]\u0017`\u0014Z*@T\u0007~QH;H\u0004\\Db|\u00092vxy`9?\u0008G\u0014b.'\u0010#\u000EQ\u0008I=/s\u001Ec\u001Dr!ZG\u0007F3\u0004\\Ha"

internal val LOCALE_WO: String =
    "007KCe\u0009\u0017u\u000Da\u0011#\\g-\u0019\u0006\u00023\u0005C*\u00186\"S\u0016+]X+\u0002w\u0001RW\"[CqIn#\u001B#[K\u001C\u00147t9-0)gJn\u0018-d\u001Cm@~\u007F\$Lu_P.\u0001)=U0BS\u0004\u0012X\"y\u0011Q@\u0006LY{.\u0017H\u0018DF\"\u000F\u000Czh&\u001F%.\u001Fp\u0018\u001B2\u000835\u007F_\"\u000Ar\\\u0015PC*\u0007N+\"LV;\u001C\u0015;\u001C-\u0019\u0015)&K=J\u0007\u0009\u00193M1a(\u0013d\u0005\u000B\u001D\u0001zi\u000E\u001E1i,pf8EZ5K\u0014Y@N\u0016K[%\u000B?I:Wju~\u001F\u001EYg^/*BoD,{V\u0017\"&\u0002\u0007vM\u000F\u001B=s/\u000F\u0016TY,o0\u0007pLg\u000EF\u0004|`]'A}\u0013\"r\u001B\u0019\u0001\u0004})aPC\u0013\u0011fd</GW,2\\xvzT`O\u0011\u0012tctK\u0012\u0005x6z\u0004\u000DTmnLw#/,C;e\u0009[g:(\u001C.\u000D:t\u0017\u0019\u0010 \u0006\u0012f\u0019X\u0001l\u0004a"
