/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_JA: String =
    "009nSU:5Q\u000E\u0003\u0011\u007F%t(g\u0002\u0005g<\u000E=Cu\u0012\u0005?\"\u0013\u0005\u001A:x[*D\u0001\u0012~!\$M!Q=7\u001A\u0011\u000F\u0014\u000BJ\u001D\u0003\u0009\u001D\u0008# yzOS2>JR\u0008IA\u001D87V.X7X\"D\u0015kA\u0001a\u0006\u0008I)\u0019r\u0002D\u000B\u000E\u0005\u0011Z+\u000C\u0013\u0012+#Db '9q}\u0003C+\u0005\u0015\u00151\u0009*=s\u0009\u0006\u001B\u0006G|W|.\u0009T\u000COrU|\u001B8f\u0018jD* \$jr3,Rrv/D\$W\u0015PqP\u0005tO\u000E^wqlt\u0012I<\u001ARY*\u001Bw\u001BH\u001A8gDd:{Mp|;Jh'6F_R \u0014<an)@\u000E)L7nWVn|'D@4IpLg9\u0005\u000D}0xTf\u0006SWGSh-P:s\\**4u+0{* v?Z\u0016\u0010b\u0007[G:%R5\u000D4\u001FH`P\u001Aw\u001C\u0013j6\u0015x]\u0001>M).A'4~PM\u000E4C=b>uC9Fr2\u0018\u007F)?HgCT)w*3\u001D'\u000AR*KUD<DZ*\u00119!sMe(#\"Wu/\u001B[\u000E\\\u000ED'N\u0009G8Nkf6\u0010\u0008wp\u0017( \u0001\u0011"

internal val LOCALE_JGO: String =
    "00F7sU8WW\u000Da\u0011@%s2w\u0001\u0004L9`T\$\u000A\u0015L\u000C'I1]rIN6NsD\u000BcL%\u00115\u001AM}d\u0019\u0012%\u0018u\u0008[_!BI*^\u001AF\u001BSf\u001D`NDT`U!xp`?~m\u001F\u000A}y\u001F3<\u001A\u0004\u000D\u0004^3=\u00161[4+-6>SaWWtB#cT|\u001D&\u001E\$\u000C\u007FMCJ\u001Ej\u0003T9-,iJWDs1\u0006\u0011Zzx\u0018f)<L\u00010i;\u000B\u001Bl\\\u0016}cqs}%\u000B?\u001DkPZo,\u000DwOMsw\"v2u\u0010z{WQ!sR\u0004\u0006D.\u0005\u001105q\u0003r\u0001e\u0015\u0001rIjSj\u0012E\u000F2&O9I8[~;\"JR&\u0001^d'}C\\mP\u000A\u0014>HT\u00072\u0006)[0!n@\u00065<\u0018O\u001A\u0008mv*>T.I\u0009\u0003~\u0007reo\u001A7}C ltwaAHO\u0019-L\u000F\u0019;lp5Ew=\u000B\u0006dw\u001B9\u000B\u000F\"n\u0009a8&6s_'D@0i:H\u001E\u00171vsS;u\u0004\u001B\u0001\u000A]AR mul{S3<;n\u001B\u0017~SY\u0014wA\\\u001A,3k\u001E|\u0003h\u0006O\u0016in\u000CK\u0007\u0009M1o\u0019@{\u0009\u0011;E)W\u0017j=Fh\u0007M?qEM A\u0011"

internal val LOCALE_JMC: String =
    "0080;di\u0017w\u0009a\u0011#\\\u007F#9\u001F\u0011E\"\u001B.\u001EI\u0016#\u0005\$!!S:A!6\u00182\u0012\u0019CuSF%0+\u001F\u007FS'u\u0014!3crk.~_\u0008M~\\&Wviy\u0014'm9\\J{NWuB)H:[\u0008\u000DY3*8Gl\u0011u4PDFltM\u000AkU],\u001C\u0007V<j.4\u0017sWt5vJ6\u0015K.Q\"%kb/\u000F)'\u000B\u0015R}jKP^\u0013\u000D\u0015SS\u0013\u0010\u0003Yy\u0012X-Y2\u0011J\"?jTh\u001Fr\u000C\u001AZ\u000882P3%\u001E9\u0017T\u000Et\u000CxK/p\u0006R,\u000AWZ*s>\u0015zu\u0003gV-\u000F&s6\u0003\u0015\u0013V9|/.\u001Bs*=z\u007Fs056DbpuM%\u0010\u000D\u000B>:b\u0019\u0013s!t\u0003D@D.\u000Bu_N>D:W6\u000FE\u0019k^?\u000DtG(~m4[\u0003Jy\u0010(u@\u0016u4H\u007Fo9@g\u0008dqE]BiG\u0001U {\u0009Yl\u000D\u0014ab\u000A\u0015\u001AD\u0010\u0019;\u001C\u000FH \u0012Xa\u000A.;\u000BA\\Ty\u001DpjX\\|^?\u001BN\u007F\u0004"

internal val LOCALE_JV: String =
    "007c+d[\u0017u\u0009a\u0015D8}Dzq\u0001'q7\u001CLb\u000E\$D\u00196)CtZ;C\u0012d1\u00097ILOM<\u0012`3:x\u0013{a\u0006h\u0015ln}\u001Fzhv}p\u0016Gf\u0016M;0Km\u0018\".V%\u001CrUv\u0003i'F\u0017paR5r\u00107ZjX\u0011UUu\u007FSslY\u0010/E??8ct\u0015\u000C\u0013OI\u0017L31J\u001B:DUO2e\u001D('8AiPz\u0005\u0015VC\u0005Aw\u001E^&55\u0019[7-\u0015\u0015bWuqx\u0013d9Ex\u0019-l-[}4FVi\u0015M^ch\u000A%\u00177Z\$(Wd\u0005\u000888T9~\\\u0008\\I\u000DYP\$@Z\u0001 V7.=Q\u0011\u0013[^=\u0018]\u0011M^=\u001Ad!_<\u0009FEs\u0014\u000A\u0014\u0016@X:\u0019xSy] 8@\u000F\u0002\u000C]\u0016.o\u000AX\$|\u0012}-B\u001D \u0012:s~P/8b\u0010&\u0010\u0001\u000E\u007F7\u0007E\u001F/M\u001E#\u0015);/\u0003A\u001Dr\u0007\u000Ce\u001B\u000BpDx~\u0012\u007Fvw\u0003Rr={gYRy"
