/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.datetime.cldr.internal.data

internal val LOCALE_STANDALONE_CA: String =
    "002L+t\u001CQM\u0001a\u000D\u00039\u000A^\u00115\u001DX6\u000E3eT7C@B\u0005h\u0019E/4U\u0004M\"|J\u000F\u000AP:yI#^mF2n]Lw#u\u0013R>=\u0017P,T\u0016\u000B\u0011Rw\$w^\u000E\u0016\u000E|\u007F%df]^\u001Az=4j29H\u0019hC95! Epan\u0006\u00010UA\u0009K\u0001\u000B\u001AM{"

internal val LOCALE_STANDALONE_CCP: String =
    "00Bb~M\u0017\u001B0@\u0008EL\u0017)\u000Ca+\u0011\u0018\u0001=%#\u0003yC\u0008\u0013:A\u0010\u0009iB\u001F\u0007r\u000C9\u0004a]\u00118bF-\u0003Ay f\u0001&\u001Fa\u0008Ff\u00111-c!NA;,A\u001F\u0017\u0015B\u0006\u0019X\u000E%\u00051*M-M\u0004\u001AA\u0002\u0012j.'\u000C\u001Aj\u0003\u0008\"\u000C!\u0006JQ\"(>\u000B46\u0012\u001E\u0008zz%\u0014LqtMDM\u001B%\u0009\u0004]K\u000Dvm\u0006\u001Ai\u0011,\u0019\$39MKG\u007F.c*K w\u000ASzj\u000E8E\u0007\u0001\u0001\u0001"

internal val LOCALE_STANDALONE_CE: String =
    "000XJfay\u00110xe\u0018\u001EZ\u0006obl2+|Y&6e\u0018|\u0018Ni\u0010E]8e\u0007A\u0001"

internal val LOCALE_STANDALONE_CS: String =
    "001bfS*UO7'<_\u000Bf|{!^ju4\u001BCR\u0001`&\u001B\u0003*\u00075]<\u001A/AUISM\u0017KI>\u000E\$\u0013tcR\u0001E\u000C,bCRMb{}U\u0007\u0012-Q\u0010et\u001AcJ@\u0011-)Sr\u0003R@\u001D%f\u0005uy\u0019\u0013\u0007es1\u0009\u0001"

internal val LOCALE_STANDALONE_CY: String =
    "001MJ~zM}NhO\u0015&\u007F5j3/t'KA.\u0015ff?UG//xf\u000BsH:9S+\u0002\u001DKT(\u0009w-*9I2\u001DQfcB\u000Dc^0\u0018Lc>\u001Dj\u0010\u0017\u00127|+\$\u001D4YV\u001Adnt+/\u001D\u000D)SrajH0\u0018A\u0009\u0001"
