package dev.carcara.kotlinx.locale.conformance

import dev.carcara.kotlinx.locale.Locale
import dev.carcara.kotlinx.locale.datetime.cldr.runtime.SkeletonFormatSource
import kotlinx.datetime.LocalDateTime
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Holds a skeleton source to the patterns ICU4J chooses.
 *
 * Unlike the rest of the datetime suite, this compares *patterns* rather than
 * formatted output, and it can: the matcher's whole job is picking a pattern,
 * and the fixtures were generated by asking ICU the same question. Comparing
 * output instead would let a wrong pattern pass whenever the sample date
 * happened to render the same.
 *
 * A skeleton naming a field this library does not render is skipped rather than
 * failed — those are declined on purpose, and the README says which.
 */
public fun SkeletonFormatSource.assertConformsToIcuSkeletons(tier: ConformanceTier) {
    if (tier != ConformanceTier.EXACT) return
    assertTrue(supportedLocales.isNotEmpty(), "a CLDR-backed source is expected to enumerate its locales")

    val mismatches = ArrayList<String>()
    var compared = 0
    var declined = 0

    for ((tag, expected) in icuSkeletonGoldenData) {
        val locale = Locale.forLanguageTag(tag)
        for ((index, skeleton) in icuGoldenSkeletons.withIndex()) {
            val icu = expected.getOrNull(index).orEmpty()
            if (icu.isEmpty()) continue
            val actual = skeletonPatternOrNull(skeleton, locale)
            if (actual == null) {
                declined++
                continue
            }
            compared++
            if (actual.normalizedSpaces() != icu.normalizedSpaces() && mismatches.size < MAX_REPORTED) {
                mismatches.add("$tag '$skeleton': expected <$icu> but was <$actual>")
            }
        }
    }

    assertTrue(compared > 0, "no skeletons were compared, which means the fixtures did not load")
    assertTrue(
        mismatches.isEmpty(),
        "the matcher disagreed with ICU on ${mismatches.size} of $compared patterns " +
            "($declined declined as unrenderable):\n" + mismatches.joinToString("\n"),
    )
}

/**
 * Runs CLDR's own datetime cases, which check formatted output rather than
 * patterns.
 *
 * A second opinion independent of ICU4J: the goldens and the matcher were both
 * written against ICU's reading of UTS #35, and these would catch the two
 * agreeing with each other and with nothing else. Thirty-six cases, all `en`,
 * so it is a smoke test rather than coverage — but it exercises the renderer as
 * well as the match, which the pattern goldens do not.
 */
public fun SkeletonFormatSource.assertMatchesCldrDateTimeCases() {
    for (case in cldrDateTimeCases) {
        val locale = Locale.forLanguageTag(case.locale)
        val dateTime = LocalDateTime.parse(case.dateTime)
        val actual = formatOrNull(dateTime, case.skeleton, locale)
        assertEquals(
            case.expected.normalizedSpaces(),
            actual?.normalizedSpaces(),
            "CLDR case ${case.locale} '${case.skeleton}' at ${case.dateTime}",
        )
    }
}

private const val MAX_REPORTED = 40
