/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.internal.data

internal val CURRENCY_COMPACT_YRL: String =
    "003n\u001AN\u0017\u000DR@\u0013I\u0017mH\\(\u0014!\u0003\u0002ai1]Iff\u0007\u0004+\u001D&\u0003\u0005Ge!Qr5RI\u0017\u0001B2^\u000CR\u0007E'u\u001FY\u001D\u0017\u001BR\u0007s\u001ASeUgBjDC\$\u001B\u0018/\u000D\u000A\u000E\u0009>:.P\u000FQV:a\u0013OP\u001D\u0013kYk#1\u0001"

internal val CURRENCY_COMPACT_YUE: String =
    "006/\u001AN\u0017\u000DR@\u0013I\u0017mH\\'\u0014\u0002Aq\u001B*9]qCUc\u000BC\u0013DZQ\u0002'6\u0003\u0006Iw\u0015\u0011\"\u0009)NA#Ds5[d:a>'\u0007\u000C\u000Did\u001163\u00018\u0006L\u000E\u0001\u0014\u000Bn%\u0009J\u0007q\u000F\u0015#\u000D~WL;e\u001EN\u0015%\u0003\u000A\u0013\u0005_'W%)4\u0019\u0015IeF\u001A\u0003R\u0011~]\u0012%4\u0002NJf\u0011\u0003\u00056q\u0001'6#\u0003\u0006\u0013!CMr\u0002#\u000C\u0013\u0016a1\u001B7\u0006N+q\u0015\u0015\\\u0012\u0002C9\u0005=\u0016#K\u0006\u0001\u0001"

internal val CURRENCY_COMPACT_YUE_HANS: String =
    "006/\u001AN\u0017\u000DR@\u0013I\u0017mH\\'\u0014\u0002Aq36plK\u000DQ\u0009kiK\u0007cC\u0006\u0019\u0015)7\$UQC\u0005\"#\u0007\u000A\u000F\u000AKTl.X\u0002z\u0019\u001A-4\u0004\u000DJRI\u0002]\u0017-\u0005\u0009NI<IR#\u00065\u000A\u000A\u0012\u0007\u001F|.Z3\u000Fg\u000B\u0013\u0002\u000DN\u0001O<n:;\u0005a\u0005\u0014\u001A\u0012\u00171]%\u001E7\u0005\u000A\u000Di1J+\u0009\u0001*\u0013\u0001\u0011/6#\u0004\u0006\u00091\"c:\u0001R\u0006J\u0007q\u000D\u0010\u001B\u0003gT)\u0003\u000B.I8\u0011\u007F\u0002\u0004@85\u0010\u0001\u0001"
