/*
 * Copyright 2026 Carcara.dev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED by :codegen from CLDR release-48-2. Do not edit.
// Regenerate with: ./gradlew :codegen:generateLocaleData
package dev.carcara.kotlinx.locale.currency.cldr.internal.data

internal val CURRENCY_FORMATS_CA: String =
    "001e\u001AM\u0007D\u0012Yc6\u001Anw\u000A'_\$X\u0002YlXK\u000Esf\u000FZ-Q\u001Au\u0008\u0004\"Cbco\u0008\u001C2l\u0011\u001DgP\u000B'\u0004\u0001\u0001"

internal val CURRENCY_FORMATS_CCP: String =
    "002C~M\u0017\u0017/o\u0010\u000A\u0017wq\u0018A\u001D\"p\u00039LU\u0006q8\u0009|A\u001F\u0016r\u0004=\u0008c?}`0\u0012lA-\u0016|f\u0003z3H\u000Db\u0002P!1\u0019\u000F\u0017q9|\u001FZ\u0002b69Sq)\u0001"

internal val CURRENCY_FORMATS_CGG: String =
    "0012\u001AM\u0007D\u0012Yc6\u001Anw\u000A'_(X\u0001YlXK\u0010sD&f\u000FZ%U\u001Cu\u0007\u0004\u0002\u0004\u0011\u0005"

internal val CURRENCY_FORMATS_CKB: String =
    "001R^o=\u000F7\u000B8\u000C8\u000CXlP\u0014NSNsncv\u007Ftct\u0013`\u001A^0KpX!3)yluvsD=Z,W*\u0016\u0007~\u0002Aa9[9[\"\u000A\u0001q\u0001"

internal val CURRENCY_FORMATS_CO: String =
    "001P\u001AM\u0007D\u0012Yc6\u001Anw\u000A'_(X\u0001YlXK\u0010sD&DFV\u0007Z#W\u001C5\u00074\u0005C\u000F2\u0008\u000C(\u000C!\u0013p\u000D[BRK9(E\u0003\u0001\u0001"
